erDiagram
  DBI_PUBLIC_DM_DM_PLT_FIJA_2022 {
    PLANTA_CLUSTER VARCHAR
    NRODOC VARCHAR
    TELEFONO VARCHAR
    FLAG_PANGEA VARCHAR
    COBERTURA_PANGEA VARCHAR
    PLANTA_PERIODO VARCHAR
  }
  DBI_PUBLIC_DM_DM_PLT_FIJA_2023 {
    PERIODO_ACTUALIZACION VARCHAR
    FECHA_ACTUALIZACION VARCHAR
    FUENTE VARCHAR
    PLANTA_PERIODO VARCHAR
    SISTEMA VARCHAR
    ABONADOATISID INT
  }
  DBI_PUBLIC_DM_DM_PLT_FIJA_2024 {
    PERIODO_ACTUALIZACION VARCHAR
    FECHA_ACTUALIZACION VARCHAR
    FUENTE VARCHAR
    PLANTA_PERIODO VARCHAR
    SISTEMA VARCHAR
    ABONADOATISID INT
  }
  E2E_FCR_2023 {
    TICKET_FCR VARCHAR
    TICKET_DESCRIPCION VARCHAR
    TICK_DESC VARCHAR
    ID_CANAL INT
    TICKET_ESTADO VARCHAR
    SERVICE_CODE VARCHAR
  }
  E2E_FCR_2024 {
    TICKET_FCR VARCHAR
    TICKET_DESCRIPCION VARCHAR
    TICK_DESC VARCHAR
    ID_CANAL INT
    TICKET_ESTADO VARCHAR
    SERVICE_CODE VARCHAR
  }
