erDiagram
  LYT_AVERIAS_LIQUIDADAS_202201 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_AVERIAS_LIQUIDADAS_202202 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_AVERIAS_LIQUIDADAS_202203 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_AVERIAS_LIQUIDADAS_202204 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_AVERIAS_LIQUIDADAS_202205 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_AVERIAS_MASIVAS_202201 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_AVERIAS_MASIVAS_202202 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_AVERIAS_MASIVAS_202203 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_AVERIAS_MASIVAS_202204 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_CONTACT_CENTER_ACCESADAS_202201 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202202 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202203 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202204 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202205 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202206 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ENTRANTES_202201 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202202 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202203 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202204 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202205 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202206 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_DEVUELTAS_TECNICAS_202201 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_PROVISION_EJECUTADA_202201 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_PROVISION_EJECUTADA_202202 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_PROVISION_EJECUTADA_202203 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_PROVISION_EJECUTADA_202204 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_PROVISION_EJECUTADA_202205 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_PROVISION_EJECUTADA_202208 {
    ORDER_ACTION_KEY VARCHAR
    ORDER_KEY VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CELULAR VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202101_202112 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202201_202212 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  MULTICONSULTA_ARBOL_DECISIONES_202201 {
    USUARIO VARCHAR
    DNIUSER VARCHAR
    FECHAHORA VARCHAR
    DIA VARCHAR
    IDCLIENTECRM INT
    AVERIA VARCHAR
  }
  MULTICONSULTA_ARBOL_DECISIONES_202202 {
    USUARIO VARCHAR
    DNIUSER VARCHAR
    FECHAHORA VARCHAR
    DIA VARCHAR
    IDCLIENTECRM INT
    AVERIA VARCHAR
  }
  MULTICONSULTA_ARBOL_DECISIONES_202203 {
    USUARIO VARCHAR
    DNIUSER VARCHAR
    FECHAHORA VARCHAR
    DIA VARCHAR
    IDCLIENTECRM INT
    AVERIA VARCHAR
  }
  MULTICONSULTA_ARBOL_DECISIONES_202204 {
    USUARIO VARCHAR
    DNIUSER VARCHAR
    FECHAHORA VARCHAR
    DIA VARCHAR
    IDCLIENTECRM INT
    AVERIA VARCHAR
  }
  MULTICONSULTA_ARBOL_DECISIONES_202205 {
    USUARIO VARCHAR
    DNIUSER VARCHAR
    FECHAHORA VARCHAR
    DIA VARCHAR
    IDCLIENTECRM INT
    AVERIA VARCHAR
  }
  MULTICONSULTA_ARBOL_DECISIONES_202206 {
    USUARIO VARCHAR
    DNIUSER VARCHAR
    FECHAHORA VARCHAR
    DIA VARCHAR
    IDCLIENTECRM INT
    AVERIA VARCHAR
  }
  MULTICONSULTA_ARBOL_DECISIONES_202207 {
    USUARIO VARCHAR
    DNIUSER VARCHAR
    FECHAHORA VARCHAR
    DIA VARCHAR
    IDCLIENTECRM INT
    AVERIA VARCHAR
  }
  MULTICONSULTA_ARBOL_DECISIONES_202208 {
    USUARIO VARCHAR
    DNIUSER VARCHAR
    FECHAHORA VARCHAR
    DIA VARCHAR
    IDCLIENTECRM INT
    AVERIA VARCHAR
  }
  MULTICONSULTA_ARBOL_DECISIONES_202209 {
    USUARIO VARCHAR
    DNIUSER VARCHAR
    FECHAHORA VARCHAR
    DIA VARCHAR
    IDCLIENTECRM INT
    AVERIA VARCHAR
  }
  MULTICONSULTA_ARBOL_DECISIONES_202210 {
    USUARIO VARCHAR
    DNIUSER VARCHAR
    FECHAHORA VARCHAR
    DIA VARCHAR
    IDCLIENTECRM INT
    AVERIA VARCHAR
  }
  MULTICONSULTA_ARBOL_DECISIONES_202211 {
    USUARIO VARCHAR
    DNIUSER VARCHAR
    FECHAHORA VARCHAR
    DIA VARCHAR
    IDCLIENTECRM INT
    AVERIA VARCHAR
  }
  MULTICONSULTA_ARBOL_DECISIONES_202212 {
    USUARIO VARCHAR
    DNIUSER VARCHAR
    FECHAHORA VARCHAR
    DIA VARCHAR
    IDCLIENTECRM INT
    AVERIA VARCHAR
  }
  MiMovistar_Convergente_2021 {
    Fecha_hora VARCHAR
    tipo_autenticacion VARCHAR
    valor VARCHAR
    documento_pd VARCHAR
    Fecha VARCHAR
    PERIODO VARCHAR
  }
  MiMovistar_Convergente_2022 {
    Fecha_hora VARCHAR
    tipo_autenticacion VARCHAR
    valor VARCHAR
    documento_pd VARCHAR
    Fecha VARCHAR
    PERIODO VARCHAR
  }
  PLANTA_CLIENTE_DIGITAL_202201 {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    TELEFONO VARCHAR
    INSCRIPCION VARCHAR
    CMS_SERVICIO VARCHAR
    PRODUCTO VARCHAR
  }
  PLANTA_CLIENTE_DIGITAL_202202 {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    TELEFONO VARCHAR
    INSCRIPCION VARCHAR
    CMS_SERVICIO VARCHAR
    PRODUCTO VARCHAR
  }
  PLANTA_CLIENTE_DIGITAL_202203 {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    TELEFONO VARCHAR
    INSCRIPCION VARCHAR
    CMS_SERVICIO VARCHAR
    PRODUCTO VARCHAR
  }
  PLANTA_CLIENTE_DIGITAL_202204 {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    TELEFONO VARCHAR
    INSCRIPCION VARCHAR
    CMS_SERVICIO VARCHAR
    PRODUCTO VARCHAR
  }
  PLANTA_CLIENTE_DIGITAL_202205 {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    TELEFONO VARCHAR
    INSCRIPCION VARCHAR
    CMS_SERVICIO VARCHAR
    PRODUCTO VARCHAR
  }
  PLANTA_CLIENTE_DIGITAL_202206 {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    TELEFONO VARCHAR
    INSCRIPCION VARCHAR
    CMS_SERVICIO VARCHAR
    PRODUCTO VARCHAR
  }
  PLANTA_CLIENTE_DIGITAL_202207 {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    TELEFONO VARCHAR
    INSCRIPCION VARCHAR
    CMS_SERVICIO VARCHAR
    PRODUCTO VARCHAR
  }
  PLANTA_CLIENTE_DIGITAL_202208 {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    TELEFONO VARCHAR
    INSCRIPCION VARCHAR
    CMS_SERVICIO VARCHAR
    PRODUCTO VARCHAR
  }
  PLANTA_CLIENTE_DIGITAL_202209 {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    TELEFONO VARCHAR
    INSCRIPCION VARCHAR
    CMS_SERVICIO VARCHAR
    PRODUCTO VARCHAR
  }
  PLANTA_CLIENTE_DIGITAL_202210 {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    TELEFONO VARCHAR
    INSCRIPCION VARCHAR
    CMS_SERVICIO VARCHAR
    PRODUCTO VARCHAR
  }
  PLANTA_CLIENTE_DIGITAL_202211 {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    TELEFONO VARCHAR
    INSCRIPCION VARCHAR
    CMS_SERVICIO VARCHAR
    PRODUCTO VARCHAR
  }
  PLANTA_CLIENTE_DIGITAL_202212 {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    TELEFONO VARCHAR
    INSCRIPCION VARCHAR
    CMS_SERVICIO VARCHAR
    PRODUCTO VARCHAR
  }
  PLANTA_FIJA_202112 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202201 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202202 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202203 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202204 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202205 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202206 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202207 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202208 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202209 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202210 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202211 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202212 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_MOVIL_202201 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202202 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202203 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202204 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202205 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202206 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202207 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202208 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202209 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202210 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202211 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202212 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  Planta_Movistar_Total_202201 {
    PERIODO VARCHAR
    PERIODO_MT VARCHAR
    AREA VARCHAR
    PROVINCIA VARCHAR
    MUNICIPIO VARCHAR
    LOCALIDAD INT
  }
  Planta_Movistar_Total_202202 {
    PERIODO VARCHAR
    PERIODO_MT VARCHAR
    AREA VARCHAR
    PROVINCIA VARCHAR
    MUNICIPIO VARCHAR
    LOCALIDAD INT
  }
  Planta_Movistar_Total_202203 {
    PERIODO VARCHAR
    PERIODO_MT VARCHAR
    AREA VARCHAR
    PROVINCIA VARCHAR
    MUNICIPIO VARCHAR
    LOCALIDAD INT
  }
  Planta_Movistar_Total_202204 {
    PERIODO VARCHAR
    PERIODO_MT VARCHAR
    AREA VARCHAR
    PROVINCIA VARCHAR
    MUNICIPIO VARCHAR
    LOCALIDAD INT
  }
  Planta_Movistar_Total_202205 {
    PERIODO VARCHAR
    PERIODO_MT VARCHAR
    AREA VARCHAR
    PROVINCIA VARCHAR
    MUNICIPIO VARCHAR
    LOCALIDAD INT
  }
  Planta_Movistar_Total_202206 {
    PERIODO VARCHAR
    PERIODO_MT VARCHAR
    AREA VARCHAR
    PROVINCIA VARCHAR
    MUNICIPIO VARCHAR
    LOCALIDAD INT
  }
  Planta_Movistar_Total_202207 {
    PERIODO VARCHAR
    PERIODO_MT VARCHAR
    AREA VARCHAR
    PROVINCIA VARCHAR
    MUNICIPIO VARCHAR
    LOCALIDAD INT
  }
  Planta_Movistar_Total_202208 {
    PERIODO VARCHAR
    PERIODO_MT VARCHAR
    AREA VARCHAR
    PROVINCIA VARCHAR
    MUNICIPIO VARCHAR
    LOCALIDAD INT
  }
  Planta_Movistar_Total_202209 {
    PERIODO VARCHAR
    PERIODO_MT VARCHAR
    AREA VARCHAR
    PROVINCIA VARCHAR
    MUNICIPIO VARCHAR
    LOCALIDAD INT
  }
  Planta_Movistar_Total_202210 {
    PERIODO VARCHAR
    PERIODO_MT VARCHAR
    AREA VARCHAR
    PROVINCIA VARCHAR
    MUNICIPIO VARCHAR
    LOCALIDAD INT
  }
  Planta_Movistar_Total_202211 {
    PERIODO VARCHAR
    PERIODO_MT VARCHAR
    AREA VARCHAR
    PROVINCIA VARCHAR
    MUNICIPIO VARCHAR
    LOCALIDAD INT
  }
  Planta_Movistar_Total_202212 {
    PERIODO VARCHAR
    PERIODO_MT VARCHAR
    AREA VARCHAR
    PROVINCIA VARCHAR
    MUNICIPIO VARCHAR
    LOCALIDAD INT
  }
