erDiagram
  RESUMEN_SATELITES_202411 {
    LLAVE VARCHAR
    PERIODO_SATELITE VARCHAR
    TIPO_SATELITE VARCHAR
    TELEFONO_CONSOLIDADO INT
    NUMERO_DOCUMENTO VARCHAR
    FECHA_MENSAJERIA VARCHAR
  }
  RESUMEN_SATELITES_202412 {
    LLAVE VARCHAR
    PERIODO_SATELITE VARCHAR
    TIPO_SATELITE VARCHAR
    TELEFONO_CONSOLIDADO INT
    NUMERO_DOCUMENTO VARCHAR
    FECHA_MENSAJERIA VARCHAR
  }
  RESUMEN_SATELITES_202501 {
    LLAVE VARCHAR
    PERIODO_SATELITE VARCHAR
    TIPO_SATELITE VARCHAR
    TELEFONO_CONSOLIDADO INT
    NUMERO_DOCUMENTO VARCHAR
    FECHA_MENSAJERIA VARCHAR
  }
  RESUMEN_SATELITES_202502 {
    LLAVE VARCHAR
    PERIODO_SATELITE VARCHAR
    TIPO_SATELITE VARCHAR
    TELEFONO_CONSOLIDADO INT
    NUMERO_DOCUMENTO VARCHAR
    FECHA_MENSAJERIA VARCHAR
  }
  RESUMEN_SATELITES_202503 {
    LLAVE VARCHAR
    PERIODO_SATELITE VARCHAR
    TIPO_SATELITE VARCHAR
    TELEFONO_CONSOLIDADO INT
    NUMERO_DOCUMENTO VARCHAR
    FECHA_MENSAJERIA VARCHAR
  }
  RESUMEN_SATELITES_202504 {
    LLAVE VARCHAR
    PERIODO_SATELITE VARCHAR
    TIPO_SATELITE VARCHAR
    TELEFONO_CONSOLIDADO INT
    NUMERO_DOCUMENTO VARCHAR
    FECHA_MENSAJERIA VARCHAR
  }
  RESUMEN_SATELITES_202505 {
    LLAVE VARCHAR
    PERIODO_SATELITE VARCHAR
    TIPO_SATELITE VARCHAR
    TELEFONO_CONSOLIDADO INT
    NUMERO_DOCUMENTO VARCHAR
    FECHA_MENSAJERIA VARCHAR
  }
  RESUMEN_SATELITES_202506 {
    LLAVE VARCHAR
    PERIODO_SATELITE VARCHAR
    TIPO_SATELITE VARCHAR
    TELEFONO_CONSOLIDADO INT
    NUMERO_DOCUMENTO VARCHAR
    FECHA_MENSAJERIA VARCHAR
  }
  RESUMEN_SATELITES_202507 {
    LLAVE VARCHAR
    PERIODO_SATELITE VARCHAR
    TIPO_SATELITE VARCHAR
    TELEFONO_CONSOLIDADO INT
    NUMERO_DOCUMENTO VARCHAR
    FECHA_MENSAJERIA VARCHAR
  }
