erDiagram
  DRH_Averias_Registradas {
    ZON VARCHAR
    CO_EJEC VARCHAR
    MDF VARCHAR
    ARM VARCHAR
    CDDIST VARCHAR
    FECENCUEST VARCHAR
  }
  DRH_Averias_Registradas_202201 {
    ZON VARCHAR
    CO_EJEC VARCHAR
    MDF VARCHAR
    ARM VARCHAR
    CDDIST VARCHAR
    FECENCUEST VARCHAR
  }
  DRH_Averias_Registradas_202202 {
    ZON VARCHAR
    CO_EJEC VARCHAR
    MDF VARCHAR
    ARM VARCHAR
    CDDIST VARCHAR
    FECENCUEST VARCHAR
  }
  DRH_Averias_Registradas_202203 {
    ZON VARCHAR
    CO_EJEC VARCHAR
    MDF VARCHAR
    ARM VARCHAR
    CDDIST VARCHAR
    FECENCUEST VARCHAR
  }
  DRH_Averias_Registradas_202204 {
    ZON VARCHAR
    CO_EJEC VARCHAR
    MDF VARCHAR
    ARM VARCHAR
    CDDIST VARCHAR
    FECENCUEST VARCHAR
  }
  DRH_Averias_Registradas_202205 {
    ZON VARCHAR
    CO_EJEC VARCHAR
    MDF VARCHAR
    ARM VARCHAR
    CDDIST VARCHAR
    FECENCUEST VARCHAR
  }
  DRH_Averias_Registradas_202206 {
    ZON VARCHAR
    CO_EJEC VARCHAR
    MDF VARCHAR
    ARM VARCHAR
    CDDIST VARCHAR
    FECENCUEST VARCHAR
  }
  DRH_Averias_Registradas_202207 {
    ZON VARCHAR
    CO_EJEC VARCHAR
    MDF VARCHAR
    ARM VARCHAR
    CDDIST VARCHAR
    FECENCUEST VARCHAR
  }
  DRH_Averias_Registradas_202208 {
    ZON VARCHAR
    CO_EJEC VARCHAR
    MDF VARCHAR
    ARM VARCHAR
    CDDIST VARCHAR
    FECENCUEST VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202201 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202202 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202203 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202204 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202205 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202206 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202207 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202208 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202209 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202210 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202211 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_TIPIFICACIONES_MES_202212 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202201_202206 {
    ID INT
    Proveedor VARCHAR
    Dni_Asesor VARCHAR
    Nombre_Asesor VARCHAR
    Servicio VARCHAR
    Plataforma VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202209 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202210 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202211 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202212 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  PLANTA_FIJA_202201 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202202 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202203 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_FIJA_202204 {
    Periodo VARCHAR
    abonadoatis VARCHAR
    FechaAltaAbonado VARCHAR
    Telefono VARCHAR
    Cliente VARCHAR
    Cuenta VARCHAR
  }
  PLANTA_MOVIL_202201 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202202 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  PLANTA_MOVIL_202203 {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
  }
  RESUMEN_REIT_TRANS_VOZ_2022 {
    PERIODO VARCHAR
    FECHA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
