erDiagram
  Visor_web_log_siem_202403 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202404 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202405 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202406 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202407 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202408 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202409 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202410 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202411 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202412 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202501 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202502 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202503 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202504 {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
  Visor_web_log_siem_202504_ant {
    id_key INT
    fecha VARCHAR
    resultado_accion VARCHAR
    app_origen VARCHAR
    cliente VARCHAR
    fecha_registro VARCHAR
  }
