erDiagram
  AVERIAS_LIQUIDADAS_202101 {
    INT id
    VARCHAR sample
  }
  AVERIAS_LIQUIDADAS_202102 {
    INT id
    VARCHAR sample
  }
  AVERIAS_LIQUIDADAS_202103 {
    INT id
    VARCHAR sample
  }
  AVERIAS_LIQUIDADAS_202104 {
    INT id
    VARCHAR sample
  }
  AVERIAS_LIQUIDADAS_202105 {
    INT id
    VARCHAR sample
  }
  AVERIAS_LIQUIDADAS_202106 {
    INT id
    VARCHAR sample
  }
  AVERIAS_LIQUIDADAS_202107 {
    INT id
    VARCHAR sample
  }
  AVERIAS_LIQUIDADAS_202108 {
    INT id
    VARCHAR sample
  }
  AVERIAS_LIQUIDADAS_202109 {
    INT id
    VARCHAR sample
  }
  AVERIAS_LIQUIDADAS_202110 {
    INT id
    VARCHAR sample
  }
  AVERIAS_LIQUIDADAS_202111 {
    INT id
    VARCHAR sample
  }
  AVERIAS_LIQUIDADAS_202112 {
    INT id
    VARCHAR sample
  }
  DEVUELTAS_COMERCIALES_QUIEBRE_202001 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_LIQUIDADAS_202101 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_LIQUIDADAS_202102 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_LIQUIDADAS_202103 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_LIQUIDADAS_202104 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_LIQUIDADAS_202105 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_LIQUIDADAS_202106 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_LIQUIDADAS_202107 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_LIQUIDADAS_202108 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_LIQUIDADAS_202109 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_LIQUIDADAS_202110 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_LIQUIDADAS_202111 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_LIQUIDADAS_202112 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_MASIVAS_202101 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_MASIVAS_202102 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_MASIVAS_202103 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_MASIVAS_202104 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_MASIVAS_202105 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_MASIVAS_202109 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_MASIVAS_202110 {
    INT id
    VARCHAR sample
  }
  LYT_AVERIAS_MASIVAS_202112 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_COMERCIALES_202101 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_COMERCIALES_202102 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_COMERCIALES_202103 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_COMERCIALES_202104 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_COMERCIALES_202105 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_COMERCIALES_202106 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_COMERCIALES_202107 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_COMERCIALES_202108 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_COMERCIALES_202109 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_COMERCIALES_202110 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_COMERCIALES_202111 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_COMERCIALES_202112 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_TECNICAS_202101 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_TECNICAS_202102 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_TECNICAS_202103 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_TECNICAS_202104 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_TECNICAS_202105 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_TECNICAS_202106 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_TECNICAS_202107 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_TECNICAS_202108 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_TECNICAS_202109 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_TECNICAS_202110 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_TECNICAS_202111 {
    INT id
    VARCHAR sample
  }
  LYT_DEVUELTAS_TECNICAS_202112 {
    INT id
    VARCHAR sample
  }
  LYT_PROVISION_EJECUTADA_202101 {
    INT id
    VARCHAR sample
  }
  LYT_PROVISION_EJECUTADA_202102 {
    INT id
    VARCHAR sample
  }
  LYT_PROVISION_EJECUTADA_202103 {
    INT id
    VARCHAR sample
  }
  LYT_PROVISION_EJECUTADA_202104 {
    INT id
    VARCHAR sample
  }
  LYT_PROVISION_EJECUTADA_202105 {
    INT id
    VARCHAR sample
  }
  LYT_PROVISION_EJECUTADA_202106 {
    INT id
    VARCHAR sample
  }
  LYT_PROVISION_EJECUTADA_202107 {
    INT id
    VARCHAR sample
  }
  LYT_PROVISION_EJECUTADA_202108 {
    INT id
    VARCHAR sample
  }
  LYT_PROVISION_EJECUTADA_202109 {
    INT id
    VARCHAR sample
  }
  LYT_PROVISION_EJECUTADA_202110 {
    INT id
    VARCHAR sample
  }
  LYT_PROVISION_EJECUTADA_202111 {
    INT id
    VARCHAR sample
  }
  LYT_PROVISION_EJECUTADA_202112 {
    INT id
    VARCHAR sample
  }
  LYT_VISOR_TIPIFICACIONES_202101_202112 {
    INT id
    VARCHAR sample
  }
  LYT_VISOR_TIPIFICACIONES_202207_202212 {
    INT id
    VARCHAR sample
  }
  MULTICONSULTA_ARBOL_DECISIONES_202106 {
    INT id
    VARCHAR sample
  }
  MULTICONSULTA_ARBOL_DECISIONES_202107 {
    INT id
    VARCHAR sample
  }
  MULTICONSULTA_ARBOL_DECISIONES_202108 {
    INT id
    VARCHAR sample
  }
  MULTICONSULTA_ARBOL_DECISIONES_202109 {
    INT id
    VARCHAR sample
  }
  MULTICONSULTA_ARBOL_DECISIONES_202110 {
    INT id
    VARCHAR sample
  }
  MULTICONSULTA_ARBOL_DECISIONES_202111 {
    INT id
    VARCHAR sample
  }
  MULTICONSULTA_ARBOL_DECISIONES_202112 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202101 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202102 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202103 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202104 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202105 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202106 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202107 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202108 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202109 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202110 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202111 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202112 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_UNICO_DIGITAL_202101 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_UNICO_DIGITAL_202102 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_UNICO_DIGITAL_202103 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_UNICO_DIGITAL_202104 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_UNICO_DIGITAL_202105 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_UNICO_DIGITAL_202106 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_UNICO_DIGITAL_202107 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_UNICO_DIGITAL_202108 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_UNICO_DIGITAL_202109 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_UNICO_DIGITAL_202110 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_UNICO_DIGITAL_202111 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_UNICO_DIGITAL_202112 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202101 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202102 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202103 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202104 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202105 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202106 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202107 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202108 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202109 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202110 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202111 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202112 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202101 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202102 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202103 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202104 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202105 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202106 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202107 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202108 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202109 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202110 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202111 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202112 {
    INT id
    VARCHAR sample
  }
  Planta_Movistar_Total_202101 {
    INT id
    VARCHAR sample
  }
  Planta_Movistar_Total_202102 {
    INT id
    VARCHAR sample
  }
  Planta_Movistar_Total_202103 {
    INT id
    VARCHAR sample
  }
  Planta_Movistar_Total_202104 {
    INT id
    VARCHAR sample
  }
  Planta_Movistar_Total_202105 {
    INT id
    VARCHAR sample
  }
  Planta_Movistar_Total_202106 {
    INT id
    VARCHAR sample
  }
  Planta_Movistar_Total_202107 {
    INT id
    VARCHAR sample
  }
  Planta_Movistar_Total_202108 {
    INT id
    VARCHAR sample
  }
  Planta_Movistar_Total_202109 {
    INT id
    VARCHAR sample
  }
  Planta_Movistar_Total_202110 {
    INT id
    VARCHAR sample
  }
  Planta_Movistar_Total_202111 {
    INT id
    VARCHAR sample
  }
  Planta_Movistar_Total_202112 {
    INT id
    VARCHAR sample
  }
  RESUMEN_REIT_TRANS_VOZ_202101_202112 {
    INT id
    VARCHAR sample
  }
  RESUMEN_TIPIFICACIONES_BASE_ENTRANTES_202101_202112 {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_AGENTES_TOTALES_2020_2021_2022 {
    INT id
    VARCHAR sample
  }
  DRH_Averias_Registradas {
    INT id
    VARCHAR sample
  }
  DRH_Averias_Registradas_202201 {
    INT id
    VARCHAR sample
  }
  DRH_Averias_Registradas_202202 {
    INT id
    VARCHAR sample
  }
  DRH_Averias_Registradas_202203 {
    INT id
    VARCHAR sample
  }
  DRH_Averias_Registradas_202204 {
    INT id
    VARCHAR sample
  }
  DRH_Averias_Registradas_202205 {
    INT id
    VARCHAR sample
  }
  DRH_Averias_Registradas_202206 {
    INT id
    VARCHAR sample
  }
  DRH_Averias_Registradas_202207 {
    INT id
    VARCHAR sample
  }
  DRH_Averias_Registradas_202208 {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES_202201 {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES_202202 {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES_202203 {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES_202204 {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES_202205 {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES_202206 {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES_202207 {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES_202208 {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES_202209 {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES_202210 {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES_202211 {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES_202212 {
    INT id
    VARCHAR sample
  }
  LYT_VISOR_TIPIFICACIONES_202201_202206 {
    INT id
    VARCHAR sample
  }
  LYT_VISOR_TIPIFICACIONES_202209 {
    INT id
    VARCHAR sample
  }
  LYT_VISOR_TIPIFICACIONES_202210 {
    INT id
    VARCHAR sample
  }
  LYT_VISOR_TIPIFICACIONES_202211 {
    INT id
    VARCHAR sample
  }
  LYT_VISOR_TIPIFICACIONES_202212 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202201 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202202 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202203 {
    INT id
    VARCHAR sample
  }
  PLANTA_FIJA_202204 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202201 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202202 {
    INT id
    VARCHAR sample
  }
  PLANTA_MOVIL_202203 {
    INT id
    VARCHAR sample
  }
  RESUMEN_REIT_TRANS_VOZ_2022 {
    INT id
    VARCHAR sample
  }
  RESUMEN_SATELITES_202411 {
    INT id
    VARCHAR sample
  }
  RESUMEN_SATELITES_202412 {
    INT id
    VARCHAR sample
  }
  RESUMEN_SATELITES_202501 {
    INT id
    VARCHAR sample
  }
  RESUMEN_SATELITES_202502 {
    INT id
    VARCHAR sample
  }
  RESUMEN_SATELITES_202503 {
    INT id
    VARCHAR sample
  }
  RESUMEN_SATELITES_202504 {
    INT id
    VARCHAR sample
  }
  RESUMEN_SATELITES_202505 {
    INT id
    VARCHAR sample
  }
  RESUMEN_SATELITES_202506 {
    INT id
    VARCHAR sample
  }
  RESUMEN_SATELITES_202507 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202403 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202404 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202405 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202406 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202407 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202408 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202409 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202410 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202411 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202412 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202501 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202502 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202503 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202504 {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_202504_ant {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202301 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202302 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202303 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202304 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202305 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202306 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202307 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202308 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202309 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202310 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202311 {
    INT id
    VARCHAR sample
  }
  PLANTA_CLIENTE_DIGITAL_202312 {
    INT id
    VARCHAR sample
  }
  STAGE.T_LISTA_TAREAS_PLANNER {
    INT id
    VARCHAR sample
  }
  Backup_Historial_Jobs_3meses {
    INT id
    VARCHAR sample
  }
  T_ADMIN_BASE_DATOS {
    INT id
    VARCHAR sample
  }
  T_ADMIN_BASE_DATOS_ANTERIOR {
    INT id
    VARCHAR sample
  }
  T_ADMIN_DISCO_DURO {
    INT id
    VARCHAR sample
  }
  T_ADMIN_DISCO_DURO_ANTERIOR {
    INT id
    VARCHAR sample
  }
  T_ADMIN_TAMANIO_TABLAS {
    INT id
    VARCHAR sample
  }
  T_ADMIN_TAMANIO_TABLAS_ANTERIOR {
    INT id
    VARCHAR sample
  }
  T_LISTA_USUARIOS_SQL {
    INT id
    VARCHAR sample
  }
  T_Lista_Tareas_Planner_Consolidado {
    INT id
    VARCHAR sample
  }
  T_WHO2_CAPTURA {
    INT id
    VARCHAR sample
  }
  USUARIOS {
    INT id
    VARCHAR sample
  }
  ECD_Encuestas_CCEE {
    INT id
    VARCHAR sample
  }
  ECD_TIPIFICACIONES_CCEE {
    INT id
    VARCHAR sample
  }
  ENCUESTAS_MEDALLIA_CHECA_TU_CASO {
    INT id
    VARCHAR sample
  }
  ENCUESTAS_MEDALLIA_ESPECIALIZADOS {
    INT id
    VARCHAR sample
  }
  USUARIOS_MULTICANAL_ULT_ACT {
    INT id
    VARCHAR sample
  }
  Ajustes_SAR_1_al_15_Marzo {
    INT id
    VARCHAR sample
  }
  Atendidas {
    INT id
    VARCHAR sample
  }
  Atendidas_Cobranzas {
    INT id
    VARCHAR sample
  }
  BASE_DEUDORA_1 {
    INT id
    VARCHAR sample
  }
  BASE_DEUDORA_2 {
    INT id
    VARCHAR sample
  }
  BASE_INTENTOS_QUEJA_VISOR_ART_70_2023_07 {
    INT id
    VARCHAR sample
  }
  Base_Contactos_wifi {
    INT id
    VARCHAR sample
  }
  CAL_MPH_ENCUESTAS_ACUMULADO_CALL_2023_05_06 {
    INT id
    VARCHAR sample
  }
  ENCUESTAS_IVR_OUT_202305 {
    INT id
    VARCHAR sample
  }
  ENCUESTAS_IVR_OUT_202306 {
    INT id
    VARCHAR sample
  }
  ENCUESTAS_IVR_OUT_FEEDBACK_GENESYS_202305 {
    INT id
    VARCHAR sample
  }
  ENCUESTAS_IVR_OUT_FEEDBACK_GENESYS_202306 {
    INT id
    VARCHAR sample
  }
  ENCUESTAS_IVR_OUT_FEEDBACK_GENESYS_202306_v2 {
    INT id
    VARCHAR sample
  }
  ENCUESTAS_IVR_OUT_LN_202305 {
    INT id
    VARCHAR sample
  }
  ENCUESTAS_LN_OUT_FEEDBACK_GENESYS_202305 {
    INT id
    VARCHAR sample
  }
  ESCM_Planta_Pangea_202304 {
    INT id
    VARCHAR sample
  }
  JSH_Base_planta_Fija_Velocidad_Configurada_OLTs {
    INT id
    VARCHAR sample
  }
  JSH_Contingencia_Art_70_Quejas_Apelaciones_reclamos_temp {
    INT id
    VARCHAR sample
  }
  JSH_Demanda_Call_Func_Movil {
    INT id
    VARCHAR sample
  }
  KAJ_ANAlisis_MSG_Abr {
    INT id
    VARCHAR sample
  }
  LINEAS_MOROSAS {
    INT id
    VARCHAR sample
  }
  LLAMADAS_ABRIL {
    INT id
    VARCHAR sample
  }
  LLAMADAS_ENERO {
    INT id
    VARCHAR sample
  }
  LLAMADAS_FEBRERO {
    INT id
    VARCHAR sample
  }
  LLAMADAS_FIJA_AGOSTO {
    INT id
    VARCHAR sample
  }
  LLAMADAS_FIJA_JULIO {
    INT id
    VARCHAR sample
  }
  LLAMADAS_MARZO {
    INT id
    VARCHAR sample
  }
  MPH_ENCUESTAS_ACUMULADO_CALL {
    INT id
    VARCHAR sample
  }
  TABLA_PROCESO_AUTO_1 {
    INT id
    VARCHAR sample
  }
  behm_Aura_Catalogo_CDU {
    INT id
    VARCHAR sample
  }
  behm_Aura_Eficiencias {
    INT id
    VARCHAR sample
  }
  behm_PBI_Aura_RepAtencion_history {
    INT id
    VARCHAR sample
  }
  data_Plan263_lumini {
    INT id
    VARCHAR sample
  }
  jsh_base_dnis_estudio_cosechas_mayo {
    INT id
    VARCHAR sample
  }
  AY_BD_DATOSMOVILES_HLR {
    INT id
    VARCHAR sample
  }
  AY_CLIENTES_UNICOS {
    INT id
    VARCHAR sample
  }
  AY_DATA {
    INT id
    VARCHAR sample
  }
  AY_INC {
    INT id
    VARCHAR sample
  }
  AY_INDICADORES_CONSOLIDADO_HIBRIDO_DIARIO {
    INT id
    VARCHAR sample
  }
  AY_INDICADORES_CONSOLIDADO_HIBRIDO_DIARIO_CL_UNICOS {
    INT id
    VARCHAR sample
  }
  AY_SMS_DIC_V3 {
    INT id
    VARCHAR sample
  }
  AY_SMS_Dic_V2 {
    INT id
    VARCHAR sample
  }
  BD_NERE {
    INT id
    VARCHAR sample
  }
  BD_NP {
    INT id
    VARCHAR sample
  }
  NP_FUNNEL_ACOTADO_RESUMEN {
    INT id
    VARCHAR sample
  }
  NP_FUNNEL_SUPER_ACOTADO_RESUMEN {
    INT id
    VARCHAR sample
  }
  PBI_RAT_LYT_ACCESADAS_AURA_RESUMEN_NOV24_JUL25 {
    INT id
    VARCHAR sample
  }
  RA_AURA_CUALQUIER_CDU_REIT {
    INT id
    VARCHAR sample
  }
  RA_AURA_MISMO_CDU_REIT {
    INT id
    VARCHAR sample
  }
  RA_AURA_REIT {
    INT id
    VARCHAR sample
  }
  RA_AVERIAS_REGISTRO_LN_MUESTRA {
    INT id
    VARCHAR sample
  }
  RA_ENCUESTAS_AURA_ULT_MES {
    INT id
    VARCHAR sample
  }
  RA_ENCUESTA_ULT3MESES {
    INT id
    VARCHAR sample
  }
  RA_ENCUESTA_ULT6MESES {
    INT id
    VARCHAR sample
  }
  RA_ENTENDIMIENTO_PREG_ABIERTA {
    INT id
    VARCHAR sample
  }
  RA_ENTENDIMIENTO_PREG_ABIERTA_MES {
    INT id
    VARCHAR sample
  }
  RA_FUNNEL_ACOTADO_RESUMEN {
    INT id
    VARCHAR sample
  }
  RA_LN_INDICADORES_CONSOLIDADO {
    INT id
    VARCHAR sample
  }
  RA_LN_INDICADORES_CONSOLIDADO_DIARIO {
    INT id
    VARCHAR sample
  }
  RA_REITERACION_DISENO_AURA_CUALQUIER_CDU {
    INT id
    VARCHAR sample
  }
  RA_REITERACION_DISENO_AURA_IND_CONSOL {
    INT id
    VARCHAR sample
  }
  RA_REITERACION_DISENO_AURA_MISMO_CDU {
    INT id
    VARCHAR sample
  }
  RA_RESUMEN_AURA_CUALQUIER_CDU_REIT {
    INT id
    VARCHAR sample
  }
  RA_RESUMEN_AURA_MISMO_CDU_REIT {
    INT id
    VARCHAR sample
  }
  SMS_Dic_v2 {
    INT id
    VARCHAR sample
  }
  sysdiagrams {
    INT id
    VARCHAR sample
  }
  20250219_Faco {
    INT id
    VARCHAR sample
  }
  20250219_Faco1 {
    INT id
    VARCHAR sample
  }
  20250219_Faco2 {
    INT id
    VARCHAR sample
  }
  DIM_MES {
    INT id
    VARCHAR sample
  }
  JCO_CAMPANAS_202503 {
    INT id
    VARCHAR sample
  }
  JCO_Faco_20250220_1 {
    INT id
    VARCHAR sample
  }
  JCO_RETEN_MOVIL {
    INT id
    VARCHAR sample
  }
  KAJ_DETALLE_ENTRANTES_VISOR_RET_DETALLE_1A1_V2 {
    INT id
    VARCHAR sample
  }
  KAJ_RESUMEN_ENTRANTES_VISOR_v2 {
    INT id
    VARCHAR sample
  }
  LD_CEI_LIMA_12DIC_26DIC_FINAL {
    INT id
    VARCHAR sample
  }
  LD_DHCP_240102 {
    INT id
    VARCHAR sample
  }
  LD_TELEMETRY_240102 {
    INT id
    VARCHAR sample
  }
  TEMP_ALDM_CASOS_MOTIVOS_TECNICOS {
    INT id
    VARCHAR sample
  }
  T_ALDM_Base_Interacciones_temp {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202401 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202402 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202403 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202403_1 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202404 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202405 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202406 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202407 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202408 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202409 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202410 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202411 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202412 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202501 {
    INT id
    VARCHAR sample
  }
  T_ALDM_Casos_consolidado_202502 {
    INT id
    VARCHAR sample
  }
  T_ALDM_base_casos_temp {
    INT id
    VARCHAR sample
  }
  AM_REPORTE_VENTAS_LIQUIDADAS {
    INT id
    VARCHAR sample
  }
  BASE_LISTA_CABINAS_TEMP {
    INT id
    VARCHAR sample
  }
  BEHM_CHATBOT_CATALOGOINTENCIONES {
    INT id
    VARCHAR sample
  }
  CCEE_AGENT_30MIN_PLATAFORMA {
    INT id
    VARCHAR sample
  }
  CCEE_AGENT_30MIN_PLATAFORMA_2024 {
    INT id
    VARCHAR sample
  }
  CCEE_ChatBot_Encuestas_PollBot {
    INT id
    VARCHAR sample
  }
  HP_REPORTE_FUNNEL_INVERTIDO {
    INT id
    VARCHAR sample
  }
  KC_SMS_APP {
    INT id
    VARCHAR sample
  }
  KC_SMS_APP_CCEE {
    INT id
    VARCHAR sample
  }
  KC_SMS_APP_TIENDAS {
    INT id
    VARCHAR sample
  }
  KC_SMS_APP_VOZ {
    INT id
    VARCHAR sample
  }
  POLL_AGENT {
    INT id
    VARCHAR sample
  }
  USERVAR_COMPARTIDO_202504 {
    INT id
    VARCHAR sample
  }
  USERVAR_COMPARTIDO_202505 {
    INT id
    VARCHAR sample
  }
  USERVAR_COMPARTIDO_202506 {
    INT id
    VARCHAR sample
  }
  USERVAR_COMPARTIDO_202507 {
    INT id
    VARCHAR sample
  }
  USERVAR_COMPARTIDO_202508 {
    INT id
    VARCHAR sample
  }
  USERVAR_COMPARTIDO_202509 {
    INT id
    VARCHAR sample
  }
  USERVAR_COMPARTIDO_202510 {
    INT id
    VARCHAR sample
  }
  USERVAR_COMPARTIDO_202511 {
    INT id
    VARCHAR sample
  }
  USERVAR_COMPARTIDO_202512 {
    INT id
    VARCHAR sample
  }
  USERVAR_COMPARTIDO_202601 {
    INT id
    VARCHAR sample
  }
  USERVAR_COMPARTIDO_202602 {
    INT id
    VARCHAR sample
  }
  USERVAR_COMPARTIDO_202603 {
    INT id
    VARCHAR sample
  }
  AM_Reporte_Seguimiento_cross_ccee_resumen {
    INT id
    VARCHAR sample
  }
  BASE_AGENTE {
    INT id
    VARCHAR sample
  }
  CCEE_AGENT_30MIN_PLATAFORMA {
    INT id
    VARCHAR sample
  }
  CCEE_T_DIM_CATEGORIA_PLATAFORMA {
    INT id
    VARCHAR sample
  }
  CCEE_T_DIM_PLATAFORMA {
    INT id
    VARCHAR sample
  }
  CCEE_T_DIM_PROVEEDOR {
    INT id
    VARCHAR sample
  }
  CCEE_T_DIM_TIEMPO_INTERVALO {
    INT id
    VARCHAR sample
  }
  CCEE_T_FACT_METRICAS_CCEE_INTERVALOS {
    INT id
    VARCHAR sample
  }
  CONSOLIDADO_METRICAS_AGENTE_CCEE {
    INT id
    VARCHAR sample
  }
  CONSOLIDADO_METRICAS_AGENTE_CCEE_DIARIO {
    INT id
    VARCHAR sample
  }
  PRONOSTICO_INTERNO_CCEE {
    INT id
    VARCHAR sample
  }
  RESUMEN_INDIC_GENERALES_VOZ_INTERVALO {
    INT id
    VARCHAR sample
  }
  RESUMEN_METRICAS_WFM_MENSUAL {
    INT id
    VARCHAR sample
  }
  RESUMEN_PRODUCTIVIDAD_PROVEEDOR_CCEE {
    INT id
    VARCHAR sample
  }
  RESUMEN_TRANSFERENCIAS_VOZ {
    INT id
    VARCHAR sample
  }
  T_DIM_MODELO_PAGO {
    INT id
    VARCHAR sample
  }
  T_DIM_NEGOCIO {
    INT id
    VARCHAR sample
  }
  T_DIM_PLATAFORMA {
    INT id
    VARCHAR sample
  }
  T_DIM_PROVEEDOR {
    INT id
    VARCHAR sample
  }
  T_DIM_TIEMPO_INTERVALO {
    INT id
    VARCHAR sample
  }
  T_INPUT_TOPE_NPS_1_2 {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_CTI_72HR {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_CTI_72HR_FACTURACION {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_CTI_MENSUAL {
    INT id
    VARCHAR sample
  }
  USUARIOS_RECLAMOS_ult_act {
    INT id
    VARCHAR sample
  }
  VW_BITACORA_EVENTOS_FORMATO_ANTERIOR {
    INT id
    VARCHAR sample
  }
  INFORMACION_CARGA_VISOR_TIPIS {
    INT id
    VARCHAR sample
  }
  KG_TEMP_VISOR {
    INT id
    VARCHAR sample
  }
  T_DIM_COLA {
    INT id
    VARCHAR sample
  }
  VISOR_TIPIFICACIONES_CURSO {
    INT id
    VARCHAR sample
  }
  sysdiagrams {
    INT id
    VARCHAR sample
  }
  tmp_tipificaciones_web {
    INT id
    VARCHAR sample
  }
  ENCUESTAS_AURA {
    INT id
    VARCHAR sample
  }
  T_DETALLE_CDR_LN_202506 {
    INT id
    VARCHAR sample
  }
  T_DETALLE_CDR_LN_202507 {
    INT id
    VARCHAR sample
  }
  T_DETALLE_CDR_LN_202508 {
    INT id
    VARCHAR sample
  }
  T_DETALLE_CDR_LN_202509 {
    INT id
    VARCHAR sample
  }
  T_DETALLE_CDR_LN_202510 {
    INT id
    VARCHAR sample
  }
  T_DETALLE_CDR_LN_202511 {
    INT id
    VARCHAR sample
  }
  T_DETALLE_CDR_LN_202512 {
    INT id
    VARCHAR sample
  }
  T_DETALLE_CDR_LN_202601 {
    INT id
    VARCHAR sample
  }
  T_DETALLE_CDR_LN_202602 {
    INT id
    VARCHAR sample
  }
  T_DETALLE_CDR_LN_MES {
    INT id
    VARCHAR sample
  }
  AM_DETALLE_CONTACT_ROAMING_POR_SEGMENTACION {
    INT id
    VARCHAR sample
  }
  BASE_25K_CX_2 {
    INT id
    VARCHAR sample
  }
  BD_CASUISTICAS_RO3 {
    INT id
    VARCHAR sample
  }
  CALCULO_PROYECCIONES {
    INT id
    VARCHAR sample
  }
  CONTROL_PROCESOS {
    INT id
    VARCHAR sample
  }
  DIM_AGRUPACION_CDU {
    INT id
    VARCHAR sample
  }
  HISPAM_Bench_CCEE {
    INT id
    VARCHAR sample
  }
  HISPAM_Bench_CU_CCEE {
    INT id
    VARCHAR sample
  }
  INDICADORES_GESTION {
    INT id
    VARCHAR sample
  }
  INDICADORES_GESTION_Revisar_JSH_20221212 {
    INT id
    VARCHAR sample
  }
  Input_Promedio_Diario {
    INT id
    VARCHAR sample
  }
  KCS_KPIS_ABORDAJE_GESTION_ {
    INT id
    VARCHAR sample
  }
  LD_KPIS_CONTACT_CENTER_PERU {
    INT id
    VARCHAR sample
  }
  OPER_CCEE_TABLERO_IMPRODUCTIVAS_CASOS_CERRADOS {
    INT id
    VARCHAR sample
  }
  OPER_CCEE_TABLERO_IMPRODUCTIVAS_CCEE {
    INT id
    VARCHAR sample
  }
  PBI_ACCESADAS_CLIENTES_UNICOS {
    INT id
    VARCHAR sample
  }
  PBI_BASE_MT {
    INT id
    VARCHAR sample
  }
  PBI_BASE_MT_DETALLE_MES {
    INT id
    VARCHAR sample
  }
  PBI_BASE_MT_RESUMEN {
    INT id
    VARCHAR sample
  }
  PBI_BASE_MT_RESUMEN_MOTIVO {
    INT id
    VARCHAR sample
  }
  PBI_BASE_MT_ULT_06_MESES {
    INT id
    VARCHAR sample
  }
  PBI_CBA_Plataformas_Ventas {
    INT id
    VARCHAR sample
  }
  PBI_CLIENTE_DIGITAL {
    INT id
    VARCHAR sample
  }
  PBI_ENTRANTES_CLIENTES_UNICOS {
    INT id
    VARCHAR sample
  }
  PBI_ENTRANTES_FECHA_LLAMADA {
    INT id
    VARCHAR sample
  }
  PBI_ENTRANTES_FECHA_LLAMADA_MOTIVO {
    INT id
    VARCHAR sample
  }
  PBI_ENTRANTES_FECHA_LLAMADA_MOTIVO_PREDOMINANTE {
    INT id
    VARCHAR sample
  }
  PBI_ENTRANTES_FECHA_LLAMADA_MOTIVO_PREVIO {
    INT id
    VARCHAR sample
  }
  PBI_FUNNEL_ACCESOS {
    INT id
    VARCHAR sample
  }
  PBI_FUNNEL_ACCESOS_ACCION {
    INT id
    VARCHAR sample
  }
  PBI_FUNNEL_ACCESOS_ACCION_NEGOCIOS {
    INT id
    VARCHAR sample
  }
  PBI_FUNNEL_ACCESOS_NEGOCIOS {
    INT id
    VARCHAR sample
  }
  PBI_FUNNEL_ACCESOS_temp {
    INT id
    VARCHAR sample
  }
  PBI_HRM_RELLAMADORES {
    INT id
    VARCHAR sample
  }
  PBI_INDICADORES_LENGUAJE_NATURAL {
    INT id
    VARCHAR sample
  }
  PBI_INDICADORES_LENGUAJE_NATURAL_CONTENCION {
    INT id
    VARCHAR sample
  }
  PBI_KAJ_AVERIAS_INGRESADAS {
    INT id
    VARCHAR sample
  }
  PBI_KAJ_AVERIAS_LIQUIDADAS {
    INT id
    VARCHAR sample
  }
  PBI_KAJ_AVERIAS_USABILIDAD_ARBOL {
    INT id
    VARCHAR sample
  }
  PBI_KAJ_ERROR_ENVIO_A_CAMPO {
    INT id
    VARCHAR sample
  }
  PBI_KAJ_RELLAMADORES_AVERIAS {
    INT id
    VARCHAR sample
  }
  PBI_KAJ_RESUMEN_RELLAMADORES_AVERIAS {
    INT id
    VARCHAR sample
  }
  PBI_KCS_ALTO_BAJO_TMO {
    INT id
    VARCHAR sample
  }
  PBI_KCS_LYT_ACCESADAS_AURA_RESUMEN {
    INT id
    VARCHAR sample
  }
  PBI_KCS_LYT_ACCESADAS_AURA_TEMP {
    INT id
    VARCHAR sample
  }
  PBI_KCS_REITERACION_DISENO_AURA {
    INT id
    VARCHAR sample
  }
  PBI_KCS_REITERACION_DISENO_AURA_7d {
    INT id
    VARCHAR sample
  }
  PBI_KCS_REITERACION_DISENO_AURA_7d_REPLICA_2024 {
    INT id
    VARCHAR sample
  }
  PBI_KCS_REITERACION_DISENO_AURA_ACCESADA {
    INT id
    VARCHAR sample
  }
  PBI_KCS_REITERACION_DISENO_AURA_ACCESADA_RESUMEN {
    INT id
    VARCHAR sample
  }
  PBI_KCS_REITERACION_DISENO_AURA_ACCESADA_RESUMEN1 {
    INT id
    VARCHAR sample
  }
  PBI_KCS_REITERACION_DISENO_AURA_TEMP {
    INT id
    VARCHAR sample
  }
  PBI_KCS_REITERACION_DISENO_AURA_TEMP_7d {
    INT id
    VARCHAR sample
  }
  PBI_KCS_REITERACION_DISENO_AURA_TEMP_ACCESADAS {
    INT id
    VARCHAR sample
  }
  PBI_KCS_TIPIFICACIONES {
    INT id
    VARCHAR sample
  }
  PBI_LD_REITERACION_DISENO_MISMO_CDU_AURA_TEMP {
    INT id
    VARCHAR sample
  }
  PBI_LD_REITERACION_DISENO_MISMO_CDU_AURA_TEMP_7d {
    INT id
    VARCHAR sample
  }
  PBI_LD_REITERACION_DISENO_MISMO_CDU_AURA_TEMP_ACCESADAS {
    INT id
    VARCHAR sample
  }
  PBI_MAQUETA_DIARIO {
    INT id
    VARCHAR sample
  }
  PBI_PLANTAS_ATENCIONES {
    INT id
    VARCHAR sample
  }
  PBI_PLANTAS_ATENCIONES_borrar {
    INT id
    VARCHAR sample
  }
  PBI_RSA_ACCESADAS {
    INT id
    VARCHAR sample
  }
  PBI_RSA_ACCESADAS_BACKUP {
    INT id
    VARCHAR sample
  }
  PBI_RSA_ACCESADAS_HIST {
    INT id
    VARCHAR sample
  }
  PBI_RSA_ACCESADAS_PRUEBA {
    INT id
    VARCHAR sample
  }
  PBI_RSA_ENTRANTES {
    INT id
    VARCHAR sample
  }
  PBI_RSA_ENTRANTES_HIST {
    INT id
    VARCHAR sample
  }
  PBI_RSA_ENTRANTES_SOCIOS {
    INT id
    VARCHAR sample
  }
  PBI_RSA_INDICADORES_OPERATIVOS {
    INT id
    VARCHAR sample
  }
  PBI_RSA_INDICADORES_OPERATIVOS_TOBE {
    INT id
    VARCHAR sample
  }
  PBI_TIPIFICACIONES_VISOR {
    INT id
    VARCHAR sample
  }
  PLANTA_PREVIA_FIJA {
    INT id
    VARCHAR sample
  }
  PLANTA_PREVIA_MOVIL {
    INT id
    VARCHAR sample
  }
  PesosProyecciones {
    INT id
    VARCHAR sample
  }
  RSA_ACCESADAS_ACCIONES_MOTIVOS {
    INT id
    VARCHAR sample
  }
  RSA_GRAFICA_ACCESADAS_BLOCKREASON {
    INT id
    VARCHAR sample
  }
  RSA_GRAFICA_ACCESADAS_BLOCKREASON_DETALLE {
    INT id
    VARCHAR sample
  }
  RSA_GRAFICA_ACCESADAS_BLOCKREASON_ant {
    INT id
    VARCHAR sample
  }
  RSA_GRAFICA_ACCESADAS_NEGOCIO_MOTIVO {
    INT id
    VARCHAR sample
  }
  RSA_GRAFICA_ACCESADAS_NEGOCIO_MOTIVO_TMP {
    INT id
    VARCHAR sample
  }
  RSA_GRAFICA_ATENDIDAS_ABANDONO {
    INT id
    VARCHAR sample
  }
  Tabla_Contencion_CCEE {
    INT id
    VARCHAR sample
  }
  Tabla_Peso_Promedio {
    INT id
    VARCHAR sample
  }
  VW_PBI_BASE_MT_RESUMEN_MOTIVO {
    INT id
    VARCHAR sample
  }
  VariacionesPromedioDiario {
    INT id
    VARCHAR sample
  }
  VariacionesPromedioDiario_borrar {
    INT id
    VARCHAR sample
  }
  VariacionesPromedioDiario_sem {
    INT id
    VARCHAR sample
  }
  indicadores_gestion_BORRAR {
    INT id
    VARCHAR sample
  }
  indicadores_gestion_entrantes {
    INT id
    VARCHAR sample
  }
  infomart_temp_todos_indicadores {
    INT id
    VARCHAR sample
  }
  prueba {
    INT id
    VARCHAR sample
  }
  sysdiagrams {
    INT id
    VARCHAR sample
  }
  telefonos_temp {
    INT id
    VARCHAR sample
  }
  tera {
    INT id
    VARCHAR sample
  }
  DRH_Catalogo_area_crm_grp {
    INT id
    VARCHAR sample
  }
  DRH_Catalogo_codigos_liquidacion {
    INT id
    VARCHAR sample
  }
  DRH_rpa {
    INT id
    VARCHAR sample
  }
  E2E_CASOS_BO {
    INT id
    VARCHAR sample
  }
  PREVIO_T_DIM_COLA {
    INT id
    VARCHAR sample
  }
  PREVIO_T_DIM_PLATAFORMA {
    INT id
    VARCHAR sample
  }
  PREVIO_T_DIM_PROGRAMA {
    INT id
    VARCHAR sample
  }
  PREVIO_T_LISTADO_DNIS_GENESYS {
    INT id
    VARCHAR sample
  }
  RETENCIONES_FIJA_ESTRATEGIA {
    INT id
    VARCHAR sample
  }
  T_DIM_COLA {
    INT id
    VARCHAR sample
  }
  T_DIM_PLATAFORMA {
    INT id
    VARCHAR sample
  }
  T_DIM_PROGRAMA {
    INT id
    VARCHAR sample
  }
  T_LISTADO_DNIS_GENESYS {
    INT id
    VARCHAR sample
  }
  Triaje_ReporteFCR {
    INT id
    VARCHAR sample
  }
  Triaje_ReporteRpa {
    INT id
    VARCHAR sample
  }
  Visor_web_log_siem_AVR {
    INT id
    VARCHAR sample
  }
  ind_usabilidad_log_siem_fcr_informe {
    INT id
    VARCHAR sample
  }
  ubigeo {
    INT id
    VARCHAR sample
  }
  web_log_siem {
    INT id
    VARCHAR sample
  }
  DIM.CASO_USO_AURA {
    INT id
    VARCHAR sample
  }
  DIM.COLA {
    INT id
    VARCHAR sample
  }
  DIM.FECHA {
    INT id
    VARCHAR sample
  }
  DIM.INTENT {
    INT id
    VARCHAR sample
  }
  DIM.TIPIFICACION {
    INT id
    VARCHAR sample
  }
  CATALOGO_VISOR_TIPIS {
    INT id
    VARCHAR sample
  }
  MOTIVO {
    INT id
    VARCHAR sample
  }
  T_DIM_COLA {
    INT id
    VARCHAR sample
  }
  T_DIM_PLATAFORMA {
    INT id
    VARCHAR sample
  }
  T_DIM_PROGRAMA {
    INT id
    VARCHAR sample
  }
  gmc_motivos_plataformas_202512 {
    INT id
    VARCHAR sample
  }
  Averias_Registradas_ACUMULADO {
    INT id
    VARCHAR sample
  }
  E2E_USUARIOS_CALL_CEE_B2C_HISTORICO {
    INT id
    VARCHAR sample
  }
  JSS_CATALOGO_UNIFICADO_CC {
    INT id
    VARCHAR sample
  }
  LD_SEGUIMIENTO_PROCESOS_AURA_Y_BOTMAKER {
    INT id
    VARCHAR sample
  }
  LYT_CONTACT_CENTER_ACCESADAS_202601 {
    INT id
    VARCHAR sample
  }
  LYT_CONTACT_CENTER_ACCESADAS_202602 {
    INT id
    VARCHAR sample
  }
  LYT_CONTACT_CENTER_ACCESADAS_202603 {
    INT id
    VARCHAR sample
  }
  LYT_CONTACT_CENTER_ENTRANTES_202601 {
    INT id
    VARCHAR sample
  }
  LYT_CONTACT_CENTER_ENTRANTES_202602 {
    INT id
    VARCHAR sample
  }
  LYT_CONTACT_CENTER_ENTRANTES_202603 {
    INT id
    VARCHAR sample
  }
  LYT_INTENT_SESIONES_202601 {
    INT id
    VARCHAR sample
  }
  LYT_INTENT_SESIONES_202602 {
    INT id
    VARCHAR sample
  }
  LYT_INTENT_SESIONES_202603 {
    INT id
    VARCHAR sample
  }
  LYT_INTERACCIONES_202601 {
    INT id
    VARCHAR sample
  }
  LYT_INTERACCIONES_202602 {
    INT id
    VARCHAR sample
  }
  LYT_INTERACCIONES_202603 {
    INT id
    VARCHAR sample
  }
  LYT_SESIONES_202601 {
    INT id
    VARCHAR sample
  }
  LYT_SESIONES_202602 {
    INT id
    VARCHAR sample
  }
  LYT_SESIONES_202603 {
    INT id
    VARCHAR sample
  }
  LYT_TIENDA_MES {
    INT id
    VARCHAR sample
  }
  LYT_TIPIFICACIONES_MES {
    INT id
    VARCHAR sample
  }
  LYT_VISOR_TIPIFICACIONES_202601 {
    INT id
    VARCHAR sample
  }
  LYT_VISOR_TIPIFICACIONES_202602 {
    INT id
    VARCHAR sample
  }
  LYT_VISOR_TIPIFICACIONES_202603 {
    INT id
    VARCHAR sample
  }
  TIPIFICACIONES_RETENCIONES_ULT_30D {
    INT id
    VARCHAR sample
  }
  USUARIOS_RECLAMOS_HISTORICO {
    INT id
    VARCHAR sample
  }
  dicccionario_v_exp {
    INT id
    VARCHAR sample
  }
  sysdiagrams {
    INT id
    VARCHAR sample
  }
  AGENTES_MIGRADOS {
    INT id
    VARCHAR sample
  }
  ArchivosCSV {
    INT id
    VARCHAR sample
  }
  ArchivosCSV_2 {
    INT id
    VARCHAR sample
  }
  CAPACIDAD_DE_ATENCION_ULT_ACT {
    INT id
    VARCHAR sample
  }
  COPIA_BASE_VISOR_RETEN_LOGICA_TRAMITADORES {
    INT id
    VARCHAR sample
  }
  COPIA_LISTA_RELLAMADORES_227 {
    INT id
    VARCHAR sample
  }
  CRONOGRAMA {
    INT id
    VARCHAR sample
  }
  Carga_Catalogo_CCPulce {
    INT id
    VARCHAR sample
  }
  Catalogo_Plataforma {
    INT id
    VARCHAR sample
  }
  Consolidado_Control_Envios {
    INT id
    VARCHAR sample
  }
  DETALLE_INTERVALO {
    INT id
    VARCHAR sample
  }
  DIAS_OPERATIVOS {
    INT id
    VARCHAR sample
  }
  DISTRIBUCION_PLATAFORMAS {
    INT id
    VARCHAR sample
  }
  DestinoDatos {
    INT id
    VARCHAR sample
  }
  DestinoDatos_CORREO_PEPE {
    INT id
    VARCHAR sample
  }
  DestinoDatos_temp1 {
    INT id
    VARCHAR sample
  }
  DestinoDatos_temp2 {
    INT id
    VARCHAR sample
  }
  ERLAG {
    INT id
    VARCHAR sample
  }
  EXPORTAR_MENSAJES_CORREO_PEPE {
    INT id
    VARCHAR sample
  }
  FORMATO_ERLAG {
    INT id
    VARCHAR sample
  }
  FTE_ACTIVOS {
    INT id
    VARCHAR sample
  }
  GTR_Conectados_Global {
    INT id
    VARCHAR sample
  }
  GTR_NDS_DIA {
    INT id
    VARCHAR sample
  }
  GTR_NDS_HORA {
    INT id
    VARCHAR sample
  }
  JCO_Consolidado_Control_Envios {
    INT id
    VARCHAR sample
  }
  JCO_PRUEBA_SMS {
    INT id
    VARCHAR sample
  }
  JCO_SMS_SEM {
    INT id
    VARCHAR sample
  }
  JCO_SMS_SEM_2 {
    INT id
    VARCHAR sample
  }
  KAJ_ANALISIS_AGENTES {
    INT id
    VARCHAR sample
  }
  KAJ_ANALISIS_FACO {
    INT id
    VARCHAR sample
  }
  KAJ_CANT_ENVIOS_TOTAL_MES {
    INT id
    VARCHAR sample
  }
  KAJ_CAPACIDAD_POR_DIA_MSG {
    INT id
    VARCHAR sample
  }
  KAJ_CAPACIDAD_SOCIO {
    INT id
    VARCHAR sample
  }
  KAJ_CAPACIDAD_SOCIO_ACUMULADO {
    INT id
    VARCHAR sample
  }
  KAJ_ENTRANTES {
    INT id
    VARCHAR sample
  }
  KAJ_ENVIOS_XDIA_PEDIDO {
    INT id
    VARCHAR sample
  }
  KAJ_FTES {
    INT id
    VARCHAR sample
  }
  KAJ_Fechas_Corte_Status {
    INT id
    VARCHAR sample
  }
  KAJ_IP_FM_2025 {
    INT id
    VARCHAR sample
  }
  KAJ_METRICAS_AGENTES_VOZ {
    INT id
    VARCHAR sample
  }
  KAJ_PREV_DIA_PPP_DETALLE {
    INT id
    VARCHAR sample
  }
  KAJ_PREV_PPP_DETALLE {
    INT id
    VARCHAR sample
  }
  KAJ_REPORTE_CAPACIDAD_LLAM_REQ_DOT_INI {
    INT id
    VARCHAR sample
  }
  KAJ_RESUMEN_AGENTE_ABAI {
    INT id
    VARCHAR sample
  }
  KAJ_RESUMEN_AGENTE_ATENTO {
    INT id
    VARCHAR sample
  }
  KAJ_RESUMEN_AGENTE_GSS {
    INT id
    VARCHAR sample
  }
  KAJ_RESUMEN_AGENTE_KONECTA {
    INT id
    VARCHAR sample
  }
  KAJ_RESUMEN_NOTIF_WHATSAPP {
    INT id
    VARCHAR sample
  }
  KAJ_RESUMEN_NOTIF_WHATSAPP_ACUMULADO {
    INT id
    VARCHAR sample
  }
  KAJ_RESUMEN_PLANTAS {
    INT id
    VARCHAR sample
  }
  KAJ_RESUMEN_PLANTA_FIJA {
    INT id
    VARCHAR sample
  }
  KAJ_STATUS_ACUMULADO {
    INT id
    VARCHAR sample
  }
  KAJ_faco_subscriber {
    INT id
    VARCHAR sample
  }
  KA_REQUERIDO_PLATAFORMA {
    INT id
    VARCHAR sample
  }
  KA_TEMP_INDICADORES {
    INT id
    VARCHAR sample
  }
  LOG_DIA_ENVIO_SMS_DERIVACION_WSAPP {
    INT id
    VARCHAR sample
  }
  Listar_Archivos {
    INT id
    VARCHAR sample
  }
  LogArchivosConvertidos {
    INT id
    VARCHAR sample
  }
  MGS_RESUMEN {
    INT id
    VARCHAR sample
  }
  MGS_RESUMEN_DIA {
    INT id
    VARCHAR sample
  }
  MGS_RESUMEN_HISTORICO {
    INT id
    VARCHAR sample
  }
  MGS_RESUMEN_PLANTA {
    INT id
    VARCHAR sample
  }
  MSGE_CONTROL_DANA {
    INT id
    VARCHAR sample
  }
  MSGE_CONTROL_DANA_ACUMULADO {
    INT id
    VARCHAR sample
  }
  MSGE_CONTROL_ENVIOS {
    INT id
    VARCHAR sample
  }
  MSGE_CONTROL_ENVIOS_ACUMULADO {
    INT id
    VARCHAR sample
  }
  MSG_CAPACIDAD_COMUNICACIONES {
    INT id
    VARCHAR sample
  }
  NO_BORRAR_BASE_FILTRAR_TRAMITADORES_ADHOC {
    INT id
    VARCHAR sample
  }
  NO_BORRAR_CDR_TODAY {
    INT id
    VARCHAR sample
  }
  NO_BORRAR_piloto_capta_fija_mt {
    INT id
    VARCHAR sample
  }
  NO_BORRAR_piloto_capta_movil_mt {
    INT id
    VARCHAR sample
  }
  PLANILLAS_PPP_MESES_ULT_ACT {
    INT id
    VARCHAR sample
  }
  PLANILLAS_PPP_MESES_ULT_ACT222 {
    INT id
    VARCHAR sample
  }
  PLANTILLA_REPORTE_CAPACIDAD {
    INT id
    VARCHAR sample
  }
  ProcesamientoLog {
    INT id
    VARCHAR sample
  }
  ProcesamientoLog_CORREO_PEPE {
    INT id
    VARCHAR sample
  }
  ProcesamientoLog_temporal {
    INT id
    VARCHAR sample
  }
  REDUCTORES {
    INT id
    VARCHAR sample
  }
  RESUMEN_CONSOLIDADO_NOTIFICACION_WHATSAPP {
    INT id
    VARCHAR sample
  }
  RESUMEN_DETALLE_INTERVALO {
    INT id
    VARCHAR sample
  }
  RESUMEN_INDICADORES_ERLANG {
    INT id
    VARCHAR sample
  }
  RESUMEN_INDIC_GENERALES_CCEE_DIA {
    INT id
    VARCHAR sample
  }
  RESUMEN_INDIC_GENERALES_CCEE_HORA {
    INT id
    VARCHAR sample
  }
  RESUMEN_INDIC_GENERALES_CCEE_INTERVALO {
    INT id
    VARCHAR sample
  }
  RESUMEN_INDIC_GENERALES_VOZ_DIA {
    INT id
    VARCHAR sample
  }
  RESUMEN_INDIC_GENERALES_VOZ_HORA {
    INT id
    VARCHAR sample
  }
  RESUMEN_INDIC_GENERALES_VOZ_INTERVALO {
    INT id
    VARCHAR sample
  }
  STATUS_WORKFORCE {
    INT id
    VARCHAR sample
  }
  STATUS_WORKFORCE_BACKUP {
    INT id
    VARCHAR sample
  }
  TABLA_TEMPORAL_FORMATO_A3_MES_EN_PROCESO {
    INT id
    VARCHAR sample
  }
  T_BASE_CRUCE_PILOTO_CAPTA_MT {
    INT id
    VARCHAR sample
  }
  T_BASE_PRUEBA {
    INT id
    VARCHAR sample
  }
  T_DIM_TIEMPO_INTERVALO {
    INT id
    VARCHAR sample
  }
  T_INFO_PREVISION_MES_PRONOSTICO {
    INT id
    VARCHAR sample
  }
  T_INFO_PREVISION_X_DIA_X_PLATAFORMA_PPP {
    INT id
    VARCHAR sample
  }
  T_INFO_PREVISION_X_INTERVALO_X_PLATAFORMA_PPP {
    INT id
    VARCHAR sample
  }
  T_INTERVALO_HORARIO {
    INT id
    VARCHAR sample
  }
  T_TEMP_FECHA {
    INT id
    VARCHAR sample
  }
  T_UMBRALES_PLATAFORMA_PPP {
    INT id
    VARCHAR sample
  }
  Temp_Status_Actual {
    INT id
    VARCHAR sample
  }
  Temporal_Cronograma {
    INT id
    VARCHAR sample
  }
  Temporal_Detalle_Intervalo {
    INT id
    VARCHAR sample
  }
  Temporal_Mallas_Tdp {
    INT id
    VARCHAR sample
  }
  Temporal_Reductores {
    INT id
    VARCHAR sample
  }
  listar_carpetas {
    INT id
    VARCHAR sample
  }
  listar_carpetas_procesar {
    INT id
    VARCHAR sample
  }
  PLANTA_CMS_202512 {
    INT id
    VARCHAR sample
  }
  LLAMADAS_CON_RETENCIONES_CRUZA_CON_VISOR_4M {
    INT id
    VARCHAR sample
  }
  LLAMADAS_RETECNIONES_CRUCE_VISOR_202510 {
    INT id
    VARCHAR sample
  }
  RETENCIONES_FIJA {
    INT id
    VARCHAR sample
  }
  RETENCIONES_MOVIL {
    INT id
    VARCHAR sample
  }
  RETENCIONES_MT {
    INT id
    VARCHAR sample
  }
  TABLERO_RETENCIONES_FIJA_MKT_ULT_ACT {
    INT id
    VARCHAR sample
  }
  TIPIFICACIONES_RETENCIONES_ULT_30D {
    INT id
    VARCHAR sample
  }
  TIPIFICACIONES_RETENCIONES_ULT_30D_REITERO {
    INT id
    VARCHAR sample
  }
  BASE_RECLAMOS_AVERIAS_DRH {
    INT id
    VARCHAR sample
  }
  CTRL_INTERACCIONES_TEMPORAL {
    INT id
    VARCHAR sample
  }
  CTRL_SESIONES_TEMPORAL {
    INT id
    VARCHAR sample
  }
  DETALLE_TABLERO_AVERIAS_LLAMADAS {
    INT id
    VARCHAR sample
  }
  E2E_DETALLE {
    INT id
    VARCHAR sample
  }
  E2E_DETALLE_2022 {
    INT id
    VARCHAR sample
  }
  E2E_DETALLE_2024 {
    INT id
    VARCHAR sample
  }
  E2E_DETALLE_RESUMEN_4M {
    INT id
    VARCHAR sample
  }
  E2E_DETALLE_RESUMEN_CALIDAD {
    INT id
    VARCHAR sample
  }
  E2E_REGISTROS_BO {
    INT id
    VARCHAR sample
  }
  INDICADORES_AGENTES_AVERIAS_SIN_INFORME {
    INT id
    VARCHAR sample
  }
  INDICADORES_AGENTES_DIARIO_ULTIMO_MES {
    INT id
    VARCHAR sample
  }
  INDICADORES_AGENTES_ULT_03M {
    INT id
    VARCHAR sample
  }
  INDICADORES_AVERIAS_DETALLE {
    INT id
    VARCHAR sample
  }
  KAJ_SKILL_FIBRA_REITERADOS {
    INT id
    VARCHAR sample
  }
  PILOTO_ASESORES {
    INT id
    VARCHAR sample
  }
  PILOTO_RESUMEN_AGENTES_CAPACITACION_TEC_FIJA {
    INT id
    VARCHAR sample
  }
  TEMPORAL_E2E_EVENTOS_MASIVOS {
    INT id
    VARCHAR sample
  }
  e2e_dic2024_extracto {
    INT id
    VARCHAR sample
  }
  SRM {
    INT id
    VARCHAR sample
  }
  VIEW_VISOR_LOGSIEM_CASO {
    INT id
    VARCHAR sample
  }
  VIEW_VISOR_LOGSIEM_CONTEXTO {
    INT id
    VARCHAR sample
  }
  VISOR_ADHERENCIA_DETALLE_USO_VISOR {
    INT id
    VARCHAR sample
  }
  VISOR_CONTROL_FUENTES {
    INT id
    VARCHAR sample
  }
  VISOR_LOGSIEM {
    INT id
    VARCHAR sample
  }
  VISOR_LOGSIEM_CONTEXTO_TOOL {
    INT id
    VARCHAR sample
  }
  VISOR_LOGUEOS {
    INT id
    VARCHAR sample
  }
  VISOR_RESET {
    INT id
    VARCHAR sample
  }
  internal.catalog_encryption_keys {
    INT id
    VARCHAR sample
  }
  internal.catalog_properties {
    INT id
    VARCHAR sample
  }
  internal.data_type_mapping {
    INT id
    VARCHAR sample
  }
  internal.environment_permissions {
    INT id
    VARCHAR sample
  }
  internal.environment_references {
    INT id
    VARCHAR sample
  }
  internal.environment_variables {
    INT id
    VARCHAR sample
  }
  internal.environments {
    INT id
    VARCHAR sample
  }
  internal.event_message_context {
    INT id
    VARCHAR sample
  }
  internal.event_messages {
    INT id
    VARCHAR sample
  }
  internal.executable_statistics {
    INT id
    VARCHAR sample
  }
  internal.executables {
    INT id
    VARCHAR sample
  }
  internal.execution_component_phases {
    INT id
    VARCHAR sample
  }
  internal.execution_data_statistics {
    INT id
    VARCHAR sample
  }
  internal.execution_data_taps {
    INT id
    VARCHAR sample
  }
  internal.execution_parameter_values {
    INT id
    VARCHAR sample
  }
  internal.execution_property_override_values {
    INT id
    VARCHAR sample
  }
  internal.executions {
    INT id
    VARCHAR sample
  }
  internal.extended_operation_info {
    INT id
    VARCHAR sample
  }
  internal.folder_permissions {
    INT id
    VARCHAR sample
  }
  internal.folders {
    INT id
    VARCHAR sample
  }
  internal.object_parameters {
    INT id
    VARCHAR sample
  }
  internal.object_versions {
    INT id
    VARCHAR sample
  }
  internal.operation_messages {
    INT id
    VARCHAR sample
  }
  internal.operation_os_sys_info {
    INT id
    VARCHAR sample
  }
  internal.operation_permissions {
    INT id
    VARCHAR sample
  }
  internal.operations {
    INT id
    VARCHAR sample
  }
  internal.packages {
    INT id
    VARCHAR sample
  }
  internal.project_permissions {
    INT id
    VARCHAR sample
  }
  internal.projects {
    INT id
    VARCHAR sample
  }
  internal.validations {
    INT id
    VARCHAR sample
  }
  20240917___LLAMADAS_ATENDIDAS_FACTURACION {
    INT id
    VARCHAR sample
  }
  20240917_____T_TMP_DETALLE {
    INT id
    VARCHAR sample
  }
  CORREOS {
    INT id
    VARCHAR sample
  }
  DEMANDA_BOLSA {
    INT id
    VARCHAR sample
  }
  DEMANDA_BOLSA_HISTORICO {
    INT id
    VARCHAR sample
  }
  DEMANDA_BOLSA_RESUMEN_PRIORIDAD_HORA {
    INT id
    VARCHAR sample
  }
  DEMANDA_BOLSA_RESUMEN_PRIORIDAD_HORA_ENTRANTES {
    INT id
    VARCHAR sample
  }
  DIAS_PROCESO_ACCESADAS {
    INT id
    VARCHAR sample
  }
  DIAS_PROCESO_CCEE {
    INT id
    VARCHAR sample
  }
  DZV_BD_ENTRANTES_RETENCIONES_202406 {
    INT id
    VARCHAR sample
  }
  ENCUESTAS {
    INT id
    VARCHAR sample
  }
  ENCUESTAS_AURA {
    INT id
    VARCHAR sample
  }
  ENCUESTAS_CCEE {
    INT id
    VARCHAR sample
  }
  FAY_EXCEL_M_X_A {
    INT id
    VARCHAR sample
  }
  FORMATO_MENSAJERIA_FIJA {
    INT id
    VARCHAR sample
  }
  FORMATO_MENSAJERIA_FIJA_FECHA_ARCHIVO {
    INT id
    VARCHAR sample
  }
  FORMATO_MENSAJERIA_MOVIL {
    INT id
    VARCHAR sample
  }
  JCO_LISTADO_CTI_DIARIO {
    INT id
    VARCHAR sample
  }
  LD_CLIENTES_REIT {
    INT id
    VARCHAR sample
  }
  LD_TMP_TABLA_BATCHERO_ELIMINA_ARCHIVOS_IHV5_POR_HORAS {
    INT id
    VARCHAR sample
  }
  LLAMADAS_ATENDIDAS {
    INT id
    VARCHAR sample
  }
  LLAMADAS_ATENDIDAS_FACTURACION {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_CONTROL {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_FIJA_DETALLE {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_FIJA_DETALLE_BACKUP {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_FIJA_DETALLE_NOCHE {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_FIJA_FECHA_BORRAR {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_FIJA_FECHA_MAXIMA {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_MOVIL_DETALLE {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_MOVIL_DETALLE_NOCHE {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_MOVIL_FECHA_BORRAR {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_MOVIL_FECHA_MAXIMA {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_RESUMEN {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_RESUMENES {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_RESUMEN_CCEE {
    INT id
    VARCHAR sample
  }
  MENSAJERIA_RESUMEN_VARIACION {
    INT id
    VARCHAR sample
  }
  MP_SUBMOTIVO_DIA {
    INT id
    VARCHAR sample
  }
  MP_SUBMOTIVO_DIA_CCEE {
    INT id
    VARCHAR sample
  }
  MP_SUBMOTIVO_DIA_CLIENTES {
    INT id
    VARCHAR sample
  }
  MP_SUBMOTIVO_DIA_CLIENTES_CCEE {
    INT id
    VARCHAR sample
  }
  MP_SUBMOTIVO_MES {
    INT id
    VARCHAR sample
  }
  MP_SUBMOTIVO_MES_CCEE {
    INT id
    VARCHAR sample
  }
  MP_SUBMOTIVO_MES_CLIENTES {
    INT id
    VARCHAR sample
  }
  MP_SUBMOTIVO_MES_CLIENTES_CCEE {
    INT id
    VARCHAR sample
  }
  MP_SUBMOTIVO_SEM {
    INT id
    VARCHAR sample
  }
  MP_SUBMOTIVO_SEM_CCEE {
    INT id
    VARCHAR sample
  }
  MP_SUBMOTIVO_SEM_CLIENTES {
    INT id
    VARCHAR sample
  }
  MP_SUBMOTIVO_SEM_CLIENTES_CCEE {
    INT id
    VARCHAR sample
  }
  PROCESO_LOG_PROCESO_REIT_Y_TRANSF {
    INT id
    VARCHAR sample
  }
  TEMP_TRAZABILIDAD_E2E_REIT {
    INT id
    VARCHAR sample
  }
  TMP_CTI {
    INT id
    VARCHAR sample
  }
  TMP_RESUMEN_AGENTE_REITERADAS {
    INT id
    VARCHAR sample
  }
  TMP_RESUMEN_AGENTE_REITERADAS_CUARTIL {
    INT id
    VARCHAR sample
  }
  TMP_RESUMEN_CTI {
    INT id
    VARCHAR sample
  }
  TMP_RESUMEN_Q_RELL {
    INT id
    VARCHAR sample
  }
  TMP_RESUMEN_Q_TRX {
    INT id
    VARCHAR sample
  }
  TMP_T_RESUMEN_AGENTE_TRANSF_CUARTIL {
    INT id
    VARCHAR sample
  }
  TMP_T_RESUMEN_AGENTE_TRX {
    INT id
    VARCHAR sample
  }
  T_DETALLE_CDR_LN_MES_TODAY {
    INT id
    VARCHAR sample
  }
  T_DETALLE_RELLAMADORES_ENTRANTES {
    INT id
    VARCHAR sample
  }
  T_DETALLE_RELLAMADORES_ENTRANTES_X_PLATAF {
    INT id
    VARCHAR sample
  }
  T_DETALLE_RELLAMADORES_EN_20D {
    INT id
    VARCHAR sample
  }
  T_DETALLE_TRANSFERENCIAS_MISMO_RP {
    INT id
    VARCHAR sample
  }
  T_DETALLE_TRANSFERENCIAS_MISMO_RP_2 {
    INT id
    VARCHAR sample
  }
  T_DIM_ARBOL_IVR {
    INT id
    VARCHAR sample
  }
  T_DIM_COLA {
    INT id
    VARCHAR sample
  }
  T_DIM_COLA_ORIGEN {
    INT id
    VARCHAR sample
  }
  T_DIM_FUENTE {
    INT id
    VARCHAR sample
  }
  T_DIM_JERARQUIA_EMPRESA {
    INT id
    VARCHAR sample
  }
  T_DIM_MODELO_PAGO {
    INT id
    VARCHAR sample
  }
  T_DIM_NEGOCIO {
    INT id
    VARCHAR sample
  }
  T_DIM_PLATAFORMA {
    INT id
    VARCHAR sample
  }
  T_DIM_PROGRAMA {
    INT id
    VARCHAR sample
  }
  T_DIM_PROVEEDOR {
    INT id
    VARCHAR sample
  }
  T_DIM_PROVEEDOR_LOCAL {
    INT id
    VARCHAR sample
  }
  T_DIM_SEGMENTO {
    INT id
    VARCHAR sample
  }
  T_DIM_SISTEMA_COMERCIAL {
    INT id
    VARCHAR sample
  }
  T_DIM_TIEMPO_DIA {
    INT id
    VARCHAR sample
  }
  T_DIM_TIEMPO_INTERVALO {
    INT id
    VARCHAR sample
  }
  T_DIM_TIPO_DISTRIBUCION_CALL {
    INT id
    VARCHAR sample
  }
  T_DIM_TIPO_GESTION {
    INT id
    VARCHAR sample
  }
  T_DIM_TIPO_INTERACCION {
    INT id
    VARCHAR sample
  }
  T_DIM_TIPO_INTERVALO {
    INT id
    VARCHAR sample
  }
  T_LISTA_AGENTE_REIT_DIA {
    INT id
    VARCHAR sample
  }
  T_LISTA_AGENTE_TRANSF_DIA {
    INT id
    VARCHAR sample
  }
  T_LISTA_BLANCA {
    INT id
    VARCHAR sample
  }
  T_LISTA_BLANCA_RELLAMADORES_AURA {
    INT id
    VARCHAR sample
  }
  T_LISTA_CTI_ATENDIDAS_TMO {
    INT id
    VARCHAR sample
  }
  T_LISTA_NEGRA {
    INT id
    VARCHAR sample
  }
  T_LISTA_RETIRAR_RPS_CLIENTES_NO_MIGRADOS {
    INT id
    VARCHAR sample
  }
  T_LISTA_RETIRAR_RPS_CLIENTES_NO_MIGRADOS_20241022 {
    INT id
    VARCHAR sample
  }
  T_LOG_BASE_NPS_AVISO_CORTE {
    INT id
    VARCHAR sample
  }
  T_METRICAS_REIT_TRANSF_AMELIA {
    INT id
    VARCHAR sample
  }
  T_METRICAS_TRANSFERENCIAS_DIA_CURSO {
    INT id
    VARCHAR sample
  }
  T_REPORTE_CTI_DIARIO {
    INT id
    VARCHAR sample
  }
  T_REPORTE_CTI_MENSUAL {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_COPC_72HR_ATENDIDAS {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_COPC_72HR_ATENDIDAS_BU {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_COPC_72_HR_GENERA {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_COPC_72_HR_GENERA_BU {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_COPC_ORI_DES_72HR {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_CTI_72HR {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_CTI_72HR_FACTURACION {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_CTI_DIARIO {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_CUARTILES {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_CUARTILES_FINAL {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_METRICAS_PLATAFORMA {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_METRICAS_REITERADAS_TRX_ODS {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_ORIGEN_DESTINO_PRUEBA {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_QUARTIL_RELL {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_QUARTIL_RELL_30MIN {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_QUARTIL_TRANS {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_RANGO_RELLAMADORES_EN_IVR {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_REITERADAS_TRXS {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_REITERADAS_TRXS_BU {
    INT id
    VARCHAR sample
  }
  T_RESUMEN_TRANSFERENCIAS_MISMP_RP {
    INT id
    VARCHAR sample
  }
  T_RES_ANALISIS_CLIENTES_TEC_FIJA {
    INT id
    VARCHAR sample
  }
  T_RES_INDICADOR_REIT_DIARIO {
    INT id
    VARCHAR sample
  }
  T_Resumen_Reiteracion_IVR {
    INT id
    VARCHAR sample
  }
  T_TABLA_RESUMEN_REPETICIONES {
    INT id
    VARCHAR sample
  }
  T_TMP_DETALLE {
    INT id
    VARCHAR sample
  }
  T_TMP_DETALLE_DIARIO {
    INT id
    VARCHAR sample
  }
  T_TMP_DETALLE_DIA_CURSO {
    INT id
    VARCHAR sample
  }
  T_TMP_DETALLE_TRAFICO {
    INT id
    VARCHAR sample
  }
  T_TMP_DETALLE_TRAFICO_TRANSFERENCIAS {
    INT id
    VARCHAR sample
  }
  T_TMP_DETALLE_TRAFICO_VENTAS {
    INT id
    VARCHAR sample
  }
  T_TMP_DETALLE_TRANSFERENCIAS {
    INT id
    VARCHAR sample
  }
  T_TMP_LD_CLIENTES_REITERADORES {
    INT id
    VARCHAR sample
  }
  T_TMP_TMO_REAL {
    INT id
    VARCHAR sample
  }
  T_TMP_TRAFICO {
    INT id
    VARCHAR sample
  }
  T_TMP_TRAZABILIDAD_CDR__TRANSF_MOVIL_A_FIJA {
    INT id
    VARCHAR sample
  }
  base_multicentro {
    INT id
    VARCHAR sample
  }
