#!/usr/bin/env python3
"""
MEP Reconstruct Scanner — Extrae artefactos de reconstrucción desde MEP outputs.

Parsea CSVs del gatherer (tables, columns, PKs, FKs, indexes, SPs, views, triggers),
SSIS packages (.dtsx), y agent jobs para producir:
  - DDL reconstruido (CREATE TABLE, INDEX, FK)
  - Relaciones FK para diagrama ER (Mermaid)
  - Lineage inferido de SQL en SPs/views/triggers/SSIS
  - Inventario de lógica de negocio
  - Análisis de completitud de datos
  - Mapa de dependencias cross-server

Uso:
    python3 mep_qa/reconstruct_scanner.py --mep-path <ruta_mep_extraído> --output <dir>
"""

import argparse
import csv
import json
import os
import re
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path

# ── CSV Reading Helpers ──────────────────────────────────────────────────────

def safe_read_csv(filepath, max_rows=None):
    """Read CSV with encoding detection, return list of dicts."""
    for enc in ["utf-8-sig", "utf-8", "latin-1", "utf-16"]:
        try:
            with open(filepath, "r", encoding=enc, errors="replace") as f:
                # Detect delimiter
                sample = f.read(2048)
                f.seek(0)
                delim = "\t" if sample.count("\t") > sample.count(",") else ","
                reader = csv.DictReader(f, delimiter=delim)
                rows = []
                for i, row in enumerate(reader):
                    if max_rows and i >= max_rows:
                        break
                    rows.append(row)
                return rows
        except Exception:
            continue
    return []


def find_csvs(base_path, pattern):
    """Find CSV files matching a name pattern (case-insensitive)."""
    results = []
    pattern_lower = pattern.lower()
    for f in Path(base_path).rglob("*.csv"):
        if pattern_lower in f.name.lower():
            results.append(f)
    return sorted(results)


# ── DDL Reconstruction ───────────────────────────────────────────────────────

def extract_tables_columns(mep_path):
    """Extract table/column definitions from gatherer CSVs."""
    tables = defaultdict(lambda: {"columns": [], "schema": "", "db": ""})

    # Find tables_columns CSVs (S01 for MSSQL, 03 for PG, tables.csv for MySQL)
    csv_files = (
        find_csvs(mep_path, "tables_columns")
        + find_csvs(mep_path, "S01_tables")
        + find_csvs(mep_path, "data_dictionary")
    )

    for csv_file in csv_files:
        # Infer DB name from directory path
        parts = csv_file.parts
        db_name = ""
        schema_from_path = ""
        for idx, p in enumerate(parts):
            if p.startswith("mep_sqlserver") or p.startswith("mep_pg"):
                # Next dir after mep_* is the DB name (for MSSQL: mep_sqlserver_SRV_DATE/DBNAME/schema/)
                remaining = parts[idx+1:]
                if len(remaining) >= 2:
                    db_name = remaining[0]
                    schema_from_path = remaining[1]
                elif len(remaining) == 1:
                    db_name = remaining[0]
            elif p.startswith("mep_") and "_20" in p:
                segments = p.split("_")
                for j, seg in enumerate(segments):
                    if seg.startswith("20") and len(seg) >= 8:
                        db_name = "_".join(segments[2:j]) if len(segments) > 3 else segments[-2]
                        break

        # Detect headerless TSV (MSSQL gatherer outputs positional TSV)
        rows = safe_read_csv(csv_file, max_rows=2)
        is_headerless_tsv = False
        if rows:
            first_keys = list(rows[0].keys())
            # If first key looks like data (schema name like "dbo"), it's headerless
            if first_keys and first_keys[0] in ("dbo", "sys", "INFORMATION_SCHEMA", "guest"):
                is_headerless_tsv = True
            # Also check if keys are numbers (auto-generated by DictReader)
            elif first_keys and all(k.isdigit() for k in first_keys[:3] if k):
                is_headerless_tsv = True

        if is_headerless_tsv:
            # Re-read as positional TSV with MSSQL S01 columns:
            # schema, table, created, modified, row_count, column, ordinal, datatype, max_len, precision, scale, nullable_flag, identity_flag, default, comment
            mssql_headers = ["schema","table","created","modified","row_count","column","ordinal","datatype","max_len","precision","scale","nullable_flag","identity_flag","col_default","comment"]
            raw_rows = []
            for enc in ["utf-8-sig", "utf-8", "latin-1"]:
                try:
                    with open(csv_file, "r", encoding=enc, errors="replace") as f:
                        reader = csv.reader(f, delimiter="\t")
                        for line in reader:
                            if len(line) >= 8:
                                row_dict = {}
                                for i, h in enumerate(mssql_headers):
                                    row_dict[h] = line[i] if i < len(line) else ""
                                raw_rows.append(row_dict)
                    break
                except Exception:
                    continue
            rows = raw_rows
        else:
            rows = safe_read_csv(csv_file)

        for row in rows:
            # Normalize column names across engines (including positional MSSQL)
            schema = (
                row.get("schema", "")
                or row.get("table_schema", "")
                or row.get("SchemaName", "")
                or row.get("TABLE_SCHEMA", "")
                or schema_from_path
                or "dbo"
            )
            table = (
                row.get("table", "")
                or row.get("table_name", "")
                or row.get("TableName", "")
                or row.get("TABLE_NAME", "")
            )
            if not table:
                continue

            key = f"{db_name}.{schema}.{table}" if db_name else f"{schema}.{table}"
            tables[key]["schema"] = schema
            tables[key]["db"] = db_name

            col_name = (
                row.get("column", "")
                or row.get("column_name", "")
                or row.get("ColumnName", "")
                or row.get("COLUMN_NAME", "")
            )
            if not col_name:
                continue

            data_type = (
                row.get("datatype", "")
                or row.get("data_type", "")
                or row.get("DataType", "")
                or row.get("DATA_TYPE", "")
            )
            max_len = (
                row.get("character_maximum_length", "")
                or row.get("MaxLength", "")
                or row.get("CHARACTER_MAXIMUM_LENGTH", "")
            )
            is_nullable = (
                row.get("is_nullable", "")
                or row.get("IsNullable", "")
                or row.get("IS_NULLABLE", "")
            )
            col_default = (
                row.get("column_default", "")
                or row.get("ColumnDefault", "")
                or row.get("COLUMN_DEFAULT", "")
            )
            ordinal = (
                row.get("ordinal_position", "")
                or row.get("OrdinalPosition", "")
                or row.get("ORDINAL_POSITION", "")
            )

            # Table size info if available (MSSQL positional: row_count is column 5)
            table_size = row.get("table_size", "") or row.get("TableSize", "") or row.get("max_len", "")
            est_rows = (
                row.get("row_count", "")
                or row.get("estimated_rows", "")
                or row.get("RowCount", "")
                or row.get("Rows", "")
            )

            # Deduplicate columns by name within the same table
            existing_col_names = {c["name"] for c in tables[key]["columns"]}
            if col_name not in existing_col_names:
                tables[key]["columns"].append({
                    "name": col_name,
                    "type": data_type,
                    "max_length": max_len,
                    "nullable": is_nullable,
                    "default": col_default,
                    "ordinal": ordinal,
                })

            if table_size and "table_size" not in tables[key]:
                tables[key]["table_size"] = table_size
            if est_rows and "est_rows" not in tables[key]:
                tables[key]["est_rows"] = est_rows

    return dict(tables)


def extract_primary_keys(mep_path):
    """Extract PK definitions."""
    pks = defaultdict(list)  # table_key -> [column_names]
    csv_files = find_csvs(mep_path, "primary_key") + find_csvs(mep_path, "S02_primary")

    for csv_file in csv_files:
        # MSSQL S02_primary_keys.csv is headerless TSV:
        # schema, table, pk_name, column, ordinal
        mssql_pk_headers = ["schema", "table", "pk_name", "column", "ordinal"]

        raw_rows = []
        for enc in ["utf-8-sig", "utf-8", "latin-1"]:
            try:
                with open(csv_file, "r", encoding=enc, errors="replace") as f:
                    sample = f.readline()
                    f.seek(0)
                    is_tsv = sample.count("\t") >= 3
                    first_field = sample.split("\t")[0].strip() if is_tsv else sample.split(",")[0].strip()
                    is_headerless = first_field in ("dbo", "sys", "DIM", "INFORMATION_SCHEMA", "guest")

                    if is_tsv and is_headerless:
                        reader = csv.reader(f, delimiter="\t")
                        for line in reader:
                            if len(line) >= 4:
                                row_dict = {mssql_pk_headers[i]: line[i] if i < len(line) else "" for i in range(len(mssql_pk_headers))}
                                raw_rows.append(row_dict)
                    else:
                        f.seek(0)
                        delim = "\t" if is_tsv else ","
                        reader = csv.DictReader(f, delimiter=delim)
                        raw_rows = list(reader)
                break
            except Exception:
                continue

        for row in raw_rows:
            schema = (
                row.get("schema", "")
                or row.get("table_schema", "")
                or row.get("SchemaName", "")
                or "dbo"
            )
            table = (
                row.get("table", "")
                or row.get("table_name", "")
                or row.get("TableName", "")
            )
            col = (
                row.get("column", "")
                or row.get("column_name", "")
                or row.get("ColumnName", "")
            )

            if not table or not col:
                continue

            key = f"{schema}.{table}"
            if col not in pks[key]:
                pks[key].append(col)

    return dict(pks)


def extract_foreign_keys(mep_path):
    """Extract FK relationships."""
    fks = []
    csv_files = find_csvs(mep_path, "foreign_key") + find_csvs(mep_path, "S04_")

    for csv_file in csv_files:
        # MSSQL S04_foreign_keys.csv is headerless TSV:
        # from_schema, from_table, fk_name, from_col, ordinal, to_schema, to_table, to_col, delete_action, update_action, is_disabled
        mssql_fk_headers = [
            "from_schema", "from_table", "fk_name", "from_col", "ordinal",
            "to_schema", "to_table", "to_col", "delete_action", "update_action", "is_disabled",
        ]

        # Detect if headerless TSV
        raw_rows = []
        for enc in ["utf-8-sig", "utf-8", "latin-1"]:
            try:
                with open(csv_file, "r", encoding=enc, errors="replace") as f:
                    sample = f.readline()
                    f.seek(0)
                    is_tsv = sample.count("\t") >= 5
                    # Check if first field looks like a schema name (not a header)
                    first_field = sample.split("\t")[0].strip() if is_tsv else sample.split(",")[0].strip()
                    is_headerless = first_field in ("dbo", "sys", "DIM", "INFORMATION_SCHEMA") or (
                        is_tsv and not any(h in sample.lower() for h in ["constraint", "table_name", "column"])
                    )

                    if is_tsv and is_headerless:
                        reader = csv.reader(f, delimiter="\t")
                        for line in reader:
                            if len(line) >= 8:
                                row_dict = {mssql_fk_headers[i]: line[i] if i < len(line) else "" for i in range(len(mssql_fk_headers))}
                                raw_rows.append(row_dict)
                    else:
                        f.seek(0)
                        reader = csv.DictReader(f, delimiter="\t" if is_tsv else ",")
                        raw_rows = list(reader)
                break
            except Exception:
                continue

        for row in raw_rows:
            fk_name = row.get("fk_name", row.get("constraint_name", row.get("FKName", "")))
            from_schema = row.get("from_schema", row.get("table_schema", row.get("SchemaName", "dbo")))
            from_table = row.get("from_table", row.get("table_name", row.get("TableName", "")))
            from_col = row.get("from_col", row.get("column_name", row.get("ColumnName", "")))
            to_schema = row.get("to_schema", row.get("referenced_table_schema", row.get("RefSchemaName", "dbo")))
            to_table = row.get("to_table", row.get("referenced_table_name", row.get("RefTableName", "")))
            to_col = row.get("to_col", row.get("referenced_column_name", row.get("RefColumnName", "")))

            if from_table and to_table:
                fks.append({
                    "name": fk_name,
                    "from": f"{from_schema}.{from_table}",
                    "from_col": from_col,
                    "to": f"{to_schema}.{to_table}",
                    "to_col": to_col,
                })
    return fks


def extract_indexes(mep_path):
    """Extract index definitions."""
    indexes = defaultdict(list)
    csv_files = find_csvs(mep_path, "index")

    for csv_file in csv_files:
        if "fulltext" in csv_file.name.lower():
            continue
        rows = safe_read_csv(csv_file)
        for row in rows:
            schema = row.get("SchemaName", row.get("table_schema", "dbo"))
            table = row.get("TableName", row.get("table_name", ""))
            idx_name = row.get("IndexName", row.get("index_name", ""))
            idx_type = row.get("IndexType", row.get("index_type", ""))
            is_unique = row.get("IsUnique", row.get("is_unique", ""))
            columns = row.get("IndexColumns", row.get("columns", row.get("column_name", "")))

            if table and idx_name:
                key = f"{schema}.{table}"
                indexes[key].append({
                    "name": idx_name,
                    "type": idx_type,
                    "unique": is_unique,
                    "columns": columns,
                })
    return dict(indexes)


def generate_ddl(tables, pks, fks, indexes):
    """Generate DDL SQL from extracted metadata."""
    ddl_statements = []

    for table_key, info in sorted(tables.items()):
        parts = table_key.rsplit(".", 2)
        if len(parts) == 3:
            schema, table = parts[1], parts[2]
        elif len(parts) == 2:
            schema, table = parts[0], parts[1]
        else:
            schema, table = "dbo", parts[0]

        cols = sorted(info["columns"], key=lambda c: int(c.get("ordinal", 0) or 0))
        if not cols:
            continue

        lines = []
        for col in cols:
            type_str = col["type"]
            if col["max_length"] and col["max_length"] not in ("-1", "", "None"):
                type_str += f"({col['max_length']})"
            elif col["max_length"] == "-1":
                type_str += "(MAX)"

            null_str = "NULL" if col["nullable"] in ("YES", "True", "1") else "NOT NULL"
            default_str = f" DEFAULT {col['default']}" if col["default"] and col["default"] != "None" else ""
            lines.append(f"    [{col['name']}] {type_str} {null_str}{default_str}")

        # Add PK constraint
        pk_key = f"{schema}.{table}"
        if pk_key in pks:
            pk_cols = ", ".join(f"[{c}]" for c in pks[pk_key])
            lines.append(f"    CONSTRAINT [PK_{table}] PRIMARY KEY ({pk_cols})")

        ddl = f"CREATE TABLE [{schema}].[{table}] (\n"
        ddl += ",\n".join(lines)
        ddl += "\n);"
        ddl_statements.append(ddl)

    # FK constraints
    for fk in fks:
        from_parts = fk["from"].split(".")
        to_parts = fk["to"].split(".")
        fk_ddl = (
            f"ALTER TABLE [{from_parts[-2] if len(from_parts)>1 else 'dbo'}].[{from_parts[-1]}]\n"
            f"    ADD CONSTRAINT [{fk['name']}]\n"
            f"    FOREIGN KEY ([{fk['from_col']}])\n"
            f"    REFERENCES [{to_parts[-2] if len(to_parts)>1 else 'dbo'}].[{to_parts[-1]}] ([{fk['to_col']}]);"
        )
        ddl_statements.append(fk_ddl)

    return ddl_statements


# ── ER Diagram (Mermaid) ─────────────────────────────────────────────────────

def generate_mermaid_er(tables, fks, pks=None, max_tables=50):
    """Generate Mermaid ER diagram from tables and FK relationships."""
    if pks is None:
        pks = {}

    # Only include tables involved in FK relationships
    fk_tables = set()
    for fk in fks:
        fk_tables.add(fk["from"].split(".")[-1])
        fk_tables.add(fk["to"].split(".")[-1])

    # Build set of PK columns per table (by short name)
    pk_cols_by_table = {}
    for pk_key, cols in pks.items():
        table_short = pk_key.split(".")[-1]
        pk_cols_by_table[table_short] = set(cols)

    lines = ["erDiagram"]

    # Add tables with their columns (limited, deduplicated)
    shown_tables = set()
    for table_key, info in tables.items():
        table_name = table_key.split(".")[-1]
        if table_name not in fk_tables:
            continue
        if table_name in shown_tables:
            continue
        if len(shown_tables) >= max_tables:
            break

        clean_name = re.sub(r'[^a-zA-Z0-9_]', '_', table_name)
        # Deduplicate columns by name
        seen_cols = set()
        unique_cols = []
        for col in info["columns"]:
            if col["name"] not in seen_cols:
                seen_cols.add(col["name"])
                unique_cols.append(col)

        display_cols = unique_cols[:10]
        pk_set = pk_cols_by_table.get(table_name, set())

        lines.append(f"    {clean_name} {{")
        for col in display_cols:
            col_type = re.sub(r'[^a-zA-Z0-9]', '', col["type"])[:20]
            col_name = re.sub(r'[^a-zA-Z0-9_]', '_', col["name"])
            pk_marker = "PK" if col["name"] in pk_set else ""
            lines.append(f"        {col_type} {col_name} {pk_marker}")
        if len(unique_cols) > 10:
            lines.append(f"        string ___plus_{len(unique_cols)-10}_more___")
        lines.append("    }")
        shown_tables.add(table_name)

    # Add relationships (deduplicated)
    seen_rels = set()
    for fk in fks:
        from_t = re.sub(r'[^a-zA-Z0-9_]', '_', fk["from"].split(".")[-1])
        to_t = re.sub(r'[^a-zA-Z0-9_]', '_', fk["to"].split(".")[-1])
        rel_key = f"{from_t}-{to_t}-{fk['from_col']}"
        if from_t in shown_tables and to_t in shown_tables and rel_key not in seen_rels:
            seen_rels.add(rel_key)
            lines.append(f"    {from_t} }}o--|| {to_t} : \"{fk['from_col']}\"")

    return "\n".join(lines)


# ── Lineage Inference ────────────────────────────────────────────────────────

SQL_TABLE_PATTERNS = [
    r'(?:FROM|JOIN|INTO|UPDATE|MERGE\s+INTO)\s+[\[\"]?(\w+)[\]\"]?\.[\[\"]?(\w+)[\]\"]?',
    r'(?:FROM|JOIN|INTO|UPDATE)\s+[\[\"]?(\w+)[\]\"]?\s',
    r'(?:INSERT\s+INTO|DELETE\s+FROM)\s+[\[\"]?(?:(\w+)\.)?(\w+)[\]\"]?',
]


def extract_lineage_from_sql(sql_text):
    """Parse SQL to extract table references (FROM, JOIN, INTO, UPDATE)."""
    refs = {"reads": set(), "writes": set()}
    if not sql_text:
        return refs

    # Normalize
    sql_upper = sql_text.upper()

    # Find reads (FROM, JOIN)
    for match in re.finditer(r'(?:FROM|JOIN)\s+[\[\"]?(?:(\w+)\.)?[\[\"]?(\w+)[\]\"]?', sql_text, re.I):
        schema = match.group(1) or ""
        table = match.group(2)
        if table.upper() not in ("SELECT", "WHERE", "SET", "VALUES", "NULL", "AS", "ON", "AND", "OR"):
            ref = f"{schema}.{table}" if schema else table
            refs["reads"].add(ref)

    # Find writes (INSERT INTO, UPDATE, MERGE INTO, DELETE FROM)
    for match in re.finditer(r'(?:INSERT\s+INTO|UPDATE|MERGE\s+INTO|DELETE\s+FROM)\s+[\[\"]?(?:(\w+)\.)?[\[\"]?(\w+)[\]\"]?', sql_text, re.I):
        schema = match.group(1) or ""
        table = match.group(2)
        if table.upper() not in ("SELECT", "WHERE", "SET", "VALUES", "NULL"):
            ref = f"{schema}.{table}" if schema else table
            refs["writes"].add(ref)

    return {"reads": list(refs["reads"]), "writes": list(refs["writes"])}


def extract_sp_lineage(mep_path):
    """Extract lineage from stored procedures."""
    sp_lineage = []
    csv_files = (
        find_csvs(mep_path, "stored_proc")
        + find_csvs(mep_path, "S03_stored")
        + find_csvs(mep_path, "plsql_code")
        + find_csvs(mep_path, "functions_code")
    )

    for csv_file in csv_files:
        rows = safe_read_csv(csv_file, max_rows=500)
        for row in rows:
            sp_name = (
                row.get("ProcedureName", "")
                or row.get("routine_name", "")
                or row.get("object_name", "")
                or row.get("function_name", "")
            )
            sp_schema = row.get("SchemaName", row.get("schema_name", "dbo"))
            sp_code = (
                row.get("ProcedureDefinition", "")
                or row.get("routine_definition", "")
                or row.get("source_code", "")
                or row.get("function_body", "")
            )

            if sp_name and sp_code and len(sp_code) > 20:
                refs = extract_lineage_from_sql(sp_code)
                if refs["reads"] or refs["writes"]:
                    sp_lineage.append({
                        "object": f"{sp_schema}.{sp_name}",
                        "type": "stored_procedure",
                        "reads": refs["reads"],
                        "writes": refs["writes"],
                        "code_length": len(sp_code),
                    })
    return sp_lineage


def extract_view_lineage(mep_path):
    """Extract lineage from views."""
    view_lineage = []
    csv_files = find_csvs(mep_path, "views") + find_csvs(mep_path, "S02_views")

    for csv_file in csv_files:
        rows = safe_read_csv(csv_file, max_rows=500)
        for row in rows:
            view_name = row.get("ViewName", row.get("view_name", ""))
            view_schema = row.get("SchemaName", row.get("table_schema", "dbo"))
            view_def = row.get("ViewDefinition", row.get("view_definition", ""))

            if view_name and view_def and len(view_def) > 10:
                refs = extract_lineage_from_sql(view_def)
                if refs["reads"]:
                    view_lineage.append({
                        "object": f"{view_schema}.{view_name}",
                        "type": "view",
                        "reads": refs["reads"],
                        "writes": [],
                        "code_length": len(view_def),
                    })
    return view_lineage


def extract_trigger_lineage(mep_path):
    """Extract lineage from triggers."""
    trigger_lineage = []
    csv_files = find_csvs(mep_path, "trigger") + find_csvs(mep_path, "S04_trigger")

    for csv_file in csv_files:
        rows = safe_read_csv(csv_file, max_rows=200)
        for row in rows:
            trig_name = row.get("TriggerName", row.get("trigger_name", ""))
            trig_table = row.get("TableName", row.get("event_object_table", ""))
            trig_def = row.get("TriggerDefinition", row.get("action_statement", ""))

            if trig_name and trig_def:
                refs = extract_lineage_from_sql(trig_def)
                trigger_lineage.append({
                    "object": trig_name,
                    "type": "trigger",
                    "on_table": trig_table,
                    "reads": refs["reads"],
                    "writes": refs["writes"],
                })
    return trigger_lineage


def extract_job_lineage(mep_path):
    """Extract lineage from SQL Agent job steps."""
    job_lineage = []

    # TSQL job steps
    for sql_file in Path(mep_path).rglob("tsql_job_steps.sql"):
        try:
            content = sql_file.read_text(encoding="utf-8", errors="replace")
            # Split by job markers
            current_job = "unknown"
            for line in content.split("\n"):
                if line.startswith("--") and "Job:" in line:
                    current_job = line.split("Job:")[-1].strip().strip("[]")
                elif line.strip() and not line.startswith("--"):
                    refs = extract_lineage_from_sql(line)
                    if refs["reads"] or refs["writes"]:
                        job_lineage.append({
                            "object": current_job,
                            "type": "agent_job",
                            "reads": refs["reads"],
                            "writes": refs["writes"],
                        })
        except Exception:
            pass

    # Agent jobs CSV
    for csv_file in find_csvs(mep_path, "agent_jobs") + find_csvs(mep_path, "all_job_steps"):
        rows = safe_read_csv(csv_file, max_rows=500)
        for row in rows:
            job_name = row.get("job_name", row.get("JobName", ""))
            command = row.get("command", row.get("Command", row.get("step_command", "")))
            if job_name and command:
                refs = extract_lineage_from_sql(command)
                if refs["reads"] or refs["writes"]:
                    job_lineage.append({
                        "object": job_name,
                        "type": "agent_job_step",
                        "reads": refs["reads"],
                        "writes": refs["writes"],
                    })

    return job_lineage


# ── SSIS Parser ──────────────────────────────────────────────────────────────

def parse_ssis_packages(mep_path):
    """Parse SSIS .dtsx files for connections and dataflows."""
    ssis_info = []

    for dtsx in Path(mep_path).rglob("*.dtsx"):
        pkg = {
            "name": dtsx.stem,
            "path": str(dtsx.relative_to(mep_path)),
            "size_kb": round(dtsx.stat().st_size / 1024, 1),
            "connections": [],
            "sql_references": [],
        }

        try:
            tree = ET.parse(dtsx)
            root = tree.getroot()
            ns = {"DTS": "www.microsoft.com/SqlServer/Dts"}

            # Extract connection managers
            for cm in root.iter():
                if "ConnectionManager" in cm.tag:
                    conn_str = cm.get("{www.microsoft.com/SqlServer/Dts}ConnectionString", "")
                    name = cm.get("{www.microsoft.com/SqlServer/Dts}ObjectName", "")
                    if conn_str:
                        # Redact passwords
                        conn_clean = re.sub(r'(?i)(password|pwd)\s*=\s*[^;]+', r'\1=***', conn_str)
                        pkg["connections"].append({"name": name, "connection": conn_clean})

            # Extract SQL from the package text
            text_content = dtsx.read_text(encoding="utf-8", errors="replace")
            refs = extract_lineage_from_sql(text_content)
            pkg["sql_references"] = refs

        except ET.ParseError:
            pkg["parse_error"] = "Invalid XML"
        except Exception as e:
            pkg["parse_error"] = str(e)[:100]

        ssis_info.append(pkg)

    return ssis_info


# ── Linked Servers / Cross-Server Dependencies ──────────────────────────────

def extract_linked_servers(mep_path):
    """Extract linked server definitions."""
    linked = []
    csv_files = find_csvs(mep_path, "linked_server")

    for csv_file in csv_files:
        rows = safe_read_csv(csv_file)
        for row in rows:
            name = row.get("LinkedServerName", row.get("name", ""))
            provider = row.get("Provider", row.get("provider_string", ""))
            data_source = row.get("DataSource", row.get("data_source", ""))
            if name:
                linked.append({
                    "name": name,
                    "provider": provider,
                    "data_source": data_source,
                })
    return linked


# ── Completitud Analysis ─────────────────────────────────────────────────────

def analyze_completitud(tables, pks):
    """Analyze data completeness: empty tables, orphans, missing PKs."""
    analysis = {
        "total_tables": len(tables),
        "tables_with_pk": 0,
        "tables_without_pk": 0,
        "empty_tables": [],
        "largest_tables": [],
        "schemas": defaultdict(int),
    }

    table_sizes = []
    for table_key, info in tables.items():
        schema = info.get("schema", "dbo")
        analysis["schemas"][schema] += 1

        # Check PK
        short_key = f"{schema}.{table_key.split('.')[-1]}"
        if short_key in pks or table_key in pks:
            analysis["tables_with_pk"] += 1
        else:
            analysis["tables_without_pk"] += 1

        # Check emptiness
        est_rows = info.get("est_rows", "")
        try:
            row_count = int(est_rows)
            if row_count == 0:
                analysis["empty_tables"].append(table_key.split(".")[-1])
            table_sizes.append((table_key.split(".")[-1], row_count, info.get("table_size", "")))
        except (ValueError, TypeError):
            pass

    # Top 10 largest
    table_sizes.sort(key=lambda x: -x[1])
    analysis["largest_tables"] = [
        {"table": t[0], "rows": t[1], "size": t[2]}
        for t in table_sizes[:20]
    ]
    analysis["schemas"] = dict(analysis["schemas"])

    return analysis


# ── Main Scanner ─────────────────────────────────────────────────────────────

def scan_for_reconstruction(mep_path):
    """Full reconstruction scan of a MEP."""
    mep_path = Path(mep_path).resolve()
    print(f"[RECONSTRUCT] Scanning: {mep_path.name}", file=sys.stderr)

    # 1. Extract metadata
    print("[RECONSTRUCT] Extracting tables/columns...", file=sys.stderr)
    tables = extract_tables_columns(mep_path)
    print(f"[RECONSTRUCT]   Found {len(tables)} tables", file=sys.stderr)

    print("[RECONSTRUCT] Extracting PKs...", file=sys.stderr)
    pks = extract_primary_keys(mep_path)

    print("[RECONSTRUCT] Extracting FKs...", file=sys.stderr)
    fks = extract_foreign_keys(mep_path)
    print(f"[RECONSTRUCT]   Found {len(fks)} foreign keys", file=sys.stderr)

    print("[RECONSTRUCT] Extracting indexes...", file=sys.stderr)
    indexes = extract_indexes(mep_path)

    # 2. Generate DDL
    print("[RECONSTRUCT] Generating DDL...", file=sys.stderr)
    ddl = generate_ddl(tables, pks, fks, indexes)

    # 3. Generate ER diagram
    print("[RECONSTRUCT] Generating ER diagram...", file=sys.stderr)
    mermaid = generate_mermaid_er(tables, fks, pks)

    # 4. Extract lineage
    print("[RECONSTRUCT] Extracting SP lineage...", file=sys.stderr)
    sp_lineage = extract_sp_lineage(mep_path)
    print(f"[RECONSTRUCT]   {len(sp_lineage)} SPs with table references", file=sys.stderr)

    print("[RECONSTRUCT] Extracting view lineage...", file=sys.stderr)
    view_lineage = extract_view_lineage(mep_path)

    print("[RECONSTRUCT] Extracting trigger lineage...", file=sys.stderr)
    trigger_lineage = extract_trigger_lineage(mep_path)

    print("[RECONSTRUCT] Extracting job lineage...", file=sys.stderr)
    job_lineage = extract_job_lineage(mep_path)
    print(f"[RECONSTRUCT]   {len(job_lineage)} job steps with table references", file=sys.stderr)

    # 5. Parse SSIS
    print("[RECONSTRUCT] Parsing SSIS packages...", file=sys.stderr)
    ssis = parse_ssis_packages(mep_path)
    print(f"[RECONSTRUCT]   {len(ssis)} SSIS packages parsed", file=sys.stderr)

    # 6. Linked servers
    linked = extract_linked_servers(mep_path)

    # 7. Completitud
    print("[RECONSTRUCT] Analyzing completitud...", file=sys.stderr)
    completitud = analyze_completitud(tables, pks)

    # 8. Build lineage graph
    all_lineage = sp_lineage + view_lineage + trigger_lineage + job_lineage
    lineage_graph = {"nodes": set(), "edges": []}
    for item in all_lineage:
        lineage_graph["nodes"].add(item["object"])
        for r in item.get("reads", []):
            lineage_graph["edges"].append({"from": r, "to": item["object"], "type": "reads"})
            lineage_graph["nodes"].add(r)
        for w in item.get("writes", []):
            lineage_graph["edges"].append({"from": item["object"], "to": w, "type": "writes"})
            lineage_graph["nodes"].add(w)
    lineage_graph["nodes"] = list(lineage_graph["nodes"])

    result = {
        "metadata": {
            "mep_path": str(mep_path),
            "mep_name": mep_path.name,
            "scanner_version": "1.0.0",
        },
        "ddl": {
            "statement_count": len(ddl),
            "statements": ddl[:100],  # Limit for JSON size
            "truncated": len(ddl) > 100,
        },
        "er_diagram": {
            "mermaid": mermaid,
            "tables_in_diagram": mermaid.count("{") - 1 if mermaid else 0,
            "relationships": len(fks),
        },
        "lineage": {
            "total_objects_with_lineage": len(all_lineage),
            "stored_procedures": len(sp_lineage),
            "views": len(view_lineage),
            "triggers": len(trigger_lineage),
            "jobs": len(job_lineage),
            "graph": {
                "node_count": len(lineage_graph["nodes"]),
                "edge_count": len(lineage_graph["edges"]),
                "nodes": lineage_graph["nodes"][:200],
                "edges": lineage_graph["edges"][:500],
            },
            "details": all_lineage[:100],
        },
        "ssis": {
            "total_packages": len(ssis),
            "packages": ssis[:50],
        },
        "linked_servers": linked,
        "completitud": completitud,
        "indexes": {
            "total_tables_with_indexes": len(indexes),
            "sample": {k: v for k, v in list(indexes.items())[:20]},
        },
        "summary": {
            "tables": len(tables),
            "pks": len(pks),
            "fks": len(fks),
            "indexes": sum(len(v) for v in indexes.values()),
            "sps_with_lineage": len(sp_lineage),
            "views_with_lineage": len(view_lineage),
            "triggers_with_lineage": len(trigger_lineage),
            "jobs_with_lineage": len(job_lineage),
            "ssis_packages": len(ssis),
            "linked_servers": len(linked),
            "lineage_nodes": len(lineage_graph["nodes"]),
            "lineage_edges": len(lineage_graph["edges"]),
            "empty_tables": len(completitud["empty_tables"]),
            "tables_without_pk": completitud["tables_without_pk"],
        },
    }

    print(f"[RECONSTRUCT] Done. Summary: {result['summary']}", file=sys.stderr)
    return result


def main():
    parser = argparse.ArgumentParser(description="MEP Reconstruct Scanner")
    parser.add_argument("--mep-path", required=True, help="Path to extracted MEP directory")
    parser.add_argument("--output", required=True, help="Output directory for reconstruction artifacts")
    args = parser.parse_args()

    mep_path = Path(args.mep_path)
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    result = scan_for_reconstruction(mep_path)

    # Write JSON
    json_path = output_dir / "reconstruct_scan.json"
    json_path.write_text(json.dumps(result, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    print(f"[RECONSTRUCT] JSON: {json_path}", file=sys.stderr)

    # Write DDL
    ddl_path = output_dir / "reconstructed_ddl.sql"
    ddl_path.write_text("\n\n".join(result["ddl"]["statements"]), encoding="utf-8")
    print(f"[RECONSTRUCT] DDL: {ddl_path} ({result['ddl']['statement_count']} statements)", file=sys.stderr)

    # Write Mermaid
    er_path = output_dir / "er_diagram.mmd"
    er_path.write_text(result["er_diagram"]["mermaid"], encoding="utf-8")
    print(f"[RECONSTRUCT] ER: {er_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
