erDiagram
  LYT_INTERACCIONES_202401 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202402 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202403 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202404 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202405 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202406 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202407 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202408 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202409 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202410 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202411 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202412 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_SESIONES_202401 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202402 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202403 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202404 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202405 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202406 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202407 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202408 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202409 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202410 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202411 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202412 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
