erDiagram
  LYT_INTENT_SESIONES_202201 {
    PERIODO VARCHAR
    SESSION_ID INT
    SESSION_CREATION_TIME VARCHAR
    CREATION_TIME VARCHAR
    MSG_FROM VARCHAR
    RULE_NAME VARCHAR
  }
  LYT_INTENT_SESIONES_202202 {
    PERIODO VARCHAR
    SESSION_ID INT
    SESSION_CREATION_TIME VARCHAR
    CREATION_TIME VARCHAR
    MSG_FROM VARCHAR
    RULE_NAME VARCHAR
  }
  LYT_INTENT_SESIONES_202203 {
    PERIODO VARCHAR
    SESSION_ID INT
    SESSION_CREATION_TIME VARCHAR
    CREATION_TIME VARCHAR
    MSG_FROM VARCHAR
    RULE_NAME VARCHAR
  }
  LYT_INTENT_SESIONES_202204 {
    PERIODO VARCHAR
    SESSION_ID INT
    SESSION_CREATION_TIME VARCHAR
    CREATION_TIME VARCHAR
    MSG_FROM VARCHAR
    RULE_NAME VARCHAR
  }
  LYT_INTENT_SESIONES_202205 {
    PERIODO VARCHAR
    SESSION_ID INT
    SESSION_CREATION_TIME VARCHAR
    CREATION_TIME VARCHAR
    MSG_FROM VARCHAR
    RULE_NAME VARCHAR
  }
  LYT_INTENT_SESIONES_202206 {
    PERIODO VARCHAR
    SESSION_ID INT
    SESSION_CREATION_TIME VARCHAR
    CREATION_TIME VARCHAR
    MSG_FROM VARCHAR
    RULE_NAME VARCHAR
  }
  LYT_INTENT_SESIONES_202207 {
    PERIODO VARCHAR
    SESSION_ID INT
    SESSION_CREATION_TIME VARCHAR
    CREATION_TIME VARCHAR
    MSG_FROM VARCHAR
    RULE_NAME VARCHAR
  }
  LYT_INTENT_SESIONES_202208 {
    PERIODO VARCHAR
    SESSION_ID INT
    SESSION_CREATION_TIME VARCHAR
    CREATION_TIME VARCHAR
    MSG_FROM VARCHAR
    RULE_NAME VARCHAR
  }
  LYT_INTENT_SESIONES_202209 {
    PERIODO VARCHAR
    SESSION_ID INT
    SESSION_CREATION_TIME VARCHAR
    CREATION_TIME VARCHAR
    MSG_FROM VARCHAR
    RULE_NAME VARCHAR
  }
  LYT_INTENT_SESIONES_202210 {
    PERIODO VARCHAR
    SESSION_ID INT
    SESSION_CREATION_TIME VARCHAR
    CREATION_TIME VARCHAR
    MSG_FROM VARCHAR
    RULE_NAME VARCHAR
  }
  LYT_INTENT_SESIONES_202211 {
    PERIODO VARCHAR
    SESSION_ID INT
    SESSION_CREATION_TIME VARCHAR
    CREATION_TIME VARCHAR
    MSG_FROM VARCHAR
    RULE_NAME VARCHAR
  }
  LYT_INTENT_SESIONES_202212 {
    PERIODO VARCHAR
    SESSION_ID INT
    SESSION_CREATION_TIME VARCHAR
    CREATION_TIME VARCHAR
    MSG_FROM VARCHAR
    RULE_NAME VARCHAR
  }
  LYT_INTERACCIONES_202201 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202202 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202203 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202204 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202205 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202206 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202207 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202208 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202209 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202210 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202211 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_INTERACCIONES_202212 {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  LYT_SESIONES_202201 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202202 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202203 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202204 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202205 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202206 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202207 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202208 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202209 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202210 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202211 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202212 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
