erDiagram
  LYT_CONTACT_CENTER_ACCESADAS_202401 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202402 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202403 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202404 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202405 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202406 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202407 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202408 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202409 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202410 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202411 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ACCESADAS_202412 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  LYT_CONTACT_CENTER_ENTRANTES_202401 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202402 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202403 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202404 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202405 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202406 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202407 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202408 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202409 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202410 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202411 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_CONTACT_CENTER_ENTRANTES_202412 {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  LYT_TIPIFICACIONES_MES_2024 {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    DIAMES VARCHAR
  }
