erDiagram
  LYT_FACO_2023 {
    PERIODO VARCHAR
    SISTEMA VARCHAR
    SERVICIO VARCHAR
    RECIBO VARCHAR
    TELEFONO VARCHAR
    COD_CTA VARCHAR
  }
  LYT_FACO_2024 {
    PERIODO VARCHAR
    SISTEMA VARCHAR
    SERVICIO VARCHAR
    RECIBO VARCHAR
    TELEFONO VARCHAR
    COD_CTA VARCHAR
  }
  LYT_FACO_SUBSCRIBER_2023 {
    EMISION VARCHAR
    PERIODO VARCHAR
    RECIBO VARCHAR
    SUBSCRIBER_KEY VARCHAR
    TELEFONO VARCHAR
    FEC_ALTA VARCHAR
  }
