erDiagram
  LYT_VISOR_TIPIFICACIONES_202301 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202302 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202303 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202304 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202305 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202306 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202307 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202308 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202309 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202310 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202311 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
  LYT_VISOR_TIPIFICACIONES_202312 {
    ID INT
    PROVEEDOR VARCHAR
    DNI_ASESOR VARCHAR
    NOMBRE_ASESOR VARCHAR
    SERVICIO VARCHAR
    PLATAFORMA VARCHAR
  }
