erDiagram
  LYT_SESIONES_202301 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202302 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202303 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202304 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202305 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202306 {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202307_NEW {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202308_NEW {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202309_NEW {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202310_NEW {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202311_NEW {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
  LYT_SESIONES_202312_NEW {
    SESSION_ID INT
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    ENTIDAD INT
    SISTEMA VARCHAR
  }
