erDiagram
  20230307_VALIDAR_REGULADOS_OSIPTEL_NO_AURA_202204 {
    PERIODO VARCHAR
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
  }
  20230307_VALIDAR_REGULADOS_OSIPTEL_NO_AURA_202208 {
    PERIODO VARCHAR
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
  }
  BD_ENCUESTAS_FACO_ABR24_ABR25 {
    TIPO_FACO VARCHAR
    TELEFONO VARCHAR
    CUENTA VARCHAR
    TEL VARCHAR
    DOCUMENTO VARCHAR
    SEGMENTO VARCHAR
  }
  Base_Q_Alarmas_202501 {
    LINE_ID INT
    AÑO VARCHAR
    SEMANA VARCHAR
    Q_Total VARCHAR
    Q_Dying_Gasp VARCHAR
    Q_No_Dying_Gasp VARCHAR
  }
  Base_Q_Alarmas_202503 {
    LINE_ID INT
    AÑO VARCHAR
    SEMANA VARCHAR
    Q_Total VARCHAR
    Q_Dying_Gasp VARCHAR
    Q_No_Dying_Gasp VARCHAR
  }
  CANAL_MARCACION {
    PERIODO VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    CANAL_MARCACION VARCHAR
  }
  CATALOGO_VISOR_TIPIS {
    ID INT
    FECHA_CREACION VARCHAR
    FUENTE VARCHAR
    MOTIVO VARCHAR
    SUB_MOTIVO VARCHAR
    MOTIVO_OK VARCHAR
  }
  Catalogo_Motivos_Tipificador_Visor_Ranking_OSIPTEL_v2 {
    motivo_ok VARCHAR
    sub_motivo_ok VARCHAR
    MOTIVO_RANKING_OSIPTEL VARCHAR
    TIPO_TRAMITE_RANKING_OSIPTEL VARCHAR
    FLAG_MOTIVO_DERIVACION_A_OTRO_CANAL_RANKING_OSIPTEL VARCHAR
  }
  GMC_CATALAGO_OSIPTEL_202401 {
    motivo_ok VARCHAR
    sub_motivo_ok VARCHAR
    MOTIVO_RANKING_OSIPTEL VARCHAR
    TIPO_TRAMITE_RANKING_OSIPTEL VARCHAR
    FLAG_MOTIVO_DERIVACION_A_OTRO_CANAL_RANKING_OSIPTEL VARCHAR
  }
  GMC_CATALOGO_V2 {
    motivo_ok VARCHAR
    sub_motivo_ok VARCHAR
    MOTIVO_RANKING_OSIPTEL VARCHAR
    TIPO_TRAMITE_RANKING_OSIPTEL VARCHAR
    FLAG_MOTIVO_DERIVACION_A_OTRO_CANAL_RANKING_OSIPTEL VARCHAR
  }
  JSH_BASE_TIPIFICACIONES_VISOR_RANKING_OSIPTEL_2023_07_08_09 {
    ID INT
    Fecha_registro VARCHAR
    CONNID_GENESYS INT
    ID_LLAMADA INT
    ID_INTERACCION_LLAMADA INT
    MOTIVO VARCHAR
  }
  JSH_BASE_TIPIFICACIONES_VISOR_RANKING_OSIPTEL_2023_10_11_12 {
    ID INT
    Fecha_registro VARCHAR
    CONNID_GENESYS INT
    ID_LLAMADA INT
    ID_INTERACCION_LLAMADA INT
    MOTIVO VARCHAR
  }
  JSH_Base_Disponibilidad_01_06_enero {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_01_20_marzo {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_03_09_febrero {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_03_09_marzo {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_07a14enero {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_10_17_marzo {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_10_18_febrero {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_15_19_enero {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_19_23_febrero {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_202507 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_20_26_enero {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_21_31_marzo {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_24_28_febrero {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_27_enero_al_02_febrero {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_abril_21_25 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_abril_26_30 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_junio_01_04 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_junio_05_10 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_junio_11_23 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_junio_21_30 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_mayo_01_04 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_mayo_05_09 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_mayo_10_14 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_mayo_15_19 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_mayo_20_25 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  JSH_Base_Disponibilidad_mayo_26_30 {
    LINE_ID1 INT
    AÑO VARCHAR
    SEMANA VARCHAR
    TIPO_USO VARCHAR
    FECHA_HORA_START VARCHAR
    Sum_Disponible VARCHAR
  }
  KCS_CATALOGO_MOTIVOS_OSIPTEL {
    MOTIVO VARCHAR
    SUB_MOTIVO VARCHAR
    EQ_OSIPTEL VARCHAR
  }
  T_BASE_202209 {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202210 {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202211 {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202212 {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202301 {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202302 {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202303 {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202304 {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202305 {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202306 {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202307 {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202308 {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202309_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202310_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202311_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202312_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202401_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202402_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202403_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202404_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202405_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202406_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202407_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202408_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202409_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202410_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202411_ENVIO_OSIPTEL {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_202411_ENVIO_OSIPTEL_NUEVA_VERSION {
    Handling VARCHAR
    Tenant VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
  }
  T_BASE_VOZ_ATENC_VIRTUAL_202305 {
    PERIODO VARCHAR
    AURA_TIPO_IVR VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_ID_LLAMADA INT
    SALTO_FIN_ID_LLAMADA INT
    ENT_PASO_INICIO_IVR_CONNID INT
  }
  T_BASE_VOZ_ATENC_VIRTUAL_202306 {
    PERIODO VARCHAR
    AURA_TIPO_IVR VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_ID_LLAMADA INT
    SALTO_FIN_ID_LLAMADA INT
    ENT_PASO_INICIO_IVR_CONNID INT
  }
  T_BASE_VOZ_ATENC_VIRTUAL_202307 {
    PERIODO VARCHAR
    AURA_TIPO_IVR VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_ID_LLAMADA INT
    SALTO_FIN_ID_LLAMADA INT
    ENT_PASO_INICIO_IVR_CONNID INT
  }
  T_BASE_VOZ_ATENC_VIRTUAL_202308 {
    PERIODO VARCHAR
    AURA_TIPO_IVR VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_ID_LLAMADA INT
    SALTO_FIN_ID_LLAMADA INT
    ENT_PASO_INICIO_IVR_CONNID INT
  }
  T_BASE_VOZ_ATENC_VIRTUAL_202309 {
    PERIODO VARCHAR
    AURA_TIPO_IVR VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_ID_LLAMADA INT
    SALTO_FIN_ID_LLAMADA INT
    ENT_PASO_INICIO_IVR_CONNID INT
  }
  T_BASE_VOZ_ATENC_VIRTUAL_202310 {
    PERIODO VARCHAR
    AURA_TIPO_IVR VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_ID_LLAMADA INT
    SALTO_FIN_ID_LLAMADA INT
    ENT_PASO_INICIO_IVR_CONNID INT
  }
  T_BASE_VOZ_ATENC_VIRTUAL_202311 {
    PERIODO VARCHAR
    AURA_TIPO_IVR VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_ID_LLAMADA INT
    SALTO_FIN_ID_LLAMADA INT
    ENT_PASO_INICIO_IVR_CONNID INT
  }
  T_BASE_VOZ_ATENC_VIRTUAL_202312 {
    PERIODO VARCHAR
    AURA_TIPO_IVR VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_ID_LLAMADA INT
    SALTO_FIN_ID_LLAMADA INT
    ENT_PASO_INICIO_IVR_CONNID INT
  }
  T_DETALLE_LN_202209 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202209_OSPTL {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202210 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202210_OSPTL {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202211 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202211_OSPTL {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202212 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202301 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202302 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202303 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202304 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202305 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202306 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202307 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202308 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202309_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202310_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202311_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202312_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202401_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202402_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202403_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202404_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202405_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202406_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202406_ENVIO_OSIPTEL_NUEVA_VERSION_NUEVO {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202407_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202408_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202409_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202410_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_DETALLE_LN_202411_ENVIO_OSIPTEL {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
    CDR_SESSION_ID INT
  }
  T_DETALLE_LN_202411_ENVIO_OSIPTEL_NUEVA_VERSION {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_FIRST_SECTION_AVH1 VARCHAR
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
  }
  T_LISTADO_DNIS {
    MES VARCHAR
    CDR_DNIS VARCHAR
    TOTAL VARCHAR
    AGRUPACION_IVR VARCHAR
    NUEVO_DNIS VARCHAR
  }
  T_LISTADO_IVR {
    REG_GRUPO_IVR VARCHAR
    REG_NEGOCIO VARCHAR
  }
  T_LISTADO_IVR_VAL {
    REG_GRUPO_IVR VARCHAR
    REG_NEGOCIO VARCHAR
  }
  T_LISTADO_IVR_VAL_2 {
    REG_GRUPO_IVR VARCHAR
    REG_NEGOCIO VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_201909 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_201910 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_201911 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_201912 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202001 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202002 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202003 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202004 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202005 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202006 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202007 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202008 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202009 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202010 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202011 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202012 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULADOS_STAR_GLOBAL_202101 {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202301 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202302 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202303 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202304 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202305 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202306 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202307 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202308 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202309 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202310 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202311 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202312 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202401 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202402 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202403 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202404 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202405 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202406 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202407 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202408 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202409 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202410 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202411 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_STAR_GLOBAL_ORIGINAL_202004 {
    FECHAANSI VARCHAR
    RANGO_HORARIO VARCHAR
    HORA_FIN_LLAMADA VARCHAR
    HORA_INICIO_LLAMADA VARCHAR
    TELEFONO VARCHAR
    CODIGO1 VARCHAR
  }
  T_STAR_GLOBAL_ORIGINAL_202005 {
    FECHAANSI VARCHAR
    RANGO_HORARIO VARCHAR
    HORA_FIN_LLAMADA VARCHAR
    HORA_INICIO_LLAMADA VARCHAR
    TELEFONO VARCHAR
    CODIGO1 VARCHAR
  }
  T_STAR_GLOBAL_ORIGINAL_202006 {
    FECHAANSI VARCHAR
    RANGO_HORARIO VARCHAR
    HORA_FIN_LLAMADA VARCHAR
    HORA_INICIO_LLAMADA VARCHAR
    TELEFONO VARCHAR
    CODIGO1 VARCHAR
  }
  T_STAR_GLOBAL_ORIGINAL_202007 {
    FECHAANSI VARCHAR
    RANGO_HORARIO VARCHAR
    HORA_FIN_LLAMADA VARCHAR
    HORA_INICIO_LLAMADA VARCHAR
    TELEFONO VARCHAR
    CODIGO1 VARCHAR
  }
  T_STAR_GLOBAL_ORIGINAL_202008 {
    FECHAANSI VARCHAR
    RANGO_HORARIO VARCHAR
    HORA_FIN_LLAMADA VARCHAR
    HORA_INICIO_LLAMADA VARCHAR
    TELEFONO VARCHAR
    CODIGO1 VARCHAR
  }
  T_STAR_GLOBAL_ORIGINAL_202009 {
    FECHAANSI VARCHAR
    RANGO_HORARIO VARCHAR
    HORA_FIN_LLAMADA VARCHAR
    HORA_INICIO_LLAMADA VARCHAR
    TELEFONO VARCHAR
    CODIGO1 VARCHAR
  }
  T_STAR_GLOBAL_ORIGINAL_202010 {
    FECHAANSI VARCHAR
    RANGO_HORARIO VARCHAR
    HORA_FIN_LLAMADA VARCHAR
    HORA_INICIO_LLAMADA VARCHAR
    TELEFONO VARCHAR
    CODIGO1 VARCHAR
  }
  T_STAR_GLOBAL_ORIGINAL_202011 {
    FECHAANSI VARCHAR
    RANGO_HORARIO VARCHAR
    HORA_FIN_LLAMADA VARCHAR
    HORA_INICIO_LLAMADA VARCHAR
    TELEFONO VARCHAR
    CODIGO1 VARCHAR
  }
  T_STAR_GLOBAL_ORIGINAL_202012 {
    FECHAANSI VARCHAR
    RANGO_HORARIO VARCHAR
    HORA_FIN_LLAMADA VARCHAR
    HORA_INICIO_LLAMADA VARCHAR
    TELEFONO VARCHAR
    CODIGO1 VARCHAR
  }
  T_STAR_GLOBAL_ORIGINAL_202101 {
    FECHAANSI VARCHAR
    RANGO_HORARIO VARCHAR
    HORA_FIN_LLAMADA VARCHAR
    HORA_INICIO_LLAMADA VARCHAR
    TELEFONO VARCHAR
    CODIGO1 VARCHAR
  }
  T_V2_REGULADOS_PW_202301 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202302 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202303 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202304 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202305 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202306 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202307 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202308 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202309 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202310 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202311 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202312 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202401 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202402 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202403 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202404 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202405 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202406 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202407 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202408 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202409 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202410 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202411 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_TEMPORAL_REGULADOS_PW {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  base {
    tabla VARCHAR
  }
  export_csv_osiptel {
    HANDLING_ATTEMPT_HINT VARCHAR
    TENANT_NAME VARCHAR
    ID INT
    HANDLING_ATTEMPT_ID INT
    TYPE VARCHAR
    HANDLING_ATTEMPT_START VARCHAR
  }
  jsh_Catalogo_Autogestion_AURA_OSIPTEL {
    LAST_CASO_DE_USO VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
  }
  jsh_Catalogo_Autogestion_AURA_Ranking_OSIPTEL_v2 {
    LAST_CASO_DE_USO VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
    TIPO_TRAMITE VARCHAR
    TRAMITE_RANKING_OSIPTEL_Ronal_Leo VARCHAR
    TRAMITE_RANKING_OSIPTEL_v2 VARCHAR
  }
  jsh_Catalogo_Autogestion_BM_CCEE_Ranking_OSIPTEL {
    intent VARCHAR
    ranking VARCHAR
  }
  jsh_Catalogo_Autogestion_BM_CCEE_Ranking_OSIPTEL_v2 {
    intent VARCHAR
    ranking VARCHAR
  }
  jsh_Catalogo_Autogestion_BM_CCEE_Ranking_OSIPTEL_v3 {
    INTENT VARCHAR
    MOTIVO VARCHAR
    SUB_MOTIVO VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
    TIPO_TRAMITE_RANKING_OSIPTEL VARCHAR
    FLAG_MOTIVO_DERIVACION_A_OTRO_CANAL_RANKING_OSIPTEL VARCHAR
  }
  jsh_Catalogo_Motivos_Tipificador_Visor_Ranking_OSIPTEL_v2 {
    motivo_ok VARCHAR
    sub_motivo_ok VARCHAR
    MOTIVO_RANKING_OSIPTEL VARCHAR
    TIPO_TRAMITE_RANKING_OSIPTEL VARCHAR
    FLAG_MOTIVO_DERIVACION_A_OTRO_CANAL_RANKING_OSIPTEL VARCHAR
  }
  jsh_Catalogo_Motivos_Tipificador_Visor_Ranking_OSIPTEL_v3 {
    motivo_ok VARCHAR
    sub_motivo_ok VARCHAR
    MOTIVO_RANKING_OSIPTEL VARCHAR
    TIPO_TRAMITE_RANKING_OSIPTEL VARCHAR
    FLAG_MOTIVO_DERIVACION_A_OTRO_CANAL_RANKING_OSIPTEL VARCHAR
    FLAG_ANTIGUEDAD VARCHAR
  }
  jsh_base_tipificaciones_Ranking_OSIPTEL_2021_2S {
    canal VARCHAR
    periodo VARCHAR
    FECHA_HORA VARCHAR
    negocio VARCHAR
    motivo_agrupado VARCHAR
    motivo VARCHAR
  }
  jsh_base_tipificaciones_Ranking_OSIPTEL_2022_05_06_07 {
    canal VARCHAR
    periodo VARCHAR
    FECHA_HORA VARCHAR
    negocio VARCHAR
    motivo_agrupado VARCHAR
    motivo VARCHAR
  }
  jsh_base_tipificaciones_Ranking_OSIPTEL_2022_07 {
    canal VARCHAR
    periodo VARCHAR
    FECHA_HORA VARCHAR
    negocio VARCHAR
    motivo_agrupado VARCHAR
    motivo VARCHAR
  }
  jsh_base_tipificaciones_Ranking_OSIPTEL_2022_07_1_al_7 {
    canal VARCHAR
    periodo VARCHAR
    FECHA_HORA VARCHAR
    negocio VARCHAR
    motivo_agrupado VARCHAR
    motivo VARCHAR
  }
  jsh_base_tipificaciones_Ranking_OSIPTEL_2022_1S {
    canal VARCHAR
    periodo VARCHAR
    FECHA_HORA VARCHAR
    negocio VARCHAR
    motivo_agrupado VARCHAR
    motivo VARCHAR
  }
  jsh_base_tipificaciones_Ranking_OSIPTEL_2022_2S {
    canal VARCHAR
    periodo VARCHAR
    FECHA_HORA VARCHAR
    negocio VARCHAR
    motivo_agrupado VARCHAR
    motivo VARCHAR
  }
  jsh_base_tipificaciones_Visor_Ranking_OSIPTEL_2022_11_12 {
    ID INT
    Fecha_registro VARCHAR
    CONNID_GENESYS INT
    ID_LLAMADA INT
    ID_INTERACCION_LLAMADA INT
    MOTIVO VARCHAR
  }
  jsh_base_tipificaciones_Visor_Ranking_OSIPTEL_2023_01_02_03 {
    ID INT
    Fecha_registro VARCHAR
    CONNID_GENESYS INT
    ID_LLAMADA INT
    ID_INTERACCION_LLAMADA INT
    MOTIVO VARCHAR
  }
  jsh_resumen_ccee_asesor_humano_Ranking_OSIPTEL_2021_2S {
    Año VARCHAR
    Mes VARCHAR
    Servicio_Involucrado VARCHAR
    CANAL VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
    Q_Contactos VARCHAR
  }
  jsh_resumen_ccee_asesor_humano_Ranking_OSIPTEL_2022_01_al_04 {
    Año VARCHAR
    Mes VARCHAR
    NUM_MES VARCHAR
    Servicio_Involucrado VARCHAR
    CANAL VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
  }
  jsh_resumen_ccee_asesor_humano_Ranking_OSIPTEL_2022_05_06_07 {
    Año VARCHAR
    Mes VARCHAR
    NUM_MES VARCHAR
    Servicio_Involucrado VARCHAR
    CANAL VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
  }
  jsh_resumen_ccee_asesor_humano_Ranking_OSIPTEL_2022_2S {
    Año VARCHAR
    Mes VARCHAR
    Servicio_Involucrado VARCHAR
    CANAL VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
    Q_Contactos VARCHAR
  }
  jsh_resumen_ccee_asesor_virtual_Ranking_OSIPTEL_2022_2S {
    Año VARCHAR
    Mes VARCHAR
    Servicio_Involucrado VARCHAR
    CANAL VARCHAR
    tramite_ranking_osiptel VARCHAR
    Q_Consultas VARCHAR
  }
  jsh_resumen_llamadas_asesor_virtual_Ranking_OSIPTEL_2022_1S {
    Año VARCHAR
    Mes VARCHAR
    Servicio_Involucrado VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
    TIPO_TRAMITE_RANKING_OSIPTEL VARCHAR
    Q_Contactos VARCHAR
  }
  jsh_resumen_tipificaciones_Ranking_OSIPTEL_2021_2S {
    Año VARCHAR
    Mes VARCHAR
    Servicio_Involucrado VARCHAR
    CANAL VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
    Q_Contactos VARCHAR
  }
  jsh_resumen_voz_asesor_humano_Ranking_OSIPTEL_2022_01_al_04 {
    Año VARCHAR
    Mes VARCHAR
    PERIODO VARCHAR
    NUM_MES VARCHAR
    DIA VARCHAR
    Servicio_Involucrado VARCHAR
  }
  jsh_resumen_voz_asesor_humano_Ranking_OSIPTEL_2022_05_06_07 {
    Año VARCHAR
    Mes VARCHAR
    PERIODO VARCHAR
    NUM_MES VARCHAR
    DIA VARCHAR
    Servicio_Involucrado VARCHAR
  }
  jsh_resumen_voz_asesor_humano_Ranking_OSIPTEL_2022_11_12 {
    Año VARCHAR
    Mes VARCHAR
    PERIODO VARCHAR
    DIA VARCHAR
    Servicio_Involucrado VARCHAR
    CANAL VARCHAR
  }
  jsh_resumen_voz_asesor_humano_Ranking_OSIPTEL_2022_1S {
    Año VARCHAR
    Mes VARCHAR
    PERIODO VARCHAR
    DIA VARCHAR
    Servicio_Involucrado VARCHAR
    CANAL VARCHAR
  }
  jsh_resumen_voz_asesor_humano_Ranking_OSIPTEL_2022_2S {
    Año VARCHAR
    Mes VARCHAR
    PERIODO VARCHAR
    DIA VARCHAR
    Servicio_Involucrado VARCHAR
    CANAL VARCHAR
  }
  jsh_resumen_voz_asesor_humano_Ranking_OSIPTEL_2022_3T {
    Año VARCHAR
    Mes VARCHAR
    PERIODO VARCHAR
    DIA VARCHAR
    Servicio_Involucrado VARCHAR
    CANAL VARCHAR
  }
  jsh_resumen_voz_asesor_virtual_Ranking_OSIPTEL_2022_01_al_04 {
    Año VARCHAR
    Mes VARCHAR
    MES_NUM VARCHAR
    DIA VARCHAR
    Servicio_Involucrado VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
  }
  jsh_resumen_voz_asesor_virtual_Ranking_OSIPTEL_2022_05_06_07 {
    Año VARCHAR
    Mes VARCHAR
    MES_NUM VARCHAR
    DIA VARCHAR
    Servicio_Involucrado VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
  }
  jsh_resumen_voz_asesor_virtual_Ranking_OSIPTEL_2022_11_12 {
    Año VARCHAR
    Mes VARCHAR
    MES_NUM VARCHAR
    DIA VARCHAR
    Servicio_Involucrado VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
  }
  jsh_resumen_voz_asesor_virtual_Ranking_OSIPTEL_2022_1S {
    Año VARCHAR
    Mes VARCHAR
    MES_NUM VARCHAR
    DIA VARCHAR
    Servicio_Involucrado VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
  }
  jsh_resumen_voz_asesor_virtual_Ranking_OSIPTEL_2022_2S {
    Año VARCHAR
    Mes VARCHAR
    MES_NUM VARCHAR
    DIA VARCHAR
    Servicio_Involucrado VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
  }
  jsh_resumen_voz_asesor_virtual_Ranking_OSIPTEL_2022_3T {
    Año VARCHAR
    Mes VARCHAR
    MES_NUM VARCHAR
    DIA VARCHAR
    Servicio_Involucrado VARCHAR
    TRAMITE_RANKING_OSIPTEL VARCHAR
  }
