erDiagram
  18052025_tramitador_Reten_2 {
    TELEFONO VARCHAR
  }
  20052025_tramitador_Reten {
    TELEFONO VARCHAR
  }
  20230105_TEMP_VALIDAR {
    CDR_ANI VARCHAR
    CDR_PRODUCTO VARCHAR
    Q_LLAM VARCHAR
    MES_NUM VARCHAR
    MES VARCHAR
    FECHA_ACTUALIZACION VARCHAR
  }
  20230109_POSTPAGO_OLA2 {
    TELEFONO VARCHAR
  }
  202301_TEMP_VALIDAR {
    CDR_ANI VARCHAR
    CDR_PRODUCTO VARCHAR
    Q_LLAM VARCHAR
    MES_NUM VARCHAR
    MES VARCHAR
    FECHA_ACTUALIZACION VARCHAR
  }
  20230211_campania_cobranza {
    ID INT
    fecha VARCHAR
    hora VARCHAR
    Hora VARCHAR
    Correo VARCHAR
    Nombre VARCHAR
  }
  20230228_Base_Retenseg_68k {
    telefono VARCHAR
  }
  202302_bd_upsell_capl {
    Telefono VARCHAR
  }
  20230313_FIJA_POTENCIAL {
    Telefono VARCHAR
    TipodeDocumento VARCHAR
    Numerodedocumento VARCHAR
    Oferta_Mensaje1 VARCHAR
    Oferta_Mensaje2 VARCHAR
    Oferta_Terminal VARCHAR
  }
  20230315_Estrangulados_01mar_al_08mar {
    telefono VARCHAR
    fechainicio VARCHAR
    segmento VARCHAR
    ciclo VARCHAR
    fecha_porta VARCHAR
  }
  20230328_INTRIGA_FASE3_IVRIN {
    BASE VARCHAR
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    GRUPO_OFERTA VARCHAR
  }
  20230328_INTRIGA_FASE3_IVRIN_FTTH_2MESES {
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    GRUPO_OFERTA VARCHAR
  }
  20230328_INTRIGA_FASE3_IVRIN_FTTH_6MESES {
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    GRUPO_OFERTA VARCHAR
  }
  20230328_INTRIGA_FASE3_IVRIN_HFC_2MESES {
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    GRUPO_OFERTA VARCHAR
  }
  20230328_INTRIGA_FASE3_IVRIN_HFC_6MESES {
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    GRUPO_OFERTA VARCHAR
  }
  202303_potenciales_fija {
    Telefono VARCHAR
    Numerodedocumento VARCHAR
    Oferta_Mensaje1 VARCHAR
    Oferta_Mensaje2 VARCHAR
    Oferta_Terminal VARCHAR
  }
  20230410_enrutamiento_cross {
    SKILL VARCHAR
    Producto_1 VARCHAR
    Negocio VARCHAR
    Tipo_demanda VARCHAR
    Producto VARCHAR
    TIPO_PLANTA VARCHAR
  }
  20230508_casos_infundados {
    ID_NUMBER INT
    TITLE VARCHAR
    CREATION_TIME VARCHAR
    CASE_TYPE_LVL3 VARCHAR
    X_CORRELATIVO_ID INT
    MODIFY_STMP VARCHAR
  }
  202305_TEMP_VALIDAR {
    CDR_ANI VARCHAR
    CDR_PRODUCTO VARCHAR
    Q_LLAM VARCHAR
    MES_NUM VARCHAR
    MES VARCHAR
    FECHA_ACTUALIZACION VARCHAR
  }
  20231109_BASES_REPO_PILOTO_OCT23 {
    TELEFONO_VISOR VARCHAR
    TELEFONO VARCHAR
    TIPODOCUMENTOUNIFICADO VARCHAR
    NUMERODOCUMENTOUNIFICADO VARCHAR
    NOMBRES VARCHAR
    SUBSCRIBER_INT VARCHAR
  }
  20231116_base_reseteo_decos_adicional {
    TELEFONO VARCHAR
    ACCESO_ID_REDADSL INT
    ACCESO_ID_REDHFC INT
    FECHAALTA VARCHAR
    CUSTOMER_KEY VARCHAR
    NOMBRES VARCHAR
  }
  20231220_2DO_PILOTO_RENTESEG {
    TELEFONO VARCHAR
  }
  202312_MT_RES_AURA_1 {
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    CLUSTER_PLANTA_PORTA VARCHAR
    MENSAJE VARCHAR
  }
  20240119_3er_PILOTO_RENTESEG {
    IMEI VARCHAR
    NUMERO_MOVIL VARCHAR
    IMSI VARCHAR
    MODALIDAD INT
    SEGMENTO VARCHAR
  }
  20240215_CROSS_MOVIL_CAPTA_FIJA_AV {
    TELEFONO VARCHAR
  }
  20240422_BOOnline_BaseClientes {
    int_service_id INT
    numero_documento VARCHAR
    telefono_fijo VARCHAR
    telefono_movil VARCHAR
    departamento VARCHAR
    provincia VARCHAR
  }
  20240515_Neutros_potenciales_Pospago {
    FECHAPLANTAOFICIAL VARCHAR
    SUSCRIPCIONID INT
    MESID INT
    SUSCRIPCIONCD VARCHAR
    NUMEROTELEFONO VARCHAR
    FE_ALTA VARCHAR
  }
  26052025_tramitadores_Reten {
    TELEFONO VARCHAR
  }
  4PILOTO_RENTESEG {
    IMEI VARCHAR
    LINEA VARCHAR
    IMSI VARCHAR
    MODALIDAD INT
    SEGMENTO VARCHAR
    MARCA VARCHAR
  }
  4PILOTO_RENTESEG_DETALLE {
    Telefono VARCHAR
    Modalidad INT
    NroDoc VARCHAR
    flg_cobertura VARCHAR
    flg_grupo VARCHAR
    tipo_cliente VARCHAR
  }
  4PILOTO_RENTESEG_cobertura_postpago {
    TELEFONO VARCHAR
  }
  AM_POTENCIAL_MIGRACION_ADSL_CON_COBERTURA {
    FIJA_TELEFONO VARCHAR
    TIPDOC VARCHAR
    DOCUMENTO VARCHAR
    CLUSTER_PLANTA VARCHAR
    CLUSTER_PLANTA_PORTA VARCHAR
    CLUSTER_FIJA VARCHAR
  }
  AM_POTENCIAL_REPETIDOR {
    TELEFONO VARCHAR
    TIPDOC VARCHAR
    DOCUMENTO VARCHAR
    PRODUCTO VARCHAR
    MARCA VARCHAR
  }
  Afiliacion_izipay_202209 {
    TELEFONO VARCHAR
    NEGOCIO VARCHAR
    FECHA VARCHAR
  }
  B2C_DAIZIPAY_WHATSAPP_OUT {
    TELEFONO VARCHAR
    FINANCIAL_ACCOUNT VARCHAR
    ARCHIVO VARCHAR
  }
  BASE2_BD_Resto_65.90 {
    TELEFONO VARCHAR
  }
  BASE3_Masificacion1MB_572K {
    TELEFONO VARCHAR
  }
  BASE_ACUMULADA_tivr_cobranzas {
    TELEFONO VARCHAR
    FECHA_MODIFICACION VARCHAR
  }
  BASE_ACUMULADA_tivr_cobranzas_V2 {
    TELEFONO VARCHAR
    LOG_ID INT
  }
  BASE_ANTERIOR_MTP_TECNICO {
    TELEFONO VARCHAR
    Grupo VARCHAR
    TIPO_GESTION VARCHAR
    SEGMENTO VARCHAR
    ESTADO VARCHAR
    FECHA_INICIO VARCHAR
  }
  BASE_AURA_PORT_OUT_HIST {
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    FECHA VARCHAR
  }
  BASE_AURA_PORT_OUT_ULT {
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
  }
  BASE_BLOQUEOS_Recargas_30_dias {
    ULT_DIA_RECARGA VARCHAR
    TELEFONO VARCHAR
    ULT_30_DIAS_RECARGA VARCHAR
    PRODUCTO VARCHAR
    RANG_REC_ULTMES VARCHAR
  }
  BASE_BLOQUEOS_Recencia_Recargas {
    DIA VARCHAR
    TELEFONO VARCHAR
    RECENCIA_RECARGA_ETIQ VARCHAR
    RECENCIA_RECARGAS VARCHAR
    PRODUCTO VARCHAR
  }
  BASE_CALL_FIJA_TEMP_CLAQUETA {
    TELEFONOS VARCHAR
    TELEFONO VARCHAR
    FVENCIMIENTO VARCHAR
    SRC_Recibo VARCHAR
    TIPO_GESTION VARCHAR
    MEDIO VARCHAR
  }
  BASE_CALL_FIJA_TEMP_SMS {
    TELEFONOS VARCHAR
    TELEFONO VARCHAR
    FVENCIMIENTO VARCHAR
    SRC_Recibo VARCHAR
    TIPO_GESTION VARCHAR
    MEDIO VARCHAR
  }
  BASE_CALL_MOVIL_TEMP {
    TELEFONO VARCHAR
    TIPO_GESTION VARCHAR
    MEDIO VARCHAR
    FECHA_PROCESO VARCHAR
    NOMBRE_ARCHIVO VARCHAR
    GRUPO VARCHAR
  }
  BASE_ENRUTAMIENTO_ADAPTATIVO_MIGRA_X_AVERIA {
    TELEFONO VARCHAR
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
  }
  BASE_EXCEL_CR_ESTRANGULAMIENTO {
    BASE_ESTRANGULAMIENTO VARCHAR
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    DIA VARCHAR
    PLATAFORMA VARCHAR
    TRANSFERENCIA_ORDEN VARCHAR
  }
  BASE_EXCEL_CR_ESTRANGULAMIENTO_CCEE {
    BASE_ESTRANGULAMIENTO VARCHAR
    PERIODO VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    PLATAFORMA VARCHAR
    INTERACTION_ORDER VARCHAR
  }
  BASE_FACTURAS_PRIMER_GRUPO_AMDOCS_CICLO_0107 {
    TELEFONO VARCHAR
    BA_NO VARCHAR
    CUSTOMER_NO VARCHAR
    FA_ID INT
    LIN VARCHAR
  }
  BASE_FIJA_SEGMENTACION {
    PERIODO VARCHAR
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENENTO VARCHAR
  }
  BASE_IMPACTO_FACO {
    TELEFONO VARCHAR
    FECHA_CARGA VARCHAR
  }
  BASE_INCIDENCIA_COBRANZA_FIJA {
    TELEFONO VARCHAR
  }
  BASE_INICIAL_TRAMITADORES {
    TELEFONO VARCHAR
    GRABACION VARCHAR
    MOTIVO_BLOQUEO VARCHAR
    USUARIO_CARGA VARCHAR
    FECHA_CARGA VARCHAR
  }
  BASE_IVR_ADAPTATIVO {
    TELEFONO VARCHAR
    Grupo VARCHAR
    TIPO_GESTION VARCHAR
    SEGMENTO VARCHAR
    ESTADO VARCHAR
    FECHA_INICIO VARCHAR
  }
  BASE_IVR_LISTA_BLANCA {
    telefono VARCHAR
    TIPO_LINEA VARCHAR
  }
  BASE_MIGRA_FIBRA_20230309 {
    fecha VARCHAR
    NUMERO_TELEFONO VARCHAR
    DNI VARCHAR
    FLAG_CRITICO VARCHAR
    POSTVENTA_GRUPO VARCHAR
  }
  BASE_MOVIL_SEGMENTACION {
    PERIODO VARCHAR
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENENTO VARCHAR
  }
  BASE_MT_PILOTO {
    TELEFONO VARCHAR
    BASE VARCHAR
  }
  BASE_OSIPTEL_20230112 {
    orden VARCHAR
    tipo VARCHAR
    TELEFONO VARCHAR
  }
  BASE_PILOTO_CROSS_202110 {
    Telefono VARCHAR
  }
  BASE_PRIORIDAD_PLATAFORMA {
    TELEFONO VARCHAR
  }
  BASE_UNIFICADA_EXCLUIDOS {
    Telefono VARCHAR
    CUC VARCHAR
    IND_OPCION_VICIO VARCHAR
    IND_ZONA_ALEJADA VARCHAR
    TIP_GPO_ATENCION VARCHAR
    ID_ABONADO INT
  }
  BASE_USSD {
    TELEFONO VARCHAR
  }
  BASE_VICIO_MOVIL {
    TELEFONO VARCHAR
  }
  BASE_tivr_cobranzas {
    TELEFONO VARCHAR
    Column VARCHAR
    Column VARCHAR
  }
  BBDD_ClientesPotenciales_20230324 {
    ID INT
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    FLAG_PLANTA_MT VARCHAR
    POSTVENTA_SERVICIO VARCHAR
    CLIENTE VARCHAR
  }
  BD_ALEATORIO_MT_POTENCIAL {
    TELEFONO VARCHAR
    BASE VARCHAR
  }
  BD_CAEQBUYBACK_202312 {
    TELEFONO VARCHAR
    NOMBRES VARCHAR
    DNI VARCHAR
    SEGMENTO_CONVERGENTE VARCHAR
    FLAG_FINANCIAMIENTO_ACTIVO VARCHAR
    GAMAEQUIPO VARCHAR
  }
  BD_CASUISTICAS_RO3 {
    TLF VARCHAR
    CLIENTE VARCHAR
    CUENTA VARCHAR
    DOCUMENTO VARCHAR
    CODSRV VARCHAR
    CODCLI VARCHAR
  }
  BD_CASUISTICAS_RO3_INICIAL {
    TLF VARCHAR
    CLIENTE VARCHAR
    CUENTA VARCHAR
    DOCUMENTO VARCHAR
    CODSRV VARCHAR
    CODCLI VARCHAR
  }
  BD_WhatsApp_2020 {
    TELEFONO VARCHAR
    SERVICIO VARCHAR
    CIERRE VARCHAR
    ID_CASO INT
    FECHA_REGISTRO VARCHAR
    CATEGORIA VARCHAR
  }
  BLOQUEOS_BASE_Recargas_30_dias {
    ULT_DIA_RECARGA VARCHAR
    TELEFONO VARCHAR
    ULT_30_DIAS_RECARGA VARCHAR
    PRODUCTO VARCHAR
    RANG_REC_ULTMES VARCHAR
  }
  BORRAR_T_ADAP_BASE {
    ETIQUETA VARCHAR
    FECHA VARCHAR
    CDR_RELEASE_SIDE INT
    CDR_IVR_ADAPT_LABEL VARCHAR
    CDR_RESULT_CODE VARCHAR
    CDR_DNIS VARCHAR
  }
  BaseRO1_Incidencia_decosTV_datafinal04012022 {
    Order_Key VARCHAR
    Order_Start_Date DATETIME
    Order_Status_Desc VARCHAR
    Order_Status_Date DATETIME
    Customer_Key VARCHAR
    Telefono VARCHAR
  }
  BaseSimulacion_TransferenciaBlindaje_Movil_20220202 {
    telefono VARCHAR
    rango_CF VARCHAR
    antiguedad_rango VARCHAR
    Cuadrante VARCHAR
  }
  Base_0_3Mbps_Traf_Ago22 {
    telefono VARCHAR
    velocidad INT
    FECHA VARCHAR
  }
  Base_Claquetas_naked_ro02 {
    TELEFONO VARCHAR
    FA_ID INT
    DOCUMENT_NUMBER VARCHAR
  }
  Base_MT_quebrados_Final_20230831 {
    XEXCLUS VARCHAR
    PARENT_ASSIGEN_PRODUCT_KEY VARCHAR
    INT_SERVICE_ID INT
    TV_SERVICE_ID INT
    TELEFONO VARCHAR
    INT_SUBSCRIBER_KEY VARCHAR
  }
  Base_Marcar_degradado_fibra_20230420 {
    CLIENTE VARCHAR
    ACCESO_ID_REDADSL INT
    ACCESO_ID_REDHFC INT
    LINE_ID INT
    TELEFONO VARCHAR
    TIPODOC VARCHAR
  }
  Base_PortalCautivo_vcto0909_2309 {
    TELEFONO VARCHAR
    id_cliente INT
    id_producto INT
    MacAddress VARCHAR
  }
  Base_PortalCautivo_vcto0909_3009 {
    TELEFONO VARCHAR
    FECHA_PIVOT VARCHAR
    ETIQUETA_1 VARCHAR
    ETIQUETA_2 VARCHAR
    ETIQUETA_3 VARCHAR
  }
  Base_Prepago_ULT_30_DIAS_MENOR_5_SOLES_CCEE {
    TELEFONO VARCHAR
  }
  Base_a_Cargar_Prepago_Diciembre {
    TELEFONO VARCHAR
  }
  Base_a_Cargar_Prepago_Noviembre {
    TELEFONO VARCHAR
  }
  Base_a_Cargar_Prepago_Octubre {
    Telefono VARCHAR
  }
  Base_piloto_Migra_acumulado {
    TELEFONO VARCHAR
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
  }
  Base_retenidos_dscto_ajuste_argumentario {
    periodo VARCHAR
    fecha_reitero VARCHAR
    telefono_visor VARCHAR
    financial_account_key VARCHAR
    documento VARCHAR
    ultima_retencion VARCHAR
  }
  Base_validacion_diaria_renteseg_012024 {
    IMEI VARCHAR
    TELEFONO VARCHAR
    FECHA_HORA VARCHAR
    TIPO_BLOQUEO VARCHAR
  }
  Base_validacion_diaria_renteseg_022024 {
    Column VARCHAR
    TELEFONO VARCHAR
    Column VARCHAR
    Column VARCHAR
  }
  Base_validacion_diaria_renteseg_112023 {
    Column VARCHAR
    TELEFONO VARCHAR
    Column VARCHAR
    Column VARCHAR
  }
  CABINA_actualizada_030522_2 {
    Telefonos VARCHAR
    Tiendas VARCHAR
    Canal VARCHAR
    Subcanal VARCHAR
    Tecnología VARCHAR
    Socio VARCHAR
  }
  CAMP_LISTA_FIJA_202101 {
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    MENSAJE_MT VARCHAR
    MENSAJE_SA VARCHAR
    OFERTA_MENSAJE VARCHAR
  }
  CAMP_LISTA_FIJA_202102 {
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    TENENCIA VARCHAR
    OFERTA_MENSAJE VARCHAR
    FECHA_INICIO_VIGENCIA_CAMPANA VARCHAR
  }
  CAMP_LISTA_FIJA_202102_ALEATORIA_20_PC {
    TELEFONO VARCHAR
  }
  CAMP_LISTA_FIJA_NEW {
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    TENENCIA VARCHAR
    OFERTA_MENSAJE VARCHAR
    FECHA_INICIO_VIGENCIA_CAMPANA VARCHAR
  }
  CAMP_LISTA_FIJA_ULT {
    TELEFONO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    OFERTA_MENSAJE VARCHAR
  }
  CAMP_LISTA_MOVIL_202101 {
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    MENSAJE_MT VARCHAR
    MENSAJE_SA VARCHAR
    OFERTA_MENSAJE VARCHAR
  }
  CAMP_LISTA_MOVIL_202102 {
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    TENENCIA VARCHAR
    OFERTA_MENSAJE VARCHAR
    FECHA_INICIO_VIGENCIA_CAMPANA VARCHAR
  }
  CAMP_LISTA_MOVIL_202102_40 {
    TELEFONO VARCHAR
  }
  CAMP_LISTA_MOVIL_202102_ALEATORIA_ENTRE_2 {
    TELEFONO VARCHAR
  }
  CAMP_LISTA_MOVIL_NEW {
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    TENENCIA VARCHAR
    OFERTA_MENSAJE VARCHAR
    FECHA_INICIO_VIGENCIA_CAMPANA VARCHAR
  }
  CAMP_LISTA_MOVIL_ULT {
    TELEFONO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    OFERTA_MENSAJE VARCHAR
  }
  CATV_CORTADOS_09_11 {
    SOLICITANTE VARCHAR
    AREA_SOLICITANTE VARCHAR
    DESCRIPCION_MENSAJE VARCHAR
    FECHA_INICIO_PUBLICACION VARCHAR
    FECHA_FIN_PUBLICACION VARCHAR
    TELEFONO VARCHAR
  }
  CATV_CORTADOS_24_11 {
    SOLICITANTE VARCHAR
    AREA_SOLICITANTE VARCHAR
    DESCRIPCION_MENSAJE VARCHAR
    FECHA_INICIO_PUBLICACION VARCHAR
    FECHA_FIN_PUBLICACION VARCHAR
    TELEFONO VARCHAR
  }
  CDR_20220630101610_0950_0955 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
    CDR_SESSION_ID INT
  }
  CDR_20240917 {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
    CDR_SESSION_ID INT
  }
  CDR_CALL_ID_202006 {
    CDR_CALL_ID INT
  }
  CDR_VALIDAR_EN_LINEA {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
    CDR_SESSION_ID INT
  }
  CMS_Gray_List_20220704 {
    CODCLI VARCHAR
    CODCTA VARCHAR
    CODSRV VARCHAR
    CODCND VARCHAR
    CODCLASRV VARCHAR
    DESCLASRV VARCHAR
  }
  COLOCAR_TELEFONO_SEGMENTO {
    TELEFONO VARCHAR
    MES VARCHAR
    SEGMENTO VARCHAR
  }
  CORTES_ADSL_0311 {
    CLIENTE VARCHAR
    CUENTA VARCHAR
    INSCRIPCION VARCHAR
    TELEFONO VARCHAR
  }
  CX_FIJA_AMDOCS_carga_bloqueo {
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    TIPO_PRODUCTO VARCHAR
  }
  Clientes_a_migrar_a_Fibra {
    TIPDOC VARCHAR
    DOCUMENTO VARCHAR
    FIJA_TELEFONO VARCHAR
    FIJA_TECNOLOGIA VARCHAR
    COBERTURA_FTTH_FIJA VARCHAR
  }
  Completa_BA_20230222 {
    TELEFONO VARCHAR
  }
  Comunicacion_TV_20240509 {
    nombres VARCHAR
    apellidos INT
    email VARCHAR
    celular_movistar VARCHAR
    celular_competencia VARCHAR
    cuenta_financiera VARCHAR
  }
  DEGRADADOS_FIBRA_20230428 {
    TELEFONO VARCHAR
  }
  DEGRADADOS_FIBRA_20230519 {
    TELEFONO VARCHAR
  }
  DEGRADADOS_FIBRA_20230626 {
    TELEFONO VARCHAR
  }
  DEGRADADOS_FIBRA_20230724 {
    TELEFONO VARCHAR
  }
  DEGRADADOS_FIBRA_20230817 {
    TELEFONO VARCHAR
  }
  DEVOLUCION_20200905 {
    TELEFONO VARCHAR
  }
  DEVOLUCION_UPFRONT_TELEFONO_DNI {
    TELEFONO VARCHAR
    DNI VARCHAR
  }
  DNIS_NUEVA_SEGMENTACION_202009 {
    DOCUMENTO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENTO VARCHAR
  }
  DWH_LISTA_MIGRACION_FIJA_20211228 {
    TIPODOCUMENTO VARCHAR
    NRODOCUMENTO VARCHAR
    TIPOPRODUCTO VARCHAR
    BUNDLE VARCHAR
    TIPOBUNDLE VARCHAR
    ESTADOPRODUCTO VARCHAR
  }
  Desbloqueo_cobranzas_20210204 {
    TELEFONO VARCHAR
  }
  ETQ_CONTRATO_CLASICO {
    TELEFONO VARCHAR
  }
  ETQ_CONTRATO_PLATA {
    TELEFONO VARCHAR
  }
  EXCLUIR_ADSL_con_FIBRA {
    TELEFONO VARCHAR
  }
  Estructura_LN {
    GRUPO VARCHAR
    TXT_LOC_INFO VARCHAR
    ACCION VARCHAR
    RP VARCHAR
    ETIQUETA_IVR VARCHAR
  }
  FA_COMUNICACION_DEGRADACION_FIJA {
    TELEFONO VARCHAR
  }
  FA_COMUNICACION_DEGRADACION_MOVIL {
    TELEFONO VARCHAR
  }
  FA_NO_BORRAR_ADAPTATIVO_Base_FFTH_NO_MT {
    telefono VARCHAR
    abonadoatis VARCHAR
    cliente VARCHAR
    cuenta VARCHAR
    fseg VARCHAR
    TIPOdocumentounificado VARCHAR
  }
  FIJA_18012020_MAIL_DANA {
    UID INT
    anexo VARCHAR
    Nombres VARCHAR
    Email VARCHAR
    Telefono VARCHAR
    Ruta VARCHAR
  }
  FIJA_202212 {
    PERIODO VARCHAR
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENTO VARCHAR
  }
  FIJA_202305 {
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENTO VARCHAR
  }
  FIJA_202305_ {
    PERIODO VARCHAR
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENTO VARCHAR
  }
  FIJA_COMPLETA_TV_20230622 {
    DOCUMENTO VARCHAR
  }
  FIJA_COMPLETA_TV_AV_20230622 {
    DOCUMENTO VARCHAR
  }
  FIJA_REITERADORES {
    TELEFONO VARCHAR
  }
  GL_ATIS_RO3.1_27JUL {
    COLUMNA VARCHAR
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
  }
  GL_CMS_RO3.1_25JUL {
    COLUMNA VARCHAR
    CLIENTE VARCHAR
    CUENTA VARCHAR
    SERVICIO VARCHAR
    DOCUMENTO VARCHAR
  }
  GL_MONO_03_06_22 {
    CODCLI VARCHAR
    CODCTA VARCHAR
    CODSRV VARCHAR
    DOCUMENTO VARCHAR
    SEGMENTO VARCHAR
    CICLO VARCHAR
  }
  GUARDAR_BASE_TRAMITADORES {
    TELEFONO VARCHAR
    GRABACION VARCHAR
    MOTIVO_BLOQUEO VARCHAR
    USUARIO_CARGA VARCHAR
    FECHA_CARGA VARCHAR
  }
  HEAVY_USERS_20200923 {
    TELEFONO VARCHAR
  }
  ID_CASO_ENCUESTAS {
    ID_CASO INT
  }
  INC_PORT_20220317 {
    TELEFONO VARCHAR
  }
  INTRIGA_IVRIN_FTTH_2MESES_20230321 {
    documento VARCHAR
    TELEFONO VARCHAR
    GRUPO_OFERTA VARCHAR
  }
  INTRIGA_IVRIN_FTTH_6MESES_20230321 {
    documento VARCHAR
    TELEFONO VARCHAR
    GRUPO_OFERTA VARCHAR
  }
  INTRIGA_IVRIN_HFC_2MESES_20230321 {
    documento VARCHAR
    TELEFONO VARCHAR
    GRUPO_OFERTA VARCHAR
  }
  INTRIGA_IVRIN_HFC_6MESES_20230321 {
    documento VARCHAR
    TELEFONO VARCHAR
    GRUPO_OFERTA VARCHAR
  }
  Iquitos_Fija {
    Telefono VARCHAR
  }
  Iquitos_Movil {
    TELEFONO VARCHAR
  }
  JC_iNCREMENTO_PRECIO_20220901 {
    Movil VARCHAR
    FECHA_IMPACTO VARCHAR
    NOMBRE_MOVIL_CF_ANTERIOR VARCHAR
    CF_MOVIL_ANTERIOR VARCHAR
    CF_MOVIL_NUEVO VARCHAR
    FECHA VARCHAR
  }
  JOURNEY_REITERADAS_CRITICO {
    TELEFONO VARCHAR
  }
  JOURNEY_REITERADAS_CRITICO_20240529 {
    SERVICIO VARCHAR
  }
  JOURNEY_REITERADAS_CRITICO_20240902 {
    TELEFONO VARCHAR
  }
  JOURNEY_REITERADAS_CRITICO_20240903 {
    TELEFONO VARCHAR
  }
  JOURNEY_REITERADAS_CRITICO_20240904 {
    servicio VARCHAR
  }
  JOURNEY_REITERADAS_CRITICO_20240905 {
    TELEFONO VARCHAR
  }
  JOURNEY_REITERADAS_CRITICO_20240906 {
    TELEFONO VARCHAR
  }
  JOURNEY_REITERADAS_CRITICO_2024_05_29 {
    SERVICIO VARCHAR
  }
  LINEAS_SEM_40 {
    TELEFONO VARCHAR
    TROBA VARCHAR
  }
  LINEAS_SEM_42 {
    TELEFONO VARCHAR
    TROBA VARCHAR
  }
  LINEAS_SEM_43 {
    TELEFONO VARCHAR
    TROBA VARCHAR
  }
  LINEAS_SEM_45 {
    TELEFONO VARCHAR
    TROBA VARCHAR
  }
  LINEAS_SEM_46 {
    TELEFONO VARCHAR
    TROBA VARCHAR
  }
  LINEAS_SEM_47 {
    TELEFONO VARCHAR
    TROBA VARCHAR
  }
  Linea_HU_4K_20230928 {
    TELEFONO VARCHAR
  }
  ListaVip_Tenencia_20220310 {
    DNI VARCHAR
    HOJA VARCHAR
    SERVICIO VARCHAR
    TDOCUMENTO VARCHAR
    NDOCUMENTO VARCHAR
    SEGMENTO VARCHAR
  }
  ListaVip_al_20220321 {
    TIP_DOC VARCHAR
    NRO_DOC VARCHAR
    SERVICIO VARCHAR
    SEGMENTO VARCHAR
    SEGMENTO_GRUPO VARCHAR
    TELEFONO VARCHAR
  }
  Lista_VIP_20220318 {
    TIP_DOC VARCHAR
    NRO_DOC VARCHAR
    SERVICIO VARCHAR
    SEGMENTO VARCHAR
    SEGMENTO_GRUPO VARCHAR
    TELEFONO VARCHAR
  }
  Llamadas_agencias_20220318 {
    COD_SISTEMA VARCHAR
    COD_CLIENTE VARCHAR
    COD_CUENTA VARCHAR
    contactabilidad INT
    TIPO_GESTION VARCHAR
    FECHA_GESTION VARCHAR
  }
  Llamadas_agencias_20220318_v1 {
    COD_SISTEMA VARCHAR
    COD_CLIENTE VARCHAR
    COD_CUENTA VARCHAR
    contactabilidad INT
    TIPO_GESTION VARCHAR
    FECHA_GESTION VARCHAR
  }
  Llamadas_agencias_20220318_v2 {
    COD_SISTEMA VARCHAR
    COD_CLIENTE VARCHAR
    COD_CUENTA VARCHAR
    contactabilidad INT
    TIPO_GESTION VARCHAR
    FECHA_GESTION VARCHAR
  }
  Llamadas_agencias_20220318_v3 {
    COD_SISTEMA VARCHAR
    COD_CLIENTE VARCHAR
    COD_CUENTA VARCHAR
    contactabilidad INT
    TIPO_GESTION VARCHAR
    FECHA_GESTION VARCHAR
  }
  MIGRA_NOKIA_20221029 {
    IDCLIENTE INT
    MACADDRESS VARCHAR
    CAMPO VARCHAR
    Parent_assigen_product_key VARCHAR
    TELEFONO VARCHAR
    INT_SERVICE_ID INT
  }
  MOVIL_202008 {
    TELEFONO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENTO VARCHAR
    DOCUMENTO VARCHAR
  }
  MOVIL_REITERADORES {
    TELEFONO VARCHAR
  }
  MTA_Bitacora_20220718 {
    ID INT
    Herramienta VARCHAR
    FECHA VARCHAR
    HORA VARCHAR
    FECHA VARCHAR
    HORA VARCHAR
  }
  MTA_Bitacora_20220823 {
    ID INT
    Año VARCHAR
    Mes VARCHAR
    FECHA VARCHAR
    HORA VARCHAR
    FECHA VARCHAR
  }
  MT_CORTADOS_1711 {
    TELEFONO VARCHAR
  }
  MT_bloqueo_20220307 {
    TELEFONO VARCHAR
    DNI VARCHAR
  }
  Migra_Consolidado_20221025 {
    TELEFONO VARCHAR
    DESCRIPCION VARCHAR
  }
  Migra_Consolidado_20230222 {
    TELEFONO VARCHAR
    DESCRIPCION VARCHAR
  }
  Migra_Consolidado_20230308 {
    TELEFONO VARCHAR
    DESCRIPCION VARCHAR
    POSTVENTA_GRUPO VARCHAR
    tipo_cruce VARCHAR
    TIPO_SALTO VARCHAR
    otro_dato VARCHAR
  }
  Migra_Consolidado_20230331 {
    TELEFONO VARCHAR
    DESCRIPCION VARCHAR
  }
  Migra_Consolidado_20230705 {
    TELEFONO VARCHAR
    DESCRIPCION VARCHAR
  }
  Migra_Consolidado_20230718 {
    TELEFONO VARCHAR
    DESCRIPCION VARCHAR
  }
  Migra_Consolidado_20230726 {
    TELEFONO VARCHAR
    DESCRIPCION VARCHAR
  }
  Migra_Consolidado_20230809 {
    TELEFONO VARCHAR
    DESCRIPCION VARCHAR
  }
  Migra_Consolidado_20240813 {
    TELEFONO VARCHAR
    DESCRIPCION VARCHAR
  }
  Migra_TV_TV_20220104 {
    Order_Key VARCHAR
    Order_Start_Date DATETIME
    Order_Status_Desc VARCHAR
    Order_Status_Date DATETIME
    Customer_Key VARCHAR
    Telefono VARCHAR
  }
  Migración_tecnologia_ADSL_20230308 {
    SOLICITANTE VARCHAR
    AREA_SOLICITANTE VARCHAR
    DESCRIPCION_MENSAJE VARCHAR
    FECHA_INICIO_PUBLICACION VARCHAR
    FECHA_FIN_PUBLICACION VARCHAR
    TELEFONO VARCHAR
  }
  Migración_tecnologia_Fibra_20230307 {
    SOLICITANTE VARCHAR
    AREA_SOLICITANTE VARCHAR
    DESCRIPCION_MENSAJE VARCHAR
    FECHA_INICIO_PUBLICACION VARCHAR
    FECHA_FIN_PUBLICACION VARCHAR
    TELEFONO VARCHAR
  }
  Migración_tecnologia_Fibra_20230307_ok {
    SOLICITANTE VARCHAR
    AREA_SOLICITANTE VARCHAR
    DESCRIPCION_MENSAJE VARCHAR
    FECHA_INICIO_PUBLICACION VARCHAR
    FECHA_FIN_PUBLICACION VARCHAR
    TELEFONO VARCHAR
  }
  MigraxAveria_20240325 {
    DOCUMENTOCLIENTE VARCHAR
    TELEFONO VARCHAR
  }
  MigraxAveria_Enrutamiento_20240320 {
    TIPODOCUMENTOCLIENTE VARCHAR
    NUMERODOCUMENTOCLIENTE VARCHAR
    TELEFONO VARCHAR
  }
  NO_BORRAR_ADAPTATIVO_Base_MigraxAveria {
    TELEFONO VARCHAR
  }
  NO_BORRAR_ADAPTATIVO_Heavy_Users {
    TELEFONO VARCHAR
  }
  NO_BORRAR_ADAPTATIVO_Planta_MT_Diaria {
    NUMERO_DOCUMENTO VARCHAR
    NUMERO_REGISTRO VARCHAR
    NUMERO_MOVIL_PADRE_MT VARCHAR
    NUMERO_FIJO_TRIO_MT VARCHAR
    TIPO_CLIENTE VARCHAR
    ESTADO VARCHAR
  }
  NO_BORRAR_ADAPTATIVO_Planta_activa_MT {
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    MOVIL1 VARCHAR
    MOVIL2 VARCHAR
  }
  NO_BORRAR_ADAPTATIVO_Planta_con_pedidos_MT {
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    MOVIL1 VARCHAR
    MOVIL2 VARCHAR
    EstadoConvergente VARCHAR
  }
  NO_BORRAR_ADAPTATIVO_Prioridad_Fija {
    PERIODO VARCHAR
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENTO VARCHAR
  }
  NO_BORRAR_ADAPTATIVO_Prioridad_Movil {
    PERIODO VARCHAR
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENTO VARCHAR
  }
  NO_BORRAR_ADAPTATIVO_Recargas_30_dias {
    ULT_DIA_RECARGA VARCHAR
    TELEFONO VARCHAR
    ULT_30_DIAS_RECARGA VARCHAR
  }
  NO_BORRAR_ADAPTATIVO_Recencia_Recargas {
    DIA VARCHAR
    TELEFONO VARCHAR
    RECENCIA_RECARGA_ETIQ VARCHAR
    RECENCIA_RECARGAS VARCHAR
  }
  NO_BORRAR_BASE_FILTRAR_TRAMITADORES_ADHOC {
    TELEFONO VARCHAR
  }
  NO_BORRAR_INFO_LOGUEO {
    ID_LOGUEO INT
    AGENT VARCHAR
    MEDIA VARCHAR
    START VARCHAR
    END VARCHAR
    ACTIVE VARCHAR
  }
  NO_BORRAR_TRAMITADORES {
    TELEFONO VARCHAR
  }
  NO_BORRAR_TRAMITADORES_BASE_RETENCIONES_167 {
    TELEFONO_ENTRADA VARCHAR
  }
  NO_BORRAR_TRAMITADORES_BASE_RETENCIONES_167_BACKUP {
    TELEFONO_ENTRADA VARCHAR
  }
  NO_BORRAR_TRAMITADORES_VISOR_BI_RETENCIONES {
    TELEFONO VARCHAR
    MOTIVO_BLOQUEO VARCHAR
    FECHA_CARGA VARCHAR
    NOMBRE VARCHAR
  }
  NO_BORRAR_archivo_loginout {
    Tenant VARCHAR
    Agent VARCHAR
    Media VARCHAR
    Start VARCHAR
    End VARCHAR
    Active VARCHAR
  }
  NO_BORRAR_lineas_tramitadores_a_retirar {
    TELEFONO VARCHAR
    MOTIVO_BLOQUEO VARCHAR
    FECHA_CARGA VARCHAR
    FECHA VARCHAR
    NOMBRE VARCHAR
  }
  NO_BORRAR_piloto_capta_fija_mt {
    TELEFONO VARCHAR
  }
  NO_BORRAR_piloto_capta_movil_mt {
    TELEFONO VARCHAR
  }
  NO_BORRAR_tramitadores_a_retirar {
    TELEFONO VARCHAR
  }
  NUEVA_SEGMENTACION_202307 {
    TELEFONO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENTO VARCHAR
    DOCUMENTO VARCHAR
    NEGOCIO VARCHAR
  }
  NUEVA_SEGMENTACION_202308 {
    TELEFONO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENTO VARCHAR
    DOCUMENTO VARCHAR
    NEGOCIO VARCHAR
  }
  PAGOS_FICTICIOS_CAMP_20_SOLES {
    CODMES VARCHAR
    COD_SISTEMA VARCHAR
    SEGMENTO VARCHAR
    CLUSTER VARCHAR
    COD_CUENTA VARCHAR
    NRO_DOCUMENTO VARCHAR
  }
  PERFIL_TRANSFERENCIA_20250507 {
    ORIGEN VARCHAR
    RP1 VARCHAR
    RP2 VARCHAR
    ETIQUETA VARCHAR
    DESTINO VARCHAR
  }
  PILOTO_RENTESEG_20K_20231130 {
    TELEFONO VARCHAR
    Column VARCHAR
  }
  PILOTO_RENTESEG_50K_20231206 {
    TELEFONO VARCHAR
  }
  PLANTA_FIJA_B2B {
    TELEFONO VARCHAR
    PERIODO VARCHAR
    CLIENTE VARCHAR
    CUENTA VARCHAR
    RUC_CLIENTE VARCHAR
    NOMBRE_CLIENTE VARCHAR
  }
  PLANTA_MT_1 {
    Telefono VARCHAR
  }
  PLANTA_MT_20230816 {
    Documento VARCHAR
    TIPODOCUMENTO VARCHAR
    BUNDLE_LOBS_FIJA VARCHAR
    TELEFONO_FIJA VARCHAR
    movil1 VARCHAR
    movil2 VARCHAR
  }
  PLANTA_PRIORIDAD_202405 {
    PERIODO VARCHAR
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENTO VARCHAR
  }
  PLANTA_RICHI_FACT {
    SUBSCRIBER_KEY VARCHAR
    TELEFONO VARCHAR
    PRODUCTO_FACT VARCHAR
    MONEDA VARCHAR
    RANG_TOT_FACT VARCHAR
    TOT_FACT VARCHAR
  }
  PORTADOS_CLARO_20210813 {
    TELEFONO VARCHAR
  }
  Pedido_Graylist_Comunicacion_20220610 {
    Telefono VARCHAR
    NombreCliente VARCHAR
    ApellidoCliente INT
    Documento VARCHAR
    TipoDocumento VARCHAR
    DireccionInstalacion VARCHAR
  }
  Planta_CMS {
    TELEFONO_FIJO VARCHAR
    TELEFONO_MOVIL VARCHAR
    PAQUETE VARCHAR
    PLATAFORMA VARCHAR
    CLUSTER VARCHAR
    CORREO VARCHAR
  }
  Planta_HFC_202202 {
    Column VARCHAR
    IDEMPRESA INT
    ESTADOCLIENTE VARCHAR
    CM_IDPRODUCTO INT
    CM_MACADDRESS VARCHAR
    CM_IP VARCHAR
  }
  Planta_MT_Ago24 {
    TELEFONO VARCHAR
    TELEFONO_POSTPAGO1 VARCHAR
    PAQUETEMT VARCHAR
    CLUSTER_ VARCHAR
    TECNOLOGIA_BA VARCHAR
  }
  Planta_MT_MargenAlto_FTTH_120824 {
    DOCUMENTO VARCHAR
    TELEFONO_POSTPAGO1 VARCHAR
    TELEFONO_POSTPAGO2 VARCHAR
    TELEFONO VARCHAR
    INT_SERVICE_ID INT
    TENENCIA_PLANTA VARCHAR
  }
  Planta_MT_MargenAlto_FTTH_120824_V2 {
    DIVISION VARCHAR
    DOCUMENTO VARCHAR
    TELEFONO_POSTPAGO1 VARCHAR
    TELEFONO_POSTPAGO2 VARCHAR
    TELEFONO VARCHAR
    INT_SERVICE_ID INT
  }
  Potencial_DIVICAUS_MxA_20231005 {
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    NOMBRE VARCHAR
    CODIGO VARCHAR
    DIVICAU VARCHAR
    FUENTE VARCHAR
  }
  Q_canales_MT_movil_10k {
    estado_plan VARCHAR
    segmento VARCHAR
    flag_mt VARCHAR
    cargo_fijo VARCHAR
    CICLO VARCHAR
    codigo_plan VARCHAR
  }
  RA_DET_PLANTA_POSTPAGO_FACT {
    PERIODO VARCHAR
    SUBSCRIBER_KEY VARCHAR
    TELEFONO VARCHAR
    TIPO_PRODUCTO VARCHAR
    PRODUCTO_FACT VARCHAR
    FECHA_EMISION VARCHAR
  }
  RA_DET_PLANTA_POSTPAGO_FACT_SEG {
    PERIODO VARCHAR
    SUBSCRIBER_KEY VARCHAR
    TELEFONO VARCHAR
    TIPO_PRODUCTO VARCHAR
    PRODUCTO_FACT VARCHAR
    FECHA_EMISION VARCHAR
  }
  RA_DET_PLANTA_POSTPAGO_FACT_SEG_2 {
    PERIODO VARCHAR
    SUBSCRIBER_KEY VARCHAR
    TELEFONO VARCHAR
    TIPO_PRODUCTO VARCHAR
    PRODUCTO_FACT VARCHAR
    FECHA_EMISION VARCHAR
  }
  RA_LLAM_ENT_CC_ULTIMO_MES {
    PERIODO VARCHAR
    Interaction VARCHAR
    Handling VARCHAR
    FECHA_LLAMADA VARCHAR
    TELEFONO VARCHAR
    TIPO VARCHAR
  }
  RA_NO_RECARGADORES_30_120_DIAS {
    FECHA VARCHAR
    TELEFONO VARCHAR
    RECENCIA VARCHAR
    RECENCIA_ETIQ VARCHAR
    DOCUMENTO VARCHAR
    MOVILES_NO_PREPAGO VARCHAR
  }
  RA_NO_RECARGADORES_30_120_DIAS_ANTERIOR {
    FECHA VARCHAR
    TELEFONO VARCHAR
    RECENCIA VARCHAR
    RECENCIA_ETIQ VARCHAR
  }
  RA_PLANTA_PREPAGO_RECARGADORA_PROM3M {
    TELEFONO VARCHAR
    ARPU_3 VARCHAR
    ARPU_2 VARCHAR
    ARPU_1 VARCHAR
    ARPU_0 VARCHAR
    PROM_ARPU3M VARCHAR
  }
  RA_PLANTA_PREPAGO_RECARGADORA_PROM3M_SEG {
    TELEFONO VARCHAR
    ARPU_3 VARCHAR
    ARPU_2 VARCHAR
    ARPU_1 VARCHAR
    ARPU_0 VARCHAR
    PROM_ARPU3M VARCHAR
  }
  RA_PLANTA_PREPAGO_RECARGADORA_ULT3M {
    TELEFONO VARCHAR
    ARPU_3 VARCHAR
    ARPU_2 VARCHAR
    ARPU_1 VARCHAR
    ARPU_0 VARCHAR
  }
  RA_REITERADAS_FIJA_MAS_DE_2_ULT24HORAS {
    TELEFONO VARCHAR
    CANT_LLAM VARCHAR
  }
  RA_REITERADAS_MAS_DE_2_ULT24HORAS {
    TELEFONO VARCHAR
    CANT_LLAM VARCHAR
  }
  RA_TELEF_UNICOS_LOGIN_APP_MIMOV {
    MES VARCHAR
    TELEFONO VARCHAR
    CANT_LOGINS VARCHAR
  }
  RA_TEL_POSTPAGO_CLUSTERS {
    PERIODO VARCHAR
    TELEFONO VARCHAR
    PRODUCTO VARCHAR
    CLUSTER_FACT VARCHAR
  }
  RA_TEL_PREPAGO_CLUSTERS {
    PERIODO VARCHAR
    TELEFONO VARCHAR
    PRODUCTO VARCHAR
    CLUSTER_RECARGA VARCHAR
  }
  RA_TEL_PREPAGO_CLUSTERS_20_25 {
    TELEFONO VARCHAR
  }
  RA_TEL_PREPAGO_CLUSTERS_25_30 {
    TELEFONO VARCHAR
  }
  RA_TMP_REITERADAS_FIJA_MAS_DE_2_ULT24HORAS {
    TELEFONO VARCHAR
    CANT_LLAM VARCHAR
  }
  RA_TMP_REITERADAS_MAS_DE_2_ULT24HORAS {
    TELEFONO VARCHAR
    CANT_LLAM VARCHAR
  }
  RENTESEG_20231213 {
    TELEFONO VARCHAR
  }
  RG_BASE_PREPAGO_RECARGADOR_00_15 {
    TELEFONO VARCHAR
  }
  RG_BASE_REITERADAS_FIJA_MAYOR3 {
    TELEFONO VARCHAR
  }
  RG_MOVIL_AUMENTA_VELOCIDAD {
    TELEFONO VARCHAR
  }
  RG_REITERADAS_2_ULT24HORAS {
    Telefono VARCHAR
    PRODUCTO VARCHAR
  }
  RG_REITERADOS_CRONICOS {
    TELEFONO VARCHAR
  }
  RG_TABLA_ENRUTAMIENTO_ALTAS_MIGRADOS {
    TELEFONO VARCHAR
  }
  RG_TABLA_ENRUTAMIENTO_TECNICA {
    TELEFONO VARCHAR
  }
  ROLL_OUT_0_20210825_NO_CONSIDERAR {
    TIPO_PRODUCTO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    DIR_INSTALACION VARCHAR
    TEL_CONTACTO VARCHAR
  }
  RO_0_20210630 {
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
  }
  RO_0_20210713 {
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
  }
  RO_0_20210727 {
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    FLAG_MT VARCHAR
  }
  RTD_Planta_Pangea_20240425 {
    address_id INT
    home_id INT
    cto_code VARCHAR
    cli_nro_doc VARCHAR
    cli_tipo_doc VARCHAR
    service_id INT
  }
  RTD_Planta_Pangea_20240801 {
    address_id INT
    home_id INT
    cto_code VARCHAR
    cli_nro_doc VARCHAR
    cli_tipo_doc VARCHAR
    service_id INT
  }
  Reclamos_080523vf {
    TELEFONO VARCHAR
    SUBSCRIBER_KEY VARCHAR
    CUSTOMER_KEY VARCHAR
    NEGOCIO_FA VARCHAR
    BASE VARCHAR
    DNI VARCHAR
  }
  Repetidor_20210713 {
    Telefono VARCHAR
    NumeroDocumentoUnificado VARCHAR
  }
  Reporte_Direccion_Instalacion_GL_PRE {
    TIPO_PRODUCTO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    DIR_INSTALACION VARCHAR
    TEL_CONTACTO VARCHAR
  }
  Reporte_Direccion_Instalacion_GL_PRE_EXCEL {
    TIPO_PRODUCTO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    DIR_INSTALACION VARCHAR
    TEL_CONTACTO VARCHAR
  }
  Reporte_Direccion_Instalacion_WL_20220731 {
    TIPO_PRODUCTO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    DIR_INSTALACION VARCHAR
    TEL_CONTACTO VARCHAR
  }
  Reporte_Direccion_Instalacion_WL_RO2_20220227 {
    TIPO_PRODUCTO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    DIR_INSTALACION VARCHAR
    TEL_CONTACTO VARCHAR
  }
  Reporte_Direccion_Instalacion_WL_V2 {
    TIPO_PRODUCTO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    DIR_INSTALACION VARCHAR
    TEL_CONTACTO VARCHAR
  }
  SUSPENSION_ADSL_0110 {
    TELEFONO VARCHAR
  }
  T3 {
    QUERY VARCHAR
  }
  T4 {
    QUERY VARCHAR
  }
  TECNICA_CROSS_potencial_202202 {
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    flag_nuevo VARCHAR
    flag_canal VARCHAR
    flag_base VARCHAR
  }
  TEMP_BASE_ACTUAL {
    TELEFONO VARCHAR
  }
  TEMP_CESAR_1 {
    ANI VARCHAR
    LLAMADAS VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    LLAMADAS_CABINA VARCHAR
    NAC_DIFERENTES VARCHAR
    PLATAFORMA VARCHAR
  }
  TEMP_EXPORT_DEGRA_OM {
    TELEFONO VARCHAR
    ID INT
  }
  TEMP_SMS_PORTA {
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
  }
  TEMP_VALIDAR {
    FECHA VARCHAR
    CROIN_Proveedor VARCHAR
    CROIN_NEGOCIO VARCHAR
    CROIN_PLATAFORMA VARCHAR
    CROIN_Codigo_Grupo VARCHAR
    Q_Planificacion_Solicitado VARCHAR
  }
  TMP_ATENDIDAS_CESAR {
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_HORA_INICIO_LLAMADA VARCHAR
    ANI VARCHAR
    NUMERO_CONSULTA VARCHAR
    DNI_AGENTE VARCHAR
    PLATAFORMA VARCHAR
  }
  TMP_CLUSTERS_IVR_ADAPTATIVO {
    TELEFONO VARCHAR
    TIPO_GESTION VARCHAR
    NEGOCIO VARCHAR
    FECHA_CREACION VARCHAR
    PERIODO_PLANTA VARCHAR
  }
  TRAMITADORES {
    TELEFONO VARCHAR
  }
  TRAMITADORES_20221003 {
    TELEFONO VARCHAR
  }
  TRAMITADORES_anterior {
    TELEFONO VARCHAR
  }
  TRAMITADOR_JULIO2019_1 {
    TELEFONO VARCHAR
  }
  TROBAS_SATURADAS_202007 {
    TELEFONO VARCHAR
    TROBA VARCHAR
  }
  TROBAS_SATURADAS_202007_ {
    Telefono VARCHAR
    TROBA VARCHAR
    Nodo VARCHAR
    Plano VARCHAR
    Area VARCHAR
    Provincia VARCHAR
  }
  TROBAS_SATURADAS_202007_ANT_V2 {
    Telefono VARCHAR
    TROBA VARCHAR
    Nodo VARCHAR
    Plano VARCHAR
    Area VARCHAR
    Provincia VARCHAR
  }
  TROBAS_SATURADAS_202007_SEM34 {
    Telefono VARCHAR
    TROBA VARCHAR
    Nodo VARCHAR
    Plano VARCHAR
    Area VARCHAR
    Provincia VARCHAR
  }
  TROBAS_SATU_PORC {
    TROBA VARCHAR
    SAT VARCHAR
  }
  TROBAS_SATU_PORC_ {
    TROBA VARCHAR
    SAT VARCHAR
  }
  TROBAS_SATU_PORC_ANT_V2 {
    TROBA VARCHAR
    SAT VARCHAR
  }
  TROBAS_SATU_PORC_SEM34 {
    TROBA VARCHAR
    SAT VARCHAR
  }
  TROBA_SATU_202008 {
    Telefono VARCHAR
    TROBA VARCHAR
    Nodo VARCHAR
    Plano VARCHAR
    Area VARCHAR
    Provincia VARCHAR
  }
  TROBA_SEM_40 {
    TROBA VARCHAR
    TIPO_SATURAC VARCHAR
    SATURAC VARCHAR
  }
  TROBA_SEM_42 {
    TROBA VARCHAR
    TIPO_SATURAC VARCHAR
    SATURAC VARCHAR
  }
  TROBA_SEM_43 {
    TROBA VARCHAR
    TIPO_SATURAC VARCHAR
    SATURAC VARCHAR
  }
  TROBA_SEM_45 {
    TROBA VARCHAR
    TIPO_SATURAC VARCHAR
    SATURAC VARCHAR
  }
  TROBA_SEM_46 {
    TROBA VARCHAR
    TIPO_SATURAC VARCHAR
    SATURAC VARCHAR
  }
  TROBA_SEM_47 {
    TROBA VARCHAR
    TIPO_SATURAC VARCHAR
    SATURAC VARCHAR
  }
  T_ADAP_BASE {
    ETIQUETA VARCHAR
    FECHA VARCHAR
    RESULT VARCHAR
    CANTIDAD INT
    FUENTE VARCHAR
    PERIODO VARCHAR
  }
  T_ADAP_BASE_V2 {
    ETIQUETA VARCHAR
    FECHA VARCHAR
    CDR_RELEASE_SIDE INT
    CDR_IVR_ADAPT_LABEL VARCHAR
    CDR_RESULT_CODE VARCHAR
    CDR_DNIS VARCHAR
  }
  T_ADAP_BASE_V3 {
    ETIQUETA VARCHAR
    FECHA VARCHAR
    CDR_RELEASE_SIDE INT
    CDR_IVR_ADAPT_LABEL VARCHAR
    CDR_RESULT_CODE VARCHAR
    CDR_BLOCK_REASON VARCHAR
  }
  T_ADAP_BASE_V4 {
    FUENTE VARCHAR
    PERIODO VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    FECHA VARCHAR
    NEGOCIO VARCHAR
  }
  T_ADAP_CDU_FCR {
    CDR_LAST_USE_cASE VARCHAR
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
  }
  T_ADAP_STATUS {
    FECHA VARCHAR
    NEGOCIO VARCHAR
    NOMBRE VARCHAR
    VOLUMEN VARCHAR
    ACCION VARCHAR
    FECHA_ACTUALIZACION VARCHAR
  }
  T_ADAP_TIPO {
    ETIQUETA VARCHAR
    NEGOCIO VARCHAR
    NOMBRE VARCHAR
    ACCION VARCHAR
    TIPO_CLIENTE VARCHAR
    NIVEL_2 VARCHAR
  }
  T_BASE {
    TELEFONO VARCHAR
  }
  T_BASEBONO_MTSA_ {
    N VARCHAR
    numerodocumento VARCHAR
    NombreCliente VARCHAR
    telefono_contacto1 VARCHAR
    telefono_contacto2 VARCHAR
    Correo_Contacto VARCHAR
  }
  T_BASES_COMUNICACION_DEGRADACION {
    TELEFONO VARCHAR
    FECHA_IMPACTO VARCHAR
    NEGOCIO VARCHAR
  }
  T_BASE_2 {
    TELEFONO VARCHAR
    BASE VARCHAR
  }
  T_BASE_50_MT_AURA {
    TELEFONO VARCHAR
  }
  T_BASE_ANALGESICO {
    telefono VARCHAR
    grupo VARCHAR
  }
  T_BASE_AUTOMATISMOS_AURA {
    CDR_RESULT_CODE VARCHAR
    CDR_BLOCK_REASON VARCHAR
    TIPO VARCHAR
    DESCRIPCION VARCHAR
    NIVEL_1 VARCHAR
    NIVEL_2 VARCHAR
  }
  T_BASE_CLIENTES_ALTAS_NUEVAS_MIGRADOS_1ERMES_PREP_AURA {
    TELEFONO VARCHAR
    PRODUCTO VARCHAR
    SISTEMA VARCHAR
    FECHA_HOY VARCHAR
    FECHA_ALTA_CARIU VARCHAR
    DIAS_HOY_VS_ALTA VARCHAR
  }
  T_BASE_CLIENTES_ALTAS_NUEVAS_MIGRADOS_AURA {
    TELEFONO VARCHAR
    PRODUCTO VARCHAR
    SISTEMA VARCHAR
    FECHA_HOY VARCHAR
    FECHA_ALTA_CARIU VARCHAR
    DIAS_HOY_VS_ALTA VARCHAR
  }
  T_BASE_CLIENTES_PRESUNTOS_TRAMITADORES {
    TELEFONO VARCHAR
    Cant_NAC_Dif VARCHAR
    Ent_Mov_Postpago VARCHAR
    Ent_Mov_Contrato VARCHAR
    Ent_Mov_Prepago VARCHAR
    Ent_Mov_Facturacion VARCHAR
  }
  T_BASE_CLIENTES_REIT_TEC_FIJA {
    ANI VARCHAR
    PLATAFORMA VARCHAR
    LLAMADAS VARCHAR
    FECHA_HOY VARCHAR
  }
  T_BASE_CLIENTES_REIT_TEC_MOVIL {
    ANI VARCHAR
    PLATAFORMA VARCHAR
    LLAMADAS VARCHAR
    FECHA_HOY VARCHAR
  }
  T_BASE_COMUNICACION_COBRANZAS {
    TELEFONO VARCHAR
    GRUPO VARCHAR
    FECHA VARCHAR
  }
  T_BASE_PILOTO_ALTAS_TACNA {
    TIPO_DOCUMENTO VARCHAR
    NUM_DOCUMENTO VARCHAR
    TELEFONO VARCHAR
  }
  T_BASE_RECENCIA_CCEE_MARIEL {
    TELEFONO VARCHAR
  }
  T_BASE_REITERADORES_TRATAMIENTO {
    ANI VARCHAR
    SISTEMA VARCHAR
    SEGMENTO VARCHAR
    PRODUCTO VARCHAR
    LLAMADAS VARCHAR
    BASE VARCHAR
  }
  T_BASE_SMS_ENVIO_IP_2021_MOVIL {
    TELEFONO VARCHAR
    ARCHIVO VARCHAR
    FECHA_IMPACTO VARCHAR
    NOMBRE_MOVIL_CF VARCHAR
    CF_MOVIL_ANTERIOR VARCHAR
    CF_MOVIL_NUEVO VARCHAR
  }
  T_BASE_SMS_ENVIO_IP_2021_MT {
    TELEFONO VARCHAR
    ARCHIVO VARCHAR
    FECHA_IMPACTO VARCHAR
    NOMBRE_MT_CF VARCHAR
    CF_MT VARCHAR
    CF_MT VARCHAR
  }
  T_CARPETA_TEMP {
    CARPETA VARCHAR
    GRUPO VARCHAR
  }
  T_CATV_CORTADOS_09_11 {
    TELEFONO VARCHAR
    ESTADOABONADODESC VARCHAR
    CMS_SERVICIO VARCHAR
    CMS_ESTADOABONADO VARCHAR
    MACROSEGMENTOTOP VARCHAR
    NUMERODOCUMENTOUNIFICADO VARCHAR
  }
  T_DETALLE_ONEMARKETER_TEMP_DAILY {
    Id_Caso INT
    Operador_Abre VARCHAR
    Servicio VARCHAR
    Nombre_Asesor VARCHAR
    Operador_Cierre VARCHAR
    Id_usuario INT
  }
  T_DIM_BASE_CONVERGENTE {
    NUMERO_DOCUMENTO VARCHAR
    NUMERO_REGISTRO VARCHAR
    NUMERO_MOVIL_PADRE_MT VARCHAR
    NUMERO_FIJO_TRIO_MT VARCHAR
    TIPO_CLIENTE VARCHAR
    ESTADO VARCHAR
  }
  T_DIM_BASE_MTP_x_CLIENTE {
    MES_ANIO VARCHAR
    SEGMENTO VARCHAR
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    CLUSTER_COMERCIAL VARCHAR
    TIPO_MOVIL VARCHAR
  }
  T_DIM_BASE_MTP_x_CLIENTE2 {
    MES_ANIO VARCHAR
    SEGMENTO VARCHAR
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    CLUSTER_COMERCIAL VARCHAR
    TIPO_MOVIL VARCHAR
  }
  T_DIM_BASE_MTP_x_CLIENTE3 {
    MES_ANIO VARCHAR
    SEGMENTO VARCHAR
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    CLUSTER_COMERCIAL VARCHAR
    TIPO_MOVIL VARCHAR
  }
  T_DIM_BASE_MTP_x_CLIENTE_ADAPTATIVO {
    MES_ANIO VARCHAR
    SEGMENTO VARCHAR
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    CLUSTER_COMERCIAL VARCHAR
    TIPO_MOVIL VARCHAR
  }
  T_DIM_LOG_IVR_ADAPTATIVO {
    MENSAJE VARCHAR
    HORA_SISTEMA VARCHAR
    NOMBRE_JOB VARCHAR
  }
  T_ENCUESTAS_LOCALIDAD_CLUSTER {
    L1 VARCHAR
    L2 VARCHAR
    NEGOCIO VARCHAR
  }
  T_ENVIO_SMS_202103 {
    TELEFONO VARCHAR
    GRUPO VARCHAR
    TIPO VARCHAR
  }
  T_EXCEL_IP_MOVIL_2021 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    PLATAFORMA VARCHAR
    TRANSFERENCIA_ORDEN VARCHAR
  }
  T_EXCEL_IP_MOVIL_2021_CCEE {
    PERIODO VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    PLATAFORMA VARCHAR
    INTERACTION_ORDER VARCHAR
  }
  T_EXPORTADO_CLIENTES_LN {
    TELEFONO VARCHAR
    GRUPO VARCHAR
  }
  T_EXPORTAR_ADAPTATIVO_CCEE {
    TELEFONO VARCHAR
    GRUPO VARCHAR
  }
  T_EXPORTAR_ADAPTATIVO_FIJA {
    TELEFONO VARCHAR
    GRUPO VARCHAR
  }
  T_EXPORTAR_ADAPTATIVO_MOVIL {
    TELEFONO VARCHAR
    GRUPO VARCHAR
  }
  T_EXPORTAR_ADAPTATIVO_MT {
    TELEFONO VARCHAR
    GRUPO VARCHAR
  }
  T_EXPORTAR_MIGRACION_FIBRA_FIJA {
    TELEFONO VARCHAR
    DESCRIPCION VARCHAR
  }
  T_GRAYLIST_RESD_ATIS_20221102_BASE_RO2 {
    DATO VARCHAR
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    FLAG_MT VARCHAR
    PRODUCTO VARCHAR
  }
  T_Grupos_CDU_1 {
    padre_cdu VARCHAR
    Grupos VARCHAR
  }
  T_Grupos_CDU_2 {
    PADRE_CDU VARCHAR
    GRUPOS VARCHAR
  }
  T_IMEI_20200227 {
    telefono VARCHAR
  }
  T_INFO_PREVISION_MES_PRONOSTICO {
    PERIODO VARCHAR
    PREV_PLATAFORMA VARCHAR
    PREV_VALOR VARCHAR
  }
  T_INFO_PREVISION_MES_PRONOSTICO_JAVI {
    PERIODO VARCHAR
    PREV_PLATAFORMA VARCHAR
    PLATAFORMA_PPP VARCHAR
    PREV_VALOR VARCHAR
  }
  T_INFO_PREVISION_X_DIA_X_GRUPO_PLATAFORMA {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    FECHA VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    ENTRANTES VARCHAR
  }
  T_INFO_PREVISION_X_DIA_X_PLATAFORMA_PPP {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    FECHA VARCHAR
    PLATAFORMA VARCHAR
    ENTRANTES VARCHAR
  }
  T_INFO_PREVISION_X_DIA_X_PLATAFORMA_PPP_DETALLE {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    FECHA VARCHAR
    PLATAFORMA VARCHAR
    ENTRANTES VARCHAR
  }
  T_INFO_PREVISION_X_DIA_X_PLATAFORMA_PPP_JAVI {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    FECHA VARCHAR
    PLATAFORMA_PPP VARCHAR
    ENTRANTES VARCHAR
  }
  T_INFO_PREVISION_X_INTERVALOS {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    INTERVALO VARCHAR
    FECHA VARCHAR
    PLATAFORMA VARCHAR
  }
  T_INFO_PREVISION_X_INTERVALO_X_PLATAFORMA_PPP {
    CANAL VARCHAR
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  T_INFO_PREVISION_X_INTERVALO_X_PLATAFORMA_PPP_DETALLE {
    CANAL VARCHAR
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  T_INFO_PREVISION_X_INTERVALO_X_PLATAFORMA_PPP_DETALLE_2 {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
    PLATAFORMA_PPP VARCHAR
  }
  T_INFO_PREVISION_X_INTERVALO_X_PLATAFORMA_PPP_JAVI {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
    PLATAFORMA_PPP VARCHAR
  }
  T_INTERVALO_HORARIO {
    INTERVALO VARCHAR
    TIPO_HORARIO VARCHAR
  }
  T_IP_INSERT {
    TELEFONO VARCHAR
    FECHA_IMPACTO VARCHAR
    NOMBRE_MOVIL_CF_ANTERIOR VARCHAR
    CF_MOVIL_ANTERIOR VARCHAR
    CF_MOVIL_NUEVO VARCHAR
    MES_INCREMENTADO VARCHAR
  }
  T_IP_INSERT_CHAMO {
    TELEFONO VARCHAR
    FECHA_IMPACTO VARCHAR
    NOMBRE_MOVIL_CF_ANTERIOR VARCHAR
    CF_MOVIL_ANTERIOR VARCHAR
    CF_MOVIL_NUEVO VARCHAR
    MES_INCREMENTADO VARCHAR
  }
  T_LOG {
    NOMBRE_BASE VARCHAR
    FECHA_LOG VARCHAR
    CANTIDAD INT
    TIPO_PROCESO VARCHAR
  }
  T_LOG_BASE_DEGRA {
    ID_BASE INT
    FECHA_SISTEMA VARCHAR
    Q_CANTIDAD_BASE INT
    NEGOCIO VARCHAR
  }
  T_LOG_BASE_NPS_AVISO_CORTE_2 {
    TELEFONO VARCHAR
    FECHA_SISTEMA VARCHAR
    Q_CANTIDAD_BASE INT
    SEGMENTO VARCHAR
  }
  T_LOG_LINEAS_DEGRA {
    ID_BASE INT
    TELEFONO VARCHAR
  }
  T_LOG_MENSAJERIA_COBRANZA_ACCESADAS {
    ID INT
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    SEMANA VARCHAR
    DIA VARCHAR
    TIPO_ACCION_LLAMADA_N1 VARCHAR
  }
  T_LOG_MENSAJERIA_COBRANZA_BASE {
    ID INT
    TELEFONO VARCHAR
  }
  T_LOG_MENSAJERIA_COBRANZA_ENTRANTES {
    ID INT
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    SEMANA VARCHAR
    DIA VARCHAR
    PLATAFORMA VARCHAR
  }
  T_LOG_MENSAJERIA_COBRANZA_ID {
    ID INT
    NEGOCIO VARCHAR
    TIPO_GESTION VARCHAR
    MEDIO VARCHAR
    GRUPO VARCHAR
    FECHA_PROCESO VARCHAR
  }
  T_LOG_PROCESO_CARGA_IVR_ADAPTATIVO {
    LOG_ID INT
    LOG_PROCESO VARCHAR
    LOG_FECHA VARCHAR
    LOG_GRUPO VARCHAR
    LOG_MODIFICACION VARCHAR
    LOG_CANTIDAD_BASE INT
  }
  T_Masificacion1MB_572K {
    TELEFONO VARCHAR
  }
  T_Mensaje_1_20210916 {
    TELEFONO VARCHAR
  }
  T_PAGOS_FICTICIOS_20220222 {
    TELEFONO VARCHAR
    FECHA_VENCIMIENTO VARCHAR
  }
  T_PLANTA_FIJA_TOTAL_IncPrecio_202201 {
    TELEFONO VARCHAR
    CICLO VARCHAR
    DOCUMENTO VARCHAR
    TIPO VARCHAR
    SISTEMA VARCHAR
    SEGMENTO VARCHAR
  }
  T_PLANTA_RENTA_202201 {
    NEGOCIO VARCHAR
    NUMEROTELEFONO VARCHAR
    PLAN_CARGOFIJO VARCHAR
    ESTADOCOMERCIALDESC VARCHAR
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    LINEANEGOCIODESC VARCHAR
  }
  T_PLANTA_RENTA_202201_COMERCIAL {
    NEGOCIO VARCHAR
    NUMEROTELEFONO VARCHAR
    PLAN_CARGOFIJO VARCHAR
    ESTADOCOMERCIALDESC VARCHAR
    SEGMENTOGRUPOCLIENTEDESC VARCHAR
    LINEANEGOCIODESC VARCHAR
  }
  T_PRUEBA_PLANTA_POSTPAGO_EDAD {
    TELEFONO VARCHAR
  }
  T_RESTO_ENTRANTES_ADAPTATIVO_ULT {
    TELEFONO VARCHAR
  }
  T_RESTO_ENTRANTES_ADAPTATIVO_ULT_TODAY {
    TELEFONO VARCHAR
  }
  T_RESUMEN_FUNNEL_CCEE_DIA {
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    DIA VARCHAR
    FUNNEL_N1 VARCHAR
    FUNNEL_N2 VARCHAR
    FUNNEL_N3 VARCHAR
  }
  T_SMS_20211026 {
    TELEFONO VARCHAR
    ARCHIVO VARCHAR
    FECHA VARCHAR
  }
  T_SMS_SMS {
    TELEFONO VARCHAR
  }
  T_TELEFONO {
    TELEFONO VARCHAR
  }
  T_TELEFONOS_NO_BLOQUEO {
    TELEFONO VARCHAR
  }
  T_TEMP_BASES_DEGRA {
    ID_BASE INT
    FECHA_INICIO VARCHAR
    NEGOCIO VARCHAR
    FECHA_FIN VARCHAR
  }
  T_TEMP_EXP_MAX {
    ID INT
    TELEFONO VARCHAR
  }
  T_TEMP_RESUMEN_ADAP {
    NEGOCIO VARCHAR
    GRUPO VARCHAR
    CANTIDAD INT
  }
  T_UMBRALES {
    PLATAFORMA VARCHAR
    TIPO_PREV_MES VARCHAR
    TIPO_HORARIO VARCHAR
    UMBRAL_MINIMO VARCHAR
    UMBRAL_MAXIMO VARCHAR
    FECHA_INICIO VARCHAR
  }
  T_UMBRALES_PLATAFORMA_PPP {
    PLATAFORMA VARCHAR
    TIPO_PREV_MES VARCHAR
    TIPO_HORARIO VARCHAR
    MINIMO VARCHAR
    MAXIMO VARCHAR
    FECHA_INICIO VARCHAR
  }
  T_VAL {
    val VARCHAR
  }
  T_VALIDAR {
    FECHA VARCHAR
    CANTIDAD INT
  }
  T_validar_cdu_202106 {
    CDU VARCHAR
    TIPO VARCHAR
    NEGOCIO VARCHAR
  }
  Tethering_20230927 {
    TELEFONO VARCHAR
  }
  Trobas_Saturadas_noviembre {
    TELEFONO VARCHAR
  }
  UP_SEM_34 {
    TROBA VARCHAR
    OCUPACION VARCHAR
  }
  VALIDAR_RP_ADAP_20221019 {
    VALIDAR_RP INT
  }
  Z_TEMP_NO_RECARGADORES_30_120_DIAS {
    FECHA VARCHAR
    TELEFONO VARCHAR
    RECENCIA_RECARGA_ETIQ VARCHAR
    RECENCIA_RECARGAS VARCHAR
  }
  agentes_cross_202305 {
    DOCUMENTO VARCHAR
    PLATAFORMA VARCHAR
  }
  agentes_cross_ranking_202305 {
    PERIODO VARCHAR
    ASESOR VARCHAR
    PRODUCTO VARCHAR
    SOCIO VARCHAR
    Q VARCHAR
    Q VARCHAR
  }
  apagado_3g_base_total {
    numero VARCHAR
    distrito_mkt VARCHAR
  }
  asistencia_11102023_BI {
    fecha_asistencia VARCHAR
    dni VARCHAR
    apellidos_nombre INT
  }
  averia_20220314 {
    SOLICITANTE VARCHAR
    AREA_SOLICITANTE VARCHAR
    DESCRIPCION_MENSAJE VARCHAR
    FECHA_INICIO_PUBLICACION VARCHAR
    FECHA_FIN_PUBLICACION VARCHAR
    TELEFONO VARCHAR
  }
  baja_shaper_20230417 {
    TELEFONO VARCHAR
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
  }
  base {
    tabla VARCHAR
  }
  base_10k_piloto_comunicacion {
    TELEFONO VARCHAR
    documento VARCHAR
    flag_movil_movistar VARCHAR
    flag_postpago VARCHAR
    flag_prepago VARCHAR
    CELULAR VARCHAR
  }
  base_MT_quebrado_20230828 {
    XEXCLUS VARCHAR
    PARENT_ASSIGEN_PRODUCT_KEY VARCHAR
    INT_SERVICE_ID INT
    TV_SERVICE_ID INT
    TELEFONO VARCHAR
    INT_SUBSCRIBER_KEY VARCHAR
  }
  base_Migracion_FTTH_No_Navega_V2 {
    Telefono VARCHAR
  }
  base_Reclamos_movil_6k_20230508 {
    FINANCIAL_ACCOUNT VARCHAR
    TELEFONO VARCHAR
  }
  base_Reclamos_movil_8k_20230508 {
    TELEFONO VARCHAR
  }
  base_migra_20230719 {
    SOLICITANTE VARCHAR
    AREA_SOLICITANTE VARCHAR
    DESCRIPCION_MENSAJE VARCHAR
    FECHA_INICIO_PUBLICACION VARCHAR
    FECHA_FIN_PUBLICACION VARCHAR
    TELEFONO VARCHAR
  }
  base_migracion_ftth_no_navega {
    Telefono VARCHAR
  }
  base_piloto_MxA_20231011 {
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    NOMBRE VARCHAR
    CODIGO VARCHAR
    DIVICAU VARCHAR
    FUENTE VARCHAR
  }
  base_porta_fija_400K {
    DNI VARCHAR
  }
  base_tramitadores_enviador_202205 {
    TELEFONO VARCHAR
    BASE VARCHAR
  }
  base_trobas_piloto_solucion_20210902 {
    TELEFONO VARCHAR
  }
  base_ventas_portabilidad_20220302 {
    FECHA VARCHAR
    BACK VARCHAR
    DNI VARCHAR
    ASESOR VARCHAR
    TURNO VARCHAR
    ANI VARCHAR
  }
  bd_upsell_capl_202301 {
    Telefono_Movil VARCHAR
  }
  bloqueo_envio_sms_2021 {
    TELEFONO VARCHAR
    TIPO VARCHAR
  }
  clientesEnPuertoSaturado {
    cliente VARCHAR
    servicio VARCHAR
    NODO VARCHAR
    troba VARCHAR
    telf1 VARCHAR
    telf2 VARCHAR
  }
  clientes_ftth_olts_saturadas {
    telefono VARCHAR
    nombrecliente VARCHAR
    provincia VARCHAR
    localidad INT
    sublocalidad INT
    sp_tecnologia VARCHAR
  }
  cmts_santarosa_20220209 {
    idclientecrm INT
    cmts VARCHAR
    telefono VARCHAR
  }
  contactabilidad_20220222 {
    Nro_Documento VARCHAR
    Telefono VARCHAR
    FECHAINICIORELACION VARCHAR
    Operador VARCHAR
    PrioFuente VARCHAR
  }
  cortados_movil_20220630 {
    FINANCIAL_ACCOUNT_KEY VARCHAR
    FECHA VARCHAR
    CUSTOMER_KEY VARCHAR
    TELEFONO VARCHAR
    SUBSCRIBER_KEY VARCHAR
  }
  cortes_atis_20220131 {
    TELEFONO VARCHAR
  }
  cortes_fija_ro2_no_naked_20220311 {
    CLIENTE VARCHAR
    CUENTA VARCHAR
    PC VARCHAR
    INSCRIPCION VARCHAR
    TELEFONO VARCHAR
    ORDEN VARCHAR
  }
  cr_lite_con_consumo_20220210 {
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
  }
  cr_lite_sin_consumo_20220208 {
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
  }
  cruce_base_seg {
    TELEFONO VARCHAR
    NUMERODOCUMENTOUNIFICADO VARCHAR
    TIPODOCUMENTOUNIFICADO VARCHAR
    TIPO VARCHAR
  }
  cruzar_intent {
    INTENT VARCHAR
  }
  cuartil_cross_202309 {
    PROVEEDOR VARCHAR
    DOCUMENTO VARCHAR
    PLATAFORMA VARCHAR
    CUARTIL VARCHAR
  }
  cuartil_fija_202309 {
    DNI VARCHAR
    APELLIDOS INT
    PLATAFORMA VARCHAR
    CENTRO VARCHAR
    CUARTIL VARCHAR
  }
  cuartil_movil_202309 {
    DNI VARCHAR
    APELLIDOS INT
    PLATAFORMA VARCHAR
    CENTRO VARCHAR
    CUARTIL VARCHAR
  }
  cuartiles_agentes_20230421 {
    NEGOCIO VARCHAR
    DNI VARCHAR
    APELLIDOS INT
    PLATAFORMA VARCHAR
    CENTRO VARCHAR
    CUARTIL VARCHAR
  }
  cuartiles_agentes_20230424 {
    NEGOCIO VARCHAR
    DNI VARCHAR
    APELLIDOS INT
    PLATAFORMA VARCHAR
    CENTRO VARCHAR
    CUARTIL VARCHAR
  }
  cuartiles_retenciones_movil_202307 {
    DNI VARCHAR
    SOCIO VARCHAR
    CUARTIL VARCHAR
  }
  enc_apoyo {
    CDR_CALL_ID INT
    CDR_NAC_TYPE VARCHAR
  }
  error_massimple_20220126 {
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
  }
  error_massimple_20220127 {
    mes VARCHAR
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
  }
  lista_vip_20220301 {
    NIVEL_1 VARCHAR
    NIVEL_2 VARCHAR
    NRO VARCHAR
    Rubro VARCHAR
    Apellido INT
    Nombre VARCHAR
  }
  lista_vip_telefonos_202202 {
    DNI VARCHAR
    PRIORIDAD INT
    HOJA VARCHAR
    SERVICIO VARCHAR
    TDOCUMENTO VARCHAR
    NDOCUMENTO VARCHAR
  }
  lite_sin_servicio_20220221 {
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
  }
  mplay_apagado_20230321 {
    TIPOUSUARIO VARCHAR
    Suscripcion VARCHAR
    MIBID INT
    USERUNIQUEID INT
    USEREMAIL VARCHAR
    SUBSCRIPTIONS VARCHAR
  }
  mplay_apagado_20230321_v2 {
    TIPOUSUARIO VARCHAR
    Suscripcion VARCHAR
    MIBID INT
    USERUNIQUEID INT
    USEREMAIL VARCHAR
    SUBSCRIPTIONS VARCHAR
  }
  nodo_planta_fija {
    NODO VARCHAR
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    flag_nodo VARCHAR
  }
  nueva_base_cross_202201 {
    telefono VARCHAR
    documento VARCHAR
    base VARCHAR
    flag VARCHAR
  }
  paginasmarillas2_20220413 {
    TELEFONO VARCHAR
  }
  phoenix_3006 {
    TELEFONO VARCHAR
  }
  piloto_2_20220221 {
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
  }
  piloto_2_dimensionamiento_mplay {
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    ARCHIVO VARCHAR
  }
  piloto_PortalCautivo_vcto0909_2809 {
    TELEFONO VARCHAR
  }
  piloto_PortalCautivo_vcto0909_3009 {
    TELEFONO VARCHAR
  }
  piloto_adsl_retenciones_202107 {
    TipoDocumentoUnificado VARCHAR
    NumeroDocumentoUnificado VARCHAR
    Telefono VARCHAR
  }
  piloto_pago_automatico_20231026 {
    FINANCIAL_ACCOUNT VARCHAR
    TIPO_DOC_ID INT
    DOCUMENTO VARCHAR
  }
  planta_hfc_voip_23062022_PROC {
    IDCLIENTE INT
    IDEMPRESA INT
    ESTADOCLIENTE VARCHAR
    CM_IDPRODUCTO INT
    CM_MACADDRESS VARCHAR
    CM_IP VARCHAR
  }
  planta_migrado_20230623 {
    Access_ID INT
    Access_ID_ INT
    NOMBRE_1 VARCHAR
    NOMBRE_2 VARCHAR
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
  }
  reclamos_averias_ult_6_meses {
    rec_reclamo_codigo VARCHAR
    rec_fecha_reclamo VARCHAR
    rec_telefono_titular VARCHAR
    cli_reclamante VARCHAR
    cli_doc_identidad_reclamante INT
    calc_grupo_informe VARCHAR
  }
  relacion_incidencias_motivos_202208 {
    Aplicación VARCHAR
    Tipificación VARCHAR
    SUB_MOTIVO VARCHAR
    MOTIVO VARCHAR
    CANAL VARCHAR
    FLAG_VALIDACION_FLUJO_IMPACTO INT
  }
  remocion_agentes_20230913 {
    CODIGO VARCHAR
    Agente VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
    Fecha_Inicio VARCHAR
    Fecha_Fin VARCHAR
  }
  remocion_agentes_20230914 {
    CODIGO VARCHAR
    Agente VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
    Fecha_Inicio VARCHAR
    Fecha_Fin VARCHAR
  }
  remocion_agentes_20230918 {
    codigo VARCHAR
    Agente VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
    Fecha_Inicio VARCHAR
    Fecha_Fin VARCHAR
  }
  remocion_agentes_20230920 {
    Codigo VARCHAR
    Agente VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
    Fecha_Inicio VARCHAR
    Fecha_Fin VARCHAR
  }
  remocion_agentes_20230921 {
    Codigo VARCHAR
    Agente VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
    Fecha_Inicio VARCHAR
    Fecha_Fin VARCHAR
  }
  remocion_agentes_20231005 {
    CODIGO VARCHAR
    Agente VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
    Fecha_Inicio VARCHAR
    Fecha_Fin VARCHAR
  }
  remocion_agentes_20231006 {
    Código VARCHAR
    Agente VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
    Fecha_Inicio VARCHAR
    Fecha_Fin VARCHAR
  }
  remocion_agentes_20231009 {
    Codigo VARCHAR
    Agente VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
    Fecha_Inicio VARCHAR
    Fecha_Fin VARCHAR
  }
  remocion_agentes_20231025 {
    Codigo VARCHAR
    Agente VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
    Fecha_Inicio VARCHAR
    Fecha_Fin VARCHAR
  }
  renta_fija_202012 {
    TELEFONO VARCHAR
    TD_RENTA VARCHAR
    DOCUMENTO VARCHAR
    SEGMENTO VARCHAR
  }
  reversiones_20K_appMM_111022 {
    FA VARCHAR
    RECIBO VARCHAR
    TIPO VARCHAR
    MONTO VARCHAR
    TELEFONO_MOVIL VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  reversiones_20K_appMM_111022_2 {
    FA VARCHAR
    RECIBO VARCHAR
    TIPO VARCHAR
    MONTO VARCHAR
    TELEFONO_MOVIL VARCHAR
    TELEFONO_FIJO VARCHAR
  }
  revisar_downsell_20230926 {
    COD_TRANSACCION VARCHAR
    GESTION VARCHAR
    SOLICITUD_2 VARCHAR
    FECHA_REGISTRO VARCHAR
    HORA_REGISTRO VARCHAR
    TELEFONO_GESTION VARCHAR
  }
  segmentacion_ingresos_b2c_202507 {
    periodo_planta VARCHAR
    documento VARCHAR
    cluster_planta_actual VARCHAR
    UBIGEO VARCHAR
    INGRESOS_FIJA_TOTALES VARCHAR
    INGRESOS_MOVIL_TOTALES VARCHAR
  }
  sin_servicio_20230324 {
    TIPOUSUARIO VARCHAR
    Suscripcion VARCHAR
    MIBID INT
    USERUNIQUEID INT
    USEREMAIL VARCHAR
    SUBSCRIPTIONS VARCHAR
  }
  soloNum104 {
    TELEFONO VARCHAR
  }
  solo_fija_mt {
    TELEFONO VARCHAR
    TELEFONO_POSTPAGO1 VARCHAR
    PAQUETEMT VARCHAR
    CLUSTER_ VARCHAR
    TECNOLOGIA_BA VARCHAR
  }
  solo_movil_mt {
    TELEFONO_POSTPAGO1 VARCHAR
    CLUSTER_ VARCHAR
    DESCPLANDESTINOMOVIL1 VARCHAR
  }
  sysdiagrams {
    name VARCHAR
    principal_id INT
    diagram_id INT
    version VARCHAR
    definition VARCHAR
  }
  t1 {
    TELEFONO VARCHAR
    Grupo VARCHAR
    TIPO_GESTION VARCHAR
    SEGMENTO VARCHAR
    ESTADO VARCHAR
    FECHA_INICIO VARCHAR
  }
  t_archivo_2_caso_fraude {
    TELEFONO VARCHAR
  }
  t_base_incidencia_20211012 {
    TELEFONO VARCHAR
  }
  t_cuadrantes_fija_202112 {
    PERIODO VARCHAR
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENTO VARCHAR
  }
  t_cuadrantes_movil_202112 {
    Periodo VARCHAR
    TELEFONO VARCHAR
    TIPO_DOCUMENTO VARCHAR
    DOCUMENTO VARCHAR
    CLUSTER_CONVERGENTE VARCHAR
    SEGMENTO VARCHAR
  }
  t_descripcion_adaptativo {
    ETIQUETA VARCHAR
    NEGOCIO VARCHAR
    NOMBRE VARCHAR
    ACCION VARCHAR
    TIPO_CLIENTE VARCHAR
    NIVEL_2 VARCHAR
  }
  t_excel_erika_accesos_RO2_389k_V2 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    SEMANA VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    TIPO_ACCION_LLAMADA_N1 VARCHAR
  }
  t_excel_erika_ccee_RO1_fija_388k {
    PERIODO VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    PLATAFORMA VARCHAR
    INTERACTION_ORDER VARCHAR
    MOTIVO VARCHAR
  }
  t_excel_erika_ccee_ip_2022 {
    PERIODO VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    PLATAFORMA VARCHAR
    INTERACTION_ORDER VARCHAR
    SegmentoGrupoClienteDesc VARCHAR
  }
  t_excel_erika_ccee_ip_fija_2022 {
    PERIODO VARCHAR
    FECHA VARCHAR
    DIA VARCHAR
    PLATAFORMA VARCHAR
    INTERACTION_ORDER VARCHAR
    CICLO VARCHAR
  }
  t_excel_erika_voz_RO1_388k {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    DIA VARCHAR
    PLATAFORMA VARCHAR
    TRANSFERENCIA_ORDEN VARCHAR
    FLAG_GESTION_POSTVENTA VARCHAR
  }
  t_excel_erika_voz_RO1_388k_V2 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    NumSemana VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    PLATAFORMA VARCHAR
  }
  t_excel_erika_voz_accesos_RO1_388k {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    DIA VARCHAR
    TIPO_ACCION_LLAMADA_N1 VARCHAR
    TIPO_ACCION_LLAMADA_N2 VARCHAR
    TIPO_ACCION_LLAMADA_N3 VARCHAR
  }
  t_excel_erika_voz_entrantes_RO2_389k_V2 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    NumSemana VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    PLATAFORMA VARCHAR
  }
  t_excel_erika_voz_ip_2022 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    DIA VARCHAR
    PLATAFORMA VARCHAR
    TRANSFERENCIA_ORDEN VARCHAR
    FLAG_GESTION_POSTVENTA VARCHAR
  }
  t_excel_erika_voz_ip_fija_2022 {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    DIA VARCHAR
    PLATAFORMA VARCHAR
    TRANSFERENCIA_ORDEN VARCHAR
    FLAG_GESTION_POSTVENTA VARCHAR
  }
  t_revisar_accesos_flag {
    PERIODO VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    FECHA_FIN_LLAMADA VARCHAR
    INGRESO_PROVEEDOR VARCHAR
    INGRESO_IVR_TIPO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  t_temp_cruce_20220222 {
    TELEFONO VARCHAR
  }
  tivr_cobranzas {
    Columna VARCHAR
    Columna VARCHAR
    Columna VARCHAR
    FECHA_CARGA VARCHAR
  }
  tivr_cobranzas_20191126 {
    Column VARCHAR
    Column VARCHAR
    Column VARCHAR
  }
  validar_CR_imei_2023 {
    TELEFONO VARCHAR
    FECHA VARCHAR
  }
  validar_campos_IH {
    ENVIO VARCHAR
    MX_PLATAFORMA_ORIGEN VARCHAR
    MX_FIRST_LOGIN_ORIGEN VARCHAR
    MX_FECHA_LLAM_ORIGEN VARCHAR
    MX_TMO_ORIGEN VARCHAR
    MX_CALL_CENTER_ORIGEN VARCHAR
  }
  validar_heavy_users {
    telefono VARCHAR
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
  }
  validar_trami {
    TELEFONO VARCHAR
    CRUCE_PLANTA VARCHAR
    DESPRI VARCHAR
    TRAMI VARCHAR
  }
