erDiagram
  AM_Reporte_Seguimiento_cross_ccee_resumen_ULT3MESES {
    PERIODO VARCHAR
    AÑO VARCHAR
    MES VARCHAR
    NOMBRE_MES VARCHAR
    DIA VARCHAR
    Q_POTENCIALES VARCHAR
  }
  BASE_AGENTE {
    cliente VARCHAR
    nombrecliente VARCHAR
  }
  CCEE_AGENT_30MIN_PLATAFORMA_ULT3MESES {
    PERIODO VARCHAR
    FECHA VARCHAR
    OPERATOR_ID INT
    ESTADO_OPERADOR VARCHAR
    INTERVALO VARCHAR
    HORA VARCHAR
  }
  CCEE_T_DIM_CATEGORIA_PLATAFORMA {
    CAT_PLATF_ID INT
    CATEGORIA_PLATAFORMA VARCHAR
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
  }
  CCEE_T_DIM_PLATAFORMA {
    PLATAF_ID INT
    PLATAF_DESCRIPCION VARCHAR
    PLATAF_ESTADO VARCHAR
    PLATAF_FACTURACION VARCHAR
    JREM_ID INT
    TIPO_PAGO VARCHAR
  }
  CCEE_T_DIM_PROVEEDOR {
    PROV_ID INT
    PROV_NOMBRE VARCHAR
    PROV_ESTADO VARCHAR
  }
  CCEE_T_DIM_TIEMPO_INTERVALO {
    TIEM_ID INT
    TIEM_ANIO VARCHAR
    TIEM_MES VARCHAR
    TIEM_DIA VARCHAR
    TIEM_HORA VARCHAR
    TIEM_MEDIA_HORA VARCHAR
  }
  CCEE_T_FACT_METRICAS_CCEE_INTERVALOS {
    CANAL_ID INT
    CATEG_ID INT
    FUEN_ID INT
    PLATAF_ID INT
    PROV_ID INT
    SERV_ID INT
  }
  CONSOLIDADO_METRICAS_AGENTE_CCEE_DIARIO_ULT3MESES {
    FECHA VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    CASOS_ATENDIDOS INT
  }
  CONSOLIDADO_METRICAS_AGENTE_CCEE_ULT3MESES {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    CASOS_ATENDIDOS INT
  }
  ENCUESTAS_MEDALLIA_CHECA_TU_CASO {
    CODIGO_DE_PROBLEMA VARCHAR
    USUARIO_FINAL_APELLIDOS_NOMBRES INT
    NUMERO_DE_DOCUMENTO_DE_IDENTIDAD_USUARIO_FINAL INT
    NUMERO_DE_DOCUMENTO_DE_IDENTIDAD_DEL_ABONADO_REPRESENTANTE INT
    NOMBRE_ABONADO_REPRESENTATE_LEGAL VARCHAR
    NUMERO_DE_SERVICIO VARCHAR
  }
  ENCUESTAS_MEDALLIA_ESPECIALIZADOS {
    POSI_CORRELATIVO VARCHAR
    POSV_DNI VARCHAR
    POSV_TELEFONO VARCHAR
    POSV_CORREO VARCHAR
    POSV_TELEFONO_CONTACTO VARCHAR
    POSV_EMB_NOMBRE VARCHAR
  }
  RESUMEN_INDIC_GENERALES_VOZ_INTERVALO_ULT3MESES {
    FECHA VARCHAR
    HORA VARCHAR
    MEDIA_HORA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  RESUMEN_METRICAS_WFM_MENSUAL_ULT3MESES {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    NDS VARCHAR
    UMBRAL VARCHAR
    SIMULTANIEDAD VARCHAR
  }
  RESUMEN_PRODUCTIVIDAD_PROVEEDOR_CCEE_ULT3MESES {
    PERIODO VARCHAR
    FECHA VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    ESTADO_PENDIENTE VARCHAR
    DESPEDIDA_SALUDO INT
  }
  RESUMEN_TRANSFERENCIAS_VOZ_ULT3MESES {
    PERIODO VARCHAR
    FECHA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  RETENCIONES_FIJA {
    ID_LLAMADA INT
    GESTION VARCHAR
    ORIGEN VARCHAR
    INTENCION VARCHAR
    PRODUCTO_CORTO VARCHAR
    PRODUCTO_LARGO VARCHAR
  }
  RETENCIONES_MOVIL {
    COD_TRANSACCION VARCHAR
    GESTION VARCHAR
    SOLICITUD VARCHAR
    SOLICITUD VARCHAR
    MOTIVO VARCHAR
    SUB VARCHAR
  }
  RETENCIONES_MT {
    ID INT
    DNI VARCHAR
    FECHA VARCHAR
    FECHA VARCHAR
    HORA VARCHAR
    TELF VARCHAR
  }
  TEMP_FACT_HORAS_SIN_DATOS {
    NEG_ID INT
    SEG_ID INT
    PROV_ID INT
    PROG_ID INT
    TIEM_ID INT
    FUEN_ID INT
  }
  T_DIM_ARBOL_IVR {
    Service_Type VARCHAR
    SERVICE_SUBTYPE VARCHAR
    CANAL_IVR VARCHAR
    NEGOCIO_IVR VARCHAR
    TIPO_ENRUTAMIENTO_IVR VARCHAR
    OPC_NIV_1 VARCHAR
  }
  T_DIM_ARBOL_IVR_Automatismos {
    Item VARCHAR
    Num_Locucion VARCHAR
    Producto VARCHAR
    Sistema_Fuente VARCHAR
    Descripcion VARCHAR
    Tipo_de_Etiqueta VARCHAR
  }
  T_DIM_ARBOL_IVR_Service_Type {
    SERVICE_SUBTYPE VARCHAR
    TIPO_FLUJO_IVR VARCHAR
    SUBTIPO_IVR VARCHAR
    NOTA VARCHAR
  }
  T_DIM_ARBOL_IVR_X_NIVELES {
    TIPO_IVR VARCHAR
    TIPO_NIVEL VARCHAR
    OPC_ARBOL_IVR VARCHAR
    DESC_ARBOL_IVR VARCHAR
    TIPO_ENRUTAMIENTO_IVR VARCHAR
    CANT VARCHAR
  }
  T_DIM_ARBOL_IVR_nuevo {
    Service_Type VARCHAR
    SERVICE_SUBTYPE VARCHAR
    CANAL_IVR VARCHAR
    NEGOCIO_IVR VARCHAR
    TIPO_ENRUTAMIENTO_IVR VARCHAR
    OPC_NIV_1 VARCHAR
  }
  T_DIM_ARBOL_IVR_temp {
    Service VARCHAR
    SERVICE VARCHAR
    CANAL VARCHAR
    NEGOCIO VARCHAR
    OPC_NIV_1 VARCHAR
    OPC_NIV_2 VARCHAR
  }
  T_DIM_BASE_MTP_TEMPORAL {
    MES_ANIO VARCHAR
    SEGMENTO VARCHAR
    DOCUMENTO VARCHAR
    TELEFONO VARCHAR
    CLUSTER_COMERCIAL VARCHAR
    TIPO_MOVIL VARCHAR
  }
  T_DIM_BASE_MTP_TEMPORAL_LLAM {
    FECHA VARCHAR
    TELEFONO VARCHAR
    TELEFONO2 VARCHAR
    PLATAFORMA VARCHAR
    ORIGEN VARCHAR
    CANTIDAD_LLAMADAS INT
  }
  T_DIM_COLA {
    COLA_ID INT
    COLA_COD VARCHAR
    CDN_CUBO VARCHAR
    PROG_ID INT
    SKILL VARCHAR
    SIT_GEN_ID INT
  }
  T_DIM_COLA_BACKUP_202206 {
    COLA_ID INT
    COLA_COD VARCHAR
    CDN_CUBO VARCHAR
    PROG_ID INT
    SKILL VARCHAR
    SIT_GEN_ID INT
  }
  T_DIM_COLA_ERROR_20230714 {
    COLA_ID INT
    COLA_COD VARCHAR
    CDN_CUBO VARCHAR
    PROG_ID INT
    SKILL VARCHAR
    SIT_GEN_ID INT
  }
  T_DIM_COLA_ORIGEN {
    COLAOR_ID INT
    COLAOR_DESCRIPCION VARCHAR
  }
  T_DIM_COLA_X_TECNOLOGIA {
    routing_point VARCHAR
    plataforma VARCHAR
    producto VARCHAR
    negocio VARCHAR
    segmento VARCHAR
    programa VARCHAR
  }
  T_DIM_FUENTE {
    FUEN_ID INT
    FUEN_DESCRIPCION VARCHAR
  }
  T_DIM_JERARQUIA_EMPRESA {
    JREM_ID INT
    JREM_DIRECCION_NOMBRE VARCHAR
    JREM_GERENCIA_NOMBRE VARCHAR
  }
  T_DIM_KPIS_REGLAS {
    PLATAFORMA VARCHAR
    KPI VARCHAR
    NEGOCIO VARCHAR
    OBSERVACION VARCHAR
    REPORTE VARCHAR
    AGRUPACION_NEGOCIO VARCHAR
  }
  T_DIM_MODELO_PAGO {
    MPAGO_ID INT
    MPAGO_DESCRIPCION VARCHAR
  }
  T_DIM_NEGOCIO {
    NEG_ID INT
    NEG_NOMBRE VARCHAR
    NEG_ESTADO VARCHAR
  }
  T_DIM_ORDEN_DIA {
    ORDEN VARCHAR
    DIA VARCHAR
  }
  T_DIM_PLATAFORMA {
    PLATAF_ID INT
    PLATAF_DESCRIPCION VARCHAR
    PLATAF_ESTADO VARCHAR
    TIPO_INTERVALO VARCHAR
    PLATAF_TIPO_ATENCION VARCHAR
    MPAGO_ID INT
  }
  T_DIM_PLATAFORMA_UMBRAL {
    PLATUMB_ID INT
    PLATAF_ID INT
    PLATUMB_NOMBRE_PLATAFORMA VARCHAR
    PLATUMB_UMBRAL_CONTRATO VARCHAR
    PLATUMB_NDS_OBJETIVO_CONTRATO VARCHAR
    PLATUMB_TMO_OBJETIVO_CONTRATO VARCHAR
  }
  T_DIM_PLATAFORMA_UMBRAL_20240112 {
    PLATUMB_ID INT
    PLATAF_ID INT
    PLATUMB_NOMBRE_PLATAFORMA VARCHAR
    PLATUMB_UMBRAL_CONTRATO VARCHAR
    PLATUMB_NDS_OBJETIVO_CONTRATO VARCHAR
    PLATUMB_TMO_OBJETIVO_CONTRATO VARCHAR
  }
  T_DIM_PLATAFORMA_UMBRAL_BACKUP_20250810 {
    PLATUMB_ID INT
    PLATAF_ID INT
    PLATUMB_NOMBRE_PLATAFORMA VARCHAR
    PLATUMB_UMBRAL_CONTRATO VARCHAR
    PLATUMB_NDS_OBJETIVO_CONTRATO VARCHAR
    PLATUMB_TMO_OBJETIVO_CONTRATO VARCHAR
  }
  T_DIM_PLATAFORMA_UMBRAL_BACKUP_20260217 {
    PLATUMB_ID INT
    PLATAF_ID INT
    PLATUMB_NOMBRE_PLATAFORMA VARCHAR
    PLATUMB_UMBRAL_CONTRATO VARCHAR
    PLATUMB_NDS_OBJETIVO_CONTRATO VARCHAR
    PLATUMB_TMO_OBJETIVO_CONTRATO VARCHAR
  }
  T_DIM_PLATAFORMA_UMBRAL_temp_nuevos_cambios {
    PLATUMB_ID INT
    PLATAF_ID INT
    PLATUMB_NOMBRE_PLATAFORMA VARCHAR
    PLATUMB_UMBRAL_CONTRATO VARCHAR
    PLATUMB_NDS_OBJETIVO_CONTRATO VARCHAR
    PLATUMB_TMO_OBJETIVO_CONTRATO VARCHAR
  }
  T_DIM_PROGRAMA {
    PROG_ID INT
    PROG_NOMBRE VARCHAR
    PROG_ESTADO VARCHAR
    SEG_ID INT
    SEG_NOMBRE VARCHAR
    TIGEST_ID INT
  }
  T_DIM_PROVEEDOR {
    PROV_ID INT
    PROV_NOMBRE VARCHAR
    PROV_ESTADO VARCHAR
  }
  T_DIM_PROVEEDOR_LOCAL {
    PROVLOC_ID INT
    PROVLOC_DESCRIPCION VARCHAR
    PROV_ID INT
    PROV_NOMBRE VARCHAR
  }
  T_DIM_SEGMENTO {
    SEG_ID INT
    SEG_NOMBRE VARCHAR
    SEG_ESTADO VARCHAR
  }
  T_DIM_SISTEMA_COMERCIAL {
    SISTCOM_ID INT
    SISTCOM_DESCRIPCION VARCHAR
  }
  T_DIM_SITE_GENESYS {
    SITGEN_ID INT
    SITGEN_DESCRIPCION VARCHAR
  }
  T_DIM_TARIFA_HP {
    THP_ID INT
    PROV_ID INT
    THP_PROVEEDOR_PAGO_1 VARCHAR
    THP_PROVEEDOR_PAGO_2 VARCHAR
    THP_PROVEEDOR_PAGO_3 VARCHAR
    THP_FECHA_INICIO VARCHAR
  }
  T_DIM_TIEMPO_DIA {
    TIEM_ID INT
    TIEM_ANIO VARCHAR
    TIEM_MES VARCHAR
    TIEM_DIA VARCHAR
    TIEM_FECHA VARCHAR
    TIEM_FECHA_SIS VARCHAR
  }
  T_DIM_TIEMPO_DIA_PRUEBA {
    TIEM_ID INT
    TIEM_ANIO VARCHAR
    TIEM_MES VARCHAR
    TIEM_DIA VARCHAR
    TIEM_FECHA VARCHAR
    TIEM_FECHA_SIS VARCHAR
  }
  T_DIM_TIEMPO_INTERVALO {
    TIEM_ID INT
    TIEM_ANIO VARCHAR
    TIEM_MES VARCHAR
    TIEM_DIA VARCHAR
    TIEM_HORA VARCHAR
    TIEM_MEDIA_HORA VARCHAR
  }
  T_DIM_TIEMPO_INTERVALO_prueba {
    TIEM_ID INT
    TIEM_ANIO VARCHAR
    TIEM_MES VARCHAR
    TIEM_DIA VARCHAR
    TIEM_HORA VARCHAR
    TIEM_MEDIA_HORA VARCHAR
  }
  T_DIM_TIPO_DISTRIBUCION_CALL {
    TDISCALL_ID INT
    TDISCALL_DESCRIPCION VARCHAR
    TDISCALL_ESTADO VARCHAR
    TDISCALL_FECHA_SISTEMA VARCHAR
  }
  T_DIM_TIPO_GESTION {
    TIGEST_ID INT
    TIGEST_DESCRIPCION VARCHAR
  }
  T_DIM_TIPO_INTERACCION {
    TINTER_ID INT
    TINTER_DESCRIPCION VARCHAR
    TINTER_ESTADO VARCHAR
  }
  T_DIM_TIPO_INTERVALO {
    TINT_ID INT
    TINT_DESCRIPCION VARCHAR
  }
  T_FACT_ATENDIDAS_INTERVALO {
    NEG_ID INT
    SEG_ID INT
    PROV_ID INT
    PROG_ID INT
    TIEM_ID INT
    FUEN_ID INT
  }
  T_FACT_BASE_INCIDENCIAS_RESUMEN {
    NUMERO VARCHAR
    BASE VARCHAR
    CANTIDAD_REG_UNICOS INT
  }
  T_FACT_BASE_INCIDENCIAS_RESUMEN_V2 {
    NUMERO VARCHAR
    BASE VARCHAR
    CANTIDAD_REG_UNICOS INT
  }
  T_FACT_CARGA_AVAYA_ATENTO {
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    AÑO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
  }
  T_FACT_DISTRIBUCION_COLA {
    COLA_ID INT
    LOC_ID INT
    PORC_DISTRIB VARCHAR
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
  }
  T_FACT_METRICAS_CC_DIA {
    NEG_ID INT
    SEG_ID INT
    PROV_ID INT
    PROG_ID INT
    TIEM_ID INT
    FUEN_ID INT
  }
  T_FACT_METRICAS_CC_INTERVALO {
    NEG_ID INT
    SEG_ID INT
    PROV_ID INT
    PROG_ID INT
    TIEM_ID INT
    FUEN_ID INT
  }
  T_FACT_RRSS_ESCENARIOS_WSPP {
    FECHA VARCHAR
    ESCENARIO VARCHAR
    CLIENTES VARCHAR
    LLAMADAS VARCHAR
  }
  T_FACT_TRAFICO_INTERVALO {
    NEG_ID INT
    SEG_ID INT
    PROV_ID INT
    PROG_ID INT
    TIEM_ID INT
    FUEN_ID INT
  }
  T_IMPACTOS_EXTERNOS_CC_PRONOSTICOS_2 {
    FE VARCHAR
    TIPO VARCHAR
    SERVICIO VARCHAR
    ENTRANTES VARCHAR
    TMO VARCHAR
  }
  T_INPUT_TOPE_NPS_1_2_ULT3MESES {
    INPS1_2_MES VARCHAR
    INPS1_2_PROV_ID INT
    INPS1_2_PLATAF_ID INT
    INPS1_2_TOPE VARCHAR
    INPS1_2_USUARIO VARCHAR
    INPS1_2_FECHA_SISTEMA VARCHAR
  }
  T_KIPU_LISTADO_ETIQUETAS_1 {
    NOMBRE_ETIQUETA VARCHAR
  }
  T_KIPU_LISTADO_ETIQUETAS_2 {
    NOMBRE_ETIQUETA VARCHAR
  }
  T_KIPU_LISTADO_ETIQUETAS_3 {
    NOMBRE_ETIQUETA VARCHAR
  }
  T_KIPU_LISTADO_ETIQUETAS_4 {
    NOMBRE_ETIQUETA VARCHAR
  }
  T_KIPU_LISTADO_ID_PROVEEDORES {
    PROV_ID INT
  }
  T_KIPU_LISTADO_NOMBRE_PROVEEDORES {
    NOMBRE_PROVEEDOR VARCHAR
  }
  T_KPIS_REGLAS {
    PLATAFORMA VARCHAR
    KPI VARCHAR
    NEGOCIO VARCHAR
    OBSERVACION VARCHAR
    REPORTE VARCHAR
  }
  T_KPIS_REGLAS_GRUPO_PLATAFORMA {
    PLATAFORMA VARCHAR
    KPI VARCHAR
    NEGOCIO VARCHAR
    OBSERVACION VARCHAR
    REPORTE VARCHAR
    AGRUPACION_NEGOCIO VARCHAR
  }
  T_LISTA_EQUIVALENCIAS_AVAYA_ATENTO {
    PLATAFORMA VARCHAR
    EQAVA_EQUIVALENCIA VARCHAR
  }
  T_LISTA_INTERVALOS {
    TIPO_INTERVALO VARCHAR
    INTER_VALOR VARCHAR
    INTER_AGRUPACION VARCHAR
  }
  T_RESUMEN_CTI_72HR_FACTURACION {
    RESCTI_NEGOCIO VARCHAR
    RESCTI_FECHA VARCHAR
    RESCTI_CAL VARCHAR
    RESCTI_CTI VARCHAR
    RESCTI_TOTAL_ATENDIDAS INT
    RESCTI_TOTAL_ATENDIDAS_PARA_REITERADAS INT
  }
  T_RESUMEN_CTI_MENSUAL_ULT3MESES {
    RESCTI_NEGOCIO VARCHAR
    RESCTI_FECHA VARCHAR
    RESCTI_CAL VARCHAR
    RESCTI_CTI VARCHAR
    RESCTI_TOTAL_ATENDIDAS INT
    RESCTI_TOTAL_ATENDIDAS_PARA_REITERADAS INT
  }
  T_RESUMEN_PLACES {
    FECHA VARCHAR
    PLACE VARCHAR
    Interaction VARCHAR
    PROGRAMA VARCHAR
    GRUPO_GESTION VARCHAR
    DNGEN_SERVICIO VARCHAR
  }
  T_TEMP_BASE_ALEATORIA {
    FECHA_LLAM VARCHAR
    PROGRAMA VARCHAR
    PLATAFORMA VARCHAR
    PERIODO VARCHAR
    CALL_CENTER VARCHAR
    TMO VARCHAR
  }
  T_TEMP_CARGA_AVAYA_ATENTO_PASO1 {
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    AÑO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
  }
  T_TEMP_CARGA_AVAYA_ATENTO_PASO2 {
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    AÑO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
  }
  T_TEMP_CARGA_AVAYA_ATENTO_PASO3 {
    TOTAL_ENTRANTES VARCHAR
    TOTAL_ATENDIDAS INT
    TOTAL_ABANDONADAS VARCHAR
    TOTAL_TIEMPO_HABLADO VARCHAR
    TOTAL_TIEMPO_ACW VARCHAR
    TOTAL_TIEMPO_HOLD VARCHAR
  }
  T_TMP_CATALOGO_TRAFICO_MES_CALIDAD {
    MES_ANIO VARCHAR
    CANTIDAD_ENCUESTAS INT
  }
  T_TMP_FACT_RESUMEN_CALIDAD {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    PROVEEDOR VARCHAR
    fecha VARCHAR
    ENCUESTAS_CRUDO VARCHAR
  }
  T_TMP_FACT_RESUMEN_CALIDAD_V2 {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    fecha VARCHAR
    ENCUESTAS_CRUDO VARCHAR
    ENCUESTAS_VALIDAS INT
  }
  T_TMP_FACT_TRAFICO_DIA {
    AGEN_ANIO VARCHAR
    AGEN_MES VARCHAR
    AGEN_DIA VARCHAR
    AGEN_FECHA VARCHAR
    NEG_NOMBRE VARCHAR
    AGEN_PROGRAMA VARCHAR
  }
  T_TMP_FACT_TRAFICO_DIA_I {
    AGEN_ANIO VARCHAR
    AGEN_MES VARCHAR
    AGEN_DIA VARCHAR
    AGEN_FECHA VARCHAR
    NEG_NOMBRE VARCHAR
    AGEN_PROGRAMA VARCHAR
  }
  T_TMP_FACT_TRAFICO_INTERVALO {
    NEG_ID INT
    SEG_ID INT
    PROV_ID INT
    PROG_ID INT
    TIEM_ID INT
    FUEN_ID INT
  }
  T_TMP_FACT_TRAFICO_MES {
    AGEN_ANIO VARCHAR
    AGEN_MES VARCHAR
    MES_ANIO VARCHAR
    NEG_NOMBRE VARCHAR
    AGEN_PROGRAMA VARCHAR
    AGEN_CALL_CRUCE_LISTA VARCHAR
  }
  T_TMP_FACT_TRAFICO_MES_I {
    AGEN_ANIO VARCHAR
    AGEN_MES VARCHAR
    MES_ANIO VARCHAR
    NEG_NOMBRE VARCHAR
    AGEN_PROGRAMA VARCHAR
    AGEN_CALL_CRUCE_LISTA VARCHAR
  }
  T_VOLCADO_CC_DIA {
    TIPO VARCHAR
    SERVICIO VARCHAR
    FECHA VARCHAR
    ENTRANTES VARCHAR
    ATENDIDAS INT
    TIEMPO VARCHAR
  }
  T_VOLCADO_CC_DIA_2 {
    TIPO VARCHAR
    SERVICIO VARCHAR
    FECHA VARCHAR
    ENTRANTES VARCHAR
    ATENDIDAS INT
    TIEMPO VARCHAR
  }
  T_VOLCADO_CC_DIA_3 {
    TIPO VARCHAR
    SERVICIO VARCHAR
    FECHA VARCHAR
    ENTRANTES VARCHAR
    ATENDIDAS INT
    TIEMPO VARCHAR
  }
  USUARIOS_MULTICANAL_ULT_ACT {
    ASESOR_DNI VARCHAR
    ASESOR_NOMBRE_APELLIDO INT
    USUARIO_SISTEMA_FENIX VARCHAR
    USUARIO_SISTEMA_CMS VARCHAR
    USUARIO_SISTEMA_ATIS VARCHAR
    USUARIO_SISTEMA_WEB_SOLUCIONES VARCHAR
  }
  USUARIOS_RECLAMOS_ult_act_ULT3MESES {
    ASESOR_DNI VARCHAR
    ASESOR_NOMBRE_APELLIDO INT
    USUARIO_SISTEMA_FENIX VARCHAR
    USUARIO_SISTEMA_CMS VARCHAR
    USUARIO_SISTEMA_ATIS VARCHAR
    USUARIO_SISTEMA_WEB_SOLUCIONES VARCHAR
  }
  VW_BITACORA_EVENTOS_FORMATO_ANTERIOR_ULT3MESES {
    EVENT_ID INT
    EVENTO VARCHAR
    FECHA_INICIO VARCHAR
    HORA_INICIO VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA_AFECTADA VARCHAR
  }
  sysdiagrams {
    name VARCHAR
    principal_id INT
    diagram_id INT
    version VARCHAR
    definition VARCHAR
  }
