erDiagram
  ACCESOS_TODAY_CRUCE {
    FECHA VARCHAR
    HORA VARCHAR
    TELEFONO_CONSOLIDADO INT
    MOTIVO VARCHAR
    SUB_MOTIVO VARCHAR
    TIPO_CRUCE VARCHAR
  }
  BASE_RESUMEN_ENVIOS {
    NombreArchivo VARCHAR
    CANTIDAD_BASE INT
    Tipo VARCHAR
    Tipo VARCHAR
    Bolsa VARCHAR
    Campaña VARCHAR
  }
  CCPULSE_AGENTES_HORA_CERRADA_CALCULADO {
    HORA VARCHAR
    PLATAFORMA VARCHAR
    DISPONIBLE_REAL VARCHAR
  }
  CCPULSE_HORA_CERRADA_CALCULADO {
    PLATAFORMA VARCHAR
    HORA_CERRADA VARCHAR
    TOTAL_ENTRANTES VARCHAR
    TOTAL_ATENDIDAS INT
    TOTAL_ABANDONADAS VARCHAR
    TOTAL_TMRA VARCHAR
  }
  CCPULSE_NDS_DIA_TOTAL_CALCULADO {
    NOMBRECARPETA VARCHAR
    PLATAFORMA VARCHAR
    TOTAL_ENTRANTES VARCHAR
    TOTAL_ATENDIDAS INT
    TOTAL_ABANDONADAS VARCHAR
    TOTAL_CLEARED VARCHAR
  }
  CCPULSE_NDS_HORA_TOTAL_CALCULADO {
    NOMBRECARPETA VARCHAR
    PLATAFORMA VARCHAR
    TOTAL_ENTRANTES VARCHAR
    TOTAL_ATENDIDAS INT
    TOTAL_ABANDONADAS VARCHAR
    TOTAL_CLEARED VARCHAR
  }
  CONECTADOS_GLOBAL {
    NombreCarpeta VARCHAR
    Grupo VARCHAR
    Logeados VARCHAR
    Wait VARCHAR
    Not_Ready VARCHAR
    Hold VARCHAR
  }
  CargaArchivos {
    NombreArchivo VARCHAR
    ValorCampo VARCHAR
  }
  Consolidado_Control_Envios {
    Codigo VARCHAR
    Tipo VARCHAR
    Solicitante VARCHAR
    Tipo VARCHAR
    Segmento VARCHAR
    Bolsa VARCHAR
  }
  Crono_ingresos_COLOMBIA {
    CROIN_Proveedor VARCHAR
    CROIN_NEGOCIO VARCHAR
    CROIN_Codigo_Grupo VARCHAR
    CROIN_PLATAFORMA VARCHAR
    CROIN_Proveedor_LOCAL VARCHAR
    CROIN_Origen_Recursos VARCHAR
  }
  ENTRANTES_TODAY_CRUCE {
    FECHA VARCHAR
    HORA VARCHAR
    TELEFONO_CONSOLIDADO INT
    PLATAFORMA VARCHAR
    SKILL VARCHAR
    CDR_RELEASE_SIDE INT
  }
  JCO_AVH2_PLATAFORMA {
    PERIODO VARCHAR
    DIA VARCHAR
    CANAL_MARCACION VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    VAR6 VARCHAR
  }
  JCO_INSERT_MESSAGE {
    Telefono VARCHAR
  }
  JSS_AGENTES_REQUERIDOS_X_MES {
    periodo VARCHAR
    proveedor VARCHAR
    plataforma VARCHAR
    Horas_Planificado_disponible VARCHAR
    Horas_Requeridas_Erlang INT
    Horas_Requeridas_Erlang_Entrante_Prev_TMO_Real INT
  }
  JSS_AGENTES_REQUERIDOS_X_SEMANA {
    periodo VARCHAR
    proveedor VARCHAR
    plataforma VARCHAR
    Semana VARCHAR
    Horas_Requeridas_Erlang INT
    Horas_Requeridas_Erlang_Entrante_Prev_TMO_Real INT
  }
  JSS_AGRUPACION_PLATAFORMAS {
    PLATAFORMA VARCHAR
    AGRUPACION VARCHAR
  }
  JSS_AGRUPACION_VISTA_DIFERENCIA_APERTURA {
    FECHA VARCHAR
    Q_LLAMADAS_PROYECTADO VARCHAR
    Q_LLAMADAS_REAL VARCHAR
    Q_LLAMADAS_PLANIFICACIÓN VARCHAR
    pais VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  JSS_APERTURA_HORARIOS_PLATAFORMA {
    CANAL VARCHAR
    PAIS VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    PROVEEDOR VARCHAR
    HORA_INICIO_JORNADA VARCHAR
  }
  JSS_BACKUP_PESO_X_INTERVALO_PLATAFORMA {
    NEGOCIO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    dia_semana VARCHAR
    HORA_MINUTO VARCHAR
    promedio_ponderado VARCHAR
  }
  JSS_BACKUP_TMO_HISTORICO {
    FECHA_CALCULO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    DIA_SEMANA VARCHAR
    HORA VARCHAR
    MINUTO VARCHAR
  }
  JSS_BASE_APERTURA_PLATAFORMAS_HISPAM {
    PERIODO_PROYECTADO VARCHAR
    PAIS VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    PESO VARCHAR
    CANAL VARCHAR
  }
  JSS_BASE_APERTURA_SOCIOS_HISPAM {
    PERIODO_PROYECTADO VARCHAR
    PAIS VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    SOCIO VARCHAR
    PESO VARCHAR
  }
  JSS_BASE_FACTORES_PROYECCION_HISPAM {
    FECHA VARCHAR
    PAIS VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    TIPO_FACTOR VARCHAR
    FACTOR VARCHAR
  }
  JSS_CALCULO_TMO_FINAL_PRONOSTICO {
    FECHA_CALCULO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    DIA_SEMANA VARCHAR
    HORA VARCHAR
    MINUTO VARCHAR
  }
  JSS_CALCULO_TMO_FINAL_PRONOSTICO_MEXICO {
    FECHA_CALCULO VARCHAR
    PLATAFORMA VARCHAR
    DIA_SEMANA VARCHAR
    HORA VARCHAR
    MINUTO VARCHAR
    TMO VARCHAR
  }
  JSS_CATALOGO_FECHAS_CRONOGRAMA_PLANIFICACION {
    Semana VARCHAR
    FECHA_INCIO_SEMANA VARCHAR
    FECHA_FIN_SEMANA VARCHAR
    NRO_SEMANA VARCHAR
  }
  JSS_CATALOGO_NEGOCIO_PLATAFORMA {
    PLATAFORMA VARCHAR
    NEGOCIO VARCHAR
  }
  JSS_CONSOLIDADO_CONTACTOS_ENTRANTES {
    CANAL VARCHAR
    PERIODO VARCHAR
    FECHA VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  JSS_CONSOLIDADO_STATUS_SEMANAL {
    periodo VARCHAR
    PROVEEDOR VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    negocio VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    plataforma VARCHAR
  }
  JSS_CORTE_HISPAM_DIFERENCIA_AGENTES {
    PERIODO VARCHAR
    ENTRANTES VARCHAR
    PLATAFORMA VARCHAR
    PROVEEDOR VARCHAR
    PAIS VARCHAR
    CANAL VARCHAR
  }
  JSS_CORTE_HISPAM_DIFERENCIA_AGENTES_MEXICO {
    PERIODO VARCHAR
    PLATAFORMA_AGRUPADO VARCHAR
    PROVEEDOR VARCHAR
    AGENTES_LOGUEADO_REAL VARCHAR
    AGENTES_DISPONIBLE_REAL VARCHAR
    AGENTES_REQ_DISPONIBLE VARCHAR
  }
  JSS_CORTE_HISPAM_GTR {
    FECHA VARCHAR
    ENTRANTES VARCHAR
    PLATAFORMA VARCHAR
    PROVEEDOR VARCHAR
    PAIS VARCHAR
    INTERVALO_30_MIN VARCHAR
  }
  JSS_CORTE_HISPAM_GTR_MEXICO {
    periodo VARCHAR
    año VARCHAR
    mes VARCHAR
    semana VARCHAR
    semana_desc VARCHAR
    dia VARCHAR
  }
  JSS_CRONOGRAMA_INGRESOS_X_SEMANA {
    CROIN_Fecha_OJT_Inicial_PROYECTADO VARCHAR
    CROIN_PROVEEDOR VARCHAR
    CROIN_Plataforma VARCHAR
    INGRESO_PROYECTADO VARCHAR
    INGRESO_REAL VARCHAR
    DIF_ VARCHAR
  }
  JSS_CRONOGRAMA_INGRESOS_X_SEMANA_backup {
    CROIN_Fecha_OJT_Inicial_PROYECTADO VARCHAR
    CROIN_PROVEEDOR VARCHAR
    CROIN_Plataforma VARCHAR
    INGRESO_PROYECTADO VARCHAR
    INGRESO_REAL VARCHAR
    DIF_ VARCHAR
  }
  JSS_CRONOGRAMA_INGRESO_CAMBIO_FECHA_OJT_PLANIFICADO {
    CROIN_Codigo_Grupo VARCHAR
    CROIN_Proveedor VARCHAR
    Fecha_OJT_Inicial_PROYECTADO_ORIGINAL VARCHAR
    Fecha_OJT_PLANIFICADO_ORIGINAL VARCHAR
    CROIN_PAIS VARCHAR
    Fecha_OJT_PLANIFICADO_MODIFICADA VARCHAR
  }
  JSS_DIAS_FALTANTES_TRAFICO {
    FECHA VARCHAR
    Y VARCHAR
    dia_ex VARCHAR
    week_number VARCHAR
    NUEVA_AGRUPACION VARCHAR
  }
  JSS_ENTRANTES_30_MIN_X_PLATAFORMA_MEXICO {
    CANAL VARCHAR
    Periodo VARCHAR
    fecha VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA_AGRUPADO VARCHAR
    CONTACTOS_ATENDIDOS INT
  }
  JSS_ENTRANTES_PROYECTADO_DIARIO {
    fecha VARCHAR
    llamadas VARCHAR
    FECHA_EJECUCION VARCHAR
    plataforma VARCHAR
    grupo_plataforma VARCHAR
    tipo_proyeccion VARCHAR
  }
  JSS_ENTRANTES_X_GRUPO_PLATAFORMA {
    canal VARCHAR
    periodo VARCHAR
    fecha VARCHAR
    proveedor VARCHAR
    grupo_plataforma VARCHAR
    CONTACTOS_ATENDIDOS INT
  }
  JSS_ENTRANTES_X_PLATAFORMA_MEXICO {
    canal VARCHAR
    periodo VARCHAR
    fecha VARCHAR
    proveedor VARCHAR
    grupo_plataforma VARCHAR
    CONTACTOS_ATENDIDOS INT
  }
  JSS_FACTORES_PLATAFORMA_PERIODO {
    CANAL VARCHAR
    PERIODO VARCHAR
    pais VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    FACTOR VARCHAR
  }
  JSS_FACTORES_REDUCTORES {
    AÑO VARCHAR
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    Aus_Lunes VARCHAR
    Aus_Martes VARCHAR
  }
  JSS_HORAS_ESTIMADAS_ERLANG_DIARIO {
    periodo VARCHAR
    FECHA VARCHAR
    proveedor VARCHAR
    plataforma VARCHAR
    ENTRANTES_PRONOSTICO VARCHAR
    ENTRANTES_REAL VARCHAR
  }
  JSS_HORAS_ESTIMADAS_ERLANG_INTERVALO {
    PERIODO VARCHAR
    FECHA VARCHAR
    HORA VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    ENTRANTES_PRONOSTICO VARCHAR
  }
  JSS_INTERVALOS_BASE_X_PLATAFORMA {
    CANAL VARCHAR
    PLATAFORMA VARCHAR
    PROVEEDOR VARCHAR
    hora_minuto VARCHAR
    PAIS VARCHAR
  }
  JSS_LIMITES_CUARTILES_TRAFICO_X_DIA_HISPAM {
    PLATAFORMA VARCHAR
    DIA_SEMANA VARCHAR
    CANAL VARCHAR
    LIMITE_INFERIOR VARCHAR
    LIMITE_SUPERIOR VARCHAR
    FECHA_EJECUCION VARCHAR
  }
  JSS_LIMITES_CUARTILES_TRAFICO_X_INTERVALO {
    PLATAFORMA VARCHAR
    dia_semana VARCHAR
    hora VARCHAR
    media_hora VARCHAR
    HORA_MINUTO VARCHAR
    limite_inferior VARCHAR
  }
  JSS_LISTA_FERIADOS {
    FECHA VARCHAR
    PAIS VARCHAR
  }
  JSS_LISTA_FERIADOS_V2 {
    fecha VARCHAR
    pais VARCHAR
    descripcion VARCHAR
    tipo_evento VARCHAR
  }
  JSS_LOG_REEMPLAZO_FERIADOS {
    id_log INT
    fecha_feriado VARCHAR
    proveedor VARCHAR
    plataforma VARCHAR
    fecha_usada_1 VARCHAR
    fecha_usada_2 VARCHAR
  }
  JSS_NDS_Y_ASA {
    NEGOCIO VARCHAR
    PLATAFORMAS VARCHAR
    NDS VARCHAR
    ASA VARCHAR
    SIMULTANIEDAD VARCHAR
  }
  JSS_NUEVA_AGRUPACION_PLATAFORMAS_PLANIFICACION {
    PLATAFORMA VARCHAR
    CANAL VARCHAR
    NUEVA_AGRUPACION VARCHAR
    ANTIGUA_AGRUPACION VARCHAR
  }
  JSS_PESO_X_INTERVALO_PLATAFORMA {
    CANAL VARCHAR
    NEGOCIO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    dia_semana VARCHAR
    HORA_MINUTO VARCHAR
  }
  JSS_PESO_X_INTERVALO_PLATAFORMA_MEXICO {
    CANAL VARCHAR
    NEGOCIO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    dia_semana VARCHAR
    HORA_MINUTO VARCHAR
  }
  JSS_PESO_X_INTERVALO_PLATAFORMA_SUAVIZADO {
    NEGOCIO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    dia_semana VARCHAR
    HORA_MINUTO VARCHAR
    promedio_ponderado VARCHAR
  }
  JSS_PESO_X_INTERVALO_PLATAFORMA_SUAVIZADO_MEXICO {
    NEGOCIO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    dia_semana VARCHAR
    HORA_MINUTO VARCHAR
    promedio_ponderado VARCHAR
  }
  JSS_PLATAFORMAS_PLAYAS_PESO_X_INTERVALO_PLATAFORMA_SUAVIZADO {
    NEGOCIO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    dia_semana VARCHAR
    HORA_MINUTO VARCHAR
    promedio_ponderado VARCHAR
  }
  JSS_PRONOSTICO_PLAYAS_2024_2025 {
    fecha VARCHAR
    PREVISION VARCHAR
    TMO VARCHAR
    PLATAFORMA VARCHAR
    SOCIO VARCHAR
  }
  JSS_PRONOSTICO_PLAYAS_2024_2025_BACKUP_20250303 {
    fecha VARCHAR
    PREVISION VARCHAR
    TMO VARCHAR
    PLATAFORMA VARCHAR
    SOCIO VARCHAR
  }
  JSS_PROYECCION_CON_FACTORES_APERTURA {
    FECHA VARCHAR
    Q_LLAMADAS_PROYECTADO VARCHAR
    Q_LLAMADAS_REAL VARCHAR
    Q_LLAMADAS_PLANIFICACIÓN VARCHAR
    PAIS VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  JSS_ROTACION_AUS_CRONOGRAMA {
    PERIODO VARCHAR
    Proveedor VARCHAR
    NEGOCIO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    AUS_FTE_PLANIF VARCHAR
  }
  JSS_RUTAS_MODELOS_PROYECCION_ENTRANTES {
    CANAL VARCHAR
    GRUPO_PLATAFORMAS VARCHAR
    PAIS VARCHAR
    RUTAS VARCHAR
    RMSE VARCHAR
    AVG_LLAMADAS VARCHAR
  }
  JSS_RUTAS_MODELOS_PROYECCION_X_PLATAFORMA {
    CANAL VARCHAR
    PLATAFORMA VARCHAR
    PAIS VARCHAR
    RUTAS VARCHAR
    RMSE VARCHAR
    AVG_LLAMADAS VARCHAR
  }
  JSS_RUTAS_MODELOS_PROYECCION_X_PLATAFORMA_BACKUP {
    CANAL VARCHAR
    PLATAFORMA VARCHAR
    PAIS VARCHAR
    RUTAS VARCHAR
    RMSE VARCHAR
    AVG_LLAMADAS VARCHAR
  }
  JSS_STATUS_SEMANAL_VISTA_DIARIA {
    periodo VARCHAR
    PROVEEDOR VARCHAR
    FECHA_INICIO_LLAMADA VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    plataforma VARCHAR
    NDS_NUMERADOR VARCHAR
  }
  JSS_STATUS_SEMANAL_VISTA_MENSUAL {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    NDS_NUMERADOR VARCHAR
    NDS_DENOMINADOR VARCHAR
  }
  JSS_STATUS_SEMANAL_VISTA_SEMANAL {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    Semana VARCHAR
    NDS_NUMERADOR VARCHAR
  }
  JSS_TABLA_BASE_PONDERADO_TMO {
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    Fecha_Ventana_30_min VARCHAR
    DIA_SEMANA VARCHAR
    TMO VARCHAR
    CANAL VARCHAR
  }
  JSS_TABLA_BASE_PONDERADO_TMO_MEXICO {
    PLATAFORMA VARCHAR
    Fecha_Ventana_30_min VARCHAR
    DIA_SEMANA VARCHAR
    TMO VARCHAR
    CANAL VARCHAR
    PROVEEDOR VARCHAR
  }
  JSS_TABLA_EXPORADO_MALLA {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  JSS_TABLA_VALIDACION_MALLAS {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  JSS_TEMP_AGOSTO_PESO_X_INTERVALO_PLATAFORMA_SUAVIZADO {
    NEGOCIO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    dia_semana VARCHAR
    HORA_MINUTO VARCHAR
    promedio_ponderado VARCHAR
  }
  JSS_TEMP_COMPLETAR_TMO_202412 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  JSS_TEMP_CRONOGRAMA {
    CROIN_Proveedor VARCHAR
    CROIN_NEGOCIO VARCHAR
    CROIN_Codigo_Grupo VARCHAR
    CROIN_PLATAFORMA VARCHAR
    CROIN_Proveedor_LOCAL VARCHAR
    CROIN_Origen_Recursos VARCHAR
  }
  JSS_TEMP_CRONOGRAMA_2 {
    Proveedor VARCHAR
    NEGOCIO VARCHAR
    Codigo_Grupo VARCHAR
    PLATAFORMA VARCHAR
    Proveedor_LOCAL VARCHAR
    Origen_Recursos VARCHAR
  }
  JSS_TEMP_DescargaMallas202411 {
    Negocio VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
    Fecha VARCHAR
    Hora VARCHAR
    Pronostico VARCHAR
  }
  JSS_TEMP_MALLA_202410_V3 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  JSS_TEMP_MALLA_202410_V3_CON_IP {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  JSS_TEMP_factor_dia {
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    FACTOR_DIA VARCHAR
  }
  JSS_TRAFICO_PARA_APERTURA_X_INTERVALO {
    CANAL VARCHAR
    NEGOCIO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    dia_semana VARCHAR
  }
  JSS_TRAFICO_PARA_APERTURA_X_INTERVALO_MEXICO {
    CANAL VARCHAR
    NEGOCIO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    dia_semana VARCHAR
  }
  JSS_UPDATE_CURVA_NORMALIZADA {
    FECHA_INICIO_LLAMADA VARCHAR
    y VARCHAR
    PLATAFORMA VARCHAR
    PAIS VARCHAR
  }
  KAJ_AGENTES_BLENDING {
    CANAL VARCHAR
    Fecha VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
    Agente VARCHAR
    Atendidas INT
  }
  KAJ_MALLAS_TDP_2025_VERSIONES {
    PREV_NEGOCIO VARCHAR
    PREV_PROVEEDOR VARCHAR
    PREV_PLATAFORMA VARCHAR
    LLAVE VARCHAR
    PREV_FECHA VARCHAR
    1 VARCHAR
  }
  LISTA_CORREOS_AUTOMATICO {
    ID INT
    CORREO VARCHAR
  }
  LogArchivosConvertidos {
    ID INT
    NombreArchivo VARCHAR
    FechaModificacion VARCHAR
    FechaCarga VARCHAR
  }
  MALLA_202510_V2_1 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  MALLA_202510_V2_3 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  MALLA_VALIDAR_202506 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  MALLA_VALIDAR_202506_V2 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  MALLA_VALIDAR_202506_V3 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  MALLA_VALIDAR_202507_V1 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  MALLA_VALIDAR_202507_V2 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  MALLA_VALIDAR_202507_V3 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  MALLA_VALIDAR_202507_V4 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  MALLA_VALIDAR_202507_V5 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  MALLA_VALIDAR_202507_V6 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  MALLA_VALIDAR_202507_V8 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  NDS_DIA_TOTAL {
    NombreCarpeta VARCHAR
    Grupo VARCHAR
    Porcentaje_ATC VARCHAR
    NDS_10seg VARCHAR
    NDS_20seg VARCHAR
    NDS_30seg VARCHAR
  }
  NDS_HORA_TOTAL {
    NombreCarpeta VARCHAR
    Grupo VARCHAR
    Porcentaje_ATC VARCHAR
    NDS_10seg VARCHAR
    NDS_20seg VARCHAR
    NDS_30seg VARCHAR
  }
  NO_BORRAR_AMELIA_CDRS_LV_today {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
    CDR_SESSION_ID INT
  }
  NO_BORRAR_AMELIA_CDRS_MI_today {
    CDR_SITE VARCHAR
    CDR_MEDIA_TYPE VARCHAR
    CDR_START_DATETIME DATETIME
    CDR_END_DATETIME DATETIME
    CDR_AMELIA_ID INT
    CDR_SESSION_ID INT
  }
  ProcesamientoLog {
    ID INT
    Ruta VARCHAR
    NombreArchivo VARCHAR
    FechaModificacion VARCHAR
    Num_Campos VARCHAR
    Valor VARCHAR
  }
  RESUMEN_EXCEL_VISTA_HORA {
    FECHA VARCHAR
    ENTRANTES VARCHAR
    PLATAFORMA VARCHAR
    HORA VARCHAR
    NDS_NUMERADOR VARCHAR
    NDS_DENOMINADOR VARCHAR
  }
  RESUMEN_INDIC_GENERALES_CCEE_INTERVALO {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    MEDIA_HORA VARCHAR
    PROVEEDOR VARCHAR
  }
  RESUMEN_INDIC_GENERALES_VOZ_INTERVALO {
    FECHA VARCHAR
    HORA VARCHAR
    MEDIA_HORA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  TEMP_VALIDAR {
    FECHA VARCHAR
    INTERVALO VARCHAR
    HORA VARCHAR
    TELEFONO_CONSOLIDADO INT
    TIPO_NAC VARCHAR
    CDR_LAST_USE_CASE VARCHAR
  }
  T_CRUCE_SKILL {
    SKILL VARCHAR
    PLATAFORMA VARCHAR
  }
  T_CRUCE_SKILL_AGENTES {
    SKILL VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    ID_AGENTES INT
  }
  T_TABLA_CORREO_CRONO_INGRESOS {
    FECHA VARCHAR
    CROIN_Proveedor VARCHAR
    CROIN_NEGOCIO VARCHAR
    CROIN_PLATAFORMA VARCHAR
    CROIN_Codigo_Grupo VARCHAR
    Q_Planificacion_Solicitado VARCHAR
  }
  T_TABLA_CORREO_CRONO_INGRESOS_CAMBIO_ESTADO {
    CROIN_CODIGO_GRUPO VARCHAR
    CROIN_Proveedor VARCHAR
    CROIN_PLATAFORMA VARCHAR
    FECHA_OJT_PROYECTADO VARCHAR
    USUARIO_ULTIMA_ACTUALIZACION VARCHAR
    FECHA_ULTIMA_ACTUALIZACION VARCHAR
  }
  VALIDAR_ACUMULADO__PLATAFORMA {
    PERIODO VARCHAR
    DIA VARCHAR
    CANAL_MARCACION VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    VARIABLE VARCHAR
  }
  VALIDAR_MALLA_202508_TEC {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  VALIDAR_MALLA_202508_TEC_V1 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  VALIDAR_PLATAFORMAS_ADHOC {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  VALIDAR_RETEN_FIJA_MOVIL {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  VALIDAR_RETEN_FIJA_MOVIL_V1 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
  VALIDAR_RETEN_FIJA_MOVIL_V2 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
  }
