erDiagram
  AMP_CONSOLIDADO_USUARIOS {
    menu_2 VARCHAR
    USUARIO VARCHAR
    NOMBRE VARCHAR
    EMAIL VARCHAR
    SOCIO VARCHAR
    FLAG_CUENTA VARCHAR
  }
  AMP_LOGS_MENU_KIPU_AHDOC {
    PERIODO VARCHAR
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    MENU_1 VARCHAR
    MENU_2 VARCHAR
  }
  AMP_RECLAMOS_SIN_DNI_AGENTE_REGISTRO {
    PERIODO VARCHAR
    CANT_AGENTES VARCHAR
    CANT_RECLAMOS VARCHAR
  }
  AMP_RECLAMOS_SIN_LLAMADA_ATENDIDA {
    TIPO_RECLAMO VARCHAR
    PERIODO VARCHAR
    DNI_AGENTE_REGISTRO VARCHAR
    TOTAL VARCHAR
  }
  AMP_SAR_SIN_DNI_AGENTE_REGISTRO {
    PERIODO VARCHAR
    CANT_AGENTES VARCHAR
    CANT_RECLAMOS VARCHAR
  }
  AMP_SAR_SIN_LLAMADA_ATENDIDA {
    TIPO_RECLAMO VARCHAR
    PERIODO VARCHAR
    DNI_ASESOR_REGISTRO VARCHAR
    TOTAL VARCHAR
  }
  AMP_TABLA_PARA_CLIENTES_UNICOS_DIA {
    FECHA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    CLIENTES_UNICOS VARCHAR
  }
  AMP_TABLA_PARA_CLIENTES_UNICOS_HORA {
    FECHA VARCHAR
    HORA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  AMP_TABLA_PARA_CLIENTES_UNICOS_MES {
    ANIO VARCHAR
    MES VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  AMP_TABLA_PARA_CLIENTES_UNICOS_SEMANA {
    ANIO VARCHAR
    SEMANA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  AMP_TC_SIN_DNI_AGENTE_REGISTRO {
    PERIODO VARCHAR
    CANT_AGENTES VARCHAR
    CANT_RECLAMOS VARCHAR
  }
  AMP_TC_SIN_LLAMADA_ATENDIDA {
    TIPO_RECLAMO VARCHAR
    PERIODO VARCHAR
    DNI_ASESOR_REGISTRO VARCHAR
    TOTAL VARCHAR
  }
  AMP_obejtivo_pesos_indicador_agente_CCEE {
    PERIODO VARCHAR
    PLATAFORMA VARCHAR
    INDICADOR VARCHAR
    OBJETIVO VARCHAR
    PESO VARCHAR
  }
  AM_CALENDARIO_SEMANA {
    FECHA VARCHAR
    DIA VARCHAR
    SEMANA VARCHAR
  }
  AM_CCEE_BASE_GENERAL_POTENCIALES_FALTANTES {
    PLANTA VARCHAR
    ANIO VARCHAR
    MES VARCHAR
    TRIMESTRE VARCHAR
    OFERTA VARCHAR
    CATEGORIA_OFERTA VARCHAR
  }
  AM_CONSOLIDADO_METRICAS_AGENTE_CCEE_CROSS {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    Q_ABORDAJE_ADSL VARCHAR
  }
  AM_CargaCrossCEE {
    Marca VARCHAR
    LINK VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    NRO VARCHAR
  }
  AM_INDICADORES_CROSS_CCEE_POR_ASESOR_MENSUAL_ABORDAJE_PREVENTA {
    periodo VARCHAR
    PROVEEDOR VARCHAR
    dni VARCHAR
    PLATAFORMA VARCHAR
    Q_POTENCIAL VARCHAR
    CU_POTENCIALES VARCHAR
  }
  AM_INDICADORES_CROSS_CCEE_POR_ASESOR_MENSUAL_ABORDAJE_PREVENTA_DIARIO {
    FECHA VARCHAR
    PROVEEDOR VARCHAR
    dni VARCHAR
    PLATAFORMA VARCHAR
    Q_POTENCIAL VARCHAR
    CU_POTENCIALES VARCHAR
  }
  AM_REPORTE_EFECTIVIDAD_Y_ABORDAJE_POR_CUARTIL_CCEE {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    DNI VARCHAR
    PLATAFORMA VARCHAR
    OFERTA_CONSOLIDADA INT
    Q_ABORDAJE VARCHAR
  }
  AM_REPORTE_EFECTIVIDAD_Y_ABORDAJE_POR_CUARTIL_CCEE_DIARIO {
    SEMANA VARCHAR
    FECHA VARCHAR
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    DNI VARCHAR
    PLATAFORMA VARCHAR
  }
  AM_REPORTE_PREVENTAS_CCEE_FORMULARIO {
    PERIODO VARCHAR
    AÑO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    NOMBRE_MES VARCHAR
    FECHA_LLAMADA VARCHAR
  }
  AM_temp_base_mayo_form_ccee_2905 {
    Marca VARCHAR
    LINK VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    NRO VARCHAR
  }
  AM_temp_base_mayo_form_ccee_2905_errores {
    Marca VARCHAR
    LINK VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    NRO VARCHAR
  }
  ANIS_VS_RELLAMADAS {
    PERIODO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    RANGO_LLAMADAS VARCHAR
    CLIENTES VARCHAR
    LLAMADAS VARCHAR
  }
  ANTIGUEDAD_AGENTES {
    HISTAG_ANIOMES VARCHAR
    HISTAG_NEGOCIO VARCHAR
    HISTAG_CALL VARCHAR
    HISTAG_PLATAFORMA VARCHAR
    HISTAG_CTI VARCHAR
    HISTAG_NOMBRES VARCHAR
  }
  AVERIAS_POR_ASESOR {
    PERIODO VARCHAR
    FECHA_REGISTRO VARCHAR
    DNI_AGENTE VARCHAR
    TOTAL_AVERIAS VARCHAR
    TOTAL_AVERIAS_INDIVIDUAL INT
    TOTAL_AVERIAS_CANCELADAS VARCHAR
  }
  AVERIAS_POR_ASESOR_HISTORICO {
    PERIODO VARCHAR
    FECHA_REGISTRO VARCHAR
    DNI_AGENTE VARCHAR
    TOTAL_AVERIAS VARCHAR
    TOTAL_AVERIAS_INDIVIDUAL INT
    TOTAL_AVERIAS_CANCELADAS VARCHAR
  }
  Agente_202402 {
    DNI VARCHAR
    NOMBRES VARCHAR
    SOCIO VARCHAR
  }
  Agentes_ccee {
    FECHA VARCHAR
    YYYY VARCHAR
    MM VARCHAR
    DIA_SEMANA VARCHAR
    TIPO_DIA VARCHAR
    SEGMENTO_GA VARCHAR
  }
  Am_TEMP_base_abril {
    Marca VARCHAR
    LINK VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    NRO VARCHAR
    TIPO VARCHAR
  }
  BASE_AJUSTE_FACTURAS_CALCULADO {
    NUMERO_RECLAMO VARCHAR
    CODIGO_RECLAMO VARCHAR
    CARGO VARCHAR
    CARGO_DESCRIPCION VARCHAR
    NUMERO_QUEJA VARCHAR
    CODIGO_QUEJA VARCHAR
  }
  BASE_AMDOCS_RECLAMOS_CALCULADO {
    NUMERO_RECLAMO VARCHAR
    CASO_KEY VARCHAR
    CASO_KEY_PADRE VARCHAR
    CASO_NUMERO VARCHAR
    NUMERO_QUEJA VARCHAR
    CODIGO_QUEJA VARCHAR
  }
  BASE_AMDOCS_RECLAMOS_CALCULADO_COUNT_LIQ_AYER {
    AÑO VARCHAR
    MES VARCHAR
    SEGMENTO VARCHAR
    INSTANCIA VARCHAR
    ESTADO VARCHAR
    TIPO VARCHAR
  }
  BASE_CMS_RECLAMOS_CALCULADO {
    CODIGO_REQ VARCHAR
    NUMERO_RECLAMO VARCHAR
    CODIGO_RECLAMO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CARTA VARCHAR
    NUMERO_CARTA VARCHAR
  }
  BASE_CMS_RECLAMOS_CALCULADO_2 {
    CODIGO_REQ VARCHAR
    NUMERO_RECLAMO VARCHAR
    CODIGO_RECLAMO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CARTA VARCHAR
    NUMERO_CARTA VARCHAR
  }
  BASE_FENIX_RECLAMOS_CALCULADO {
    NUMERO_RECLAMO VARCHAR
    CODIGO_RECLAMO VARCHAR
    CARGO VARCHAR
    CARGO_DESCRIPCION VARCHAR
    NUMERO_QUEJA VARCHAR
    CODIGO_QUEJA VARCHAR
  }
  BASE_FENIX_RECLAMOS_CALCULADO_COUNT_LIQ_AYER {
    AÑO VARCHAR
    MES VARCHAR
    SEGMENTO VARCHAR
    INSTANCIA VARCHAR
    ESTADO VARCHAR
    TIPO VARCHAR
  }
  BASE_MAS_SIMPLE_RECLAMOS_CALCULADO {
    NUMERO_RECLAMO VARCHAR
    CODIGO_RECLAMO VARCHAR
    CARGO VARCHAR
    CARGO_DESCRIPCION VARCHAR
    NUMERO_QUEJA VARCHAR
    CODIGO_QUEJA VARCHAR
  }
  BITACORA_ACTUALIZACIONES {
    MENU VARCHAR
    OPCION VARCHAR
    SUB_OPCION VARCHAR
    ACTUALIZACION_DATA VARCHAR
    ACTUALIZACION_PROCESO VARCHAR
    ORDEN VARCHAR
  }
  BITACORA_ACTUALIZACIONES_SEL {
    MENU VARCHAR
    OPCION VARCHAR
    SUB_OPCION VARCHAR
    ACTUALIZACION_DATA VARCHAR
    ACTUALIZACION_PROCESO VARCHAR
    ORDEN VARCHAR
  }
  BITACORA_EVENTOS {
    ID INT
    EVENTO VARCHAR
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA_AFECTADA VARCHAR
  }
  BITACORA_EVENTOS_BKP_27032024 {
    ID INT
    EVENTO VARCHAR
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA_AFECTADA VARCHAR
  }
  BITACORA_EVENTOS_PROVEEDORES {
    ID INT
    PROVEEDOR VARCHAR
  }
  BKP_RESUMEN_INDIC_GENERALES_VOZ_DIA_2024 {
    FECHA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    LLAMADAS_ENTRANTES VARCHAR
  }
  BKP_RESUMEN_INDIC_GENERALES_VOZ_HORA_2024 {
    FECHA VARCHAR
    HORA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  BKP_RESUMEN_INDIC_GENERALES_VOZ_INTERVALO_2024 {
    FECHA VARCHAR
    HORA VARCHAR
    MEDIA_HORA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  BKP_RESUMEN_INDIC_GENERALES_VOZ_MES_2024 {
    ANIO VARCHAR
    MES VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  BKP_RESUMEN_INDIC_GENERALES_VOZ_SEMANA_2024 {
    ANIO VARCHAR
    SEMANA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  CAPACIDAD_DE_ATENCION_HISTORICO {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    TIPO_GESTION VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    PRONOSTICO VARCHAR
  }
  CAPACIDAD_DE_ATENCION_ULT_ACT {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    TIPO_GESTION VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    PRONOSTICO VARCHAR
  }
  CARGA_FRAUDES_OBS {
    OBSERVACIONES VARCHAR
  }
  CATALOGO_OPCIONES_EVOLUTIVO_OSIPTEL {
    opcion VARCHAR
  }
  CATALOGO_REPORTE_EVOLUTIVO_OSIPTEL {
    formato VARCHAR
    tipo VARCHAR
  }
  CATALOGO_SEGMENTOS_EVOLUTIVO_OSIPTEL {
    segmento VARCHAR
  }
  CCEE_BASE_CUMPLIMIENTO_FIBRA_RESUMEN {
    ANIO VARCHAR
    MES VARCHAR
    REPORTE VARCHAR
    SUB_REPORTE VARCHAR
    TOTAL VARCHAR
    SOCIO VARCHAR
  }
  CCEE_BASE_GENERAL_AVANCE {
    ANIO VARCHAR
    MES VARCHAR
    TRIMESTRE VARCHAR
    SOCIO VARCHAR
    PLATAFORMA VARCHAR
    OFERTA VARCHAR
  }
  CCEE_BASE_GENERAL_AVANCE_RESUMEN {
    ANIO VARCHAR
    PERIODO VARCHAR
    REPORTE VARCHAR
    TOTAL VARCHAR
  }
  CCEE_BASE_GENERAL_CUARTILES {
    PERIODO VARCHAR
    MES VARCHAR
    ANIO VARCHAR
    TRIMESTRE VARCHAR
    SEMANA VARCHAR
    N_SEMANA_MES VARCHAR
  }
  CCEE_BASE_GENERAL_NO_CROSEADORES {
    PERIODO VARCHAR
    MES VARCHAR
    ANIO VARCHAR
    TRIMESTRE VARCHAR
    SEMANA VARCHAR
    SEMANA_DEL_MES VARCHAR
  }
  CCEE_BASE_GENERAL_POTENCIALES {
    PLANTA VARCHAR
    ANIO VARCHAR
    MES VARCHAR
    TRIMESTRE VARCHAR
    OFERTA VARCHAR
    CATEGORIA_OFERTA VARCHAR
  }
  CCEE_BASE_GENERAL_POTENCIALES_temp_otras_ofertas {
    PLANTA VARCHAR
    ANIO VARCHAR
    MES VARCHAR
    TRIMESTRE VARCHAR
    OFERTA VARCHAR
    CATEGORIA_OFERTA VARCHAR
  }
  CCEE_BASE_GESTION_OPERATIVA_FIBRA_GRAF_RESUMEN {
    ANIO VARCHAR
    MES VARCHAR
    REPORTE VARCHAR
    TOTAL VARCHAR
    SOCIO VARCHAR
    PLATAFORMA VARCHAR
  }
  CCEE_BASE_MOTIVOS_ABORDAJE_RESUMEN {
    ANIO VARCHAR
    MES VARCHAR
    ACEPTA_OFERTA VARCHAR
    MOTIVO_NO_ACEPTA VARCHAR
    MOTIVO_AGRUPADO VARCHAR
    GRUPO_1 VARCHAR
  }
  CCEE_BASE_MOTIVOS_ABORDAJE_RESUMEN_BACKUP {
    ANIO VARCHAR
    MES VARCHAR
    ACEPTA_OFERTA VARCHAR
    MOTIVO_NO_ACEPTA VARCHAR
    MOTIVO_AGRUPADO VARCHAR
    GRUPO_1 VARCHAR
  }
  CCEE_BASE_MOTIVOS_ABORDAJE_RESUMEN_COPY {
    ANIO VARCHAR
    MES VARCHAR
    ACEPTA_OFERTA VARCHAR
    MOTIVO_NO_ACEPTA VARCHAR
    MOTIVO_AGRUPADO VARCHAR
    GRUPO_1 VARCHAR
  }
  CCEE_BASE_PILOTO_PORTABILIDAD {
    PERIODO VARCHAR
    MES VARCHAR
    GRUPO_TOPICO VARCHAR
    TOPICO VARCHAR
    Q VARCHAR
  }
  CCEE_BASE_PILOTO_PORTABILIDAD_BCKP_KCS {
    PERIODO VARCHAR
    MES VARCHAR
    GRUPO_TOPICO VARCHAR
    TOPICO VARCHAR
    Q VARCHAR
  }
  CCEE_BASE_POTENCIAL_MAS_SIMPLE {
    fecha VARCHAR
    SOCIO VARCHAR
    GroupPlataforma VARCHAR
    Q_interaciones VARCHAR
    q_cliente VARCHAR
  }
  CCEE_BASE_RECONTACTOS_CROSS_RESUMEN {
    ANIO VARCHAR
    MES VARCHAR
    REPORTE VARCHAR
    TOTAL VARCHAR
    DENOMINADOR VARCHAR
    SOCIO VARCHAR
  }
  CCEE_BASE_RECONTACTOS_RESUMEN {
    ANIO VARCHAR
    MES VARCHAR
    REPORTE VARCHAR
    SUB_REPORTE VARCHAR
    TOTAL VARCHAR
    DENOMINADOR VARCHAR
  }
  CCEE_DETALLE_ERROR_DITO {
    ANIO VARCHAR
    MES VARCHAR
    MOTIVO_NO_ACEPTA VARCHAR
    Q VARCHAR
  }
  CONSOLIDADO_METRICAS_AGENTE_CCEE {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    CASOS_ATENDIDOS INT
  }
  CONSOLIDADO_METRICAS_AGENTE_CCEE_DIARIO {
    FECHA VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    CASOS_ATENDIDOS INT
  }
  CONSOLIDADO_METRICAS_AGENTE_CCEE_MASTERS {
    periodo VARCHAR
    proveedor VARCHAR
    plataforma VARCHAR
    DNI VARCHAR
    CASOS_ATENDIDOS INT
    tiempo_login VARCHAR
  }
  CONSOLIDADO_METRICAS_AGENTE_CCEE_NPS {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    CASOS_ATENDIDOS INT
  }
  CONSOLIDADO_METRICAS_AGENTE_VOZ {
    PERIODO VARCHAR
    CALL_CENTER VARCHAR
    PLATAFORMA VARCHAR
    AGENTE VARCHAR
    ATEND_CON_EXCLUSIONES VARCHAR
    ATEND_SIN_EXCLUSIONES VARCHAR
  }
  CONSOLIDADO_METRICAS_AGENTE_VOZ_DIARIO {
    PERIODO VARCHAR
    CALL_CENTER VARCHAR
    PLATAFORMA VARCHAR
    AGENTE VARCHAR
    ATEND_CON_EXCLUSIONES VARCHAR
    ATEND_SIN_EXCLUSIONES VARCHAR
  }
  CONSOLIDADO_METRICAS_AGENTE_VOZ_PLATINUM {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    SUPERVISOR VARCHAR
    AGENTE VARCHAR
  }
  CONSOLIDADO_METRICAS_AGENTE_VOZ_SEMANAL {
    ANIO VARCHAR
    PERIODO VARCHAR
    CALL_CENTER VARCHAR
    PLATAFORMA VARCHAR
    AGENTE VARCHAR
    ATEND_CON_EXCLUSIONES VARCHAR
  }
  CONSOLIDADO_METRICAS_CALIDAD_CCEE {
    FECHA VARCHAR
    SEMANA VARCHAR
    ANIO_MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    CANT_ENCUESTAS_IN VARCHAR
  }
  CONSOLIDADO_METRICAS_CALIDAD_CCEE_OUT {
    FECHA VARCHAR
    SEMANA VARCHAR
    ANIO_MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    TOTAL_ENCUESTAS VARCHAR
  }
  CONSOLIDADO_METRICAS_PROVEEDOR_VOZ {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    LLAMADAS_ENTRANTES VARCHAR
    LLAMADAS_ATENDIDAS INT
    PRONOSTICO_LLAMADAS_VMO VARCHAR
  }
  CONSOLIDADO_METRICAS_PROVEEDOR_VOZ_GRUPO {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    LLAMADAS_ENTRANTES VARCHAR
    LLAMADAS_ATENDIDAS INT
    PRONOSTICO_LLAMADAS_VMO VARCHAR
  }
  CONSOLIDADO_METRICAS_SUPERVISORES_VOZ_PLATINUM {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    SUPERVISOR VARCHAR
    ATENDIDAS INT
    TMO VARCHAR
  }
  CONSOLIDADO_METRICAS_SUPERVISOR_CCEE_MASTERS {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    SUPERVISOR VARCHAR
    CASOS_ATENDIDOS INT
    TIEMPO_LOGIN VARCHAR
  }
  CONSOLIDADO_TIPIFICACIONES_VISOR {
    Proveedor VARCHAR
    Dni_Asesor VARCHAR
    Nombre_Asesor VARCHAR
    Servicio VARCHAR
    Plataforma VARCHAR
    Ani_Llamante VARCHAR
  }
  CORTE_CROSS_20221206 {
    ID INT
    Doc_identidad_cliente_TITULAR INT
    Nombre_completo_cliente_TITULAR VARCHAR
    DNI_agente VARCHAR
    Usuario_agente VARCHAR
    nombre_agente VARCHAR
  }
  CORTE_CROSS_20221206_atento {
    ID INT
    Doc_identidad_cliente_TITULAR INT
    Nombre_completo_cliente_TITULAR VARCHAR
    DNI_agente VARCHAR
    Usuario_agente VARCHAR
    nombre_agente VARCHAR
  }
  CORTE_CROSS_20221206_gss {
    ID INT
    Doc_identidad_cliente_TITULAR INT
    Nombre_completo_cliente_TITULAR VARCHAR
    DNI_agente VARCHAR
    Usuario_agente VARCHAR
    nombre_agente VARCHAR
  }
  CORTE_CROSS_20221206_gss_nov {
    ID INT
    Doc_identidad_cliente_TITULAR INT
    Nombre_completo_cliente_TITULAR VARCHAR
    DNI_agente VARCHAR
    Usuario_agente VARCHAR
    nombre_agente VARCHAR
  }
  CRONOGRAMA_INGRESOS_FINAL {
    Proveedor VARCHAR
    NEGOCIO VARCHAR
    Codigo_Grupo VARCHAR
    PLATAFORMA VARCHAR
    MOTIVO VARCHAR
    Fecha_OJT_Inicial_PROYECTADO VARCHAR
  }
  CRONOGRAMA_INGRESOS_HISTORICO {
    CROIN_Proveedor VARCHAR
    CROIN_NEGOCIO VARCHAR
    CROIN_Codigo_Grupo VARCHAR
    CROIN_PLATAFORMA VARCHAR
    CROIN_Proveedor_LOCAL VARCHAR
    CROIN_Origen_Recursos VARCHAR
  }
  CRONOGRAMA_INGRESOS_INTEGRATEL_HISTORICO {
    Proveedor VARCHAR
    NEGOCIO VARCHAR
    Codigo_Grupo VARCHAR
    PLATAFORMA VARCHAR
    MOTIVO VARCHAR
    Fecha_OJT_Inicial_PROYECTADO VARCHAR
  }
  CRONOGRAMA_INGRESOS_SOCIOS_HISTORICO {
    Proveedor VARCHAR
    NEGOCIO VARCHAR
    Codigo_Grupo VARCHAR
    PLATAFORMA VARCHAR
    MOTIVO VARCHAR
    Fecha_OJT_Inicial_PROYECTADO VARCHAR
  }
  CRONOGRAMA_INGRESOS_ULT_ACT {
    CROIN_Proveedor VARCHAR
    CROIN_NEGOCIO VARCHAR
    CROIN_Codigo_Grupo VARCHAR
    CROIN_PLATAFORMA VARCHAR
    CROIN_Proveedor_LOCAL VARCHAR
    CROIN_Origen_Recursos VARCHAR
  }
  CRONOGRAMA_INGRESOS_ULT_ACT_AM_ERROR {
    CROIN_Proveedor VARCHAR
    CROIN_NEGOCIO VARCHAR
    CROIN_Codigo_Grupo VARCHAR
    CROIN_PLATAFORMA VARCHAR
    CROIN_Proveedor_LOCAL VARCHAR
    CROIN_Origen_Recursos VARCHAR
  }
  CRONOGRAMA_INGRESOS_X_SEMANA {
    CROIN_Fecha_OJT_Inicial_PROYECTADO VARCHAR
    CROIN_PROVEEDOR VARCHAR
    CROIN_Plataforma VARCHAR
    INGRESO_PROYECTADO VARCHAR
    INGRESO_REAL VARCHAR
    DIF_ VARCHAR
  }
  CROSS_CCEE_EVOLUTIVO_OFERTAS_DIARIA {
    PERIODO VARCHAR
    DIA VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    REPORTE VARCHAR
    RESULTADO VARCHAR
  }
  CROSS_CCEE_RANKING_AGENTES {
    PERIODO VARCHAR
    FECHA VARCHAR
    SEMANA VARCHAR
    DNI_OPERADOR VARCHAR
    NOMBRE_OPERADOR VARCHAR
    PROVEEDOR VARCHAR
  }
  CR_BASE_LOG {
    ID INT
    USUARIO VARCHAR
    NOMBRE_BASE VARCHAR
    CONTACTOS_CRUCE VARCHAR
    NEGOCIO_CRUCE VARCHAR
    TIPO_CRUCE VARCHAR
  }
  CUOTAS_DETALLE_CROSS_CALL_CENTER {
    PERIODO VARCHAR
    TIPO VARCHAR
    PROVEEDOR VARCHAR
    CANAL VARCHAR
    PRODUCTO VARCHAR
    SUB_PRODUCTO VARCHAR
  }
  CUOTAS_DETALLE_CROSS_CALL_CENTER_HISTORICO {
    PERIODO VARCHAR
    TIPO VARCHAR
    PROVEEDOR VARCHAR
    CANAL VARCHAR
    PRODUCTO VARCHAR
    SUB_PRODUCTO VARCHAR
  }
  CUOTA_FIBRA_CROSS {
    NEGOCIO VARCHAR
    DIA VARCHAR
    REPORTE VARCHAR
    TOTAL VARCHAR
  }
  Cliente_TDI_Piloto_1_Base_73k {
    CLIENTE VARCHAR
    ACCESO_ID_REDADSL INT
    ACCESO_ID_REDHFC INT
    LINE_ID INT
    TELEFONO VARCHAR
    TIPODOC VARCHAR
  }
  Cliente_TDI_Piloto_2_Base_46k {
    CLIENTE VARCHAR
    ACCESO_ID_REDADSL INT
    ACCESO_ID_REDHFC INT
    LINE_ID INT
    TELEFONO VARCHAR
    TIPODOC VARCHAR
  }
  DETALLE_ACCESADAS_TODAY {
    FECHA VARCHAR
    INTERVALO VARCHAR
    MOTIVO VARCHAR
    SUB_MOTIVO VARCHAR
    CASO_DE_USO VARCHAR
    INGRESO_ID_LLAMADA INT
  }
  DETALLE_AVERIAS_POR_AGENTE_3MESES {
    PERIODO VARCHAR
    DNI_AGENTE VARCHAR
    Incident_Number INT
    Tipo_de_incidencia__c INT
    Area_CRM VARCHAR
    COD_TECNICO_TOA__c VARCHAR
  }
  DETALLE_CRUCE_FIBRA_LLAMADAS {
    CANAL VARCHAR
    DIA VARCHAR
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  DETALLE_DE_USUARIOS_KIPU {
    ID INT
    NOMBRE VARCHAR
    EMAIL VARCHAR
    CONTRASEÑA VARCHAR
    DNI VARCHAR
    ID_PROVEEDOR INT
  }
  DETALLE_DE_USUARIOS_KIPU_BKP_120226 {
    ID INT
    NOMBRE VARCHAR
    EMAIL VARCHAR
    CONTRASEÑA VARCHAR
    DNI VARCHAR
    ID_PROVEEDOR INT
  }
  DETALLE_ENTRANTES_CCEE {
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
    TELEFONO_CONSOLIDADO INT
  }
  DETALLE_OPCIONES_MENU_KIPU {
    ID INT
    MENU VARCHAR
    SUB_MENU VARCHAR
    MENU_URL VARCHAR
    NOMBRE_RUTA VARCHAR
    ICONO_MENU VARCHAR
  }
  DETALLE_OPCIONES_MENU_KIPU_temp {
    ID INT
    MENU VARCHAR
    SUB_MENU VARCHAR
    MENU_URL VARCHAR
    NOMBRE_RUTA VARCHAR
    ICONO_MENU VARCHAR
  }
  DETALLE_REITERADAS_Y_TRANSFERENCIAS {
    ID_INTERACCION INT
    FECHA VARCHAR
    FECHA_LLAM VARCHAR
    SEMANA_ANIO VARCHAR
    CDN VARCHAR
    SKILL VARCHAR
  }
  DIM_USUARIOS_ESTADO {
    ESTADO_ID INT
    ESTADO_DESCRIPCION VARCHAR
  }
  DIM_USUARIOS_PERFIL {
    PERFIL_ID INT
    PERFIL_DESCRIPCION VARCHAR
  }
  DIM_USUARIOS_PROVEEDOR {
    PROVEEDOR_ID INT
    PROVEEDOR_DESCRIPCION VARCHAR
  }
  Data_gestion_avail_CARGA {
    Evento VARCHAR
    Fecha VARCHAR
    Fecha VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
    Cuartil VARCHAR
  }
  Data_gestion_avail_CARGA_2 {
    ID INT
    Evento VARCHAR
    Fecha VARCHAR
    Fecha VARCHAR
    Proveedor VARCHAR
    Plataforma VARCHAR
  }
  ENCUESTAS_MEDALLIA_CHECA_TU_CASO {
    CODIGO_DE_PROBLEMA VARCHAR
    USUARIO_FINAL_APELLIDOS_NOMBRES INT
    NUMERO_DE_DOCUMENTO_DE_IDENTIDAD_USUARIO_FINAL INT
    NUMERO_DE_DOCUMENTO_DE_IDENTIDAD_DEL_ABONADO_REPRESENTANTE INT
    NOMBRE_ABONADO_REPRESENTATE_LEGAL VARCHAR
    NUMERO_DE_SERVICIO VARCHAR
  }
  ENCUESTAS_MEDALLIA_ESPECIALIZADOS {
    POSI_CORRELATIVO VARCHAR
    POSV_DNI VARCHAR
    POSV_TELEFONO VARCHAR
    POSV_CORREO VARCHAR
    POSV_TELEFONO_CONTACTO VARCHAR
    POSV_EMB_NOMBRE VARCHAR
  }
  EVIDENCIA_VALIDACION_REASIGNACION {
    ID_EVIDENCIA INT
    DNI_CLIENTE VARCHAR
    TELEFONO VARCHAR
    RUC VARCHAR
    NUMERO_RECLAMO VARCHAR
    Tx_ClienteTitular VARCHAR
  }
  EXAMEN_AGENTES_PLATINUM_VOZ {
    PERIODO VARCHAR
    DNI VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    NOTA VARCHAR
    RESULTADO VARCHAR
  }
  FACTURACION_PARAMETROS {
    PARAMETRO VARCHAR
    VALOR VARCHAR
    USUARIO_ACTUALIZA VARCHAR
    FECHA_ACTUALIZA VARCHAR
  }
  FIBRA_VISOR {
    COD_SOLICITUD VARCHAR
    SERVICIO VARCHAR
    TELEFONO VARCHAR
    FECHA_SOLICITUD VARCHAR
    RESULTADO VARCHAR
    OFERTA_ELEGIDA INT
  }
  FILTROS_INDICADORES_GENERALES_CCEE {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    PERIODO VARCHAR
  }
  FILTROS_INDICADORES_GENERALES_VOZ {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    PERIODO VARCHAR
  }
  FILTROS_INDICADORES_GENERALES_VOZ_MATRIX {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    PERIODO VARCHAR
  }
  FILTROS_MALLAS {
    TIPO VARCHAR
    PERIODO VARCHAR
  }
  FILTROS_PLATAFORMAS_CCEE {
    ID INT
    Head_ID INT
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  FILTROS_PLATAFORMAS_VOZ {
    ID INT
    Head_ID INT
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  FILTROS_PLATAFORMAS_VOZ_MATRIX {
    ID INT
    Head_ID INT
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  FILTROS_RESUMEN_IVR_ADAPTATIVO {
    ID INT
    Head_ID INT
    NEGOCIO VARCHAR
    IVR VARCHAR
  }
  FILTROS_TIPIFICACIONES_VISOR {
    ANIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  FILTROS_TIPIFICACIONES_VISOR_PLAT {
    ID INT
    Head_ID INT
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  FILTRO_AUTOGESTIONES {
    sistema VARCHAR
    calc_segmento VARCHAR
    CALC_NEGOCIO VARCHAR
    CALC_INSTANCIA VARCHAR
    CALC_ESTADO_RECLAMO VARCHAR
    CALC_TIPO_RECLAMO VARCHAR
  }
  FOMULARIO_DRIVE_RECLAMOS_2DA_CALL_CENTER {
    Flag VARCHAR
    Conjunto VARCHAR
    Conjunto VARCHAR
    Resumen VARCHAR
    Reclamo VARCHAR
    Reclamo VARCHAR
  }
  FORMULARIO_CROSS_CCEE_VOZ {
    ID INT
    DNI_Cliente_Titular VARCHAR
    Nombre_Cliente_Titular VARCHAR
    Email_Cliente_Titular VARCHAR
    DNI_Vendedor VARCHAR
    Usuario_Vendedor VARCHAR
  }
  FORMULARIO_CROSS_VOZ_ADSL {
    ID INT
    Start VARCHAR
    Completion VARCHAR
    Email VARCHAR
    Name VARCHAR
    TECNOLOGIA VARCHAR
  }
  GENERACION_MALLAS_DISTRIBUCION_HORARIA {
    MES VARCHAR
    NEGOCIO VARCHAR
    CALL VARCHAR
    PLATAFORMA VARCHAR
    INTERVALO VARCHAR
    LUNES VARCHAR
  }
  GENERACION_MALLAS_PARTICIPACION_PROVEEDOR {
    MES VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    ATENTO VARCHAR
    COMDATA VARCHAR
    GSS VARCHAR
  }
  HISTORICO_CARGA_USUARIOS_RECLAMOS {
    USUREC_MES VARCHAR
    USUREC_ASESOR_DNI VARCHAR
    USUREC_ASESOR_NOMBRE_APELLIDO INT
    USUREC_USUARIO_SISTEMA_FENIX VARCHAR
    USUREC_USUARIO_SISTEMA_CMS VARCHAR
    USUREC_USUARIO_SISTEMA_ATIS VARCHAR
  }
  HISTORICO_ORIGEN_VENTA_CHECA_TU_CASO {
    CODIGO VARCHAR
    USUARIO VARCHAR
    FECHA VARCHAR
    TIPO VARCHAR
    NUMERO VARCHAR
    NOMBRE VARCHAR
  }
  HISTORICO_REASIGNACION_RECLAMOS {
    DNI_CLIENTE VARCHAR
    TELEFONO VARCHAR
    RUC VARCHAR
    NUMERO_RECLAMO VARCHAR
    Tx_ClienteTitular VARCHAR
    USUARIO_CARGA VARCHAR
  }
  HP_DATA_RECUPERO {
    TELEFONO_CONSOLIDADO INT
    TELEFONO_LLAMANTE VARCHAR
    TELEFONO_CONSULTA VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    PROVEEDOR VARCHAR
    FECHA VARCHAR
  }
  HP_ENTRANTES_PROYECTADO {
    PERIODO VARCHAR
    FECHA_COMPLETA VARCHAR
    FECHA VARCHAR
    HORA VARCHAR
    MINUTOS VARCHAR
    LLAMADAS VARCHAR
  }
  INCIDENCIAS_1991 {
    ID INT
    IDENTIFICADOR INT
    FECHA_APERTURA VARCHAR
    AREA_APERTURA VARCHAR
    USUARIO_APERTURA VARCHAR
    TICKET VARCHAR
  }
  INCIDENCIAS_1991_CATEGORIAS {
    ID INT
    categoria VARCHAR
  }
  INCIDENCIAS_1991_ESTADOS {
    ID INT
    estado VARCHAR
  }
  INCIDENCIAS_1991_IDENTIFICADORES {
    ID INT
    identificador_1 INT
    identificador_2 INT
  }
  INCIDENCIAS_1991_SEVERIDADES {
    ID INT
    severidades INT
  }
  IND_CALL_CENTER_RESUMEN_GRUPO_PLATAFORMA {
    GRUPO_INDICADOR VARCHAR
    INDICADOR VARCHAR
    PERIODO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    NUMERADOR VARCHAR
    DENOMINADOR VARCHAR
  }
  IVR {
    YYYY VARCHAR
    Mes VARCHAR
    Fecha VARCHAR
    Opcion_IVR VARCHAR
    Homologacion VARCHAR
    Cantidad INT
  }
  JCO_MOTIVOS_CONTACTOS {
    PERIODO VARCHAR
    DIA VARCHAR
    TIPO_CONTACTO VARCHAR
    TIPO_GESTION VARCHAR
    MOTIVO VARCHAR
    SUB_MOTIVO VARCHAR
  }
  JG_BACKUP_20221124_CRONOGRAMA_INGRESOS_ULT_ACT_ERRORES {
    CROIN_Proveedor VARCHAR
    CROIN_NEGOCIO VARCHAR
    CROIN_Codigo_Grupo VARCHAR
    CROIN_PLATAFORMA VARCHAR
    CROIN_Proveedor_LOCAL VARCHAR
    CROIN_Origen_Recursos VARCHAR
  }
  JSS_AGRUPACION_VISTA_DIFERENCIA {
    FECHA VARCHAR
    Q_LLAMADAS_PROYECTADO VARCHAR
    Q_LLAMADAS_REAL VARCHAR
    Q_LLAMADAS_PLANIFICACIÓN VARCHAR
    pais VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  JSS_AGRUPACION_VISTA_DIFERENCIA_APERTURA {
    FECHA VARCHAR
    Q_LLAMADAS_PROYECTADO VARCHAR
    Q_LLAMADAS_REAL VARCHAR
    Q_LLAMADAS_PLANIFICACIÓN VARCHAR
    pais VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  JSS_AVERIAS_X_APERTURA {
    FECHA_REGISTRO VARCHAR
    TECNOLOGIA VARCHAR
    TOTAL_AVERIAS VARCHAR
    PLATAFORMA VARCHAR
    FLAG_DNI_VACIO VARCHAR
    GRUPO_TIPO_AVERIA VARCHAR
  }
  JSS_BASE_APERTURA_PLATAFORMAS_HISPAM {
    PERIODO_PROYECTADO VARCHAR
    PAIS VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    PESO VARCHAR
    CANAL VARCHAR
  }
  JSS_BASE_APERTURA_SOCIOS_HISPAM {
    PERIODO_PROYECTADO VARCHAR
    PAIS VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    SOCIO VARCHAR
    PESO VARCHAR
  }
  JSS_BASE_FACTORES_PROYECCION_HISPAM {
    FECHA VARCHAR
    PAIS VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    TIPO_FACTOR VARCHAR
    FACTOR VARCHAR
  }
  JSS_CALCULO_TMP_MALLA {
    FECHA_CALCULO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    DIA_SEMANA VARCHAR
    HORA VARCHAR
    MINUTO VARCHAR
  }
  JSS_CATALOGO_SEMANA_FECHAS_PLANIFICACION {
    fecha VARCHAR
    num_semana VARCHAR
    fecha_inicio_semana VARCHAR
    fecha_fin_semana VARCHAR
  }
  JSS_CLIENTES_BAJO_TDI {
    NRODOC VARCHAR
  }
  JSS_CLIENTES_BAJO_TDI_2DO_GRUPO {
    NRODOC VARCHAR
  }
  JSS_CLIENTES_BAJO_TDI_3ER_GRUPO {
    CLIENTE VARCHAR
    ACCESO_ID_REDADSL INT
    ACCESO_ID_REDHFC INT
    LINE_ID INT
    TELEFONO VARCHAR
    TIPODOC VARCHAR
  }
  JSS_LOG_SP {
    PASO VARCHAR
    FECHA VARCHAR
    PERIODO VARCHAR
  }
  JSS_PROYECCION_CON_FACTORES {
    FECHA VARCHAR
    Q_LLAMADAS_PROYECTADO VARCHAR
    Q_LLAMADAS_REAL VARCHAR
    Q_LLAMADAS_PLANIFICACIÓN VARCHAR
    PAIS VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  JSS_PROYECCION_CON_FACTORES_APERTURA {
    FECHA VARCHAR
    Q_LLAMADAS_PROYECTADO VARCHAR
    Q_LLAMADAS_REAL VARCHAR
    Q_LLAMADAS_PLANIFICACIÓN VARCHAR
    PAIS VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  JSS_TABLA_BASE_PONDERADO_TMO {
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    Fecha_Ventana_30_min VARCHAR
    DIA_SEMANA VARCHAR
    TMO VARCHAR
    CANAL VARCHAR
  }
  JSS_TEMP_PRONOSTICO_CORTE_30D_DIFERENCIA {
    periodo VARCHAR
    fecha VARCHAR
    pais VARCHAR
    VERSION_PROYECTADO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    plataforma VARCHAR
  }
  JSS_TEMP_PRONOSTICO_CORTE_PEGADO {
    periodo VARCHAR
    fecha VARCHAR
    pais VARCHAR
    VERSION_PROYECTADO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    plataforma VARCHAR
  }
  JSS_catalogo_fechas_cronograma_planificacion {
    Semana VARCHAR
    FECHA_INCIO_SEMANA VARCHAR
    FECHA_FIN_SEMANA VARCHAR
  }
  KCRM_VENTAS_2DA_LINEA_CROSS_CCEE {
    Fecha VARCHAR
    Intencion VARCHAR
    N_De_Telefono_Entrada VARCHAR
    N_De_Telefono_Gestin VARCHAR
    Conn_ID INT
    Motivo VARCHAR
  }
  KCS_ENTRANTES_PILOTO {
    IND VARCHAR
    PERIODO_SESION VARCHAR
    FECHA_SESION VARCHAR
    PROVEEDOR VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
  }
  KCS_MOT_NO_ACEPT_CROSS_CCEE {
    MOTIVO VARCHAR
    GRUPO_1 VARCHAR
    MOTIVO_AGRUPADO VARCHAR
  }
  LD_METRICAS_ANTIGUEDAD_AGENTES_REQ_BEATRIZ {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    AGENTE VARCHAR
    ANTIGUEDAD_AGENTE VARCHAR
    ANTIGUEDAD_AGENTE_AGRUPADO VARCHAR
  }
  LD_METRICAS_ANTIGUEDAD_AGENTES_REQ_BEATRIZ_v2 {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    AGENTE VARCHAR
    ANTIGUEDAD_AGENTE VARCHAR
    ANTIGUEDAD_AGENTE_AGRUPADO VARCHAR
  }
  LD_RESUMEN_MOTIVOS_CAIDAS_POR_CAMPAÑAS_CROSS_CCEE {
    PERIODO VARCHAR
    AÑO VARCHAR
    MES VARCHAR
    NOMBRE_MES VARCHAR
    DIA VARCHAR
    REPORTE VARCHAR
  }
  LISTA_AGENTES_GENESYS_HIST {
    CENTRO VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    APELLIDOS_NOMBRES INT
    SUPERVISOR VARCHAR
  }
  LISTA_AGENTES_GENESYS_ULT_ACT {
    CENTRO VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    APELLIDOS_NOMBRES INT
    SUPERVISOR VARCHAR
  }
  LISTA_RELLAMADORES {
    TELEFONO VARCHAR
    GRABACION VARCHAR
    MOTIVO_BLOQUEO VARCHAR
    USUARIO_CARGA VARCHAR
    FECHA_CARGA VARCHAR
  }
  LOG_ACTIVIDAD_USUARIOS {
    USUARIO VARCHAR
    ACTIVIDAD INT
    FECHA_REGISTRO VARCHAR
  }
  LOG_ACTUALIZACIONES_DATA {
    ID INT
    PROCESO VARCHAR
    SUB_PROCESO VARCHAR
    ACCION VARCHAR
    OBSERVACIONES VARCHAR
    USUARIO VARCHAR
  }
  LOG_CONSULTAS_MENU {
    MENU_1 VARCHAR
    MENU_2 VARCHAR
    MENU_3 VARCHAR
    USUARIO VARCHAR
    FECHA_REGISTRO VARCHAR
  }
  LOG_GENERACION_MALLAS {
    ACCION VARCHAR
    FECHA_MODIFICACION VARCHAR
    TIPO_FACTOR_INGRESADO VARCHAR
    FACTOR_INGRESADO VARCHAR
    USUARIO_MODIFICA VARCHAR
    PLATAFORMA_AFECTADA VARCHAR
  }
  LOG_PASS_USUARIOS {
    USUARIO VARCHAR
    PASS VARCHAR
    FECHA_REGISTRO VARCHAR
  }
  LOG_REPROCESOS_KIPU {
    ACCION VARCHAR
    NEGOCIO VARCHAR
    FECHA VARCHAR
    USUARIO_EJECUTA VARCHAR
    REPROCESO_FECHA_INICIO VARCHAR
    REPROCESO_FECHA_FIN VARCHAR
  }
  MALLAS_AGENTES_HISTORICO {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    SITIO VARCHAR
    DNI VARCHAR
    NOMBRES VARCHAR
  }
  MALLAS_AGENTES_ULT_ACT {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    SITIO VARCHAR
    DNI VARCHAR
    NOMBRES VARCHAR
  }
  MALLAS_PARAMETROS {
    PARAMETRO VARCHAR
    VALOR VARCHAR
    USUARIO_ACTUALIZA VARCHAR
    FECHA_ACTUALIZA VARCHAR
  }
  MALLAS_PROVEEDOR_HISTORICO {
    PREV_FECHA VARCHAR
    PREV_HORA VARCHAR
    PREV_NEGOCIO VARCHAR
    PREV_PROVEEDOR VARCHAR
    PREV_PLATAFORMA VARCHAR
    PREV_VALOR_AGENTES VARCHAR
  }
  MALLAS_PROVEEDOR_ULT_ACT {
    PREV_FECHA VARCHAR
    PREV_HORA VARCHAR
    PREV_NEGOCIO VARCHAR
    PREV_PROVEEDOR VARCHAR
    PREV_PLATAFORMA VARCHAR
    PREV_VALOR_AGENTES VARCHAR
  }
  MALLAS_TDP_HISTORICO {
    PREV_FECHA VARCHAR
    PREV_HORA VARCHAR
    PREV_NEGOCIO VARCHAR
    PREV_PROVEEDOR VARCHAR
    PREV_PLATAFORMA VARCHAR
    PREV_VALOR VARCHAR
  }
  MALLAS_TDP_HISTORICO_SIM_202110 {
    PREV_FECHA VARCHAR
    PREV_HORA VARCHAR
    PREV_NEGOCIO VARCHAR
    PREV_PROVEEDOR VARCHAR
    PREV_PLATAFORMA VARCHAR
    PREV_VALOR VARCHAR
  }
  MALLAS_TDP_ULT_ACT {
    PREV_FECHA VARCHAR
    PREV_HORA VARCHAR
    PREV_NEGOCIO VARCHAR
    PREV_PROVEEDOR VARCHAR
    PREV_PLATAFORMA VARCHAR
    PREV_VALOR VARCHAR
  }
  METAS_RANKING_AGENTES_CCEE_V2 {
    PLATAFORMA VARCHAR
    METRICA VARCHAR
    OBJETIVO VARCHAR
    PESO VARCHAR
    PERIODO VARCHAR
  }
  METRICAS_OPERATIVAS_TODAY_ACCESADAS {
    FECHA VARCHAR
    INTERVALO VARCHAR
    MOTIVO VARCHAR
    SUB_MOTIVO VARCHAR
    CASO_DE_USO VARCHAR
    LLAMADAS_ACCESADAS VARCHAR
  }
  METRICAS_OPERATIVAS_TODAY_CCEE {
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
    CASOS_ENTRANTES VARCHAR
  }
  METRICAS_OPERATIVAS_TODAY_VOZ {
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
    LLAMADAS_ENTRANTES VARCHAR
  }
  OBJETIVOS_AGENTES_VOZ_PLATINUM {
    PERIODO VARCHAR
    NEGOCIO VARCHAR
    METRICA VARCHAR
    VAL_MAX VARCHAR
    VAL_MIN VARCHAR
    PESO VARCHAR
  }
  OBJETIVOS_CEE_W {
    PLATAFORMA VARCHAR
    NDS_OBJ VARCHAR
    ASA VARCHAR
    SIMULTANIEDAD VARCHAR
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
  }
  OBJETIVOS_CEE_W_bk_am {
    PLATAFORMA VARCHAR
    NDS_OBJ VARCHAR
    ASA VARCHAR
    SIMULTANIEDAD VARCHAR
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
  }
  OBJETIVOS_RANKING_PROV {
    FECHA VARCHAR
    REITERACION_PUNTOS VARCHAR
    REITERACION_OBJETIVO VARCHAR
    TRANSFERENCIAS_PUNTOS VARCHAR
    TRANSFERENCIAS_OBJETIVO VARCHAR
    NPS_PUNTOS VARCHAR
  }
  OBJETIVOS_RANKING_VOZ {
    FECHA VARCHAR
    REITERACION_PUNTOS VARCHAR
    REITERACION_OBJETIVO VARCHAR
    TRANSFERENCIAS_PUNTOS VARCHAR
    TRANSFERENCIAS_OBJETIVO VARCHAR
    SOLUCION_PUNTOS VARCHAR
  }
  ORIGEN_VENTA_CHECA_TU_CASO_ULT_ACT {
    CODIGO VARCHAR
    USUARIO VARCHAR
    FECHA VARCHAR
    TIPO VARCHAR
    NUMERO VARCHAR
    NOMBRE VARCHAR
  }
  OSIPTEL_EVOLUTIVO_INFORME_REGULADOS {
    Origen VARCHAR
    an VARCHAR
    mes VARCHAR
    dia VARCHAR
    Departamento VARCHAR
    calc_negocio VARCHAR
  }
  OSIPTEL_EVOLUTIVO_INFORME_REGULADOS_old {
    Origen VARCHAR
    an VARCHAR
    mes VARCHAR
    dia VARCHAR
    Departamento VARCHAR
    calc_negocio VARCHAR
  }
  PARAMETROS {
    PARAMETRO VARCHAR
    VALOR VARCHAR
    USUARIO_ACTUALIZA VARCHAR
    FECHA_ACTUALIZA VARCHAR
  }
  PBI_PERIODOS_DESCARGAS {
    REPORTE VARCHAR
    PERIODO VARCHAR
  }
  PECUF_PECNEG_HISTORICO {
    Segmento VARCHAR
    Plataforma VARCHAR
    Sub_Plataforma VARCHAR
    Documento VARCHAR
    Apellidos_y_Nombres INT
    Coordinador VARCHAR
  }
  PECUF_PECNEG_ULT_ACT {
    Segmento VARCHAR
    Plataforma VARCHAR
    Sub_Plataforma VARCHAR
    Documento VARCHAR
    Apellidos_y_Nombres INT
    Coordinador VARCHAR
  }
  PERFILES_MENU {
    ID_T INT
    ID_PERFIL INT
    ID_MENU INT
  }
  PLANILLAS_PPP_DIAS_HISTORICO {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
    REQUERIDOS_PROYECTADOS INT
  }
  PLANILLAS_PPP_DIAS_ULT_ACT {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
    REQUERIDOS_PROYECTADOS INT
  }
  PLANILLAS_PPP_MESES_HISTORICO {
    INDICADOR VARCHAR
    CANAL VARCHAR
    PROVEEDOR VARCHAR
    ANIO VARCHAR
    MES VARCHAR
    PLATAFORMA VARCHAR
  }
  PLANILLAS_PPP_MESES_ULT_ACT {
    Indicador VARCHAR
    Canal VARCHAR
    Proveedor VARCHAR
    Anio VARCHAR
    mes VARCHAR
    plataforma VARCHAR
  }
  PLANILLAS_PPP_REDUCTORES_HISTORICO {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    Aus_Lunes VARCHAR
    Aus_Martes VARCHAR
    Aus_Miercoles VARCHAR
  }
  PLANILLAS_PPP_REDUCTORES_ULT_ACT {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    Aus_Lunes VARCHAR
    Aus_Martes VARCHAR
    Aus_Miercoles VARCHAR
  }
  PLANILLAS_PPP_SEMANAS_HISTORICO {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    SITE VARCHAR
    CONEXION VARCHAR
    SEMANA VARCHAR
  }
  PLANILLAS_PPP_SEMANAS_ULT_ACT {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    SITE VARCHAR
    CONEXION VARCHAR
    SEMANA VARCHAR
  }
  PLANILLAS_PPP_SEMANAS_ULT_ACT_BACKUP {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    SITE VARCHAR
    CONEXION VARCHAR
    SEMANA VARCHAR
  }
  PLATAFORMAS_PAISES {
    REGIION VARCHAR
    PLATAFORMA VARCHAR
    GESTION VARCHAR
    PROVEEDOR VARCHAR
    SITE_PROVEEDOR VARCHAR
    TIPO_DE_NEGOCIO VARCHAR
  }
  PLATAFORMAS_PAISES_bk {
    REGIION VARCHAR
    PLATAFORMA VARCHAR
    GESTION VARCHAR
    PROVEEDOR VARCHAR
    SITE_PROVEEDOR VARCHAR
    TIPO_DE_NEGOCIO VARCHAR
  }
  PLATAFORMAS_X_VALOR {
    ORDEN VARCHAR
    PLATAFORMA VARCHAR
    NEGOCIO VARCHAR
    ESTADO VARCHAR
    INGRESO VARCHAR
  }
  POTENCIALES_FIBRA_202208 {
    DIA VARCHAR
    FECHA VARCHAR
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    FLAG_CRITICO VARCHAR
    FECHA_ACTUALIZACION VARCHAR
  }
  PREVENTAS_CAPL_VISOR {
    cod_solicitud VARCHAR
    servicio VARCHAR
    telefono VARCHAR
    fecha_solicitud VARCHAR
    resultado VARCHAR
    oferta_elegida INT
  }
  PREVENTAS_CROSS_TODAS_CAMP_DIARIO {
    ID INT
    Doc_identidad_cliente_TITULAR INT
    Nombre_completo_cliente_TITULAR VARCHAR
    DNI_agente VARCHAR
    Usuario_agente VARCHAR
    nombre_agente VARCHAR
  }
  PREVENTAS_CROSS_TODAS_CAMP_DIARIO_bk_0612 {
    ID INT
    Doc_identidad_cliente_TITULAR INT
    Nombre_completo_cliente_TITULAR VARCHAR
    DNI_agente VARCHAR
    Usuario_agente VARCHAR
    nombre_agente VARCHAR
  }
  PREVENTAS_FEEDBACK {
    ID INT
    DNI_Cliente_Titular VARCHAR
    Nombre_Cliente_Titular VARCHAR
    Email_Cliente_Titular VARCHAR
    DNI_Vendedor VARCHAR
    Usuario_Vendedor VARCHAR
  }
  PREVENTAS_FEEDBACK_KONECTA_KIPU {
    ID INT
    DNI_Cliente_Titular VARCHAR
    Nombre_Cliente_Titular VARCHAR
    Email_Cliente_Titular VARCHAR
    DNI_Vendedor VARCHAR
    Usuario_Vendedor VARCHAR
  }
  PREVENTAS_POR_ASESOR {
    GESTION VARCHAR
    CAMPAÑA VARCHAR
    PERIODO VARCHAR
    USUARIO_DNI VARCHAR
    NEGOCIO VARCHAR
    TOTAL VARCHAR
  }
  PREVENTAS_RECEPTIVOS_CCEE {
    ID INT
    Fecha VARCHAR
    Hora VARCHAR
    Gestión VARCHAR
    Plataforma VARCHAR
    Atención VARCHAR
  }
  PREVENTAS_VOZ_FEEDBACK {
    ID INT
    DNI_Cliente_Titular VARCHAR
    Nombre_Cliente_Titular VARCHAR
    Email_Cliente_Titular VARCHAR
    DNI_Vendedor VARCHAR
    Usuario_Vendedor VARCHAR
  }
  PREVISION_CALIDAD_PROGRAMACION {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    INTERVALO VARCHAR
    NEGOCIO VARCHAR
  }
  PROCESOS_NO_RESOLUTIVOS_TEMATICO_TIPIFICACIONES_CCEE {
    TIPIFICACION VARCHAR
    MOTIVO_1 VARCHAR
    MOTIVO_2 VARCHAR
  }
  PROCESOS_NO_RESOLUTIVOS_VISTA_CALIDAD_PROCESOS {
    PERIODO VARCHAR
    COLA VARCHAR
    PRODUCTO VARCHAR
    TECNOLOGIA VARCHAR
    TIPIFICACION VARCHAR
    DETALLE VARCHAR
  }
  PROCESOS_NO_RESOLUTIVOS_VISTA_PROCEDIMIENTOS_QUEBRADOS {
    SUB_CANAL VARCHAR
    NUMERO_GESTION VARCHAR
    PROCEDIMIENTO VARCHAR
    ESTATUS VARCHAR
    MES VARCHAR
    ANIO VARCHAR
  }
  PROCESOS_NO_RESOLUTIVOS_VISTA_TRAFICO_CCEE {
    PERIODO VARCHAR
    COLA VARCHAR
    NEGOCIO_TIPI VARCHAR
    TECNOLOGIA VARCHAR
    TOTAL_CASOS VARCHAR
  }
  PRONOSTICO_INTERNO_CCEE {
    PREV_FECHA VARCHAR
    PREV_HORA VARCHAR
    PREV_NEGOCIO VARCHAR
    PREV_PROVEEDOR VARCHAR
    PREV_PLATAFORMA VARCHAR
    PREV_VALOR VARCHAR
  }
  PR_Control_Q_AMDOCS {
    año VARCHAR
    mes VARCHAR
    dia VARCHAR
    CALC_INSTANCIA VARCHAR
    calc_negocio VARCHAR
    calc_tipo_reclamo VARCHAR
  }
  PR_Control_Q_CMS {
    año VARCHAR
    mes VARCHAR
    dia VARCHAR
    CALC_INSTANCIA VARCHAR
    calc_tipo_reclamo VARCHAR
    CALC_CLUSTER_RECLAMO VARCHAR
  }
  PR_Control_Q_FENIX {
    año VARCHAR
    mes VARCHAR
    dia VARCHAR
    CALC_INSTANCIA VARCHAR
    calc_negocio VARCHAR
    calc_tipo_reclamo VARCHAR
  }
  PR_INCIDENCIAS_Carga_usuarios_reclamos {
    ASESOR_DNI VARCHAR
    ASESOR_NOMBRE_APELLIDO INT
    CANAL VARCHAR
    AREA VARCHAR
    RESPONSABLE_CANAL VARCHAR
    USUARIO_CARGA VARCHAR
  }
  RECLAMOS_POR_ASESOR {
    PERIODO VARCHAR
    USUARIO_LOGIN VARCHAR
    TIPO_RECLAMO VARCHAR
    CANAL VARCHAR
    AREA VARCHAR
    SUB_AREA VARCHAR
  }
  RECONTACTO_CROSS_CCEE_2022_DIC {
    FECHA VARCHAR
    LINK_BOTMAKER VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI_AGENTE VARCHAR
    NUMERO_GESTION VARCHAR
  }
  RECONTACTO_CROSS_CCEE_2022_NOV {
    FECHA VARCHAR
    LINK_BOTMAKER VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI_AGENTE VARCHAR
    NUMERO_GESTION VARCHAR
  }
  RECONTACTO_CROSS_CCEE_2023_ENE {
    FECHA VARCHAR
    LINK_BOTMAKER VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI_AGENTE VARCHAR
    NUMERO_GESTION VARCHAR
  }
  RECONTACTO_CROSS_CCEE_2023_ENE_31 {
    MES VARCHAR
    FECHA VARCHAR
    SEMANA VARCHAR
    HORA VARCHAR
    MARCA VARCHAR
    LINK VARCHAR
  }
  RECONTACTO_CROSS_CCEE_ALL_NUEVO {
    FECHA VARCHAR
    LINK_BOTMAKER VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI_AGENTE VARCHAR
    NUMERO_GESTION VARCHAR
  }
  RECONTACTO_CROSS_CCEE_BKP_202207_202210 {
    FECHA VARCHAR
    LINK_BOTMAKER VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI_AGENTE VARCHAR
    NUMERO_GESTION VARCHAR
  }
  RECONTACTO_CROSS_CCEE_COPY {
    FECHA VARCHAR
    LINK_BOTMAKER VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI_AGENTE VARCHAR
    NUMERO_GESTION VARCHAR
  }
  RECONTACTO_CROSS_CCEE_TEMP_202210 {
    FECHA VARCHAR
    LINK_BOTMAKER VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI_AGENTE VARCHAR
    NUMERO_GESTION VARCHAR
  }
  RECONTACTO_CROSS_CCEE_all_bk_1707 {
    FECHA VARCHAR
    LINK_BOTMAKER VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI_AGENTE VARCHAR
    NUMERO_GESTION VARCHAR
  }
  RECONTACTO_CROSS_CCEE_bk_1707 {
    FECHA VARCHAR
    LINK_BOTMAKER VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI_AGENTE VARCHAR
    NUMERO_GESTION VARCHAR
  }
  RECONTACTO_CROSS_VOZ {
    ID INT
    Hora VARCHAR
    Hora VARCHAR
    Correo VARCHAR
    Nombre VARCHAR
    AGENTE VARCHAR
  }
  REGISTROS_RFX {
    ID INT
    TIPO_SOLICITANTE VARCHAR
    CARGO_SOLICTIANTE VARCHAR
    PROVEEDOR_SOLICITANTE VARCHAR
    REQUERIMIENTO VARCHAR
    DETALLE_REQUERIMIENTO VARCHAR
  }
  REGISTROS_RFX_PROVEEOR {
    ID INT
    PROVEEDOR VARCHAR
  }
  REGISTROS_RFX_REQUERIMIENTO {
    ID INT
    REQUERIMIENTO VARCHAR
  }
  REGISTROS_RFX_TIPO_SOLICITANTE {
    ID INT
    TIPO VARCHAR
  }
  REPORTE_EVOLUTIVO_FIBRA {
    DIA VARCHAR
    Base VARCHAR
    Llamadas VARCHAR
    Llamadas VARCHAR
    Llamadas VARCHAR
    Ventas VARCHAR
  }
  REPORTE_EVOLUTIVO_FIBRA_PREVENTA {
    FECHA VARCHAR
    TIPO VARCHAR
    TOTAL VARCHAR
  }
  REPORTE_FIBRA_CROSS_GLOBAL {
    DIA VARCHAR
    ORDEN VARCHAR
    REPORTE VARCHAR
    TOTAL VARCHAR
  }
  REPORTE_FIBRA_CROSS_MOTIVOS_NO_ACEPTA {
    COD_SOLICITUD VARCHAR
    SERVICIO VARCHAR
    TELEFONO VARCHAR
    FECHA_SOLICITUD VARCHAR
    RESULTADO VARCHAR
    OFERTA_ELEGIDA INT
  }
  REPORTE_FIBRA_CROSS_SEMANAL_GLOBAL {
    SEMANA VARCHAR
    ORDEN VARCHAR
    REPORTE VARCHAR
    TOTAL VARCHAR
  }
  REPORTE_FORMACION_CORRELATIVO_CANALES {
    CANAL VARCHAR
    SUB_CANAL VARCHAR
    PROGRAMA VARCHAR
    CONJUNTO VARCHAR
  }
  REPORTE_FORMACION_HISTORICO {
    DNI VARCHAR
    NOMBRES VARCHAR
    APELLIDOS INT
    ESTADO VARCHAR
    CANAL VARCHAR
    CARGO VARCHAR
  }
  REPORTE_FORMACION_OJT_CCEE {
    PERIODO VARCHAR
    FECHA VARCHAR
    DNI VARCHAR
    AGENTE VARCHAR
    SOCIO VARCHAR
    SKILL VARCHAR
  }
  REPORTE_FORMACION_OJT_CCEE_HISTORICO {
    SOCIO VARCHAR
    SKILL VARCHAR
    GRUPO VARCHAR
    FORMADOR VARCHAR
    DNI VARCHAR
    AGENTE VARCHAR
  }
  REPOSITORIO_INCIDENCIAS_B2C {
    ID_INCIDENCIA INT
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
    TIPO_INCIDENCIA INT
    TIPO_FUENTE_O_REPORTE VARCHAR
    RESPONSABLE_SOLUCION VARCHAR
  }
  REPO_INTELIGENCIA_PLATAFORMA {
    ID_PLATAFORMA INT
    PLATAFORMA VARCHAR
    CATEGORIA_PLATAFORMA VARCHAR
    UMBRAL_NDS VARCHAR
    CANAL_CONTACTO VARCHAR
    FECHA_INGRESO VARCHAR
  }
  REQUERIMIENTOS_DIM_ESTADOS {
    ESTADOS_ID INT
    ESTADOS_NOMBRE VARCHAR
    ESTADOS_DESCRIPCION VARCHAR
  }
  REQUERIMIENTOS_DIM_TRABAJADORES {
    TRABAJADOR_ID INT
    TRABAJADOR_NOMBRE VARCHAR
    TRABAJADOR_EMAIL VARCHAR
    ACTIVO VARCHAR
  }
  REQUERIMIENTOS_DIM_TRABAJADORES_bkp {
    TRABAJADOR_ID INT
    TRABAJADOR_NOMBRE VARCHAR
    TRABAJADOR_EMAIL VARCHAR
  }
  REQUERIMIENTOS_KIPU {
    IDREQ INT
    SOLICITANTE_NOMBRE VARCHAR
    SOLICITANTE_CORREO VARCHAR
    SOLICITANTE_AREA VARCHAR
    SOLICITANTE_TELEFONO VARCHAR
    REQUERIMIENTO_TITULO VARCHAR
  }
  REQUERIMIENTOS_KIPU_BKP {
    IDREQ INT
    SOLICITANTE_NOMBRE VARCHAR
    SOLICITANTE_CORREO VARCHAR
    SOLICITANTE_AREA VARCHAR
    SOLICITANTE_TELEFONO VARCHAR
    REQUERIMIENTO_TITULO VARCHAR
  }
  REQUERIMIENTOS_KIPU_ULTIMA_ACT {
    IDREQ INT
    SOLICITANTE_NOMBRE VARCHAR
    SOLICITANTE_CORREO VARCHAR
    SOLICITANTE_AREA VARCHAR
    SOLICITANTE_TELEFONO VARCHAR
    REQUERIMIENTO_TITULO VARCHAR
  }
  RESUMEN_ACCESADAS_VOZ_HORA {
    FECHA VARCHAR
    HORA VARCHAR
    NEGOCIO VARCHAR
    TOTAL_ACCESADAS VARCHAR
  }
  RESUMEN_ANALISIS_DEMANDA {
    EVOLUTIVO VARCHAR
    PERIODO VARCHAR
    MES VARCHAR
    ACCESADAS_VOZ_CCEE VARCHAR
    CLIENTES_UNICOS_ACCESADAS VARCHAR
    DEMANDA_CCEE VARCHAR
  }
  RESUMEN_ANALISIS_DEMANDA_CLI_UNICOS {
    EVOLUTIVO VARCHAR
    PERIODO VARCHAR
    MES VARCHAR
    CLIENTES_UNICOS_VOZ_CCEE_ACCESADAS VARCHAR
    CLIENTES_UNICOS_VOZ_ACCESADAS VARCHAR
    CLIENTES_UNICOS_CCEE_ACCESADAS VARCHAR
  }
  RESUMEN_ANALISIS_DEMANDA_DISTRIBUCION {
    EVOLUTIVO VARCHAR
    PERIODO VARCHAR
    MES VARCHAR
    NEGOCIO VARCHAR
    TRANSACCIONES VARCHAR
    TRANSACCIONES_TOTAL VARCHAR
  }
  RESUMEN_ANIS_VS_RELLAMADAS {
    TIPO VARCHAR
    PERIODO VARCHAR
    PERIODO2 VARCHAR
    PERIODO3 VARCHAR
    RANGO_LLAMADAS VARCHAR
    CLIENTES_UNICOS VARCHAR
  }
  RESUMEN_ANIS_VS_RELLAMADAS_MOTIVOS {
    TIPO VARCHAR
    PERIODO VARCHAR
    PERIODO2 VARCHAR
    PERIODO3 VARCHAR
    RANGO_LLAMADAS VARCHAR
    MOTIVO VARCHAR
  }
  RESUMEN_CARATULA_CCEE {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    NEGOCIO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  RESUMEN_CARATULA_VOZ {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    NEGOCIO VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  RESUMEN_CATEGORIAS_CCEE {
    PERIODO VARCHAR
    FECHA VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    CIERRE_AUTOMATICO VARCHAR
    DESPEDIDA_SALUDO INT
  }
  RESUMEN_CUBO_METRICAS_CCEE_DIA {
    FECHA VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    CLIENTES_UNICOS_PLATAFORMA VARCHAR
    HORAS_LOGIN VARCHAR
  }
  RESUMEN_CUBO_METRICAS_CCEE_MES {
    ANIO VARCHAR
    MES VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    CLIENTES_UNICOS_PLATAFORMA VARCHAR
  }
  RESUMEN_EVOLUTIVO_METRICAS_AGENTES_NUEVOS {
    PERIODO VARCHAR
    FECHA VARCHAR
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    PROVEEDOR VARCHAR
  }
  RESUMEN_FIBRA {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    PRODUCTO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    PLATAFORMA VARCHAR
    dia VARCHAR
  }
  RESUMEN_FIBRA_POTENCIALES {
    PERIODO VARCHAR
    FECHA_SESION VARCHAR
    SESSION_ID INT
    TELEFONO VARCHAR
    NUMERO_DOCUMENTO VARCHAR
    DOCUMENTO_OPERADOR VARCHAR
  }
  RESUMEN_FIBRA_VISOR {
    COD_SOLICITUD VARCHAR
    SERVICIO VARCHAR
    TELEFONO VARCHAR
    FECHA_SOLICITUD VARCHAR
    RESULTADO VARCHAR
    OFERTA_ELEGIDA INT
  }
  RESUMEN_INCREMENTO_PRECIO {
    NEGOCIO VARCHAR
    PERIODO VARCHAR
    FECHA VARCHAR
    TIPIFICACION1 VARCHAR
    MOTIVO VARCHAR
    TIPIFICACION VARCHAR
  }
  RESUMEN_INDIC_GENERALES_CCEE_DIA {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  RESUMEN_INDIC_GENERALES_CCEE_HORA {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  RESUMEN_INDIC_GENERALES_CCEE_INTERVALO {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    MEDIA_HORA VARCHAR
    PROVEEDOR VARCHAR
  }
  RESUMEN_INDIC_GENERALES_CCEE_INTERVALO_BACKUP {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    MEDIA_HORA VARCHAR
    PROVEEDOR VARCHAR
  }
  RESUMEN_INDIC_GENERALES_CCEE_INTERVALO_BK_AM {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    MEDIA_HORA VARCHAR
    PROVEEDOR VARCHAR
  }
  RESUMEN_INDIC_GENERALES_CCEE_INTERVALO_bk_28_08 {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
    MEDIA_HORA VARCHAR
    PROVEEDOR VARCHAR
  }
  RESUMEN_INDIC_GENERALES_CCEE_MES {
    ANIO VARCHAR
    MES VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    CASOS_ATENDIDOS INT
  }
  RESUMEN_INDIC_GENERALES_CCEE_SEMANAS {
    ANIO VARCHAR
    MES VARCHAR
    SEMANA VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  RESUMEN_INDIC_GENERALES_VOZ_DIA {
    FECHA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    LLAMADAS_ENTRANTES VARCHAR
  }
  RESUMEN_INDIC_GENERALES_VOZ_DIA_MATRIX {
    ID INT
    FECHA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  RESUMEN_INDIC_GENERALES_VOZ_HORA {
    FECHA VARCHAR
    HORA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  RESUMEN_INDIC_GENERALES_VOZ_HORA_MATRIX {
    ID INT
    FECHA VARCHAR
    HORA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  RESUMEN_INDIC_GENERALES_VOZ_INTERVALO {
    FECHA VARCHAR
    HORA VARCHAR
    MEDIA_HORA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  RESUMEN_INDIC_GENERALES_VOZ_INTERVALO_MATRIX {
    ID INT
    FECHA VARCHAR
    HORA VARCHAR
    MEDIA_HORA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
  }
  RESUMEN_INDIC_GENERALES_VOZ_MES {
    ANIO VARCHAR
    MES VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  RESUMEN_INDIC_GENERALES_VOZ_MES_MATRIX {
    ID INT
    ANIO VARCHAR
    MES VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  RESUMEN_INDIC_GENERALES_VOZ_SEMANA {
    ANIO VARCHAR
    SEMANA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  RESUMEN_INDIC_GENERALES_VOZ_SEMANA_MATRIX {
    ID INT
    ANIO VARCHAR
    SEMANA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  RESUMEN_INTERVALOS_CALL {
    INTERVALO VARCHAR
  }
  RESUMEN_IVR_ADAPTATIVO {
    TIPO_IVR VARCHAR
    SUBTIPO_IVR VARCHAR
    FECHA VARCHAR
    HORA VARCHAR
    ACCION_IVR_2 VARCHAR
    ACCESOS VARCHAR
  }
  RESUMEN_METRICAS_WFM {
    AÑO VARCHAR
    MES VARCHAR
    NOMBRE VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    NDS VARCHAR
  }
  RESUMEN_METRICAS_WFM_DIARIO {
    FECHA VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    NDS VARCHAR
    UMBRAL VARCHAR
    SIMULTANIEDAD VARCHAR
  }
  RESUMEN_METRICAS_WFM_HORA {
    FECHA VARCHAR
    HORA VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    NDS VARCHAR
    UMBRAL VARCHAR
  }
  RESUMEN_METRICAS_WFM_INTERVALO {
    FECHA VARCHAR
    HORA VARCHAR
    MEDIA_HORA VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    NDS VARCHAR
  }
  RESUMEN_METRICAS_WFM_MENSUAL {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    NDS VARCHAR
    UMBRAL VARCHAR
    SIMULTANIEDAD VARCHAR
  }
  RESUMEN_METRICAS_WFM_SEMANAL {
    ANIO VARCHAR
    SEMANA VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    NDS VARCHAR
    UMBRAL VARCHAR
  }
  RESUMEN_PRODUCTIVIDAD_PROVEEDOR_CCEE {
    PERIODO VARCHAR
    FECHA VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    ESTADO_PENDIENTE VARCHAR
    DESPEDIDA_SALUDO INT
  }
  RESUMEN_REIETRADAS_VOZ {
    PERIODO VARCHAR
    FECHA VARCHAR
    AGENTE VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    TOTAL_REITERADAS VARCHAR
  }
  RESUMEN_REITERADAS_CCEE {
    FECHA VARCHAR
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    DOCUMENTO_OPERADOR VARCHAR
  }
  RESUMEN_REITERADORES_CRONICOS {
    TELEFONO_LLAMANTE VARCHAR
    TELEFONO_CONSULTA VARCHAR
    IVR_CONNID INT
    PERIODO VARCHAR
    FECHA VARCHAR
    PROVEEDOR VARCHAR
  }
  RESUMEN_REIT_TRANS_VOZ_FILTROS {
    PERIODO VARCHAR
  }
  RESUMEN_RETORNOS_CCEE {
    FECHA VARCHAR
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA_ORIGEN VARCHAR
    PLATAFORMA_ORIGEN VARCHAR
    PROVEEDOR_RETORNA VARCHAR
  }
  RESUMEN_SALIENTES {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA_PRINCIPAL VARCHAR
    PLATAFORMA VARCHAR
    AGENTE VARCHAR
    ATENDIDAS_INBOUND INT
  }
  RESUMEN_TECNOLOGIA_AGENTES {
    INTERVALO VARCHAR
    PERIODO VARCHAR
    PERIODO_1 VARCHAR
    PERIODO_2 VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
  }
  RESUMEN_TECNOLOGIA_ASESORES {
    INTERVALO VARCHAR
    PERIODO VARCHAR
    PERIODO_1 VARCHAR
    PERIODO_2 VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
  }
  RESUMEN_TECNOLOGIA_TIPIFIACIONES_VS_CALIDAD {
    INTERVALO VARCHAR
    PERIODO VARCHAR
    PERIODO_1 VARCHAR
    PERIODO_2 VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
  }
  RESUMEN_TECNOLOGIA_TIPIFICACIONES {
    INTERVALO VARCHAR
    PERIODO VARCHAR
    PERIODO_1 VARCHAR
    PERIODO_2 VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
  }
  RESUMEN_TECNOLOGIA_TRAFICO {
    INTERVALO VARCHAR
    PERIODO VARCHAR
    PERIODO_1 VARCHAR
    PERIODO_2 VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
  }
  RESUMEN_TIPIFICACIONES_BASE_ENTRANTES {
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    AGENTE VARCHAR
    FECHA_COMPLETA VARCHAR
    FECHA VARCHAR
  }
  RESUMEN_TIPIFICACIONES_CCEE {
    PERIODO VARCHAR
    FECHA VARCHAR
    TIPIFICACION1 VARCHAR
    MOTIVO VARCHAR
    TIPIFICACION VARCHAR
    TOTAL_REGISTROS VARCHAR
  }
  RESUMEN_TRANSFERENCIAS_VOZ {
    PERIODO VARCHAR
    FECHA VARCHAR
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  RESUMEN_TRANSFERENICAS_CCEE {
    FECHA VARCHAR
    PERIODO VARCHAR
    DOCUMENTO_OPERADOR_ORIGEN VARCHAR
    PROVEEDOR_ORIGEN VARCHAR
    GRUPO_PLATAFORMA_ORIGREN VARCHAR
    PLATAFORMA_ORIGEN VARCHAR
  }
  RETENCIONES_CAMPANIAS_OUT {
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    TIPO_MARCACION VARCHAR
    BASE VARCHAR
    EFECTIVIDAD INT
  }
  RETENCIONES_CAMPANIAS_OUT_ULT_ACT {
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    TIPO_MARCACION VARCHAR
    BASE VARCHAR
    EFECTIVIDAD INT
  }
  RETENCIONES_CUARTILES_AGENTES {
    ANIO VARCHAR
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    Q_EFECT VARCHAR
  }
  RETENCIONES_FEEDBACK {
    PRV_ID_PROVEE INT
    TCNTEL VARCHAR
    FEC_1ERA_LLAM VARCHAR
    FECHA_LLAMADA VARCHAR
    INTENTOS VARCHAR
    COD_RESUL_LLAM VARCHAR
  }
  SEGURIDAD_PARAMETROS {
    PARAMETRO VARCHAR
    VALOR VARCHAR
    USUARIO_ACTUALIZA VARCHAR
    FECHA_ACTUALIZA VARCHAR
  }
  TABLERO_IMPRODUCTIVAS_CASOS_CERRADOS_CCEE {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DOCUMENTO_OPERADOR VARCHAR
    TOTAL_CASOS VARCHAR
    TIPIFCACION_NO_VALIDA INT
  }
  TABLERO_IMPRODUCTIVAS_CCEE {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    AGENTE VARCHAR
    SUPERVISOR VARCHAR
  }
  TIPIFICACIONES_VISOR {
    PROVEEDOR VARCHAR
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
    ASESOR VARCHAR
    SERVICIO VARCHAR
    ANI_LLAMANTE VARCHAR
  }
  TMP_ABORDAJE_VOZ {
    PERIODO VARCHAR
    FECHA_HORA VARCHAR
    RESULTADO VARCHAR
    CANAL VARCHAR
    TIPO VARCHAR
    MOTIVO_NO_ACEPTA VARCHAR
  }
  TMP_AGENTES_PILOTO_CROSS_SELL {
    NOMBRE_AGENTE VARCHAR
    DNI_AGENTE VARCHAR
    ESTADO VARCHAR
    INICIO VARCHAR
    FIN VARCHAR
    NEGOCIO VARCHAR
  }
  TMP_ANTIGUEDAD_AGENTES {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    AGENTE VARCHAR
    ANTIGUEDAD_AGENTE VARCHAR
    ANTIGUEDAD_AGENTE_AGRUPA VARCHAR
  }
  TMP_ANTIGUEDAD_AGENTES_CCEE {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    AGENTE VARCHAR
    ANTIGUEDAD_AGENTE VARCHAR
    ANTIGUEDAD_AGENTE_AGRUPA VARCHAR
  }
  TMP_ANTIGUEDAD_VOZ_DIAS {
    ANTIGUEDAD_DIAS VARCHAR
    FECHA VARCHAR
    ANIO VARCHAR
    PERIODO VARCHAR
    SEMANA VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  TMP_AVERIAS_CON_METRICAS {
    PERIODO VARCHAR
    DNI_AGENTE VARCHAR
    TOTAL_AVERIAS VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    GRUPO_PLATAFORMA VARCHAR
  }
  TMP_BASE_JAVIER {
    ID INT
    Hora VARCHAR
    Hora VARCHAR
    Correo VARCHAR
    Nombre VARCHAR
    AGENTE VARCHAR
  }
  TMP_BORRAR_CCEE {
    FECHA VARCHAR
    MARCA_TEMPORAL VARCHAR
    LINK_BOTMAKER VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI_AGENTE VARCHAR
  }
  TMP_CAPACIDAD_DE_ATENCION {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    TIPO_GESTION VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    PRONOSTICO VARCHAR
  }
  TMP_CARGA_AGENTES_VENTAS_CROSS_RECEPTIVOS {
    DNI_ASESOR VARCHAR
    SOCIO VARCHAR
    PERIODO VARCHAR
    CANAL_CALCULADO VARCHAR
    FUNCION VARCHAR
    FUENTE VARCHAR
  }
  TMP_CARGA_FRAUDE_CERTIFICADO_FIJA {
    codigo VARCHAR
    fecha_registro VARCHAR
    monto_ajustado VARCHAR
    usuario VARCHAR
  }
  TMP_CARGA_FRAUDE_CERTIFICADO_FIJA_RECLAMOS {
    registro_fecha VARCHAR
    montoreclamado VARCHAR
    registro_apenom VARCHAR
    reclamo_numero VARCHAR
  }
  TMP_CARGA_FRAUDE_CERTIFICADO_MOVIL {
    casonumero VARCHAR
    casoreguladorid INT
    usuario VARCHAR
    enviado_a VARCHAR
    estado VARCHAR
  }
  TMP_CARGA_FRAUDE_POSIBLE_FRAUDE {
    TIPO_DE_OPERACION VARCHAR
    CODIGO_RECLAMO VARCHAR
    DNI_RESPONSABLE_SOCIO VARCHAR
    NOMBRE_RESPONSABLE_SOCIO VARCHAR
    CANAL VARCHAR
    USUARIO_POSIBLE_FRAUDE VARCHAR
  }
  TMP_CARGA_FRAUDE_REVERTIDO_FIJA {
    codigo VARCHAR
    fecha_registro VARCHAR
    monto_ajustado VARCHAR
    usuario VARCHAR
    robot VARCHAR
    fecha_proceso VARCHAR
  }
  TMP_CARGA_FRAUDE_REVERTIDO_FIJA_RECLAMOS {
    registro_fecha VARCHAR
    montoreclamado VARCHAR
    registro_apenom VARCHAR
    reclamo_numero VARCHAR
    respuesta VARCHAR
    fecha_proceso VARCHAR
  }
  TMP_CARGA_FRAUDE_REVERTIDO_MOVIL {
    casonumero VARCHAR
    casoreguladorid INT
    usuario VARCHAR
    respuesta VARCHAR
    REVISION_FECHA_PROCESO VARCHAR
    id_factura INT
  }
  TMP_CCEE_CULPABLES_REITERACIONES {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    OPERATOR_ROLE VARCHAR
    CLI_UNICOS VARCHAR
  }
  TMP_CCEE_CULPABLES_REITERACIONES_DIARIO {
    FECHA VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    OPERATOR_ROLE VARCHAR
    CLI_UNICOS VARCHAR
  }
  TMP_CONTACT_RATE {
    TELEFONO VARCHAR
    DNI VARCHAR
    ETIQUETA_1 VARCHAR
    ETIQUETA_2 VARCHAR
    ETIQUETA_3 VARCHAR
    ETIQUETA_4 VARCHAR
  }
  TMP_CRONOGRAMA_INGRESOS {
    Proveedor VARCHAR
    NEGOCIO VARCHAR
    Codigo_Grupo VARCHAR
    PLATAFORMA VARCHAR
    Proveedor_LOCAL VARCHAR
    Origen_Recursos VARCHAR
  }
  TMP_CRONOGRAMA_INGRESOS_INTEGRATEL {
    Proveedor VARCHAR
    NEGOCIO VARCHAR
    Codigo_Grupo VARCHAR
    PLATAFORMA VARCHAR
    MOTIVO VARCHAR
    Fecha_OJT_Inicial_PROYECTADO VARCHAR
  }
  TMP_CRONOGRAMA_INGRESOS_SOCIOS {
    Proveedor VARCHAR
    NEGOCIO VARCHAR
    Codigo_Grupo VARCHAR
    PLATAFORMA VARCHAR
    MOTIVO VARCHAR
    Fecha_OJT_Inicial_PROYECTADO VARCHAR
  }
  TMP_CROSS_CCEE {
    FECHA VARCHAR
    LINK_BOTMAKER VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI_AGENTE VARCHAR
    NUMERO_GESTION VARCHAR
  }
  TMP_CROSS_CCEE2 {
    FECHA VARCHAR
    LINK_BOTMAKER VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI_AGENTE VARCHAR
    NUMERO_GESTION VARCHAR
  }
  TMP_CROSS_CCEE3 {
    ID INT
    DNI_Cliente_Titular VARCHAR
    Nombre_Cliente_Titular VARCHAR
    Email_Cliente_Titular VARCHAR
    DNI_Vendedor VARCHAR
    Usuario_Vendedor VARCHAR
  }
  TMP_CROSS_TODAS_CAMP {
    ID INT
    DNI_Cliente_Titular VARCHAR
    Nombre_Cliente_Titular VARCHAR
    Email_Cliente_Titular VARCHAR
    DNI_Vendedor VARCHAR
    Usuario_Vendedor VARCHAR
  }
  TMP_CROSS_VOZ {
    ID INT
    Hora VARCHAR
    Hora VARCHAR
    Correo VARCHAR
    Nombre VARCHAR
    AGENTE VARCHAR
  }
  TMP_CROSS_VOZ_0 {
    ID INT
    Start_time VARCHAR
    Completion_time VARCHAR
    Email VARCHAR
    Nombre VARCHAR
    CENTRO VARCHAR
  }
  TMP_CROSS_VOZ_ADSL {
    ID INT
    Start VARCHAR
    Completion VARCHAR
    Email VARCHAR
    Name VARCHAR
    TECNOLOGIA VARCHAR
  }
  TMP_CROSS_VOZ_nuevo {
    ID INT
    Start_time VARCHAR
    Completion_time VARCHAR
    Email VARCHAR
    Name VARCHAR
    Socio VARCHAR
  }
  TMP_CRUCE_POTENCIALES_CCEE {
    DIA VARCHAR
    FECHA VARCHAR
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    FLAG_CRITICO VARCHAR
    FECHA_ACTUALIZACION VARCHAR
  }
  TMP_CRUCE_POTENCIALES_LLAMADAS {
    DIA VARCHAR
    FECHA VARCHAR
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    FLAG_CRITICO VARCHAR
    FECHA_ACTUALIZACION VARCHAR
  }
  TMP_CUOTAS_DETALLE_CROSS_CALL_CENTER {
    PERIODO VARCHAR
    TIPO VARCHAR
    PROVEEDOR VARCHAR
    CANAL VARCHAR
    PRODUCTO VARCHAR
    SUB_PRODUCTO VARCHAR
  }
  TMP_ENCUESTAS_MEDALLIA_CHECA_TU_CASO {
    CODIGO_DE_PROBLEMA VARCHAR
    USUARIO_FINAL_APELLIDOS_NOMBRES INT
    NUMERO_DE_DOCUMENTO_DE_IDENTIDAD_USUARIO_FINAL INT
    NUMERO_DE_DOCUMENTO_DE_IDENTIDAD_DEL_ABONADO_REPRESENTANTE INT
    NOMBRE_ABONADO_REPRESENTATE_LEGAL VARCHAR
    NUMERO_DE_SERVICIO VARCHAR
  }
  TMP_ENCUESTAS_MEDALLIA_ESPECIALIZADOS {
    POSI_CORRELATIVO VARCHAR
    POSV_DNI VARCHAR
    POSV_TELEFONO VARCHAR
    POSV_CORREO VARCHAR
    POSV_TELEFONO_CONTACTO VARCHAR
    POSV_EMB_NOMBRE VARCHAR
  }
  TMP_EVOLUTIVO_MOTIVOS_PT {
    TELEFONO_CONSOLIDADO INT
    IVR_CONNID INT
    GRUPO_PLATAFORMA VARCHAR
    PERIODO1 VARCHAR
    PERIODO2 VARCHAR
    PERIODO3 VARCHAR
  }
  TMP_FACTURACION_CONTINGENCIA_BO_OTROS {
    AGRUPACION VARCHAR
    DETALLE VARCHAR
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    ATENDIDAS INT
  }
  TMP_FACTURACION_CONTINGENCIA_CCEE {
    AGRUPACION VARCHAR
    DETALLE VARCHAR
    MES VARCHAR
    SERVICIO VARCHAR
    SOCIO VARCHAR
    HORA VARCHAR
  }
  TMP_FACTURACION_CONTINGENCIA_VOZ {
    AGRUPACION VARCHAR
    DETALLE VARCHAR
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    LLAMADAS_ATENDIDAS INT
  }
  TMP_FACTURACION_COR {
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    NEGOCIO VARCHAR
    MODELO_REMUNERATIVO VARCHAR
    FECHA VARCHAR
  }
  TMP_FACTURACION_FACTOR_DESEMPENIO {
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    FACTOR_DESEMPENIO VARCHAR
  }
  TMP_FACTURACION_PECUF_PECNEG {
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    MODELO_REMUNERATIVO VARCHAR
    PECUF VARCHAR
    PECNEG VARCHAR
  }
  TMP_FACTURACION_SATISFACCION {
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    MODELO_REMUNERATIVO VARCHAR
    CANTIDAD_BUENAS INT
    CANTIDAD_REGULAR INT
  }
  TMP_FACTURACION_TOPE_NPS_1_2 {
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    TOPE_NPS_1_2 VARCHAR
  }
  TMP_FACTURACION_USO_GENIO {
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    USO_GENIO VARCHAR
  }
  TMP_FIBRA_CROSS_CALL {
    ID INT
    Hora VARCHAR
    Hora VARCHAR
    Correo VARCHAR
    Nombre VARCHAR
    AGENTE VARCHAR
  }
  TMP_FORMULARIO_RECLAMOS {
    FLAG VARCHAR
    CONJUNTO_DE_ESCENARIO VARCHAR
    CONJUNTO_TRANSACCION VARCHAR
    RESUMEN_RECLAMOS VARCHAR
    RECLAMO_FIJA VARCHAR
    RECLAMO_MOVIL VARCHAR
  }
  TMP_GENERACION_MALLAS_DH {
    MES VARCHAR
    NEGOCIO VARCHAR
    CALL VARCHAR
    PLATAFORMA VARCHAR
    INTERVALO VARCHAR
    LUNES VARCHAR
  }
  TMP_GENERACION_MALLAS_PP {
    MES VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    ATENTO VARCHAR
    COMDATA VARCHAR
    GSS VARCHAR
  }
  TMP_HP_DESPLIEGUE {
    DNI VARCHAR
    NOTA VARCHAR
  }
  TMP_HP_DETALLE_INTERACCIONES_EXPORTADO {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    PERIODO_SESION VARCHAR
    FECHA_HORA_SESION VARCHAR
    FECHA_SESION VARCHAR
    PERIODO_INTERACCION VARCHAR
  }
  TMP_ID_OPERADORES_RRSS {
    PERIODO_SESION VARCHAR
    ID_OPERADOR INT
    GRUPO_PLATAFORMA VARCHAR
    PLATAFORMA VARCHAR
  }
  TMP_INTERACCIONES_POTENCIALES_TODAS_LAS_CAMPANIAS {
    PERIODO VARCHAR
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    FECHA_HORA_SESION VARCHAR
    FECHA_HORA VARCHAR
    ENTIDAD INT
  }
  TMP_LISTA_AGENTES_GENESYS {
    CENTRO VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    APELLIDOS_NOMBRES INT
    SUPERVISOR VARCHAR
  }
  TMP_LISTA_RELLAMADORES {
    TELEFONO VARCHAR
    GRABACION VARCHAR
    MOTIVO_BLOQUEO VARCHAR
  }
  TMP_LLAMADAS_POTENCIALES_TODAS_LAS_CAMPANIAS {
    PERIODO VARCHAR
    TELEFONO_CONSULTA VARCHAR
    TELEFONO_LLAMANTE VARCHAR
    TELEFONO_CONSOLIDADO INT
    NUMERO_DOCUMENTO VARCHAR
    TMO VARCHAR
  }
  TMP_MALLAS_AGENTES {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    SITIO VARCHAR
    DNI VARCHAR
    NOMBRES VARCHAR
  }
  TMP_MALLAS_PROVEEDOR {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    HORA VARCHAR
    VALOR_AGENTES VARCHAR
  }
  TMP_MALLLAS_TDP {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    HORA VARCHAR
    TMO VARCHAR
  }
  TMP_OBSERVACIONES_CARGAS {
    OBSERVACIONES VARCHAR
    CANTIDAD INT
  }
  TMP_OBSERVACIONES_CARGAS_CRONOGRAMA {
    OBSERVACIONES VARCHAR
    CANTIDAD INT
  }
  TMP_OBSERVACIONES_REPROCESO_KIPU {
    OBSERVACIONES VARCHAR
    CANTIDAD INT
  }
  TMP_ORIGEN_VENTA_CHECA_TU_CASO {
    CODIGO VARCHAR
    USUARIO VARCHAR
    FECHA VARCHAR
    TIPO VARCHAR
    NUMERO VARCHAR
    NOMBRE VARCHAR
  }
  TMP_PECUF_PECNEG {
    Segmento VARCHAR
    Plataforma VARCHAR
    Sub_Plataforma VARCHAR
    Documento VARCHAR
    Apellidos_y_Nombres INT
    Coordinador VARCHAR
  }
  TMP_PLANILLAS_PPP_DIAS {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    FECHA VARCHAR
    INTERVALO VARCHAR
    REQUERIDOS_PROYECTADOS INT
  }
  TMP_PLANILLAS_PPP_MESES {
    indicador VARCHAR
    canal VARCHAR
    proveedor VARCHAR
    annio VARCHAR
    mes VARCHAR
    plataforma VARCHAR
  }
  TMP_PLANILLAS_PPP_SEMANAS {
    NEGOCIO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    SITE VARCHAR
    CONEXION VARCHAR
    SEMANA VARCHAR
  }
  TMP_POTENCIALES_FIBRA_BEA {
    DIA VARCHAR
    FECHA VARCHAR
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    FLAG_CRITICO VARCHAR
    FECHA_ACTUALIZACION VARCHAR
  }
  TMP_PREVENTAS_CAPL {
    cod_solicitud VARCHAR
    servicio VARCHAR
    telefono VARCHAR
    fecha_solicitud VARCHAR
    resultado VARCHAR
    oferta_elegida INT
  }
  TMP_PREVENTAS_RECEPTIVOS_CCEE {
    ID INT
    Fecha VARCHAR
    Hora VARCHAR
    Gestión VARCHAR
    Plataforma VARCHAR
    Atención VARCHAR
  }
  TMP_PREVENTAS_VOZ {
    ID INT
    DNI_Cliente_Titular VARCHAR
    Nombre_Cliente_Titular VARCHAR
    Email_Cliente_Titular VARCHAR
    DNI_Vendedor VARCHAR
    Usuario_Vendedor VARCHAR
  }
  TMP_PROCESOS_NO_RESOLUTIVOS_VISTA_PROCEDIMIENTOS_QUEBRADOS {
    SUB_CANAL VARCHAR
    NUMERO_GESTION VARCHAR
    PROCEDIMIENTO VARCHAR
    ESTATUS VARCHAR
    MES VARCHAR
    ANIO VARCHAR
  }
  TMP_RANKING_MASTER {
    periodo VARCHAR
    proveedor VARCHAR
    plataforma VARCHAR
    DNI VARCHAR
    CASOS_ATENDIDOS INT
    tiempo_login VARCHAR
  }
  TMP_RANKING_PROVEDORES {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    NPS VARCHAR
    SOLUCION VARCHAR
    RELLAMADAS VARCHAR
    TRANSFERENCIAS VARCHAR
  }
  TMP_RC_CROSS_POTENCIAL_FIBRA_RES {
    DIA VARCHAR
    FECHA VARCHAR
    TELEFONO VARCHAR
    DOCUMENTO VARCHAR
    FLAG_CRITICO VARCHAR
    FECHA_ACTUALIZACION VARCHAR
  }
  TMP_REASIGNACION_RECLAMOS {
    DNI_CLIENTE VARCHAR
    TELEFONO VARCHAR
    RUC VARCHAR
    NUMERO_RECLAMO VARCHAR
    Tx_ClienteTitular VARCHAR
  }
  TMP_REDUCTORES {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    Aus_Lunes VARCHAR
    Aus_Martes VARCHAR
    Aus_Miercoles VARCHAR
  }
  TMP_RELLAMADORES_SEMANAL_PT {
    IVR_CONNID INT
    FECHA_LLAMADA VARCHAR
    ANIO VARCHAR
    MES VARCHAR
    SEMANA VARCHAR
    TELEFONO VARCHAR
  }
  TMP_REPORTE_FIBRA_CROSS_GLOBAL {
    DIA VARCHAR
    ORDEN VARCHAR
    REPORTE VARCHAR
    TOTAL VARCHAR
  }
  TMP_REPORTE_FIBRA_CROSS_SEMANAL_GLOBAL {
    SEMANA VARCHAR
    ORDEN VARCHAR
    REPORTE VARCHAR
    TOTAL VARCHAR
    PERIODO VARCHAR
  }
  TMP_REPORTE_FORMACION {
    DNI VARCHAR
    NOMBRES VARCHAR
    APELLIDOS INT
    ESTADO VARCHAR
    CANAL VARCHAR
    CARGO VARCHAR
  }
  TMP_REPORTE_FORMACION_LIDER {
    DNI VARCHAR
    NOMBRES VARCHAR
    APELLIDOS INT
    ESTADO VARCHAR
    CANAL VARCHAR
    CARGO VARCHAR
  }
  TMP_REPORTE_FORMACION_OJT_CCEE {
    SOCIO VARCHAR
    SKILL VARCHAR
    GRUPO VARCHAR
    FORMADOR VARCHAR
    DNI VARCHAR
    AGENTE VARCHAR
  }
  TMP_RESUMEN_INDIC_GENERALES_CCEE_TODAY {
    SESSION_ID INT
    INTERACTION_ORDER VARCHAR
    INTERACTION_ID INT
    INTERACTION_ID_ORIGEN INT
    INTERACTION_ID_DESTINO INT
    PERIODO VARCHAR
  }
  TMP_RESUMEN_INDIC_GENERALES_VOZ_TODAY {
    PERIODO VARCHAR
    CELULAR VARCHAR
    TELEFONO_FIJO VARCHAR
    CODIGO_CLIENTE VARCHAR
    CODIGO_CUENTA VARCHAR
    CODIGO_INSCRIPCION VARCHAR
  }
  TMP_RETENCIONES_CAMPANIAS_OUT {
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    TIPO_MARCACION VARCHAR
    BASE VARCHAR
    EFECTIVIDAD INT
  }
  TMP_RETENCIONES_CUARTIL_AGENTES {
    ANIO VARCHAR
    MES VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    Q_EFECT VARCHAR
  }
  TMP_RETENCIONES_FEEDBACK {
    PRV_ID_PROVEE INT
    TCNTEL VARCHAR
    FEC_1ERA_LLAM VARCHAR
    FECHA_LLAMADA VARCHAR
    INTENTOS VARCHAR
    COD_RESUL_LLAM VARCHAR
  }
  TMP_SEMANAL_VISTA_MOTIVO_2 {
    PERIODO_ORIGEN VARCHAR
    MOTIVO_ORIGEN VARCHAR
    SUB_MOTIVO_ORIGEN VARCHAR
    TELEFONO_CONSOLIDADO INT
    ENTRANTES_ORIGEN VARCHAR
    PERIODO_DESTINO1 VARCHAR
  }
  TMP_TMO_PAGO {
    PERIODO VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    TMO_PAGO VARCHAR
    TMO_PROPUESTO VARCHAR
  }
  TMP_USUARIOS_CAPL {
    DNI VARCHAR
    NOMBRES VARCHAR
    CARGO VARCHAR
    FECHA_INICIO VARCHAR
    VISOR_TOBE VARCHAR
    VISOR_ASIS VARCHAR
  }
  TMP_USUARIOS_GENIO {
    DNI VARCHAR
    NOMBRES VARCHAR
    APELLIDOS INT
    CARGO VARCHAR
    SOCIO VARCHAR
    REGIÓN VARCHAR
  }
  TMP_USUARIOS_RECLAMOS {
    ASESOR_DNI VARCHAR
    ASESOR_NOMBRE_APELLIDO INT
    USUARIO_SISTEMA_FENIX VARCHAR
    USUARIO_SISTEMA_CMS VARCHAR
    USUARIO_SISTEMA_ATIS VARCHAR
    USUARIO_SISTEMA_WEB_SOLUCIONES VARCHAR
  }
  TMP_USUARIO_JOHANA {
    ASESOR VARCHAR
    CANAL VARCHAR
    AREA VARCHAR
    SUB_AREA VARCHAR
    SITE VARCHAR
    SUPERVISOR_DEL_ASESOR VARCHAR
  }
  TMP_VENTAS_2DA_LINEA_CROSS_CCEE {
    Fecha VARCHAR
    Intencion VARCHAR
    N_De_Telefono_Entrada VARCHAR
    N_De_Telefono_Gestin VARCHAR
    Conn_ID INT
    Motivo VARCHAR
  }
  TMP_V_CCEE_CULPABLES_REITERACIONES {
    FECHA VARCHAR
    PLATAFORMA VARCHAR
    EMAIL_OPERADOR VARCHAR
    DOCUMENTO_OPERADOR VARCHAR
    ID_OPERADOR INT
    PROVEEDOR VARCHAR
  }
  T_DIM_PLATAFORMA_CANAL_OUT {
    PLATAF_ID INT
    PLATAF_DESCRIPCION VARCHAR
    PLATAF_ESTADO VARCHAR
    PLATAF_FACTURACION VARCHAR
    JREM_ID INT
    TIPO_PAGO VARCHAR
  }
  T_EXAMEN_RANKING_AGENTES_CCEE {
    DNI VARCHAR
    Nota VARCHAR
    Nota VARCHAR
    Nota VARCHAR
    Nota VARCHAR
    Nota VARCHAR
  }
  T_METAS_RANKING_AGENTES_CCEE {
    meta VARCHAR
    valor_meta VARCHAR
    periodo VARCHAR
    PESO VARCHAR
  }
  T_MTA_RANKING_AGENTES_CCEE {
    DNI VARCHAR
    Q VARCHAR
    PERIODO VARCHAR
  }
  Temp_jss_AVERIAS_POR_ASESOR_backup {
    PERIODO VARCHAR
    FECHA_REGISTRO VARCHAR
    DNI_AGENTE VARCHAR
    TOTAL_AVERIAS VARCHAR
    TOTAL_AVERIAS_INDIVIDUAL INT
    TOTAL_AVERIAS_CANCELADAS VARCHAR
  }
  USUARIOS_CAPL_VISOR {
    DNI VARCHAR
    NOMBRES VARCHAR
    CARGO VARCHAR
    FECHA_INICIO VARCHAR
    VISOR_TOBE VARCHAR
    VISOR_ASIS VARCHAR
  }
  USUARIOS_RECLAMOS_AREAS {
    AREAREC_ID INT
    AREAREC_NOMBRE_COMPLETO_AREA VARCHAR
    AREAREC_ESTADO VARCHAR
    AREAREC_RESPONSABLE_CANAL VARCHAR
    AREAREC_FECHA_CAMBIO VARCHAR
  }
  USUARIOS_RECLAMOS_HISTORICO {
    ASESOR_DNI VARCHAR
    ASESOR_NOMBRE_APELLIDO INT
    USUARIO_SISTEMA_FENIX VARCHAR
    USUARIO_SISTEMA_CMS VARCHAR
    USUARIO_SISTEMA_ATIS VARCHAR
    USUARIO_SISTEMA_WEB_SOLUCIONES VARCHAR
  }
  USUARIOS_RECLAMOS_LISTA_INVALIDOS {
    USUARIO_INVALIDO INT
  }
  USUARIOS_RECLAMOS_ULT_ACT {
    ASESOR_DNI VARCHAR
    ASESOR_NOMBRE_APELLIDO INT
    USUARIO_SISTEMA_FENIX VARCHAR
    USUARIO_SISTEMA_CMS VARCHAR
    USUARIO_SISTEMA_ATIS VARCHAR
    USUARIO_SISTEMA_WEB_SOLUCIONES VARCHAR
  }
  aa_MallasProveedor {
    Negocio VARCHAR
    Call VARCHAR
    Plataforma VARCHAR
    Fecha VARCHAR
    Intervalo VARCHAR
    Agentes VARCHAR
  }
  aa_MallasTDP {
    Negocio VARCHAR
    Call VARCHAR
    Plataforma VARCHAR
    Fecha VARCHAR
    Intervalo VARCHAR
    TMO VARCHAR
  }
  agentes {
    YYYY VARCHAR
    MM VARCHAR
    OPERACION VARCHAR
    SEGMENTACION VARCHAR
    CENTRO VARCHAR
    FECHA VARCHAR
  }
  agentes_capacitados_blending {
    SOCIO VARCHAR
    NOMBRE VARCHAR
    DNI VARCHAR
    CORREO VARCHAR
    FECHA VARCHAR
  }
  am_temp_fibra_voz {
    ID INT
    Start_time VARCHAR
    Completion_time VARCHAR
    Email VARCHAR
    Nombre VARCHAR
    TIPO_DE_GESTION_COMDATA VARCHAR
  }
  ccee_cross {
    MARCA VARCHAR
    LINK VARCHAR
    PROVEEDOR VARCHAR
    PLATAFORMA VARCHAR
    DNI VARCHAR
    NRO VARCHAR
  }
  niveles {
    YYYY VARCHAR
    MM VARCHAR
    SEMANA VARCHAR
    OPERACION VARCHAR
    CENTRO VARCHAR
    SEGMENTACION VARCHAR
  }
  nueva_tmp {
    FECHA VARCHAR
    SEMANA VARCHAR
    HORA VARCHAR
    MARCA VARCHAR
    LINK VARCHAR
    PROVEEDOR VARCHAR
  }
  plataforma_felipe {
    REGION VARCHAR
    PLATAFORMA VARCHAR
    GESTION VARCHAR
    PROVEEDOR VARCHAR
    SITE VARCHAR
    TIPO VARCHAR
  }
  plataformas_cro {
    REGION VARCHAR
    PLATAFORMA VARCHAR
    GESTION VARCHAR
    PROVEEDOR VARCHAR
    SITE VARCHAR
    TIPO VARCHAR
  }
  prevision {
    FECHA VARCHAR
    OPERACION VARCHAR
    CENTRO VARCHAR
    SEGMENTACION VARCHAR
    YYYY VARCHAR
    MM VARCHAR
  }
  sysdiagrams {
    name VARCHAR
    principal_id INT
    diagram_id INT
    version VARCHAR
    definition VARCHAR
  }
  tbilllog_idicadores {
    PARTID INT
    CALLID INT
    CALLIDNUM INT
    CALLERNO VARCHAR
    CALLEENO VARCHAR
    WAITBEGIN VARCHAR
  }
  temp {
    partname VARCHAR
    manufacturer VARCHAR
    quality VARCHAR
    price VARCHAR
  }
  temp_incidencias_corregidas {
    ID INT
    IDENTIFICADOR INT
    FECHA_APERTURA VARCHAR
    AREA_APERTURA VARCHAR
    USUARIO_APERTURA VARCHAR
    TICKET VARCHAR
  }
  temporal_cross {
    ID INT
    Hora VARCHAR
    Hora VARCHAR
    Correo VARCHAR
    Nombre VARCHAR
    AGENTE VARCHAR
  }
  tmo {
    CENTRO VARCHAR
    SEGMENTACION VARCHAR
    MACRO_SEGMENTOS_TABLEROS VARCHAR
    YYYY VARCHAR
    MM VARCHAR
    DD VARCHAR
  }
  tmp_carga_fibra {
    Hora VARCHAR
    Hora VARCHAR
    Correo VARCHAR
    AGENTE VARCHAR
    ANI VARCHAR
    ANI VARCHAR
  }
  ventas_fibra_cross_octubre {
    FECHA VARCHAR
    SEMANA VARCHAR
    HORA VARCHAR
    MARCA VARCHAR
    LINK VARCHAR
    PROVEEDOR VARCHAR
  }
