erDiagram
  JG_DITO {
    MES VARCHAR
    DNI VARCHAR
  }
  LD_VISTA_RESUMEN_INPUT_PARA_COMITE_FUNCIONAMIENTO_TEC {
    MES VARCHAR
    CANTIDADES INT
    CLIENTES VARCHAR
    CANAL VARCHAR
    KPI VARCHAR
  }
  TEMP_REPORTE_SOLUCION {
    FECHA VARCHAR
    HORA VARCHAR
    ANI VARCHAR
    NAC VARCHAR
    NUMGESTION VARCHAR
  }
  TTR_AGENTES_OD {
    ID_TRANS INT
    FECHA VARCHAR
    DNI_AGENTE VARCHAR
    PROGRAMA_ORIGEN VARCHAR
    PROGRAMA_DESTINO VARCHAR
    CALL_CENTRO VARCHAR
  }
  TTR_AGENTES_ORI_DEST_VF {
    FECHA_INICIO VARCHAR
    CDN_ORIGEN VARCHAR
    PROGRAMA_ORIGEN VARCHAR
    CALL_CENTER_ORIGEN VARCHAR
    AGENTE_ORIGEN VARCHAR
    FECHA_DESTINO VARCHAR
  }
  TTR_ATENDIDAS_RESUMEN {
    ID_ATEND INT
    FECHA VARCHAR
    PROGRAMA_DESTINO VARCHAR
    ATENDIDAS INT
  }
  TTR_GRUPO_REITERACION {
    ID INT
    FECHA VARCHAR
    PROGRAMA VARCHAR
    GRUPO_REITERACION VARCHAR
    CANTIDAD_REITERACION INT
    ATENDIDAS INT
  }
  TTR_INDICADOR_REITERADAS_RESUMEN {
    ID_REIT INT
    FECHA VARCHAR
    PROGRAMA VARCHAR
    ATENDIDAS INT
    REITERADAS VARCHAR
  }
  TTR_INDICADOR_TRANSFERENCIA_RESUMEN {
    ID_TRANS INT
    FECHA VARCHAR
    PROGRAMA_ORIGEN VARCHAR
    ATENDIDAS INT
    CANT_TRANS VARCHAR
  }
  TTR_TRANSFERENCIAS_RESUMEN {
    ID_TRANS INT
    FECHA VARCHAR
    CENTRO_ORIGEN VARCHAR
    CENTRO_DESTINO VARCHAR
    CDN_ORIGEN VARCHAR
    CDN_DESTINO VARCHAR
  }
  T_AGEN_ORI_DEST_MISMO_RP {
    FECHA_INICIO VARCHAR
    RP_ORIGEN VARCHAR
    CDN_ORIGEN VARCHAR
    PROGRAMA_ORIGEN VARCHAR
    CALL_CENTER_ORIGEN VARCHAR
    AGENTE_ORIGEN VARCHAR
  }
  T_BASE_LLAM_IMPACTO_IVR {
    FECHA VARCHAR
    HORA VARCHAR
    BASE VARCHAR
    LLAMADAS_IVR VARCHAR
    LLAMADAS_OPERADOR VARCHAR
  }
  T_BASE_LLAM_IMPACTO_IVR_V2 {
    FECHA VARCHAR
    HORA VARCHAR
    BASE VARCHAR
    LLAMADAS_IVR VARCHAR
    LLAMADAS_OPERADOR VARCHAR
  }
  T_CATALOGO_DET_EXPERIENCIA_RADAR {
    MOVIL_FIJA VARCHAR
    PRODUCTO VARCHAR
    RESPONSABLE VARCHAR
    CONTACTO VARCHAR
    EXPERIENCIA VARCHAR
    DETALLE VARCHAR
  }
  T_CLIENTES_NOTA_15DIAS {
    TELEFONO VARCHAR
    NOTA_SATISFACCION VARCHAR
  }
  T_DETALLE_AGENT_SUMMARY {
    AgentName VARCHAR
    FechaHora VARCHAR
    ActiveTime VARCHAR
    ReadyTime VARCHAR
    NotReadyTime VARCHAR
    BusyTime VARCHAR
  }
  T_DETALLE_INFOMART_ULT7DIAS {
    From VARCHAR
    Handling VARCHAR
    Last VARCHAR
    NAC_IVR VARCHAR
    NAC_Desktop VARCHAR
    CALL_RETRY_1 VARCHAR
  }
  T_DETALLE_ONEMARKETER {
    Id_Caso INT
    Operador_Abre VARCHAR
    Servicio VARCHAR
    Operador_Cierre VARCHAR
    Id_usuario INT
    Evento VARCHAR
  }
  T_INDICADORES_REGULADOS {
    MARCACION_IVR VARCHAR
    Service VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    DIA VARCHAR
    NEGOCIO VARCHAR
    GRUPO_RO VARCHAR
  }
  T_LD_EVOLUTIVO_TRAFICO_POR_SERVICE_SUBTYPE {
    DIA VARCHAR
    MES VARCHAR
    SERVICE VARCHAR
    PLATAF_DESCRIPCION VARCHAR
    Q_ENTRANTES VARCHAR
  }
  T_LD_FLUJO_CLIENTES_DEGRADADOS {
    FECHA VARCHAR
    SEGMENTO VARCHAR
    CLIENTES_BASE VARCHAR
  }
  T_LD_FLUJO_CLIENTES_DEGRADADOS_ATENDIDAS {
    FECHA VARCHAR
    CLIENTES_ATENDIDOS INT
    PLATAFORMA VARCHAR
    SEGMENTO VARCHAR
  }
  T_LD_FLUJO_CLIENTES_DEGRADADOS_ENTRANTES {
    FECHA VARCHAR
    CLIENTES_ENTRANTES VARCHAR
    PLATAFORMA VARCHAR
    SEGMENTO VARCHAR
  }
  T_LD_FLUJO_CLIENTES_DEGRADADOS_ENTRANTES_ATENDIDAS {
    FECHA VARCHAR
    CLIENTES_ENTRANTES VARCHAR
    PLATAFORMA VARCHAR
    SEGMENTO VARCHAR
    CLIENTES_ATENDIDOS INT
  }
  T_LD_FLUJO_CLIENTES_DEGRADADOS_TOTAL {
    FECHA VARCHAR
    SEGMENTO VARCHAR
    CLIENTES_BASE VARCHAR
    PLATAFORMA VARCHAR
    CLIENTES_ENTRANTES VARCHAR
    CLIENTES_ATENDIDOS INT
  }
  T_LD_REPORTE_METRICAS_RECURRENTES_TEC_FIJO {
    ANIO VARCHAR
    MES VARCHAR
    Q_CLIENTES_UNICOS VARCHAR
    NEGOCIO VARCHAR
    Q_ENTRANTES VARCHAR
  }
  T_LD_RESUMEN_ENTR_Y_CLI_UNICOS_X_PLATAFORMA {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    PLATAFORMA VARCHAR
    LLAMADAS_ATENDIDAS INT
    LLAMADAS_ENTRANTES VARCHAR
  }
  T_LD_RESUMEN_VISTA_POR_CASOS_DE_USO_AURA {
    ANIO_NUM VARCHAR
    MES_NUM VARCHAR
    DIA_NUM VARCHAR
    NOMBRE_MES VARCHAR
    NEGOCIO VARCHAR
    CASO_DE_USO VARCHAR
  }
  T_LISTA_CTI_COPC_V1 {
    COPC_NEGOCIO VARCHAR
    COPC_FECHA VARCHAR
    COPC_CALL VARCHAR
    COPC_CTI VARCHAR
    COPC_TOTAL_ATENDIDAS INT
    COPC_TMO_ATENDIDAS INT
  }
  T_LISTA_CTI_COPC_V1_72HR {
    COPC_NEGOCIO VARCHAR
    COPC_FECHA VARCHAR
    COPC_CALL VARCHAR
    COPC_CTI VARCHAR
    COPC_TOTAL_ATENDIDAS INT
    COPC_TOTAL_TMO VARCHAR
  }
  T_LISTA_CTI_COPC_V1_72HR_DIARIO {
    COPC_NEGOCIO VARCHAR
    COPC_FECHA VARCHAR
    COPC_CALL VARCHAR
    COPC_CTI VARCHAR
    COPC_TOTAL_ATENDIDAS INT
    COPC_TMO_ATENDIDAS INT
  }
  T_LISTA_TELEFONOS_UNICOS_COPC_V1 {
    COPC_NEGOCIO VARCHAR
    COPC_FECHA VARCHAR
    COPC_PROGRAMA VARCHAR
    COPC_TOTAL_LLAMADAS VARCHAR
    COPC_TOTAL_CLIENTES VARCHAR
  }
  T_METRICAS_RECURRENTES_FUNCIONAMIENTO_CALL_CENTER {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    FECHA VARCHAR
    SEMANA VARCHAR
    Q_CLIENTES_UNICOS VARCHAR
  }
  T_REITERADORES_CRONICOS {
    ANI VARCHAR
    MES VARCHAR
    PLATAFORMA VARCHAR
    LLAMADAS VARCHAR
    PROM_NOTA_SATIS VARCHAR
  }
  T_REPORTE_SEMANAS {
    SEMANAS VARCHAR
    FECHA_INICIO VARCHAR
    FECHA_FIN VARCHAR
  }
  T_REPORTE_SOLUCION {
    FECHA VARCHAR
    HORA VARCHAR
    ANI VARCHAR
    NAC VARCHAR
    NUMGESTION VARCHAR
  }
  T_RESUMEN_ABANDONO_REAL {
    FECHA VARCHAR
    AÑO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    PLATAFORMA VARCHAR
    CANT_ABANDONADAS_REAL VARCHAR
  }
  T_RESUMEN_CLIENTES_SUSPENDIDOS_MOVIL {
    NOMBRE_MES VARCHAR
    FECHA VARCHAR
    AÑO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
  }
  T_RESUMEN_CLIENTES_SUSPENDIDOS_MOVIL_2 {
    NOMBRE_MES VARCHAR
    FECHA VARCHAR
    AÑO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
  }
  T_RESUMEN_CLIENTES_SUSPENDIDOS_MOVIL_ACCESOS {
    NOMBRE_MES VARCHAR
    FECHA VARCHAR
    AÑO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    HORA VARCHAR
  }
  T_RESUMEN_COPC_FILTROS_v4 {
    RNIR_FECHA_PROCESO VARCHAR
    RNIR_FECHA_INFORME VARCHAR
    RNIR_BASE_ANALISIS VARCHAR
    RNIR_AGRUPACION VARCHAR
    RNIR_VALOR VARCHAR
  }
  T_RESUMEN_COPC_FILTROS_v4_72HR {
    RNIR_FECHA_PROCESO VARCHAR
    RNIR_FECHA_INFORME VARCHAR
    RNIR_BASE_ANALISIS VARCHAR
    RNIR_AGRUPACION VARCHAR
    RNIR_VALOR VARCHAR
  }
  T_RESUMEN_COPC_ORIGEN_DESTINO_V1 {
    COPC_NEGOCIO VARCHAR
    COPC_PROGRAMA_ORIGEN VARCHAR
    COPC_PROGRAMA_DESTINO VARCHAR
    COPC_CALL_ORIGEN VARCHAR
    COPC_CALL_DESTINO VARCHAR
    COPC_SITE_ORIGEN VARCHAR
  }
  T_RESUMEN_COPC_ORIGEN_DESTINO_V1_72HR {
    COPC_NEGOCIO VARCHAR
    COPC_PROGRAMA_ORIGEN VARCHAR
    COPC_PROGRAMA_DESTINO VARCHAR
    COPC_CALL_ORIGEN VARCHAR
    COPC_CALL_DESTINO VARCHAR
    COPC_SITE_ORIGEN VARCHAR
  }
  T_RESUMEN_COPC_V1 {
    COPC_NEGOCIO VARCHAR
    COPC_VISTA VARCHAR
    COPC_MES VARCHAR
    COPC_SEMANA VARCHAR
    COPC_PROGRAMA VARCHAR
    COPC_CALL VARCHAR
  }
  T_RESUMEN_COPC_V1_72HR {
    COPC_NEGOCIO VARCHAR
    COPC_VISTA VARCHAR
    COPC_MES VARCHAR
    COPC_SEMANA VARCHAR
    COPC_PROGRAMA VARCHAR
    COPC_CALL VARCHAR
  }
  T_RESUMEN_KPIS_GERENCIALES {
    MES VARCHAR
    CALL_CENTER VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    GENERA VARCHAR
    ATENDIDAS INT
  }
  T_RESUMEN_KPIS_PET {
    MES VARCHAR
    CALL_CENTER VARCHAR
    PLATAF_DESCRIPCION VARCHAR
    NEGOCIO VARCHAR
    KPI VARCHAR
    VALOR VARCHAR
  }
  T_RESUMEN_KPIS_PET_SEMANALES {
    MES VARCHAR
    CALL_CENTER VARCHAR
    SEMANA VARCHAR
    PLATAF_DESCRIPCION VARCHAR
    NEGOCIO VARCHAR
    KPI VARCHAR
  }
  T_RESUMEN_KPIS_PET_SITE {
    MES VARCHAR
    CALL_CENTER VARCHAR
    SITE VARCHAR
    PLATAF_DESCRIPCION VARCHAR
    NEGOCIO VARCHAR
    KPI VARCHAR
  }
  T_RESUMEN_PLAN_DE_FUNCIONAMIENTO_CC_BLACK {
    PERIODO VARCHAR
    MES VARCHAR
    PLATAFORMA VARCHAR
    CANAL VARCHAR
    REITERADAS VARCHAR
    ATENDIDAS_FILTRADAS INT
  }
  T_RESUMEN_PLAN_DE_FUNCIONAMIENTO_CC_Y_CCEE {
    ANIO VARCHAR
    MES VARCHAR
    CANAL VARCHAR
    NEGOCIO VARCHAR
    DENOMINADOR VARCHAR
    NUMERADOR VARCHAR
  }
  T_RESUMEN_PLAN_DE_FUNCIONAMIENTO_CC_Y_CCEE_CLIENTES_UNICOS {
    ANIO VARCHAR
    MES VARCHAR
    CANAL VARCHAR
    NEGOCIO VARCHAR
    Q_CLIENTES_UNICOS VARCHAR
    KPI VARCHAR
  }
  T_RESUMEN_SEGMENTACION_IVR_V2 {
    RSIVR_FECHA VARCHAR
    RSIVR_EQUIVALENCIA VARCHAR
    RSIVR_PRODUCTO VARCHAR
    RSIVR_TIPO_CLIENTE VARCHAR
    RSIVR_TIPO_CLIENTE2 VARCHAR
    RSIVR_CANTIDAD INT
  }
  T_RESUMEN_TRAFICO_VENTAS_IN_MOVIL_FIJA {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    FECHA VARCHAR
    ROUTING_POINT VARCHAR
    ORIGEN_LLAMADA VARCHAR
  }
  T_RESUMEN_TRAFICO_VENTAS_IN_MOVIL_FIJA_BACKUP_NOBORRAR {
    ANIO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    FECHA VARCHAR
    ROUTING_POINT VARCHAR
    ORIGEN_LLAMADA VARCHAR
  }
  T_RES_CLI_UNICOS_VOZ_Y_CCEE {
    FECHA VARCHAR
    AÑO VARCHAR
    MES VARCHAR
    DIA VARCHAR
    CLIENTES_UNICOS VARCHAR
    CANAL VARCHAR
  }
  T_RPT_SOL_LLAMADA {
    TELEFONO_LLAMADA VARCHAR
    FECHA_SOLUCION VARCHAR
    HORA_SOLUCION VARCHAR
    FECHA_HORA_SOLUCION VARCHAR
    NAC_SOLUCION VARCHAR
    FECHA_HORA_LLAMADA VARCHAR
  }
  T_RPT_SOL_LLAMADA_RES {
    FECHA VARCHAR
    PLATAFORMA_SOLUCION VARCHAR
    SEGMENTO_SOLUCION VARCHAR
    PLATAFORMA_DESPUES VARCHAR
    SEGMENTO_DESPUES VARCHAR
    DIAS_LLAM_DESPUES VARCHAR
  }
  T_TABLA_ABANDONOS_CALL_CENTER {
    FECHA VARCHAR
    PLATAFORMA VARCHAR
    CANT_ABANDONOS_CLIENTE VARCHAR
    CANT_ABANDONOS_ASESOR VARCHAR
    CANT_ENTRANTES VARCHAR
  }
  T_TABLA_PETS_ABANDONADAS {
    MES VARCHAR
    CALL_CENTER VARCHAR
    PLATAF_DESCRIPCION VARCHAR
    NEGOCIO VARCHAR
    ABANDONADAS VARCHAR
    ENTRANTES VARCHAR
  }
  T_TABLA_PETS_ENTRANTES {
    MES VARCHAR
    CALL_CENTER VARCHAR
    PLATAF_DESCRIPCION VARCHAR
    NEGOCIO VARCHAR
    ENTRANTES VARCHAR
  }
  T_TEMPORAL_DETALLE_AGENT_SUMMARY {
    AgentName VARCHAR
    FechaHora VARCHAR
    ActiveTime VARCHAR
    ReadyTime VARCHAR
    NotReadyTime VARCHAR
    BusyTime VARCHAR
  }
  T_TEMPORAL_DETALLE_AGENT_SUMMARY_v2 {
    Agent VARCHAR
    Hour VARCHAR
    Active VARCHAR
    Ready VARCHAR
    Not VARCHAR
    Busy VARCHAR
  }
  T_TMP_DETALLE_INDIDENCIAS {
    FECHA VARCHAR
    TIPO_ATEN VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    TELEFONO VARCHAR
    CANTIDAD INT
  }
  T_TMP_DETALLE_INDIDENCIAS_V2 {
    FECHA VARCHAR
    TIPO_ATEN VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    TELEFONO VARCHAR
    CANTIDAD INT
  }
  T_TMP_INCIDENCIAS {
    FECHA VARCHAR
    HORA VARCHAR
    TIPO_ATEN VARCHAR
    PLATAFORMA VARCHAR
    BASE VARCHAR
    SISTEMA_COMERCIAL VARCHAR
  }
  T_TMP_INCIDENCIAS_V2 {
    FECHA VARCHAR
    HORA VARCHAR
    TIPO_ATEN VARCHAR
    PLATAFORMA VARCHAR
    BASE VARCHAR
    SISTEMA_COMERCIAL VARCHAR
  }
  T_TMP_KPIS_GERENCIALES {
    IND VARCHAR
    MES VARCHAR
    CALL_CENTER VARCHAR
    NEGOCIO VARCHAR
    PLATAFORMA VARCHAR
    GENERA VARCHAR
  }
  T_TMP_REPORTE_SOLUCION {
    FECHA VARCHAR
    HORA VARCHAR
    ANI VARCHAR
    NAC VARCHAR
    NUMGESTION VARCHAR
  }
  T_TMP_RPT_SOL_LLAMADA {
    TELEFONO_LLAMADA VARCHAR
    FECHA_SOLUCION VARCHAR
    HORA_SOLUCION VARCHAR
    FECHA_HORA_SOLUCION VARCHAR
    NAC_SOLUCION VARCHAR
    FECHA_HORA_LLAMADA VARCHAR
  }
  T_TMP_SUBMOTIVOS_INCIDENCIAS {
    FECHA VARCHAR
    BASE VARCHAR
    TELEFONO VARCHAR
    FUENTE VARCHAR
    MOTIVO VARCHAR
    SUBMOTIVO VARCHAR
  }
  T_TMP_SUBMOTIVOS_INCIDENCIAS_PREV {
    FECHA VARCHAR
    BASE VARCHAR
    TELEFONO VARCHAR
    FUENTE VARCHAR
    MOTIVO VARCHAR
    SUBMOTIVO VARCHAR
  }
  T_TMP_SUBMOTIVOS_INCIDENCIAS_PREV_V2 {
    FECHA VARCHAR
    BASE VARCHAR
    TELEFONO VARCHAR
    FUENTE VARCHAR
    MOTIVO VARCHAR
    SUBMOTIVO VARCHAR
  }
  T_VISTA_RESUMEN_TRAFICO_ROAMING {
    SEGMENTO VARCHAR
    MES VARCHAR
    LLAMADAS VARCHAR
    ANIO VARCHAR
  }
