erDiagram
  T_V2_REGULADOS_PW_202308 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202309 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202310 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202311 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202312 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202401 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202402 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202403 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202404 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202405 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202406 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202407 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202408 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202409 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202410 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
