erDiagram
  T1_1 {
    QUERY VARCHAR
  }
  T1_111 {
    QUERY VARCHAR
  }
  T_LISTADO_IVR {
    REG_GRUPO_IVR VARCHAR
    REG_NEGOCIO VARCHAR
  }
  T_LISTADO_IVR_VAL {
    REG_GRUPO_IVR VARCHAR
    REG_NEGOCIO VARCHAR
  }
  T_LISTADO_IVR_VAL_2 {
    REG_GRUPO_IVR VARCHAR
    REG_NEGOCIO VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202202_V2 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202307 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202308 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202309 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202310 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202311 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202312 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202401 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202402 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202403 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202404 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202405 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202406 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202407 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202408 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202409 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202410 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202411 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202412 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202501 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202502 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202503 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202504 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202505 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202506 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202507 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_REGULATORIO_LENGUAJE_NATURAL_202508 {
    CDR_START_DATETIME DATETIME
    CDR_SESSION_ID INT
    CDR_CALL_ID INT
    CDR_SITE VARCHAR
    CDR_TRACE VARCHAR
    TIEMPOS VARCHAR
  }
  T_RESUMEN_REGULADOS_PW {
    REG_GRUPO_IVR VARCHAR
    REG_MARCACION_IVR VARCHAR
    REG_NEGOCIO VARCHAR
    REG_NOMBRE_PROGRAMA VARCHAR
    REG_GRUPO_RO VARCHAR
    REG_GRUPO_AVH2 VARCHAR
  }
  T_RESUMEN_REGULADOS_PW_AURA {
    FECHA VARCHAR
    INDICADOR VARCHAR
    ANTES_40S VARCHAR
    TOTAL_PA VARCHAR
  }
  T_RESUMEN_REGULADOS_PW_V2 {
    REG_GRUPO_IVR VARCHAR
    REG_MARCACION_IVR VARCHAR
    REG_NEGOCIO VARCHAR
    REG_NOMBRE_PROGRAMA VARCHAR
    REG_GRUPO_RO VARCHAR
    REG_GRUPO_AVH2 VARCHAR
  }
  T_TEMPORAL_REGULADOS_PW {
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHA VARCHAR
    Handling VARCHAR
  }
  T_TEMP_DETALLE_STAR_GLOBAL {
    TELEFONO VARCHAR
    MARCACION_IVR VARCHAR
    SERVICE_TYPE VARCHAR
    NOMBRE_PROGRAMA VARCHAR
    FECHAANSI VARCHAR
    Handling_Attempt_Start VARCHAR
  }
  T_V2_REGULADOS_PW_202301 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202302 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202303 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202304 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202305 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202306 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202307 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202308 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202309 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202310 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202311 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202312 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202410 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202411 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202412 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202501 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202502 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202503 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_REGULADOS_PW_202504 {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V2_TEMPORAL_REGULADOS_PW {
    Interaction VARCHAR
    Interaction VARCHAR
    MARCACION_IVR VARCHAR
    Service VARCHAR
    TO VARCHAR
    NOMBRE_PROGRAMA VARCHAR
  }
  T_V5_TODAY {
    Interaction VARCHAR
    Interaction VARCHAR
    GUID INT
    IVR_CONNID INT
  }
  VALIDAR_ACUMULADO_RESUMEN {
    CANAL_MARCACION VARCHAR
    SUB_REPORTE VARCHAR
    REG_FECHA VARCHAR
    VAR_7 VARCHAR
    VAR_6 VARCHAR
    VAR_5 VARCHAR
  }
